### ISSUE TITLE
GraphQL error handling

### ISSUE THREAD

**Issue by incompletude** [nestjs/graphql#1053]
Nest version: lastest.

Throwing errors with Nest HttpException does not play well with GraphQL.

`throw new UnauthorizedException()` will generate the following:

```
{
  "errors": [
    {
      "message": "Unauthorized",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "login"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "response": {
            "statusCode": 401,
            "message": "Unauthorized"
          },
          "status": 401,
          "message": "Unauthorized",
          "stacktrace": [stack]
        }
      }
    }
  ],
  "data": null
}
```

While `throw new AuthenticationError("AuthenticationError")` from `import { AuthenticationError } from "apollo-server-express"` will generate the proper friendly error:

```
{
  "errors": [
    {
      "message": "AuthenticationError",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "login"
      ],
      "extensions": {
        "code": "UNAUTHENTICATED",
        "exception": {
          "stacktrace": [stack]
        }
      }
    }
  ],
  "data": null
}
```

When using the GraphQL the error responses should be in second format.

https://www.apollographql.com/docs/apollo-server/data/errors/

**Comment by JVMartin** [comment]
This is a show-stopper - every single thrown HTTP exception results in INTERNAL_SERVER_ERROR, making GraphQL unusable in nest.

Any updates?

**Comment by incompletude** [comment]
> This is a show-stopper - every single thrown HTTP exception results in INTERNAL_SERVER_ERROR, making GraphQL unusable in nest.
> 
> Any updates?

I found a workaround.

https://www.apollographql.com/docs/apollo-server/data/errors/

You can import these erros like:

`from import { UserInputError } from "apollo-server-express"``

Then it will work as intended.

**Comment by prokopsimek** [comment]
+1

The `nestjs-graphql` lib could re-export native apollo errors and then we can use `formatError` to re-throw correct graphql error.

**Comment by delucca** [comment]
+1

**Comment by leograde** [comment]
+1

**Comment by leograde** [comment]
You can pass a `formatError` when registering the GraphQL module such as:

```TypeScript
      formatError: (error: GraphQLError) => {
        const graphQLFormattedError: GraphQLFormattedError = {
          message: error.extensions?.exception?.response?.message || error.message,
        };
        return graphQLFormattedError;
      }
```

I found the answer here: https://stackoverflow.com/a/64129469/5959721

**Comment by itstheandre** [comment]
So what is the possible fix for this currently? Is that we use apollo server errors instead of the BadRequestException of nestjs?

How do we handle with class validator errors as well? Is there a way to check the difference between both possible error types?

**Comment by adamgajzlerowicz** [comment]
@leograde Thanks for the tip.

I added my own custom formatter that looks like this

```
formatError: (error: GraphQLError) => error.extensions?.exception?.response || || error.message,
```

Is there any benefit behind returning the `GraphQLFormattedError` rather than the custom structure?

**Comment by jfrader** [comment]
Bump?

**Comment by fyrstelin** [comment]
We are using a middleware that enriches the request with the user or throws the relevant http exception before hitting gql. This really works nicely for us. 
A fix for nestjs, could be that global guards works this way, and guards on resolvers wraps it in the gql response. 

For us, this have only been a problem with 401 (and in a few cases 403). For all other errors, it makes a lot of sense to have them in the graph response - the http request did work, and now it is just a response to the query. I don't think http errors should be thrown inside resolvers. Imaging querying you api through another transport layer (like a socket, ipc or even emails) - should that layer handle https exception or some more or less domain specific exceptions?

**Comment by dayota** [comment]
Another patch solution ...

- catching validation errors with global ValidationPipe and transform to `UserInputError` from `apollo-server-errors`
```
  app.useGlobalPipes(
    new ValidationPipe({
      transform: true,
      exceptionFactory: (errors: ValidationError[]): => {
        return new UserInputError('VALIDATION_ERROR', {
          invalidArgs: errors,
        });
      },
    }),
  );
```

- catching and formatting `UserInputError` to `GraphQLFormattedError`
```
    GraphQLModule.forRoot({
      autoSchemaFile: true,
      debug: false,
      formatError: (error: GraphQLError) => {
        if (error.message === 'VALIDATION_ERROR') {
          const extensions = {
            code: 'VALIDATION_ERROR',
            errors: [],
          };

          Object.keys(error.extensions.invalidArgs).forEach((key) => {
            const constraints = [];
            Object.keys(error.extensions.invalidArgs[key].constraints).forEach(
              (_key) => {
                constraints.push(
                  error.extensions.invalidArgs[key].constraints[_key],
                );
              },
            );

            extensions.errors.push({
              field: error.extensions.invalidArgs[key].property,
              errors: constraints,
            });
          });

          const graphQLFormattedError: GraphQLFormattedError = {
            message: 'VALIDATION_ERROR',
            extensions: extensions,
          };

          return graphQLFormattedError;
        } else {
          return error;
        }
      },
    }),
```

Thanks to @prokopsimek @leograde

**Comment by makuzaverite** [comment]
> Another patch solution ...
> 
> * catching validation errors with global ValidationPipe and transform to `UserInputError` from `apollo-server-errors`
> 
> ```
>   app.useGlobalPipes(
>     new ValidationPipe({
>       transform: true,
>       exceptionFactory: (errors: ValidationError[]): => {
>         return new UserInputError('VALIDATION_ERROR', {
>           invalidArgs: errors,
>         });
>       },
>     }),
>   );
> ```
> 
> * catching and formatting `UserInputError` to `GraphQLFormattedError`
> 
> ```
>     GraphQLModule.forRoot({
>       autoSchemaFile: true,
>       debug: false,
>       formatError: (error: GraphQLError) => {
>         if (error.message === 'VALIDATION_ERROR') {
>           const extensions = {
>             code: 'VALIDATION_ERROR',
>             errors: [],
>           };
> 
>           Object.keys(error.extensions.invalidArgs).forEach((key) => {
>             const constraints = [];
>             Object.keys(error.extensions.invalidArgs[key].constraints).forEach(
>               (_key) => {
>                 constraints.push(
>                   error.extensions.invalidArgs[key].constraints[_key],
>                 );
>               },
>             );
> 
>             extensions.errors.push({
>               field: error.extensions.invalidArgs[key].property,
>               errors: constraints,
>             });
>           });
> 
>           const graphQLFormattedError: GraphQLFormattedError = {
>             message: 'VALIDATION_ERROR',
>             extensions: extensions,
>           };
> 
>           return graphQLFormattedError;
>         } else {
>           return error;
>         }
>       },
>     }),
> ```
> 
> Thanks to @prokopsimek @leograde

This worked for me thanks @dayota

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/graphql/pull/1292
