### ISSUE TITLE
Error in compilation: TS2430: Interface 'GqlModuleOptions' incorrectly extends interface Pick<....>

### ISSUE THREAD

**Issue by phunguyen19** [nestjs/graphql#106]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior

I try using `npm run prestart:prod` to compile code and get the error

```
node_modules/@nestjs/graphql/dist/interfaces/gql-module-options.interface.d.ts:7:18 - error TS2430: Interface 'GqlModuleOptions' incorrectly extends interface 'Pick<Config, "modules" | "context" | "cache" | "debug" | "plugins" | "schema" | "formatError" | "rootValue" | "validationRules" | "formatResponse" | "fieldResolver" | "tracing" | ... 12 more ... | "playground">'.
  Types of property 'schemaDirectives' are incompatible.
    Type '{ [name: string]: typeof SchemaDirectiveVisitor; }' is not assignable to type 'Record<string, typeof SchemaDirectiveVisitor>'.
      Index signatures are incompatible.
        Type 'typeof import("node_modules/@nestjs/graphql/node_modules/graphql-tools/dist/schemaVisitor").SchemaDirectiveVisitor' is not assignable to type 'typeof import("node_modules/graphql-tools/dist/schemaVisitor").SchemaDirectiveVisitor'.
          Property 'getDeclaredDirectives' is protected but type 'SchemaDirectiveVisitor' is not a class derived from 'SchemaDirectiveVisitor'.

7 export interface GqlModuleOptions extends Omit<Config, 'typeDefs'>, Partial<Pick<ServerRegistration, 'onHealthCheck' | 'disableHealthCheck' | 'path' | 'cors' | 'bodyParserConfig'>> {
```

## Environment

<pre><code>
"@nestjs/common": "^5.1.0"
"@nestjs/core": "^5.1.0"
"@nestjs/graphql": "^5.4.0"
"graphql": "^14.0.2"
"graphql-tools": "^4.0.3"
"graphql-type-json": "^0.2.1"
"typescript": "^3.0.1"

</code></pre>

tsconfig.json
<pre><code>
{
  "compilerOptions": {
    "module": "commonjs",
    "lib": ["esnext", "dom"],
    "declaration": true,
    "noImplicitAny": false,
    "removeComments": true,
    "noLib": false,
    "allowSyntheticDefaultImports": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es6",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./src"
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules", "**/*.spec.ts"]
}
</code></pre>

For Tooling issues:
<pre><code>
- Node version: v10.14.2  
- Platform: Mac 
</code></pre>

**Comment by fuqihan** [comment]
Have this problem in linux，but win nothing.

**Comment by SqueezeToyAliens** [comment]
Having the same problem on **Windows**.

Any idea?

**Comment by fbrbovic** [comment]
same problem here

**Comment by workoo** [comment]
the quick fix is: 
`
// node_modules\@nestjs\graphql\dist\interfaces\gql-module-options.interface.d.ts
import { Type } from '@nestjs/common';
import { ModuleMetadata } from '@nestjs/common/interfaces';
import { Config, IResolverValidationOptions, ServerRegistration, SchemaDirectiveVisitor } from 'apollo-server-express';
import { IDirectiveResolvers,  } from 'graphql-tools';
`
 [ref#this](https://github.com/apollographql/graphql-tools/issues/957#issuecomment-426488903)

**Comment by nikitakot** [comment]
same issue, Mac

**Comment by phunguyen19** [comment]
@sgraham785 It works. Thanks. But I this issue should be kept opened.

**Comment by kamilmysliwiec** [comment]
Should be fixed in 5.5.1

**Comment by jon301** [comment]
I still get this error in 5.5.1

**Comment by yangchongduo** [comment]
No fix, why should I close it?

**Comment by phunguyen19** [comment]
It should not be closed.

**Comment by kamilmysliwiec** [comment]
I have just published 5.5.2 Could you check now?

**Comment by yangchongduo** [comment]
Already fixed

**Comment by phunguyen19** [comment]
It's fixed. So, this bug can be closed.
