### ISSUE TITLE
Provide a @nestjs/graphql shim model

### ISSUE THREAD

**Issue by LandazuriPaul** [nestjs/graphql#1082]
## I'm submitting a...
<pre>
[x] Feature request
</pre>

## Current behavior
Currently, I have to define my entities on the server package. As I use the same entities on the client, what I usually do is:
- Define common interfaces in a `domain` package
- Define entities in the server package which extend the `domain`'s entities
- Define classes in the client package which extend the `domain`'s entities as well

But both the server and client entities are the same in the end. The only differences come from the decorators they might (or might not) need.

As I discovered very recently that [TypeORM](https://typeorm.io/) offers a ["shim model"](https://github.com/typeorm/typeorm/blob/master/extra/typeorm-model-shim.js) for its decorators, it allows us to have the entities only defined once in the domain, directly as classes. The `typeorm`'s decorators are simply "unused" when the client compiles them.

This is very handy as I can now define my entities only in the domain package and each end package simply compiles them with the available decorators.

Unfortunately, `@nestjs/graphql` doesn't offer such a "shim" (or I didn't find it). As it seems quite a quick extra to add to the package but it can bring such an advantage for the Developer Experience, I thought it was worth mentioning.

## Expected behavior
So ideally, we could add this "model shim" and resolve to it in a potential `webpack` config for example.

## What is the motivation / use case for changing the behavior?
Improve the Developer Experience by reducing the repeated entity/class declarations and reducing the potential errors introduced in such a process.

If this is considered as an interesting feature/improvement, I'm down to help on it as it seems quite easy to integrate.

---
Have a great one and thank you for this awesome framework which truly changed my Node.js life! \o/

**Comment by kamilmysliwiec** [comment]
> If this is considered as an interesting feature/improvement, I'm down to help on it as it seems quite easy to integrate.

Sounds great! PRs are more than welcome :) 

> Have a great one and thank you for this awesome framework which truly changed my Node.js life! \o/

Thank you!
