### ISSUE TITLE
Using code first approach and GraphQLModule changes the order of mutation inputs

### ISSUE THREAD

**Issue by PedramMarandi** [nestjs/graphql#1095]
## Current behavior
I have a mutation like below 
```typescript
Mutation(() => [QuoteDto])
  async updateQuoteStatus(
    @Args({ name: 'where', type: () => WhereQuoteDto }) where: WhereQuoteDto,
    @Args({ name: 'quote_status_id', type: () => Int }) quoteStatusId: number,
    @Args({ name: 'accepted_by', type: () => Int, nullable: true }) acceptedById?: number,
  ) {}
```

When NestJS `GraphQLModule` runs, it produces the below graphql mutation 
```graphql  updateQuoteStatus(accepted_by: Int, quote_status_id: Int!, where: WhereQuoteInput!): [QuoteDto!]! ```

I have another service for generating Typescript classes from the auto-generated graphql file, using `GraphQLDefinitionsFactory` and the above mutation will be generated like below 

```typescript
abstract updateQuoteStatus(accepted_by?: number, quote_status_id: number, where: WhereQuoteInput): QuoteDto[] | Promise<QuoteDto[]>;
```

This will cause an error in Typescript like below: 
``` A required parameter cannot follow an optional parameter.

1056     updateQuoteStatus(accepted_by?: number, quote_status_id: number, where: WhereQuoteInput): QuoteDto[] | Promise<QuoteDto[]>;
                                                 ~~~~~~~~~~~~~~~


1:58:18 pm - Found 1 error. Watching for file changes.
```

## Expected behavior

I expect the code first GraphQL module to order the inputs accordingly without any change to the original order. 
In this case, the accepted_by_id parameter should be the last as it is in the mutation source.

## Environment
- Nest version: 7.1.0
- Nest GraphQL version: 7.4.5

For Tooling issues:
- Node version: 14.2.0
- Platform:  Mac

## Extra

```typescript
 GraphQLModule.forRoot({
      debug: !!process.env.DEBUG,
      playground: process.env.NODE_ENV !== 'production',
      autoSchemaFile: path.join(process.cwd(), './src/schema.graphql'),
      introspection: true,
      include: []
})
```

**Comment by hymair** [comment]
Just ran into this as well. Expected `id` to be the first argument.

resolver:
```
@Mutation(() => User, { name: 'userUpdate' })
update(
  @Args('id', { type: () => Int }) id: number,
  @Args('updateUserDto') updateUserDto: UpdateUserDto,
) {
  return this.usersService.update(id, updateUserDto)
}
```

generated schema:
```
type Mutation {
  userUpdate(updateUserDto: UpdateUserDto!, id: Int!): User!
}
```

ping @jmcdo29 @kamilmysliwiec
