### ISSUE TITLE
useGlobalPrefix not working for Apollo Gateway module

### ISSUE THREAD

**Issue by ldiego08** [nestjs/graphql#1158]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior

A global prefix has been set at the app level, but it won't work with the Apollo Gateway module. Accessing `../api/graphql` results in a 404 but `../graphql` works.

## Expected behavior

Since the global prefix has been set to `/api`, the GraphQL endpoint should be accessible at `../api/graphql`

## Minimal reproduction of the problem with instructions

I'm using the following app module code:

using the following code in the app module:

```ts
@Module({
    imports: [
        GraphQLGatewayModule.forRootAsync({
            useFactory: () => ({
                server: {
                    cors: true,
                    useGlobalPrefix: true, // .. set as '/api' in main.ts
                    path: '/graphql',
                },
                gateway: {
                    serviceList: /* .. my services */,
                },
            }),
        }),
    ],
})
export class AppModule {}
```

## Environment

<pre><code>
Nest version: 7.4.2

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by kamilmysliwiec** [comment]
Fixed in this commit https://github.com/nestjs/graphql/commit/24653709816b7e276bebc900bb227908dc67d30c. This will be a part of the next release.
