### ISSUE TITLE
GraphQL Server Including Unused Classes

### ISSUE THREAD

**Issue by j** [nestjs/graphql#1171]
I have a mono-repo with a shared "models" library.  The models have decorated object types, etc.  I have multiple GraphQL services and if I have a service that includes just one of those models, the service is still pulling in all other types since they are exported globally.

How can I have a service only include the types that are actually being used?

In other words, it should recursively select only the types actually needed.

**Comment by kamilmysliwiec** [comment]
The only solution, for now, is to avoid using barrel files (index.ts). This won't be the case once this ticket https://github.com/nestjs/graphql/issues/721 is resolved (it looks like a different issue at a first glance, but boils down to the same problem)
