### ISSUE TITLE
[Question] Is there a way to inject the GraphQLSchemaHost in one class?

### ISSUE THREAD

**Issue by esvm** [nestjs/graphql#1174]
Hello, my application has endpoints REST and GraphQL and I want to make the REST endpoint call a specific query of GraphQL. For this, I want to use the `graphql` function passing the schema and the query. But when I try to use the class GraphQLSchemaHost I receive the error:

```
GraphQL schema has not yet been created. Make sure to call the \"GraphQLSchemaHost#schema\" getter when the application is already initialized (after the \"onModuleInit\" hook triggered by either \"app.listen()\" or \"app.init()\" method).
```

I injected the GraphQLSchemaHost as provider os my module but still doesn't work. Can someone help me?

Hello, I want to use the `graphql` function using the schema of my application. 

I'm using `"@nestjs/graphql": "^7.6.0"`

**Comment by esvm** [comment]
I'm using the `GraphQLModule.forRootAsync`

**Comment by kamilmysliwiec** [comment]
You shouldn't access the schema before the `OnApplicationBootstrap` hook is called. 
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
