### ISSUE TITLE
How to make use  of currentUser in graphql subscription authguard.

### ISSUE THREAD

**Issue by Zony-Zhao** [nestjs/graphql#1213]
Thanks to #84 , I managed to get my @currentUser from graphql subscription authguard.( parsed from authorization token)
![image](https://user-images.githubusercontent.com/50739849/97259302-7a6a3680-1855-11eb-801f-4d7a34a00a9a.png)
I found that the user variable is not in this filter(payload,variables), which makes sense( user is not a graphql parameter), but this behavior makes my authguard useless. 
I still need to pass my userId to do the filtering. This user variable is available but can't be used in this function body.

How can I use this user variable in the filter, instead of passing a  tedious userId?

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
