### ISSUE TITLE
Resolver Union type not't support Auth Guards

### ISSUE THREAD

**Issue by medz** [nestjs/graphql#1218]
I created an AuthGuard according to the document. My GraphQL development method is "schema first". In using @Resolver(Type), AuthGuard works very well, but I cannot run it in @Resolver(Union)!

error: `Cannot read property 'headers' of undefined`

![image](https://user-images.githubusercontent.com/5564821/97576504-3891e980-1a29-11eb-9526-31ed39c4ff2b.png)

According to the document, I tried to protect a certain module, but the same error

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
