### ISSUE TITLE
Modify args in middleware

### ISSUE THREAD

**Issue by ph55** [nestjs/graphql#124]
I have application wide middleware.
When request done from controller I can get and modify body/query/params in following way:

```ts
// ....
  async resolve(...args: any[]): Promise<MiddlewareFunction> {
    return async (req, res, next) => {
      // get current user
      const user = await this.userService.getCurrent(req);

      if (!user) {
        next();
        return;
      }

      // attach user to request object
      req.user = user;

      // attach id of user to related request properties
      // used by validation pipes  
      switch (req.method) {
        case 'GET':
          req.query._userId = user.id;
          break;
        case 'POST':
          req.body._userId = user.id;
          break;
        default:
          req.params._userId = user.id;
      }

      next();
    };
```

Then its accessible via decorators `@Body()`, `@Query()` and `@Param()`

Can't figure out though how can I change args when GraphQL request done. 
So it will be accessible via `@Args()` decorator in resolver.

**Comment by kamilmysliwiec** [comment]
You can use an interceptor https://docs.nestjs.com/graphql/tooling (attach a user to the context object and inject it inside the resolver using `@Context()`)

Please, use [StackOverflow](https://stackoverflow.com/questions/tagged/nestjs) for such questions.
