### ISSUE TITLE
`schema` undefined when using `transformSchema` without `autoSchemaFile`

### ISSUE THREAD

**Issue by j** [nestjs/graphql#1240]
"schema" is undefined when using `transformSchema` unless I uncomment `autoSchemaFile`.  See below.

```typescript
    // ...

    GraphQLModule.forRoot({
      path: '/',
      // autoSchemaFile: 'schema.gql', // if I uncomment this, transformSchema works
      introspection: true,
      playground: true,
      transformSchema: (schema: GraphQLSchema) => {
        console.log(schema); // undefined unless I uncomment the above line

        return applyShieldMiddleware(schema);
      }
    }),

    // ...
```

**Comment by kamilmysliwiec** [comment]
@j if you comment the `autoSchemaFile` property out, `@nestjs/graphql` package assumes that you're building a schema first app. In the example above, I don't see `typeDefs` or `typePaths` which - in schema first approach - Nest would use to construct the schema. In this case, the initialization process **should** crash.

**Comment by j** [comment]
Hm, I thought the code first approach directly created a schema and types
making a schema file irrelevant.

**Comment by kamilmysliwiec** [comment]
@j in this case, you must use `autoSchemaFile: true`. This instructs the package to use the code-first approach and create a schema in memory.
