### ISSUE TITLE
[discussion] Specify TypeScript types for custom scalars

### ISSUE THREAD

**Issue by david-golightly-leapyear** [nestjs/graphql#1248]
Feature Request.

I'm having the same issue as https://github.com/nestjs/graphql/issues/540, but I'd like to take my own stab at explaining it, and why the resolution of this issue is unsatisfactory.

I'm a big fan of TypeScript and having consistently applied, strong types throughout my server code. To support that, I'm using https://github.com/urigo/graphql-scalars for more specialized scalars, to support custom scalar types like BigInt, DateTime etc.

I've defined application-custom scalars in `base.graphql`:

```graphql
"""
A date-time string at UTC, such as 2019-12-03T09:54:33Z, compliant with the date-time format.
"""
scalar DateTime

"""
An arbitrary JSON blob
"""
scalar JSON
```

And have supplied appropriate resolvers for them in the GraphQL module, etc. This all works fine, and GraphQL correctly serializes and deserializes the scalar values.

However, the generated TypeScript types are insufficient:

```ts
export type DateTime = any;
export type JSON = any;
```

Even though I've defined my DateTime resolver to parse to/serialize from a JS `Date` object, I'm unable to leverage that knowledge - that my application is in full control of - to know that a GraphQL argument of type `DateTime` is actually a `Date`. Instead, I have a bunch of `any` values. And in my application, I go to pains to avoid the use of `any`.

So first of all, a more appropriate default "unknown" type would be TypeScript 3.0's ['unknown`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-0.html#new-unknown-top-type). This would force explicit (rather than implicit) casting, and require assumptions to be made clear.

But secondly, like the author of the original ticket, I've used [`graphql-codegen`](https://graphql-code-generator.com/) and think its model works fairly well as an example of what might be possible in a framework as ambitious as Nest.js.

In graphql-codegen, I can manually specify how I want my custom GraphQL scalar values to be mapped to TypeScript like so:

```yml
config:
  scalars:
    DateTime: 'Date'
    JSON: 'JSON'
```

Now I'm able to generate the following TypeScript:

```ts
export type Scalars = {
  DateTime: Date
  JSON: JSON
}
```

This is the functionality I'm looking for.

Of course, if you want to get technical about it, Nest.js has some shortcomings in terms of its interaction with TypeScript and build-time type safety. For example, as an argument to a resolver query or mutation, I can write:

```ts
@Args('date') date: Date
```

And the compiler has no way of checking that this is an actual argument specified in any GraphQL `input` type for this function; it has to do all its checking at runtime. Likewise, overriding custom scalars with a compiler mapping like this is really just a "fancy" way to cast what's really an `any`; the compiler has to "take my word for it" that these types are correct.

The advantage of being able to specify this mapping, however, is that assuming the mapping is correct, any code _downstream_ from the generated types will now be typesafe.

In sum: `any` is essentially the worst possible type that can be generated, and its use in output should be avoided at all costs. _Ideally_ there would be a way to specify a scalar mapping as I've outlined, but _at a minimum_ `unknown` should be used in the place of `any` in all generated types.

Thanks for your consideration and for all the work you've put into a very solid framework.

**Comment by kamilmysliwiec** [comment]
This is something we definitely want to add to the TS definitions generator at some point. If you would like to create a PR for this, that would be awesome!

**Comment by david-golightly-leapyear** [comment]
I'd love to take a look at a PR for this, after I meet some looming deadlines...

**Comment by david-golightly-leapyear** [comment]
After exploring the code a bit, here's my proposal:

1. Change `DefinitionsGeneratorOptions` to:

```ts
export interface DefinitionsGeneratorOptions {
    emitTypenameField?: boolean;
    skipResolverArgs?: boolean;
    defaultScalarType?: string; // defaults to 'any' for backwards compatibility
    scalarDefinitions?: Record<string, string>;
}
```

2. Change https://github.com/nestjs/graphql/blob/7349926f4e1335a9da6c13261950ba1e974ba291/lib/graphql-ast.explorer.ts#L348 to accept `options: DefinitionsGeneratorOptions,` and emit the value in `scalarDefinitions` if specified and it contains a key for the current `item.name.value`, or the `defaultScalarType` if specified, or `any`.

I think this can be done in a non-breaking way, and in fact, the PR shouldn't be too onerous. Thoughts/comments?

**Comment by david-golightly-leapyear** [comment]
One other feature that this will require is the ability to add a "header" to the generated `.ts` file. For example, if I want to define a scalar that generates a type from an external library (eg. bignumber.js), I'll need the ability to add an import definition (like `import { BigNumber } from 'bignumber.js'`).

I think this could be served by another optional string key `header`  to `DefinitionsGeneratorOptions`.

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/graphql/pull/1253
