### ISSUE TITLE
GraphQL Scalars interface is missing

### ISSUE THREAD

**Issue by vlio20** [nestjs/graphql#126]
Hi,
From the [documentation](https://docs.nestjs.com/graphql/scalars) there is an option to create custom scalars. It seems like a custom scalar should implement some interface (serialize, etc.).
I couldn't find such interface, if there is no interface for this yet, I would be happy to submit a PR.

Thanks

**Comment by adamclerk** [comment]
I think it still missing. 

I'm getting the follow error after updating to 6.0.2

```
 Argument of type '{ path: string; typePaths: string[]; resolvers: { JSON: any; }; debug: boolean; playground: boole...' is not assignable to parameter of type 'GqlModuleOptions'.
  Object literal may only specify known properties, and 'resolvers' does not exist in type 'GqlModuleOptions'. (2345)
```

**Comment by adamclerk** [comment]
Scratch that. I was using an older version of typescript. Once I upgraded to 3+ it started working. Sorry for the trouble.
