### ISSUE TITLE
How to create a custom type (2D array) in graphql + nest

### ISSUE THREAD

**Issue by LeonYanghaha** [nestjs/graphql#1264]
I saw this [document](https://docs.nestjs.com/graphql/scalars#code-first). I wanted to create a two-dimensional array, but I encountered many problems. The data stored in the database was also wrong. Can someone tell me how I define this field. My field data looks like this.
```json
{
     "_id" : "5fbf01ba46fddb38b4325307",
    "desc" : "....",
    "domain" : [ 
        [     "name",  "=",   "leon"  ],
        [     "name",   "in",  ["leon" , "john", "annie"]       ],
    ]
}
```

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by LeonYanghaha** [comment]
I'm very sorry. Thank you for your reminder @kamilmysliwiec
