### ISSUE TITLE
[GraphQL] Validation not working with @InputType

### ISSUE THREAD

**Issue by ssslambda** [nestjs/graphql#1289]
## Current behavior

```graphql
mutation CreateComment {
  createComment(postId: 1, input: { text: "" }) {
    text
  }
}
```
This is working, but shouldn't, but @ArgsType is working, but i need @InputType

## Input Code

```ts
@InputType()
export class CreateCommentInput {
  @Field()
  @IsNotEmpty({ message: "Comment text can't be blank." }) // @MinLength(1) also not working
  @MaxLength(10000, {
    message: 'Comment text must be shorter than 10000 characters.',
  })
  text!: string;
}
```

## Expected behavior

I expect this to work and throw error when text is empty

## Environment

<pre><code>
Nest version: 7.6.1
class-validator version: 0.12.2

**Comment by ssslambda** [comment]
@jmcdo29 https://codesandbox.io/s/nifty-kirch-nvtmx?file=/src/app.resolver.ts I think this is enough

**Comment by jmcdo29** [comment]
> @jmcdo29 https://codesandbox.io/s/nifty-kirch-nvtmx?file=/src/app.resolver.ts I think this is enough

@ssslambda can you make a git repo, as stated in the link I provided?

**Comment by ssslambda** [comment]
> > @jmcdo29 https://codesandbox.io/s/nifty-kirch-nvtmx?file=/src/app.resolver.ts I think this is enough
> 
> @ssslambda can you make a git repo, as stated in the link I provided?

https://github.com/ssslambda/nest-graphql-repro the same code, but in repo

**Comment by jmcdo29** [comment]
You're missing essential decorators to tell class-validator and class-transformer how to handle the sub-class. Make your `DoWorkArgs` this and it will work as intended.

```ts
@ArgsType()
class DoWorkArgs {
  @Field(() => DoWorkInput)
  @Type(() => DoWorkInput)
  @ValidateNested()
  input!: DoWorkInput;
}
```
This is how `class-transformer` and `class-valdiator` are intended to work and not a problem within the Nest ecosystem.

You also need to give the proper type to the parameter in the query handler like so
```ts
@Mutation(() => Int)
  doWork(@Args({ type: () => DoWorkArgs }) { input }: DoWorkArgs) {
    num = input.num;
    return num;
  }
```

**Comment by ssslambda** [comment]
> You're missing essential decorators to tell class-validator and class-transformer how to handle the sub-class. Make your `DoWorkArgs` this and it will work as intended.
> 
> ```ts
> @ArgsType()
> class DoWorkArgs {
>   @Field(() => DoWorkInput)
>   @Type(() => DoWorkInput)
>   @ValidateNested()
>   input!: DoWorkInput;
> }
> ```
> 
> This is how `class-transformer` and `class-valdiator` are intended to work and not a problem within the Nest ecosystem.
> 
> You also need to give the proper type to the parameter in the query handler like so
> 
> ```ts
> @Mutation(() => Int)
>   doWork(@Args({ type: () => DoWorkArgs }) { input }: DoWorkArgs) {
>     num = input.num;
>     return num;
>   }
> ```

oh, my bad, im closing issue now, later will check, but I believe this should work thanks

**Comment by ssslambda** [comment]
yeah, it works, thank you!

**Comment by IslamGamal88** [comment]
@jmcdo29 it doesn't work for me
https://github.com/IslamGamal88/scaleup
 what am i missing here?

**Comment by jmcdo29** [comment]
> @jmcdo29 it doesn't work for me [IslamGamal88/scaleup](https://github.com/IslamGamal88/scaleup) what am i missing here?

Please provide a clear [minimum reproduction repository](https://minimum-reproduction.wtf). There's no need for a database here, it just muddies up the code

**Comment by IslamGamal88** [comment]
> > @jmcdo29 it doesn't work for me [IslamGamal88/scaleup](https://github.com/IslamGamal88/scaleup) what am i missing here?
> 
> Please provide a clear [minimum reproduction repository](https://minimum-reproduction.wtf). There's no need for a database here, it just muddies up the code

@jmcdo29 i updated the code, it is now just that.

**Comment by jmcdo29** [comment]
> > > @jmcdo29 it doesn't work for me [IslamGamal88/scaleup](https://github.com/IslamGamal88/scaleup) what am i missing here?
> > 
> > 
> > Please provide a clear [minimum reproduction repository](https://minimum-reproduction.wtf). There's no need for a database here, it just muddies up the code
> 
> @jmcdo29 i updated the code, it is now just that.

You never bind the `ValidationPipie`. 

Please use our [Discord](https://discord.gg/nestjs) channel (Support). We are using GitHub to track Bug Reports, Feature Requests, and Regressions.

**Comment by IslamGamal88** [comment]
oh dang, of course! thanks a lot @jmcdo29

**Comment by mtsaryk** [comment]
> 
@jmcdo29 
Thanks a lot) You saved my day
