### ISSUE TITLE
GraphQLDefinitionsFactory not exported from @nestjs/graphql@6.0.0-alpha.3

### ISSUE THREAD

**Issue by siriushaha** [nestjs/graphql#129]
import { GraphQLDefinitionsFactory } from '@nestjs/graphql';
import { join } from 'path';

const definitionsFactory = new GraphQLDefinitionsFactory();
definitionsFactory.generate({
  typePaths: ['./src/modules/**/*.graphql'],
  path: join(process.cwd(), 'src/graphql.ts'),
  outputAs: 'class',
  watch: true,
});

TSError: ⨯ Unable to compile TypeScript:
src/generate-typings.ts(1,10): error TS2305: Module '"../node_modules/@nestjs/graphql"' has no exported member 'GraphQLDefinitionsFactory'.

This above error is from @nestjs/graphql@6.0.0-alpha.3 version

**Comment by kamilmysliwiec** [comment]
Fixed in `6.0.0-rc.1` :)
