### ISSUE TITLE
[Doc Request] Add examples of e2e testing of GraphQL subscriptions to documentation/repository.

### ISSUE THREAD

**Issue by Liubyvyi** [nestjs/graphql#1303]
## I'm submitting a...
<pre><code>
[ ] Regression
[ ] Bug report
[ ] Feature request
[x] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior

There are no any examples of e2e testing of GraphQL subscriptions in documentation/repository. I found a lot of examples of how to test Queries and Mutations, but not a single example of how to test GraphQL Subscriptions with e2e approach.

## Desired behavior

Examples of e2e testing of GraphQL subscriptions are available in documentation/repository.

## What is the motivation / use case for changing the behavior?

- Give new users like me simple and practical examples for implementing e2e tests for GraphQL subscriptions.
- Better reflect the documentation's perspective of testing as one of the "fundamentals"
- Serve as quick reference to users.

## Environment
<pre><code>
Nest version: latest
</code></pre>

**Comment by kamilmysliwiec** [comment]
This sounds more like a technology-agnostic GraphQL subscriptions testing tutorial. Although we would love to cover all potential scenarios in the documentation, this would make it very heavy & hard to grasp. Therefore, we've been trying to put in the docs **only** things that are exclusively related to the framework (with a few general & common "additions"/suggestions/examples unrelated to the framework).

**Comment by kasir-barati** [comment]
@Liubyvyi Maybe this can help you: https://github.com/kasir-barati/graphql-js-ts/tree/main/subscription

> [!NOTE]
>
> A word of warning, I have some issues with this example though, I mean it is working just fine in that repo but when I try to use it in other projects it does not. My best guess is that it is due to 3rd party libraries and different versions of npm packages I use.
