### ISSUE TITLE
[discussion]: Custom GraphQL over WebSocket protocol when enabling subscriptions

### ISSUE THREAD

**Issue by asmeikal** [nestjs/graphql#1341]
When [enabling subscriptions](https://github.com/nestjs/graphql/blob/master/lib/graphql.module.ts#L156), the GraphQL module relies on the [default behaviour](https://github.com/apollographql/apollo-server/blob/main/packages/apollo-server-core/src/ApolloServer.ts#L599) of Apollo Server, which is to use [`subscriptions-transport-ws`](https://github.com/apollographql/subscriptions-transport-ws). The library is not actively maintained anymore, and their README points to `graphql-ws` as an alternative. Apollo Server has still `subscription-transport-ws` in their docs (see [here](https://www.apollographql.com/docs/react/data/subscriptions/#setting-up-the-transport)), but according to their [roadmap](https://github.com/apollographql/apollo-server/blob/main/ROADMAP.md#tech-debt-paid-down) they want to remove it somewhere in the future.

`subscriptions-transport-ws` has several protocol bugs that haven't been addressed in the last year. One of them is [this one](https://github.com/apollographql/subscriptions-transport-ws/issues/349), which allows connections to be established while skipping the recommended way to perform [authentication](https://www.apollographql.com/docs/graphql-subscriptions/authentication/). Other protocol bugs are on the client side, and they [keep coming](https://github.com/apollographql/subscriptions-transport-ws/issues/808) even after the [last batch](https://github.com/apollographql/subscriptions-transport-ws/issues/777#issuecomment-674835070) of bug fixes, and [old bugs](https://github.com/apollographql/subscriptions-transport-ws/issues/339) have still not been addressed.

`subscriptions-transport-ws` is clearly not production ready. I've seen the impact of all of these bugs on the project I'm currently working on, and fixed some of them by forking the library and using the fork in our NestJS subscription servers, but we are desperate for a long term solution. Switching from `subscriptions-transport-ws` to `graphql-ws` (as suggested on the first library repo) cannot be done transparently: the two protocols have differences in the structure of messages that are exchanged between client and server that make them incompatible, so which protocol to use should be left as a choice to the user.

What I'd like is for the GraphQL module to allow the user to choose which GraphQL over WebSocket protocol to use, while still defaulting to `subscriptions-transport-ws`. It should be possible, since `subscriptions-transport-ws` is not directly referenced anywhere in this repo, but I still haven't made an attempt. I will try as soon as I can and update this issue.

**EDIT:** I've put together a simple and rough integration of `graphql-ws`. It's available [here](https://github.com/asmeikal/graphql/tree/graphql-ws) and it's in no way good, but it works. The new protocol is enabled by passing `protocol: 'graphql-ws'` to the `subscriptions` option of the GraphQL module. The `subscriptions` option is a union to allow this (see [here](https://github.com/asmeikal/graphql/blob/graphql-ws/lib/interfaces/gql-module-options.interface.ts#L35)). Using the `graphql-ws` protocol is relatively straight forward (see [here](https://github.com/asmeikal/graphql/blob/graphql-ws/lib/graphql.module.ts#L160)), but that code is relying on [this function](https://github.com/enisdenjo/graphql-ws/blob/master/src/use/ws.ts#L30) provided by `graphql-ws`, and the authors say that it's just an example implementation.

I've added a [test](https://github.com/asmeikal/graphql/blob/graphql-ws/tests/subscriptions/subscription-transport-ws.spec.ts) to make sure that the `subscriptions-transport-ws` protocol still works, and [one](https://github.com/asmeikal/graphql/blob/graphql-ws/tests/subscriptions/graphql-ws.spec.ts) to test the `graphql-ws` protocol.

**Comment by kamilmysliwiec** [comment]
Thanks for reporting & leaving a good explanation. If it's something that Apollo has on their roadmap, we should start tracking this too. Would you like to submit a PR?

**Comment by asmeikal** [comment]
Hi @kamilmysliwiec, yes, I can try to clean up the example to get a PR for this.

I've been expanding the example implementation, and everything provided by NestJS seems to work out of the box. There are some differences on how authentication should be performed when using `connectionParams`, it should probably be addressed in [this documentation issue](https://github.com/nestjs/docs.nestjs.com/issues/394) once this is done.

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/graphql/pull/1348
