### ISSUE TITLE
Schema polling not working

### ISSUE THREAD

**Issue by ridyio** [nestjs/graphql#1358]
## I'm submitting a...
<pre><code>
[ ] Regression
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
Graphql playground polling feature doesn't seems to work. Every time a change is made into schema a refresh needs to be made so new schema would take effect.

## Expected behavior
Playground has a polling feature integrated and it fetches new schema every 2 seconds by default.

## Minimal reproduction of the problem with instructions
Make a change into DTO class. schema is regenerated with change but playground doesn't updates automatically.

## What is the motivation / use case for changing the behavior?
It can make development flow faster and easier if changes took effect immediately.

## Environment

<pre><code>
Nest version: 7.6.7
 
For Tooling issues:
- Node version: 15.3.0
- Platform: Mac

Others:
I am using fastify and webpack.
</code></pre>

**Comment by kamilmysliwiec** [comment]
Please report this issue in the `apollo-server` repository https://github.com/apollographql/apollo-server
