### ISSUE TITLE
Error encoding trace: root.child.error.message: string expected

### ISSUE THREAD

**Issue by sepiette** [nestjs/graphql#1369]
## Current behavior
I just upgraded our `apollo-server-express` versions from 2.12.0 to 2.19.0 and am suddenly seeing a lot of errors firing in our logs with the following:
```
" Error encoding trace: root.child.error.message: string expected"
"    at /app/node_modules/apollo-server-core/dist/plugin/usageReporting/plugin.js:265:39"
"    at Generator.next (<anonymous>)</anonymous>"
"    at fulfilled (/app/node_modules/apollo-server-core/dist/plugin/usageReporting/plugin.js:5:58)"
Object
```

## Expected behavior
I expect not to have any console errors.

## Possible Solution
 I found the following [thread](https://github.com/nestjs/nest/issues/1832), but can't join the Discord channel to find out more. It may be a similar problem with the `class-validator` library and Nest. The other [issue](https://github.com/nestjs/nest/issues/1832) I found related to this error seems to have been resolved in Nest version 6.0.4 and we are on 6.7.2.

## Environment
Nest version: 6.7.2

**Comment by sepiette** [comment]
@jmcdo29 linked below:

**Note** - I am only seeing this error in our deployed environments, so I haven't been able to re-produce locally. However I've made a basic server with the same versions of NestJS and GraphQL packages we are currently using. We also have configured environment variables for Apollo GraphQL Studio in our deployed environment.

[Repo Here](https://github.com/sepiette/apollo-issue-mvp) 

Deployed instance of App - [http://apollo-issue-mvp.herokuapp.com/graphql](http://apollo-issue-mvp.herokuapp.com/graphql). I have log monitoring hooked up to it to see if the same thing is happening.

**Comment by kamilmysliwiec** [comment]
This issue seems to be related to the underlying `apollo-server-core` package. I've just updated all dependencies & triggered a new release, hope that will solve this issue.
