### ISSUE TITLE
gateway doesn't startup properly in federation

### ISSUE THREAD

**Issue by flyhigh-hifi** [nestjs/graphql#1412]
## Current behavior
When the gateway server is starting and trying to fetch schema from services it does not fail when service is not available, simply console logging error. No way to intercept this process and take an action in case of error.

## Input Code
The example from the documentation

## Expected behavior
It should fail on error during schema fetching.

## Possible Solution
1. It should fail.
2. There were issues in apollo which were fixed in PR https://github.com/apollographql/apollo-server/pull/3867
3. Should be reflected in docs
4. Few improvements I'd add, which would be especially useful in docker/non-docker environments to handle deploys:
  - retry logic
  - delayed schema fetch(like wait-port)
  - ability to refetch schema on dependent service schema update(without server restart)

## Environment

<pre>
"@apollo/federation": "^0.21.2",
"@apollo/gateway": "^0.23.2",
"@nestjs/common": "^7.6.13",
"@nestjs/core": "^7.6.13",
"@nestjs/graphql": "^7.9.10",
"@nestjs/platform-express": "^7.6.13",
<code>
Nest version: 7.5.1

**Comment by kamilmysliwiec** [comment]
Please provide a minimum reproduction repository.

**Comment by dberardo-com** [comment]
well i also experience this issue, quite simply, the gateway is starting up before other services, and it fails with an exception 


```
he `pollIntervalInMs` option is deprecated and will be removed in a future version of `@apollo/gateway`. Please migrate to the equivalent `fallbackPollIntervalInMs` configuration option. The poll interval is now defined by Uplink, this option will only be used if it is greater than the value defined by Uplink or as a fallback.
Gateway successfully initialized (but not yet loaded)
Loading gateway...
Error: Couldn't load service definitions for "...." at http://localhost:3332/graphql
```

the "solution" is basically triggering a reload of the gateway code, by simply making a small change somewhere and saving the file

very annoying though.

**Comment by karimch27** [comment]
how is this missing clarification? the issue is well explained and still there.
Instead of showing a console log like this, it should maybe fail or add a retry mechanism for the gateway to wait for other microservices to start
`Error starting app module: Error: Couldn't load service definitions for "..." at http://localhost:3101/...: request to http://localhost:3101/... failed, reason: connect ECONNREFUSED ::1:3101`

**Comment by vincio71** [comment]
The issue could be the startup order of the microservices. Apollo Gateway, for example, doesn't handle the requirement that the Gateway should be started last. For this, you should use solutions like Kubernetes or manually create an orchestrator. I personally went crazy trying to figure out this error for days (I have an architecture based on Nest.js and Apollo Federation with Apollo Gateway) and couldn’t understand the problem. I can confirm that there's nothing native in Apollo (nor in Nest.js) that handles this type of issue.

In my case, I also made a huge mistake in my `docker-compose.yml`. Specifically, I had a project structure like this (where `package.json` is shared among all services):

```plaintext
.
├── apps
│   ├── gateway
│   │   ├── Dockerfile
│   │   ├── src
│   │   └── test
│   ├── service1
│   │   ├── Dockerfile
│   │   ├── src
│   │   └── test
│   ├── service2
│   │   ├── Dockerfile
│   │   ├── src
│   │   └── test
├── docker-compose.yml
├── nest-cli.json
├── package-lock.json
├── package.json
├── tsconfig.build.json
└── tsconfig.json

I had set the context incorrectly in the `docker-compose.yml`, and in each Dockerfile within every microservice, I was using the command `COPY . .`, which ended up creating containers that included all the contents of the `apps` folder.
