### ISSUE TITLE
Options of @Field gets ignored 

### ISSUE THREAD

**Issue by piyushk96** [nestjs/graphql#1424]
## Current behavior

The options provided in `@Field` of the field in entity class get ignored if there is a `@ResolveField` for that field prenent in the resolver.

## Input Code

If there is an entity class with a field having some options like:
```
@ObjectType
class MyEntity {
  @Field(()=> ID, {description: "Something", nullable: true})
  field1?: number
}
```

and there is a resolver class as:
```
@Resolver(() => MyEntity)
class MyEntityResolver {
  @ResolveField("field1", () => ID)
  getField(@Parent() entity: MyEntity) {
    return 1;
  }
}
```
Now if we generate the GraphQL schema for this, the field `field1` will show up as non-nullable and without any description in the GraphQL schema

## Expected behavior
The options in `@ResolveField` should override options of `@Field` if provided. Otherwise, options of `@Field` should be taken by default.

## Environment

<pre><code>
Nest version: 7.5.1

 
For Tooling issues:
- Node version: 14  
- Platform:  Mac

**Comment by fregadev** [comment]
That would be a big change. A breaking one, even.
I suggest we warn on the console when the code declares any field twice.
 Maybe throw an error if `NODE_ENV==='production'`.

**Comment by kamilmysliwiec** [comment]
That's correct. Think of `@ResolveField` as it would "override" your property resolver & configuration, not _inherit/extend_ it. There are currently no plans to change this behavior, but if you have time and you're willing to contribute, PRs are more than welcome!

**Comment by cyc1e** [comment]
Hi guys, this is really bad for me. I have an Entity with fields from the DB, but I get some fields through the API, and sometimes they can be NULL. Why i cant set nullable: true in @ResolveField? Thanks for your work!
