### ISSUE TITLE
InterfaceType decorator doesn't support implementing other interfaces

### ISSUE THREAD

**Issue by jpanther** [nestjs/graphql#1428]
## I'm submitting a...

<pre><code>[ ] Regression 
[x] Bug report
[x] Feature request
[ ] Documentation issue or request
[ ] Support request 
</code></pre>

## Current behavior

Currently you cannot implement a parent interface using the `@InterfaceType` decorator when using the code first approach.

However, using the schema first approach this syntax works as expected:

```graphql
interface ParentInterface {
    id: String!
}
interface ChildInterface implements ParentInterface {
    id: String!
}
type ChildType implements ChildInterface {
    id: String!
}
```

## Expected behavior

Using similar syntax to the `@ObjectType` implementation, I would expect `@InterfaceType` to allow the following argument to implement a parent interface:
```js
@InterfaceType({
    implements: () => [ParentInterface]
})
```

## Minimal reproduction of the problem with instructions

Create a basic parent interface:
```js
import { Field, ID, InterfaceType } from "@nestjs/graphql";

@InterfaceType()
export abstract class ParentInterface {
  @Field((type) => ID)
  id: string;
}
```
Then attempt to implement the ParentInterface in a second child interface:
```js
import { InterfaceType } from "@nestjs/graphql";
import { ParentInterface } from "./parentinterface.model";

@InterfaceType({
    implements: () => [ParentInterface]
})
export abstract class ChildInterface implements ParentInterface {
  id: string;
}
```
The `@InterfaceType` decorator does not support the `implements` option.

## What is the motivation / use case for changing the behavior?

This is supported as part of the GraphQL spec. The schema first approach works as expected so the code first approach should mirror the same behaviour.

## Environment
<pre><code>Nest core/common: 7.6.13
Nest graphql: 7.9.11
 
For Tooling issues:
- Node version: 15.11.0
- Platform: macOS 11.2.3
</code></pre>

**Comment by kamilmysliwiec** [comment]
Please provide a minimum reproduction repository.

**Comment by gevuong** [comment]
Hi,

Earlier, I tried implementing something similar, an interface implementing another interface, using the code-first approach. However, as stated by the author, `@InterfaceType` does not support an `implements` option. 
Is there an alternate way of implementing this? Will the `implements` option be included in an upcoming version?

Thanks in advance.

**Comment by kamilmysliwiec** [comment]
@jpanther would you like to create a PR for this issue?

**Comment by jpanther** [comment]
@kamilmysliwiec I had a quick look but I think this change is beyond my abilities

**Comment by kamilmysliwiec** [comment]
Added in the latest release

**Comment by jpanther** [comment]
Thanks @kamilmysliwiec! Seems to be working well.

**Comment by gevuong** [comment]
thanks for the update! 

Question, I noticed that the local graphql playground does not show updates where an interface implements another interface. For example, it would show the following.

```
interface A {
  a: String
  b: String
}
```

However, I notice the `src/schema.gql` file that gets auto-generated using the code-first approach, it shows that an interface implemented another interface.

```
interface A implements B {
  a: String
  b: String
}
```

Is this an issue caused by nestjs/graphql?
