### ISSUE TITLE
Wildcard controller route overwrites /graphql route

### ISSUE THREAD

**Issue by thisismydesign** [nestjs/graphql#1485]
## Current behavior

The `/graphql` route seems to be registered too late, so that a `@Get('*')` will overwrite it, even if it's imported later.

## Input Code

`app.module.ts`
```ts
@Module({
  imports: [
    GraphQLModule.forRoot({
      autoSchemaFile: join(process.cwd(), 'src/schema.gql'),
    }),
    MyModule,
  ],
})
```

Where `MyModule` has the following controller:
```
@Controller('/')
export class MyController {
  @Get('*')
  static(@Req() req: Request, @Res() res: Response) {
    // ....
  }
}
```

My repo to reproduce: https://github.com/thisismydesign/nestjs-playground/tree/8ae086c05b9f2510ff7efef955134781cf55a802 (module is called `ViewModule`).

## Expected behavior

`/graphql` is registered first and is accessible.

## Resources

- What I'm trying to do: https://javascript.plainenglish.io/render-next-js-with-nestjs-did-i-just-made-next-js-better-aa294d8d2c67
- Related issue: https://github.com/nestjs/graphql/issues/71
- Related issue: https://github.com/nestjs/nest/issues/1108

## Environment

<pre><code>
Nest version: 7.5.1

</code></pre>

**Comment by kamilmysliwiec** [comment]
`/graphql` is just a regular endpoint. If you use `@Get('*')` elsewhere, it will override it and that's the expected behavior.
