### ISSUE TITLE
Selective Authentication on Graphql Federation Layer

### ISSUE THREAD

**Issue by NikhilSSeth** [nestjs/graphql#1495]
## I'm submitting a...
Feature request

## Expected behavior
 If we have a GraphQl federation layer and two microservices i.e MS-1 and MS-2. There should be a way to write your authentication at the federation layer which can give us selective authentication. For example: if i want authentication for MS-1
and not MS-2 then there should be a way to handle this scenario on the federation layer.

For now, i have created a middleware which will be getting the token from the request and verify it. But i am unable to find a way to distinguish or have a selective authentication.

## Environment
Nest version: 7.6.13

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?
