### ISSUE TITLE
Graphql nested mapped types cannot determine input type on nested ObjectType

### ISSUE THREAD

**Issue by greenreign** [nestjs/graphql#1516]
## Current behavior
When using mapped-types two levels deep, nestjs is unable to determine the InputType of the second level.  

```
(node:14024) UnhandledPromiseRejectionWarning: Error: Cannot determine a GraphQL input type for the "level2s". Make sure your class is decorated with an appropriate decorator.
```

### Reproducible repo
https://github.com/greenreign/nest-mapped-types-nested-error

### relevant code inline
```
@ObjectType()
export class Level2 {}

@ObjectType()
export class Level1 {  
  @Field()
  id: string;
  @Field(() => [Level2])
  level2s: Level2[];
}

@InputType()
export class Level0 extends OmitType(Level1, ['id'], InputType) {}

// In resolver    
@Mutation(() => Level1)
mutate(@Args('input') input: Level0): Promise<Level1> {
   return this.someService.create(input);
}
```
## Expected behavior

This should work the same as a regular`InputType` which has attributes of type `ObjectType`.

## Environment

```
$ yarn list --pattern @nestjs
yarn list v1.22.10
├─ @nestjs/cli@7.6.0
├─ @nestjs/common@7.6.15
├─ @nestjs/core@7.6.15
├─ @nestjs/graphql@7.10.6
├─ @nestjs/mapped-types@0.4.1
├─ @nestjs/platform-express@7.6.15
├─ @nestjs/schematics@7.3.1
└─ @nestjs/testing@7.6.15
Done in 0.52s.
```

**Comment by woltob** [comment]
I think you have to define Leve1 with InputType({isAbstract:true}) so that the properties are inheritable.

```
@ObjectType()
@InputType({isAbstract: true})
export class Level1 {  
  @Field()
  id: string;
  @Field(() => [Level2])
  level2s: Level2[];
}
```

Let me know if this works. 
Since the InputType would use Level2 also then, perhaps it's necessary to define an InputType for Level2 as well and use it as a the type for the levels2 field in Level1.

I'm also struggling currently with nested InputTypes yielding an
```
Error: Schema must contain uniquely named types but contains multiple types named
```
Error.

Can anyone of the core nestjs/graphql team provide a repo with a working code base and nested types?

Thanks.

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by greenreign** [comment]
I don't know that there is a resolution or clear path forward that I'm understanding.  I actually forgot about this issue and then got stumped by it again when trying to compose an InputType with another object which was an ObjectType.  It seems it's just not possible?

**Comment by woltob** [comment]
We solved it by making the ObjectType having @InputType({isAbstract: true}) and then creating an InputType as such, omitting the nested attribute and adding it manually. For that nested attribute, you have to create another InputType following the same strategy until all nested objects you require are covered.

```
@InputType()
export class DeviceInput extends PickType(
  Device,
  ['id', 'deviceType'],
  InputType,
) {
  @Field((_type) => DevicePropertiesInput)
  public deviceProperties: DevicePropertiesInput;
}
```
