### ISSUE TITLE
Graphql error logging

### ISSUE THREAD

**Issue by NykolaySavin** [nestjs/graphql#1540]
You will be able to use plugins once this PR is merged https://github.com/nestjs/graphql/pull/634
The docs will be updated as well

_Originally posted by @kamilmysliwiec in https://github.com/nestjs/graphql/issues/649#issuecomment-597079089_

But how to inject nestJS logger there? Looks like it is out of nest js context

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
