### ISSUE TITLE
Support typeDef in GraphQLDefinitionsFactory

### ISSUE THREAD

**Issue by Crocsx** [nestjs/graphql#1581]
## I'm submitting a...

 I am using Schema First approach, and I have the following situation where an ENUM value would varies based on the environment the application use.
 
 ```
     GraphQLModule.forRoot({
      typeDefs: `
      enum Provider {
        AMAZON 
        ${process.env.NODE_ENV === 'local' ? '' : 'GOOGLE'}
      }`,
      typePaths: ['./**/*.graphql'],
      definitions: {
        path: join(process.cwd(), 'src/graphql.ts'),
      },
```

Now, this above works good when the application start, the appropriated type are defined.

the problem is with the auto-generation as there is no way to defined a typeDef inside this method. so the codegen always fail with error 

> Unknown type "Provider" 
 
 ```
 const definitionsFactory = new GraphQLDefinitionsFactory();
definitionsFactory.generate({
  typePaths: ['./src/**/*.graphql'],
  path: join(process.cwd(), 'src/graphql.ts'),
});
```
 

## Expected behavior

Like when I start the app, I should be allowed to define a typeDef to the `GraphQLDefinitionsFactory` so that autogeneration would also work

## Minimal reproduction of the problem with instructions
https://github.com/Crocsx/nestGraphql

when `NODE_ENV=local` and run `npm run start` it will generate the following interface 
```
export enum Provider {
    AMAZON = "AMAZON",
    GOOGLE = "GOOGLE"
}
```

when `NODE_ENV=production` and run `npm run start` it will generate the following interface 
```
export enum Provider {
    AMAZON = "AMAZON",
}
```

when running the command `npm run codegen` it will always fail cause Provider is not defined.

## What is the motivation / use case for changing the behavior?

Using typedef in auto generation should be allowed, as it is allowed on application start.

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by Crocsx** [comment]
oh, heu.

I can check what I can do next week end, but do not my abilities on this  ^^

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/graphql/pull/1439
