### ISSUE TITLE
inject @Req / context / info to @ResolveProperty()

### ISSUE THREAD

**Issue by hkjeffchan** [nestjs/graphql#16]
In @Query, we get the parameters (args, context, info) like this
```
@Query()
user(_, args, context, info) {
```
And req can be retrieved from context or info

Is it possible to get the req from @ResolveProperty too? I have tried something like this but it does not work.

```
@ResolveProperty()
userExperience(user: user, @Req() request) {
```

**Comment by hkjeffchan** [comment]
```
@ResolveProperty()
userExperience(user: user, @Req() request, @Req() request2) {
```
Just found that request is empty object and request2 does get the request object. What is the correct way to get the request object? Thanks.

**Comment by hkjeffchan** [comment]
I am stupid...

Just found from the apollo doc that ResolveProperty and Query share the same resolver function signature.

```
fieldName(obj, args, context, info) { result }
```

https://www.apollographql.com/docs/graphql-tools/resolvers.html

**Comment by 4F2E4A2E** [comment]
@hkjeffchan at some level we all are :)
Keep giving back to the community, that's great! 👍
