### ISSUE TITLE
GraphQL Tools Schema Stitching Support

### ISSUE THREAD

**Issue by j** [nestjs/graphql#1602]
https://www.graphql-tools.com/docs/stitch-directives-sdl

I'm not quite sure how hard it will be to implement GraphQL Tools Schema Stitching (better support than Federation now and not "commercialized") to a Nest.js GraphQL project.

I'm able to get it somewhat working by using `transformSchema`, however, since `@nestjs/graphql` is tied to ApolloServer, I'm unable to cleanly do schema refreshing.

Is there a way to opt-out of ApolloServer and use my own implementation while utilizing nest's ecosystem & schema generation?

**Comment by kamilmysliwiec** [comment]
Currently, there's no simple way that would allow opting out the ApolloServer (the easiest way would be to literally just fork the package), and given the team's bandwidth, there are no plans to implement GraphQL Tools Schema Stitching as part of this library in the foreseeable future.

**Comment by j** [comment]
@kamilmysliwiec It seems as if it's 99% there?  All that's really needed is to just generate a schema and then one can apply it to the underlying server of their choice (express/fastify based).

I.E. `type-graphql`'s entry point is `buildSchema` and you just get a schema and serve it up how you want.  Ideally there's a `buildSchema` and `buildTypeDefsAndResolvers` type functionality.

Being so married to a corporate single server eliminates a lot of potential with community driven OSS around graphql.  I.E. https://the-guild.dev/ (envelope, graphql-helix, graphql over WS, etc).

All that's needed is schema & type definition creation which is already built for ApolloServer.

**Comment by kamilmysliwiec** [comment]
PRs are more than welcome if you're interested in working on this feature. We don't have time to address this now and very likely anytime soon.

**Comment by j** [comment]
I’m always welcome for PRs. I like asking about a feature before spending
time on it and see if there’s a preferred way to go about it if there is
interest.

**Comment by j** [comment]
@kamilmysliwiec Another library that'd benefit from not being tied to ApolloServer.

https://github.com/Davide-Gheri/nestjs-mercurius (nest integration.. uses this library but super hacked in)

https://github.com/mercurius-js/mercurius (cool GraphQL fastify implementation with extra features & arguably better federation implementation than Apollo)
