### ISSUE TITLE
Federation: Export `ApolloGateway`

### ISSUE THREAD

**Issue by j** [nestjs/graphql#1603]
I want to manage my own service SDL & reloading.  I'd like to be able to access the gateway to force `.load()`.

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR to address this issue?

**Comment by j** [comment]
@kamilmysliwiec I'd be willing to give it a shot.  Any reason why "ApolloServer" is chosen to be a property within `GraphQLModule` and not a provider to be injected elsewhere?

**Comment by j** [comment]
I was going through the code for everything and it's all just so married to `apollo-server`.

I suppose in a perfect world, we'd have

`@nestjs/graphql` - Schema Generation
`@nestjs/apollo-server` - Uses `@nestjs/graphql`, contains apollo specific plugins, etc.

Then anyone in the community can create super useful Nest.js GraphQL providers.  I.E.

`nestjs-graphql-helix` - Based on https://github.com/contrawork/graphql-helix
`nestjs-graphql-mercurius` - Based on https://github.com/mercurius-js/mercurius

Without having to re-invent or pluck sensitive modules from `@nestjs/graphql`

**Comment by jmcdo29** [comment]
Maybe a goal for Nest v9 (as v8 is already so close), split apart the apollo and general graphql implementation, kind of like how with HTTP we have the generic adapter and then the express and fastify adapters. That way we can have the GraphQL adapter and then an apollo adapter Nest maintains and community adapters for other GQL engines?

**Comment by j** [comment]
@jmcdo29 That to me sounds like the best option to go with.

I was about to just implement the preliminary idea of it and instantly saw that everything is so tied to Apollo.  I'm sort of over Apollo at the moment.  Their team is so slow to implement things that 3rd party OSS guys are coming up with as well as they're really pushing people towards their managed services and our organization doesn't like to be tied down.

Projects like https://github.com/Davide-Gheri/nestjs-mercurius, https://github.com/ardatan/graphql-tools (stitching is alive and well again due to Apollo Federation not being so great), https://www.graphql-mesh.com/.. the list can go on.

I tried using `@nestjs/graphql` + `graphql-tools` and it felt so hacky and I wasn't even sure if a future `@nestjst/graphql` release will break it.  I end up resorting in my gateway not even using `@nestjs/graphql` :-\.  ATM you have to use `transformSchema` to do cool things to a schema.

Nearly all GraphQL servers at this moment take in a schema and it's good to go.

Some require `typeDefs` and a resolver map. (which you can just use `graphql-tools` to get these things if you really need them):

```typescript
const typeDefs = printSchemaWithDirectives(schema);
const resolverMap = getResolversFromSchema(schema);
```

So a utility module without any server marriage would come in handy to use 3rd party server integrations.  It'd make the entire Nest.js GraphQL ecosystem that much better :)

**Comment by j** [comment]
@jmcdo29 Again, a great example of a 3rd party library consuming `@nestjs/graphql` to output a non-apollo server is https://github.com/Davide-Gheri/nestjs-mercurius.  I'd be afraid of that library breaking and having to be locked into a specific Nest version.

**Comment by j** [comment]
I'm just going to close this to take the discussion to #1640.

**Comment by sgentile** [comment]
it's not just the schema though - take this example :

https://www.apollographql.com/blog/backend/federation/using-subscriptions-with-your-federated-data-graph/

NestJS needs to expose the ApolloGateway for scenarios such as this.
