### ISSUE TITLE
'uploads' does not exist in type 'GqlModuleOptions'

### ISSUE THREAD

**Issue by ridyio** [nestjs/graphql#1642]
## I'm submitting a...
<pre><code>
[x] Regression
[ ] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
We used to be able to disable uploads feature by setting `uploads` to false in Graphql module import. This looks to be removed now.

## Expected behavior
Being able to disable uploads feature of Graphql.

## Minimal reproduction of the problem with instructions
<code>
GraphQLModule.forRoot({
      uploads: false
})
</code>

## What is the motivation / use case for changing the behavior?
Disabling uploads of Apollo server v2 is crucial because if enabled its middlewares won't allow HTTP 'multipart' setup.

## Environment

<pre><code>
Nest version: 7.6.17 (core) 7.10.6 (graphql)
 
For Tooling issues:
- Node version: 16
- Platform:  macOS
</code></pre>

**Comment by GuanRunhua** [comment]
src/app.module.ts:21:9 - error TS2322: Type '{ path: string; }' is not assignable to type 'boolean | GraphQLWsSubscriptionsConfig'.
  Object literal may only specify known properties, and 'path' does not exist in type 'GraphQLWsSubscriptionsConfig'.

21         path: '/api/subscriptions',
           ~~~~~~~~~~~~~~~~~~~~~~~~~~

  node_modules/@nestjs/graphql/dist/interfaces/gql-module-options.interface.d.ts:36:5
    36     subscriptions?: GraphQLWsSubscriptionsConfig | boolean;
           ~~~~~~~~~~~~~
    The expected type comes from property 'subscriptions' which is declared here on type 'GqlModuleOptions'

Found 1 error(s).

I have the similar issue.

**Comment by kamilmysliwiec** [comment]
`@nestjs/graphql` v8 is not compatible with Apollo v3. You should use Apollo v2 instead.
