### ISSUE TITLE
GraphQL Code First does not resolve functions

### ISSUE THREAD

**Issue by stemis** [nestjs/graphql#1660]
## Bug Report
When using `autoSchemaFile: false` with a schema file(SchemaFirst), passing a function resolves perfectly as per [Apollo server default resolver flow](https://www.apollographql.com/docs/apollo-server/data/resolvers/#default-resolvers). However, when using `autoSchemaFile: true`(CodeFirst), the function is not resolved and GraphQL complains about detecting a function instead of an `int`

IMO `autoSchemaFile` should only handle the dynamic building of the schema, not decide if Apollo's default resolver flow should be bypassed or not.

## Current behavior

**When `autoSchemaFile: false` (SchemaFirst)**

Resolves successfully, `3` returned

When **`autoSchemaFile: true` (CodeFirst)**
```Int cannot represent non-integer value: [function count]```
## Input Code

```ts
@ObjectType()
export default class Test {
  @Field(() => Number)
  count!: number;
}

@Resolver()
export default class TestResolver {
  @ResolveField(() => Test)
  test() {
    return {
      count: () => 3
    };
  }
}
```

## Expected behavior

Successful resolution of function like  [Apollo Server default resolvers flow](https://www.apollographql.com/docs/apollo-server/data/resolvers/#default-resolvers) does

## Environment

<pre><code>
Nest version: 7.5.2
</code></pre>

**Comment by stemis** [comment]
Please see:
https://github.com/stemis/nestjs-apollo-function-resolve-issue/tree/master/src

This is the example with `autoSchemaFile: true`
The error that is thrown when quering:
```
query {
  test {
    count
  }
}
```
 is:
```
Int cannot represent non-integer value: [function count]
```


When autoSchemaFile is set to false, and I'm providing a schemaFile myself, the resolver works without issues

**Comment by kamilmysliwiec** [comment]
Thanks for sharing!

A few notes after looking at your example: this is not how the code-first is supposed to work. The correct syntax would be:

```typescript
@Resolver(Test)
export default class TestResolver {
  @ResolveField('count')
  count() {
    return 3;
  }
}
```

Nested functions in literal JS objects are not supported by this package (and there's no reason to use them).

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
