### ISSUE TITLE
Allow subscription graphql to have a different path than normal graphql

### ISSUE THREAD

**Issue by ddehghan** [nestjs/graphql#1688]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@nestjs/graphql@9.0.0-next.6` for the project I'm working on.

We can't have the same timeout for connection on normal graphql and subscription graphql on our front end load balancers. Normal graphqls have a time out of 30 sec whereas subscription graphqls have 5 min.

We use the path to distinguish the 2 from each other using Google Load balancers ingress in Kubernetes.

We have tested this patch and it works and allows us to have different timeouts. 

REAL SOLUTION IS: There should be a path option under 'graphql-ws' which would be used to create the websocket. 

Thanks again for supporting graphql-ws 💯  👍 

David 

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@nestjs/graphql/dist/graphql-ws/graphql-subscription.service.js b/node_modules/@nestjs/graphql/dist/graphql-ws/graphql-subscription.service.js
index 3aaf321..686b70f 100644
--- a/node_modules/@nestjs/graphql/dist/graphql-ws/graphql-subscription.service.js
+++ b/node_modules/@nestjs/graphql/dist/graphql-ws/graphql-subscription.service.js
@@ -11,7 +11,7 @@ class GraphQLSubscriptionService {
         this.options = options;
         this.httpServer = httpServer;
         this.wss = new ws.Server({
-            path: this.options.path,
+            path: '/ws' + this.options.path,
             noServer: true,
         });
         this.subTransWs = new ws.Server({
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by kamilmysliwiec** [comment]
Added in 9.0.0-next.7

**Comment by ddehghan** [comment]
Thank you. That was quick. I tried to submit a patch but I had not done that Partial type before and I didn't have time to figure out. But now I see your solution. I was very close. :-)
