### ISSUE TITLE
Cannot stitch .graphql schemas via build command

### ISSUE THREAD

**Issue by borisowsky** [nestjs/graphql#171]
## I'm submitting a...
[ ] Regression
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request

## Current behavior
When server is compiled I'm getting error
```
(node:30371) UnhandledPromiseRejectionWarning: Error: Query.me defined in resolvers, but not in schema
```

## Expected behavior
Server should works as well as it does on `yarn dev`

## Minimal reproduction of the problem with instructions
```
yarn build
yarn serve:prod
```

## Environment
Repo: https://github.com/borisowsky/nestjs-apollo-prisma

Nest version: 6.0.2
 
For Tooling issues:
- Node version: 8.14.1
- Platform:  Mac

**Comment by kamilmysliwiec** [comment]
```
yarn serve:prod
```
This command will run your compiled application located in `dist` directory. You have to manually (or use a script) copy `.graphql` files in there.
