### ISSUE TITLE
Missing Details/Unexpected behaviour Authenticating over Websocket using graphql-ws.

### ISSUE THREAD

**Issue by Efosaok** [nestjs/graphql#1756]
## Bug Report
The section of the documentation on [authentication over websocket](https://docs.nestjs.com/graphql/subscriptions#authentication-over-websocket) says that the data returned from `forRoot.subscriptions.['subscription-transport-ws' || 'graphql-ws'].onConnect` callback will be acessible in the `forRoot.context` callback via `connection.context`. However that doesn't seem to be the case at least for `graphql-ws`. _connection_ is undefined in _context_ regardless of what is returned from _onConnect_.

Irrespective of what was returned from `forRoot.subscriptions.[graphql-ws'].onConnect`, I was only able to access the `connectionParams` parsed from the client via _context_ directly like this

```
{
  context: ({ connectionParams, connection }) => { } // connection will evaluate to undefined while connectionParams hold necessary authentication parameters. 
}
```
I am not sure if this is the intended behaviour and was missed out on the documentation or a bug but I am sure someone else will experience this soon enough.

**Comment by kamilmysliwiec** [comment]
Please provide a minimum reproduction repository.

**Comment by Efosaok** [comment]
I'll create one today. my apologies I have had no time really.

**Comment by SakisTsalk** [comment]
> I believe I was able to resolve the issue:
> 
> On this line within subscriptions-transport-ws: https://github.com/apollographql/subscriptions-transport-ws/blob/master/src/server.ts#L316
> 
> The result of the onConnect cb is merged with the context for subsequent messages, and in my case, my current-user decorator was accessing `context.req.user`, so my change was simple:
> 
> ```ts
> // From
> const user = await authorize(connectionParams?.accessToken);
> return { user };
> 
> // To
> const user = await authorize(connectionParams?.accessToken);
> return { req: { user } };
> ```
> 
> That said, the `context` method is still never called for subscriptions, which is OK, because the subscriptions-transport-ws lib is doing this merge you. But this might be worth updating in the documentation, if it is indeed the case.

Yes this worked for me as well. @kamilmysliwiec FYI
