### ISSUE TITLE
Access args of parent resolver inside field resolver

### ISSUE THREAD

**Issue by sujeeet-kumar** [nestjs/graphql#1772]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I have this below resolver,

```
  @ResolveField()
  async config(@Parent() pet: Pet, @Context() ctx, @Info() info): Promise<CourseConfig> {
    return await this.petService.getConfig(syllabus, ctx, info);
  }
```
How can I get args  passed to root resolver inside `petServic.getConfig()`? 
I know I can use `@Args()` decorator.

But It is only returning `args` passed to the `fieldResolver` i.e. `config(id: "someId")` but not those passed to the root resolver.

### Describe the solution you'd like

I would like to access arguments passed to the root query in `fieldResolvers`.

### What is the motivation / use case for changing the behavior?

If I could access parent query argument in field Resolvers, passing same argument in both parent query and field would be removed.
```
query {
      pet(id: petId) {
         config(id: PetId) { // this should not necessary as the id is already on parent query
         image
        }
 }
}
```

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
