### ISSUE TITLE
ResolveProperty('__resolveType') not working with type-graphql

### ISSUE THREAD

**Issue by apiel** [nestjs/graphql#178]
The last few days I migrated our project to use type-graphql with nest. I managed to migrate everything, but I am still stuck on one thing. Providing a custom `__typename` doesn't seem to work.

Here is my resolver:
```
@Resolver(ServiceProvider)
export class ServiceProviderResolvers {
    constructor(private readonly searchService: SearchService) {}

    @Query(() => [ServiceProvider])
    all(): Promise<ServiceProvider[]> {
        return this.searchService.all();
    }

    @ResolveProperty('__resolveType')
    resolveType(obj: ServiceProvider): string {
         return obj.type;
    }

    @ResolveProperty()
    test(obj: ServiceProvider): string {
         return obj.type;
    }
}
```
But the `resolveType` doesn't seem to be called, where `test` method is called if I query for `test` field.

I also tried to use some interface like suggested 19majkel94 (from type-graphql) but still doesn't work: https://github.com/19majkel94/type-graphql/issues/181#issuecomment-475166589

Is there any way to customize `__typename` with nest using type-graphql?

**Comment by apiel** [comment]
We make request on our elasticsearch database with an index that share different types of document. We need to identify which kind of document we are dealing with in our graphql schema. For example you would have an elasticsearch database with car and truck.

**Comment by 19majkel94** [comment]
@apiel
`__typename` means type name - `__typename` of `type Recipe` = `Recipe` and you can't change that.

You can only provide a custom `__resolveType` function that will return a hint for graphql-runtime about the underlying `type` of the runtime data you are returning, like generic `interface Person` and specific `type Student`.

It may read `__typename` property value of data object (default behavior), check object prototype/`instance of` or use the `type` property like in your example (`return obj.type`).

**Comment by apiel** [comment]
Hmm, I think I don't manage to explain myself. But I created another small repo making the wished behavior without type-graphql: https://github.com/apiel/nest-eg2

```
{
  getCats {
    id
    name
    __typename
  }
}
```
I get the wished response:

```
{
  "data": {
    "getCats": [
      {
        "id": 1,
        "name": "Cat",
        "__typename": "CatA"
      }
    ]
  }
}
```

See the `cats.graphql`
```
interface Cat {
  id: Int
  name: String
  age: Int
}

type CatA implements Cat {
  id: Int
  name: String
  age: Int
}
```

And finally the resolver:
```
  @ResolveProperty('__resolveType')
  resolveType(): string {
      return 'CatA';
  }
```

How can I do the same with nest using type-graphql?

**Comment by apiel** [comment]
Also you are not passing `propertyName` to the `FieldResolver` from type-graphql. So `@ResolveProperty("whatevername")` will never work, cause type-graphql will not be able to generate the schema for `whatevername`.

https://github.com/nestjs/graphql/blob/77c55fcdb8270e283218990a3ac8b83220508f12/lib/decorators/resolvers.utils.ts#L45

```
export function createPropertyDecorator(
  propertyName?: string,
  typeFunc?: ReturnTypeFunc,
  options?: AdvancedOptions,
): MethodDecorator {
  return (
    target: Function | Object,
    key?: string | symbol,
    descriptor?: any,
  ) => {
    SetMetadata(RESOLVER_NAME_METADATA, propertyName)(target, key, descriptor);
    SetMetadata(RESOLVER_PROPERTY_METADATA, true)(target, key, descriptor);
    FieldResolver && FieldResolver(typeFunc, options)(target, key, descriptor);
  };
}
```

**Comment by kamilmysliwiec** [comment]
@apiel so I took a look at your examples and they are different, hence, the behavior is different as well. 

> Also you are not passing propertyName to the FieldResolver from type-graphql. 

We don't have to - Nest is using `type-graphql` only to generate GraphQL definitions.

**Comment by apiel** [comment]
How to achieve https://github.com/apiel/nest-eg2 with type-graphql?

**Comment by kamilmysliwiec** [comment]
First of all, you would have to use interfaces (not types) as in  https://github.com/apiel/nest-eg2 (`Cat` interface)

**Comment by apiel** [comment]
But how can I use interface with nest and type-graphql? Do you have any example?

**Comment by kamilmysliwiec** [comment]
See https://typegraphql.ml/docs/interfaces.html

**Comment by apiel** [comment]
Hey super, this seem to be what I need ;-) Then I guess it might work with:
```
@Query(returns => MyInterface)
myInterface() {
  // use class instances 
  const response = new MyObjectType();
  response.sampleField = "sampleFieldValue";
  return response;
}
```
I will try tomorrow and then close the issue. Thx

**Comment by apiel** [comment]
Still having issue:

```
@InterfaceType()
export abstract class Recipe {
  @Field(type => ID)
  id: string;

  @Field()
  title: string;

  @Field({ nullable: true })
  description?: string;

  @Field()
  creationDate: Date;

  @Field(type => [String])
  ingredients: string[];
}

@ObjectType({ implements: Recipe })
export class RecipeA implements Recipe {
  id: string;
  title: string;
  description: string;
  creationDate: Date;
  ingredients: string[];
}
```

```
@Resolver(of => Recipe)
export class RecipesResolver {
  constructor(private readonly recipesService: RecipesService) {}

  @Query(returns => [Recipe])
  async recipes(@Args() recipesArgs: RecipesArgs): Promise<Recipe[]> {
    return this.recipesService.findAll(recipesArgs);
  }

  @ResolveProperty('__resolveType')
  resolveType(recipe: Recipe): string {
    return 'RecipeA';
  }
}
```
It's not compiling because `@Resolver(of => Recipe)` has typing issue: `Type 'typeof Recipe' is not assignable to type 'Type<any>'.
  Cannot assign an abstract constructor type to a non-abstract constructor type.`

If I remove abstract on the class `Recipe` it compile but fail on runtime with the error `UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'fields' of undefined`.

If I change resolver to `@Resolver('Recipe')`, I get the runtime error `UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getObjectType' of undefined`

https://github.com/apiel/nest-eg/tree/recipeA

**Comment by 19majkel94** [comment]
> Also you are not passing propertyName to the FieldResolver from type-graphql.

> We don't have to - Nest is using type-graphql only to generate GraphQL definitions.

Actually, we have to. According to TypeGraphQL docs:

> Note that if a field name of a field resolver doesn't exist in resolver object type, it will create in schema a field with this name. This feature is useful when the field is purely calculable (eg. averageRating from ratings array) and you don't want to pollute the class signature.

So @apiel code will produce a `Recipe` type with id, title, ... and `resolveType: String!`.
Changing the name to `__resolveType` I guess will result with schema generation error as `graphql-js` doesn't allow to create fields with name starting with an underscore.

There is a pending TypeGraphQL issue about that, as by default it uses `instance of` checks to resolve the type that might be not convenient when the 3rd party library like Typegoose doesn't use class instances.
https://github.com/19majkel94/type-graphql/issues/181

**Comment by apiel** [comment]
@19majkel94 thanks for the clarification

**Comment by appsolutegeek** [comment]
@kamilmysliwiec I am also having the same issue, can you confirm its an issue with the graphql nestjs implementation ?

Being going around crazy for the last few hours :-) I just can't get a simple example to work.

**Comment by michelcve** [comment]
@kamilmysliwiec  I'm also having the same problems as @apiel. No matter what I do, I can't get the @ResolveProperty to work. As soon as I use it, the server 'hangs'. When inspecting with debugger, I see the same error as @apiel : `UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'fields' of undefined`.

**Comment by kamilmysliwiec** [comment]
Please, create a separate issue + provide a repo that reproduces it @michelcve

**Comment by michelcve** [comment]
@kamilmysliwiec While creating a test project, I finally figured it out.

In my tsconfig.json I had `target: es5`. This works fine, until you start using `@ResolveProperty`. The resolution for this is switching target to `target: es6`.

**Comment by apiel** [comment]
Why do we close this issue? Is it solved?

**Comment by kamilmysliwiec** [comment]
Let's track this issue in a one place https://github.com/19majkel94/type-graphql/issues/181

**Comment by apiel** [comment]
But some weeks ago, when I tried to use interface https://typegraphql.ml/docs/interfaces.html, as you suggested, it didn't work. Nest didn't seem to support this feature from type-graphql. Did you fix this? If yes could you provide link of the commit/PR number?

**Comment by kamilmysliwiec** [comment]
See:
https://github.com/nestjs/graphql/issues/231
https://github.com/nestjs/graphql/issues/203

**Comment by apiel** [comment]
Ah super :D I will give a try tomorrow.
