### ISSUE TITLE
Injectable Apollo Server

### ISSUE THREAD

**Issue by parisholley** [nestjs/graphql#1836]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Continuing discussion from: #1368 

### Describe the solution you'd like

https://docs.nestjs.com/fundamentals/module-ref#instantiating-custom-classes-dynamically

NestJS supports registering providers within onModuleInit and from what I understand, `_apolloServer` could be exposed this way, and the dependent providers could use `moduleRef` along with `onModuleInit` or `onApplicationBootstrap` to inject.

Without this, the web server and integrations have to manually modify singletons in the container to make it work like so:

```typescript
  const app = await NestFactory.create<NestExpressApplication>(MyModule);

  const service = app.get(MyService);
  service.graphql = app.get(GraphQLModule);
```

### What is the motivation / use case for changing the behavior?

I am building a react SSR implementation and want to invoke Apollo directly vs. going through HTTP.

**Comment by kamilmysliwiec** [comment]
Already replied to this issue here https://github.com/nestjs/graphql/issues/1368#issuecomment-775784193.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
