### ISSUE TITLE
Things started to fail when I upgraded graphql to 16.0.0

### ISSUE THREAD

**Issue by nsisodiya** [nestjs/graphql#1837]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I upgraded graphql package to 16.0.0 - https://www.npmjs.com/package/graphql
and started facing errors. I reverted my changes and it works fine again. 

### Minimum reproduction code

NA

### Expected behavior

npm install graphql to 16.0.0 should work.

### Package version

latest

### Graphql version

`graphql`: 
`apollo-server-express`: 
`apollo-server-fastify`: 

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
It's a major version changes, in semver, mean breaking changes. We're tracking this here: #1834

**Comment by RokeAlvo** [comment]
what versions of packages needed to run now? I tried graphql@15, graphql@15 + nest/graphql@8 - its not started

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/graphql/pull/1834
