### ISSUE TITLE
Missing dependency for Graphql Federation Module

### ISSUE THREAD

**Issue by NeutronScott12** [nestjs/graphql#1838]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I've been getting this issue, once I remove the module then the error goes away, so it seems there's an issue in the internal references because I do have apollo/federation within in node_modules, though I will add it's within a yarn workspace, I don't think that's the issue though.

`The "@apollo/federation" package is missing. Please, make sure to install this library ($ npm install @apollo/federation) to take advantage of ApolloFederation.`

### Minimum reproduction code

https://github.com/OGNeutron/TheLastHurrah/tree/master/packages/the-last-hurrah-authentication

### Steps to reproduce

```
yarn
yarn migrate:generate
yarn start:dev
```

Then the above error will appear.

### Expected behavior

The server is ready to accept requests.

### Package version

9.1.1

### Graphql version

`graphql`: 16.0.0

### NestJS version

8.1.2

### Node.js version

16.13.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by stokei** [comment]
I'm waiting for a solution.

**Comment by OGNeutron** [comment]
> I'm waiting for a solution.

The only solution currently is keeping your @apollo/federation at 0.33.1 and Graphql at 15.7.2, I've had the urge to fork and make a pull request, but lack of time.

**Comment by mattAktify** [comment]
This is an issue for me as well

**Comment by stokei** [comment]
> > I'm waiting for a solution.
> 
> 
> 
> The only solution currently is keeping your @apollo/federation at 0.33.1 and Graphql at 15.7.2, I've had the urge to fork and make a pull request, but lack of time.

It's work for me.

**Comment by Fl4v** [comment]
I had a somehow similar issue but I was getting an `@apollo/subgraph` package missing, the above solution worked for me.
