### ISSUE TITLE
Support ESM named exports

### ISSUE THREAD

**Issue by vadistic** [nestjs/graphql#1843]
### Did you read the migration guide?

~~- [ ] I have read the whole migration guide~~

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Versions

9.1.1

### Describe the regression

Exactly the same issue as https://github.com/nestjs/nest/issues/8320 for core packages

For core packages upgrade to 8.1.1+ fixes it, for `nestjs/graphql` - current verison `9.1.1` still hast this issue. 

```
import { Query, Resolver } from '@nestjs/graphql';
         ^^^^^
SyntaxError: Named export 'Query' not found. The requested module '@nestjs/graphql' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@nestjs/graphql';
const { Query, Resolver } = pkg;
```

### Minimum reproduction code

```ts
import { Query, Resolver } from '@nestjs/graphql'
```

in project with package `type: "module"` and `target: "esnext"`

### Expected behavior

Node ESM named import works.

### Other

I did not see the issue about it 🤷‍♂️

**Comment by moshest** [comment]
This should fixed that: https://github.com/microsoft/TypeScript/pull/47070

Maybe release an updated version now with the latest TypeScript compiler?

**Comment by BenSjoberg** [comment]
@moshest Unfortunately, that fix hasn't landed in a stable TypeScript release yet, so updating won't help. Thankfully it looks like it'll make it into 4.6 (I just tried it in the latest 4.6 dev build) but that's not scheduled to come out until [late next month](https://github.com/microsoft/TypeScript/issues/46858).

**Comment by kamilmysliwiec** [comment]
PR should be auto-created shortly

**Comment by moshest** [comment]
Still not working for me at version `10.0.6`:

```
SyntaxError: The requested module '@nestjs/graphql' does not provide an export named 'Args'
```

**Comment by xiaoyu-tamu** [comment]
it would be nice `@nestjs/apollo` support esm too
