### ISSUE TITLE
DateTime scalar breaks the query result with `0000-00-00 00:00:00` date and doesn't throw anything

### ISSUE THREAD

**Issue by Yehonal** [nestjs/graphql#1848]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Working with TypeORM (mysql) and zero-ed dates (`0000-00-00 00:00:00`) I've faced an issue where the scalar DateTime can't handle this date format.
It can be fine, but no errors are thrown. So it was a nightmare for me to investigate on it in production.
The result of the entire query is simply `null` and you do not have any way to know what field causes it.
By putting that field as nullable works, however, when it's not nullable and the scalar receives that value, it should throw an error.

### Minimum reproduction code

Can't create a repository right now (in progress)

### Steps to reproduce

1. Create a non-nullable DateTime field in your `type`
2. pass to that field the result of a timestamp mysql column filled by the `0000-00-00 00:00:00` value
3. fetch the query

### Expected behavior

It should throw an error

### Package version

9.1.1

### Graphql version

`graphql`: 15.5.3
`apollo-server-fastify`: 3.4.0

### NestJS version

8.1.1

### Node.js version

14

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Please provide a minimum reproduction repository.
