### ISSUE TITLE
Support for LocalGraphQLDataSource

### ISSUE THREAD

**Issue by sahanatroam** [nestjs/graphql#1853]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Problem: It would be nice to build a nest.js server with federation but on a single server and in a modular manner

### Describe the solution you'd like

Exactly what https://www.graphql-modules.com but for nest.js to work with federation similar to the following federation implementation:
https://codesandbox.io/s/apollo-federation-localization-forked-gyexs?file=/src/index.js:701-773

### What is the motivation / use case for changing the behavior?

Exactly what https://www.graphql-modules.com but for nest.js to work with federation similar to the following federation implementation:
https://codesandbox.io/s/apollo-federation-localization-forked-gyexs?file=/src/index.js:701-773

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

There are no plans to implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
