### ISSUE TITLE
DeprecationWarning: 'buildFederatedSchema' is deprecated. Use 'buildSubgraphSchema' instead.

### ISSUE THREAD

**Issue by iamonkey** [nestjs/graphql#1856]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The following error is generated when using this with the latest versions of apollo 

```
(node:12056) DeprecationWarning: 'buildFederatedSchema' is deprecated. Use 'buildSubgraphSchema' instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

```

We are unable to use 

```
    "@apollo/federation": "^0.33.6",
    "@apollo/gateway": "^0.43.1",
```

### Minimum reproduction code

http://github.com/tbc

### Steps to reproduce

yarn start:dev

### Expected behavior

No dep error

### Package version

9.1.1

### Graphql version

    "@apollo/federation": "^0.33.6",
    "@apollo/gateway": "^0.43.1",
    "apollo-server-core": "^3.4.0",
    "apollo-server-express": "^3.4.0",

    "@nestjs/common": "^8",
    "@nestjs/core": "^8",
    "@nestjs/graphql": "^9.1.1",
    "@nestjs/platform-express": "^8",

### NestJS version

8.1.0

### Node.js version

16.13.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Other

none

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/graphql/pull/1813
