### ISSUE TITLE
Error: Expected undefined to be a GraphQL schema

### ISSUE THREAD

**Issue by denerFernandes** [nestjs/graphql#1858]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Cześć,

When implementing graphql following the code first in the documentation, the error is displayed:

UnhandledPromiseRejectionWarning: Error: Expected undefined to be a GraphQL schema

### Minimum reproduction code

https://github.com/denerFernandes/nest-graphql-bug-test

### Steps to reproduce

1. Create new project  
`nest new test`

2. Add Graphql dependencies 
`npm i @nestjs/graphql graphql apollo-server-express` 

3. Create a new module, select Graphql Code First
`nest g resource users`

4. Import the GraphQLModule and configure it
`GraphQLModule.forRoot({
      installSubscriptionHandlers: true,
      autoSchemaFile: './src/schema.gql',
    }),`

5. Start nest
`npm run start:dev`

### Expected behavior

Generate the graphql file and start the server

### Package version

9.1.1

### Graphql version

`graphql`:  16.0.1
`apollo-server-express`: 3.5.0

### NestJS version

8.2.0

### Node.js version

14.17.4

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [X] Linux

### Other

When i run npm list, i have this:

`npm ERR! peer dep missing: graphql@^15.5.1, required by @nestjs/graphql@9.1.1
npm ERR! peer dep missing: ajv@^6.9.1, required by ajv-keywords@3.5.2
npm ERR! peer dep missing: ajv@^6.9.1, required by ajv-keywords@3.5.2
npm ERR! peer dep missing: ajv@^6.9.1, required by ajv-keywords@3.5.2
npm ERR! peer dep missing: graphql@^14.0.0 || ^15.0.0, required by @graphql-tools/merge@6.2.5
npm ERR! peer dep missing: graphql@^14.0.0 || ^15.0.0, required by @graphql-tools/schema@7.1.5
npm ERR! peer dep missing: graphql@^14.0.0 || ^15.0.0, required by @graphql-tools/utils@7.10.0
npm ERR! peer dep missing: graphql@^14.0.0 || ^15.0.0, required by @graphql-tools/schema@7.1.5
npm ERR! peer dep missing: graphql@^14.0.0 || ^15.0.0, required by @graphql-tools/utils@7.10.0
npm ERR! peer dep missing: graphql@^14.0.0 || ^15.0.0, required by @graphql-tools/utils@7.10.0
npm ERR! peer dep missing: graphql@^14.2.1 || ^15.0.0, required by apollo-graphql@0.9.5`

**Comment by denerFernandes** [comment]
I try to install all peer dep missing and work to me.

**Comment by jmcdo29** [comment]
`graphql@16` is not supported yet. Please downgrade to graphql 15

**Comment by denerFernandes** [comment]
Thanks man!
