### ISSUE TITLE
Hidden Elements from Introspection

### ISSUE THREAD

**Issue by jbool24** [nestjs/graphql#1861]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Not necessarily a problem.

### Describe the solution you'd like

Integration with `graphql-introspection-filtering` to selectively expose/hide things from the Introspection Query. Currently the schema is generated using decorations (code first approach) so it would be nice to allow a custom decorator to hide "private" nodes/fields from the schema introspection. More information about the technique here [Keeping certain parts of your GraphQL schema hidden from Introspection](https://dev.to/useanvil/keeping-certain-parts-of-your-graphql-schema-hidden-from-introspection-16l5)

### What is the motivation / use case for changing the behavior?

Public access usage sometimes should not include ALL parts of a schema. To achieve this without schema stitching or federation it would be nice to use a decorator to hide fields from introspection.

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

There are no plans to implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
