### ISSUE TITLE
Distinct whether an injectable is a resolver or not in runtime

### ISSUE THREAD

**Issue by biyingshuai** [nestjs/graphql#1867]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I want to know if an injectable is a resolver and then filter them。The GqlAuthGuard is registered global   the 'this.reflector.getAll(RESOLVER_TYPE_METADATA.....'   can help me do this, but it is imported from @nestjs/graphql/dist/graphql.constants, which is a little tricky。Should it be exported from index.d.js or there are other functions can help me？

`
import { ExecutionContext, Injectable, UnauthorizedException, } from '@nestjs/common';
import { AuthGuard } from '@nestjs/passport';
import { GqlExecutionContext } from '@nestjs/graphql';
import { RESOLVER_TYPE_METADATA } from '@nestjs/graphql/dist/graphql.constants';
import { Reflector } from '@nestjs/core';

@Injectable()
export class GqlAuthGuard extends AuthGuard('jwt') {
    constructor(private reflector: Reflector) {
        super();
    }
    canActivate(context: ExecutionContext) {
        const resolvers = this.reflector.getAll(RESOLVER_TYPE_METADATA, [
            context.getClass(),
        ]);
        if (!(resolvers.length && resolvers[0])) {
            return true;
        }
        return super.canActivate(context);
    }

    getRequest(context: ExecutionContext) {
        const ctx = GqlExecutionContext.create(context);
        return ctx.getContext().req;
    }
}
`

### Describe the solution you'd like

 expose the RESOLVER_TYPE_METADATA
or
are there other way?

### What is the motivation / use case for changing the behavior?

I want to know if an injectable is a resolver and then filter them in run time

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
