### ISSUE TITLE
Putting a custom scalar in "providers" before it's used causes an error

### ISSUE THREAD

**Issue by synic** [nestjs/graphql#1870]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Defining a custom scalar (in my example, `WeiScalar`) and putting it in `providers` before actually using it anywhere causes an error:

```
/home/synic/Projects/nestjs-custom-scalar/node_modules/@nestjs/graphql/dist/schema/src/addResolversToSchema.js:18
    Object.keys(resolvers).forEach(typeName => {
                           ^
Error: "Wei" defined in resolvers, but not in schema
    at /home/synic/Projects/nestjs-custom-scalar/node_modules/@nestjs/graphql/dist/schema/src/addResolversToSchema.js:35:23
    at Array.forEach (<anonymous>)
    at addResolversToSchema (/home/synic/Projects/nestjs-custom-scalar/node_modules/@nestjs/graphql/dist/schema/src/addResolversToSchema.js:18:28)
    at schemaTransforms (/home/synic/Projects/nestjs-custom-scalar/node_modules/@nestjs/graphql/dist/schema/src/makeExecutableSchema.js:66:41)
    at /home/synic/Projects/nestjs-custom-scalar/node_modules/@nestjs/graphql/dist/schema/src/makeExecutableSchema.js:108:65
    at Array.reduce (<anonymous>)
    at makeExecutableSchema (/home/synic/Projects/nestjs-custom-scalar/node_modules/@nestjs/graphql/dist/schema/src/makeExecutableSchema.js:108:29)
    at GraphQLFactory.mergeOptions (/home/synic/Projects/nestjs-custom-scalar/node_modules/@nestjs/graphql/dist/graphql.factory.js:34:72)
    at GraphQLModule.onModuleInit (/home/synic/Projects/nestjs-custom-scalar/node_modules/@nestjs/graphql/dist/graphql.module.js:93:31)
    at Object.callModuleInitHook (/home/synic/Projects/nestjs-custom-scalar/node_modules/@nestjs/core/hooks/on-module-init.hook.js:51:9)
```

### Minimum reproduction code

https://github.com/synic/nestjs-custom-scalar

### Steps to reproduce

1. Define a custom scalar
2. Put it in `providers` in one of your modules
3. Try to start nest

### Expected behavior

It should NOT throw an error

### Package version

@nestjs/graphql@9.1.1

### Graphql version

`graphql`: graphql@15.7.2
`apollo-server-express`: apollo-server-express@3.5.0

### NestJS version

8.2.0

### Node.js version

v16.10.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by immint023** [comment]
@synic The reason is that you did not use custom scalar in any resolver, so your `app.resolver.ts` should be like this
```typescript
import { Query, Resolver } from '@nestjs/graphql';
import { Wei } from './wei.scalar';

@Resolver()
export class AppResolver {
  @Query(() => Wei)
  async hello() {
    return new Wei('Hello World!');
  }
}
```

**Comment by synic** [comment]
Yes, I know that the reason is that I didn't use the scalar. However, I believe that it is not uncommon to define a scalar before it is in use, or even have a scalar defined and unknowingly remove the only model that used it.

This should not cause an unrecoverable error with an obscure message if at all possible. I only discovered the cause of the problem by accident. This obscure error sent me on a wild goose chase thinking I had defined the scalar incorrectly, even though it was nearly identical to another scalar that seemed to work without issue.

If you define a service and put it in providers even before it's being used, it doesn't prevent NestJS from starting, it's perfectly acceptable to declare a provider before it's used, except in this one case. It is very confusing

**Comment by kamilmysliwiec** [comment]
This error:

> Error: "Wei" defined in resolvers, but not in schema

Is thrown by the underlying library, not NestJS. We detect a scalar (as it was registered as a provider) and automatically generate a resolver for it. There's no built-in mechanism that would check whether you use this type in a schema or not. Underlying tools (i.a. `@graphql-tools/merge`) are in charge of that. You can turn this off https://www.graphql-tools.com/docs/api/interfaces/utils_src.IResolverValidationOptions#requireresolverstomatchschema

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
