### ISSUE TITLE
Unable to use Subscriptions

### ISSUE THREAD

**Issue by Shivam-Pathak1** [nestjs/graphql#1899]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I have been trying to implement graphQL subscriptions. The idea is to publish the created object inside the mutation using PubSub with a topic name. The subscription filters the object based on `videoAdded`.
When I call the subscription on GraphQL Playground, it listens for a few milliseconds and then responds with the message:
```
{
  "error": "Could not connect to websocket endpoint ws://localhost:4000/graphql. Please check if the endpoint url is correct."
}
```
I tried `graphql-ws,  subscriptions-transport-ws`, and `installSubscriptionHandlers` but nothing worked. Is there a way I can indicate the subscription to keep alive?
My `app.module.ts` looks like this:

```
import { Module } from '@nestjs/common';
import { GraphQLModule } from '@nestjs/graphql';
import { VideoModule } from './videos/video.module';

@Module({
  imports: [
    VideoModule,
    GraphQLModule.forRoot({
      typePaths: ['./**/*.graphql'],
      installSubscriptionHandlers: true,
    }),
  ],
})
export class AppModule {}

```
The subscription in my resolver is something like this:
 ```
  @Subscription(returns => Video, {
    name: 'videoAdded',
    filter: (payload, variables) =>
      payload.videoAdded.title === variables.titile,
  })
  videoAdded() {
    this.pubSub.asyncIterator('videoAdded');
  }
}
```
And the mutation for publishing is:
```
 @Mutation('createVideo')
  async create(@Args('input') args: CreateVideoDto): Promise<Video> {
    const videoAdded = await this.videoService.create(args);
    this.pubSub.publish('videoAdded', { videoAdded: videoAdded });
    return videoAdded;
  }
```
I am calling it like this in the playground:
```

subscription($title: String!){
  videoAdded(title: $title) {
    id
    title
    url
  }
}
```

### Minimum reproduction code

https://github.com/Shivam-Pathak1/gql-subscription

### Expected behavior

The playground should show listening and print in case a video is created.

### Package version

9.0.6

### Graphql version

 "graphql": "^15.7.2",
   "apollo-server-express": "^3.4.0",

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
