### ISSUE TITLE
Resolver throws scope error if there are both queries and subscriptions

### ISSUE THREAD

**Issue by W4G1** [nestjs/graphql#1913]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Currently, if you have a resolver with both a Query handler and a Subscription handler you get the error:

`"UsersResolver" resolver is request or transient-scoped. Resolvers that register subscriptions with the "@Subscription()" decorator must be static (singleton).`

If you remove either one, the code works just fine.

### Minimum reproduction code

https://gist.github.com/W4G1/9a9fa9ca670b3080de4b02a7e428b86c

### Steps to reproduce

`npm start:dev`

### Expected behavior

No error, or a way to specify the scope of the resolver/query/subscription.

### Package version

9.1.2

### Graphql version

`graphql`: 15.5.1
`apollo-server-express`: 2.25.2
`graphql-subscriptions`: 1.0.0

### NestJS version

8.2.3

### Node.js version

14.17.3

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
