### ISSUE TITLE
@Directive decorator does not affect generated schema

### ISSUE THREAD

**Issue by pazdernikpavel** [nestjs/graphql#1918]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Whenever you declare `@Directive(...)` decorator on query, mutation, field, etc. it simply does not appear in generated `schema.gql` in code first approach. I've found a lot of issues describing this problem, but usually got closed on lack of reproduction repository.
I declared directive decorator in my [resolver](https://github.com/pazdernikpavel/code-first-graphql-directives/blob/main/src/car.resolver.ts) which implement build-in deprecated directive and one [custom made](https://github.com/pazdernikpavel/code-first-graphql-directives/blob/main/src/customDirective.directive.ts) directive. Both examples are done following official [documentation](https://docs.nestjs.com/graphql/directives) but none of these two seems to be working. Previous issue declaring this problem was closed due to apollo server problem, however it seems to be problem with [@Directive](https://github.com/nestjs/graphql/blob/master/lib/decorators/directive.decorator.ts) decorator itself and the way it generates the schema with code first approach.

### Minimum reproduction code

https://github.com/pazdernikpavel/code-first-graphql-directives

### Steps to reproduce

1. Install dependencies
2. Run `npm run start:dev` (or any other available command to make the server running)
3. Check `src/schema.gql`, you will find out that declared directives are missing.
4. (Optional) You can remove generated schema, but new one will generated just as the old one.

### Expected behavior

When you use directives in code-first approach, I would expect to get this

```
type Car {
  name: String!
}

type Query {
  getCars: [Car!]! @deprecated
  getCar: Car! @isAdmin
}
```

instead of this

```
type Car {
  name: String!
}

type Query {
  getCars: [Car!]!
  getCar: Car!
}
```

### Package version

^9.1.2

### Graphql version

```
"apollo-server-express": "^3.5.0",
"graphql": "^15.8.0",
"@nestjs/graphql": "^9.1.2",
"@graphql-tools/utils": "^7.7.3",

```

### NestJS version

^8.0.0

### Node.js version

14.16.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please search through some of our old issues on this (this has been discussed several times in the past).
