### ISSUE TITLE
Logging fro Graphql resolvers is not providing useful information

### ISSUE THREAD

**Issue by wave-light** [nestjs/graphql#1928]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

As mentioned in this issue: https://github.com/nestjs/graphql/issues/649
There is no meaningful logging for GraphQL resolvers. The thread was closed with a comment stating that this would be achievable using plugins, however it is not clear how this can be done.

### Describe the solution you'd like

I would like to have a way to output meaningful logs for GraphQL queries, including:

- Log the graphql query and variables for a request
- Log the status code
- Log the time taken by the whole request
- If there was an error, log it

### What is the motivation / use case for changing the behavior?

This would be useful in logging GraphQL queries and errors.

**Comment by jmcdo29** [comment]
This information can definitely be added in via plugins or interceptors. I have a logging library [ogma](https://github.com/jmcdo29/ogma) that logs most what what you've outlined above (only missing the query and variables) and there's ways to extend it to add that in. [You can read the docs for the library here](https://jmcdo29.github.io/ogma/docs).
