### ISSUE TITLE
Responses are not being stored in Redis

### ISSUE THREAD

**Issue by bmajkut** [nestjs/graphql#1942]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I am quite desperate right now and I am looking for any kind of help. I am trying to setup cache mechanism in my project using GraphQL and Redis. This is how I configure GraphQLModule:
```GraphQLModule.forRoot({
cache: new BaseRedisCache({
                client: new Redis({
                    host: 'localhost',
                    port: 6379,
                    password: 'Zaq1xsw@',
                }),
                cacheControl: {
                    defaultMaxAge: 10000
                },
            }),
            plugins: [
                responseCachePlugin()
            ],
            autoSchemaFile: path.resolve(__dirname, `../generated/schema.graphql`),
            installSubscriptionHandlers: true,
        }),
```
This is how I’ve created queries and mutations:
```   @Resolver()
    export class AuthResolver {
constructor(
    private readonly prismaService: PrismaService,
    private readonly authService: AuthService,
){}

@Query(returns => String)
async testowe(@Args(`input`) input: String, @Info() info: any) {
    info.cacheControl.setCacheHint({ maxAge: 5000, scope: 'PUBLIC' });
    return 'test';
}}
```

When I am using GraphQL Playground and try this query I get the response and header looks like that:
```
    HTTP/1.1 200 OK
    X-Powered-By: Express
    Access-Control-Allow-Origin: *
    Content-Type: application/json; charset=utf-8
    cache-control: max-age=5000, public
    Content-Length: 28
    ETag: W/"1c-2Df/lONPXcLzs1yVERHhOmONyns"
    Date: Tue, 28 Dec 2021 21:35:11 GMT
    Connection: keep-alive
    Keep-Alive: timeout=5
```

As You may see there is a part with “cache-control”. My problem is that I cannot see any keys or values stored in Redis. I am connected to Redis server with redis-cli tool and Ive tried “KEYS ‘*’” command. There is nothing stored in Redis.

Also I have problem with more complex queries - I do not even get a header with “cache-control” part.

Do You have any idea what I am doing wrong here? Should I be able to see stored values in Redis with such approach? Thank You in advance for any advice.

### Minimum reproduction code

https://github.com/bmajkut/graphql-redis

### Expected behavior

Query response should be stored in Redis and the keys should be visible with redis-cli "KEYS *" command.

### Package version

8.1.3

### Graphql version

`graphql`: 
`apollo-server-express`: 
`apollo-server-fastify`: 

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
