### ISSUE TITLE
graphql-upload & invalid response bodies

### ISSUE THREAD

**Issue by j** [nestjs/graphql#1955]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

If `graphql-upload` middlware errors, the error isn't formatted as a `graphql` type.  I confirmed that it's still `http` when using a catch all exception handler.

Is there a way to have `graphql-upload` express middleware be converted to a `graphql` context type to have properly formatted graphql errors by chance?

### Minimum reproduction code

...

### Steps to reproduce

```typescript
// app bootstrap...

const app = await NestFactory.create<NestExpressApplication>(AppModule);
app.use(graphqlUploadExpress());


```

```curl
curl --request POST \
  --url http://localhost:4000/ \
  --header 'Content-Type: multipart/form-data; boundary=---011000010111000001101001' \
  --form 'operations={
	"query": "mutation($input: UploadInput!) { upload(input: $input) { ok } }",
	"variables": { "input": { "files": [null] } }
}' \
  --form 'mapz={}'
```

### Expected behavior

`mapz` is not valid, so `graphql-upload` errors.  I want this to bubble down to the graphql error to format it as a valid GraphQL request.

The error is:

```json
{
	"statusCode": 400,
	"message": "Missing multipart field ‘map’ (https://github.com/jaydenseric/graphql-multipart-request-spec)."
}
```

I'd like to have:

```json
{
	"errors": [
		{
			"message": "Missing multipart field ‘map’ (https://github.com/jaydenseric/graphql-multipart-request-spec).",
		}
	]
}
```

Is this possible?

### Package version

9.1.2

### Graphql version

`graphql`: 15.8.0
`apollo-server-express`: 3.6.1

### NestJS version

^8.0.0

### Node.js version

16

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Given that the `graphqlUploadExpress()` is registered as a middleware it runs outside of the GQL context. In this case, you have to manually map errors to be more GQL-friendly.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
