### ISSUE TITLE
Migration to GraphiQL

### ISSUE THREAD

**Issue by all2pie** [nestjs/graphql#1956]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Not able to share Playground or Studio in production with Federation

### Describe the solution you'd like

Please add GraphiQL by default for both Apollo and Federation 

### What is the motivation / use case for changing the behavior?

https://github.com/graphql/graphql-playground/issues/1143

**Comment by kamilmysliwiec** [comment]
There are currently no plans to migrate to GraphiQL. This will likely change once they release v2 that will have feature parity with GraphQL Playground.
