### ISSUE TITLE
Unknown behaviour when using decorators as a property object. Eg: `@Decoratos.Some()`

### ISSUE THREAD

**Issue by arthurfiorette** [nestjs/graphql#1964]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

It can be reproduced with any modified decorator that lives under a parent object. Doesn't matter if it was from star import, from an exported namespace or just a simple object.

```ts
// Simplified example

const Decorators = { Decorator: () => ExternalDecorator(someParam) };
// Or
import * as Decorators from '...'

class SomeClass {
  @Decorators.Decorator()
  field: string;
}
```

It get's stuck on this:

![image](https://user-images.githubusercontent.com/47537704/150838994-faf0a8a0-20af-4669-874f-b93c233305f0.png)

### Minimum reproduction code

https://github.com/arthurfiorette/nestj-graphql-bug

### Steps to reproduce

1. Any nest command that will try to compile / execute the above code

### Expected behavior

To works fine or throws a recognizable error.

### Package version

9.1.1

### Graphql version

`graphql`: 15.7.2
`apollo-server-fastify`: 3.5.0

### NestJS version

8.2.0

### Node.js version

v16.13.1

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [x] Linux (WSL)

### Other

I've tracked down the issue to this line:

https://github.com/nestjs/graphql/blob/00f7f40a4a8f566897d2fc07a164e3c410177880/packages/graphql/lib/plugin/utils/ast-utils.ts#L147-L149

Apparently when using by property access, the `expression.kind` has the value of `SyntaxKind.PropertyAccessExpression(205)` not `SyntaxKind.Identifier(79)`.

I don't know why the `expression` has to be an `Identifier`, but it might be able to be `PropertyAccessExpression`. Even so, the error generated should have an explanatory message or a link to this issue.

**Comment by jmcdo29** [comment]
Please provide a [minimum reproduction repository](http://minimum-reproduction.wtf).

**Comment by arthurfiorette** [comment]
@jmcdo29 added.

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR to address this issue @arthurfiorette?

**Comment by arthurfiorette** [comment]
I'm a little busy these days, but if the PR is just to add an useful message to the issue, i'll do it. Anything more than that i'm afraid that someone else would have to fix it :(

**Comment by ybh1760** [comment]
https://github.com/nestjs/graphql/blob/00f7f40a4a8f566897d2fc07a164e3c410177880/packages/graphql/lib/plugin/utils/ast-utils.ts#L145-L151
I think getIdentifierFromName function shoud check identifier.kind is SyntaxKind.Identifier rather than expression.kind..

like below
```
function getIdentifierFromName(expression: LeftHandSideExpression) {
  const identifier = getNameFromExpression(expression);
  if (identifier && identifier.kind !== SyntaxKind.Identifier) {
    throw new Error();
  }
  return identifier;
}
```
what do you think about this suggestion?

**Comment by arthurfiorette** [comment]
If this fixes it, no problem at all.
