### ISSUE TITLE
Errors thrown in context function aren't logged

### ISSUE THREAD

**Issue by trymoto** [nestjs/graphql#1994]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Error, generated in context function, is returned to the client but isn't logged by logger.

### Minimum reproduction code

https://github.com/trymoto/gql-context-example

### Steps to reproduce

1. `npm i`
2. `npm start`
3. Run any `gql` query against `http://localhost:3000/grqphql` (for example, using apollo explorer) https://studio.apollographql.com/sandbox/explorer?endpoint=http%3A%2F%2Flocalhost%3A3000%2Fgraphql&explorerURLState=N4IgJg9gxgrgtgUwHYBcQC4QEcYIE4CeABAIq6FHAA6SRRCAHgIZwAOANgjQL4jdA

### Expected behavior

Error, generated in context function, is returned to the client AND logged by logger.

### Package version

9.1.2

### Graphql version

`graphql`: 15.8.0
`apollo-server-express`: 3.6.2

### NestJS version

8.0.0

### Node.js version

17.3.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by trymoto** [comment]
Any error thrown in resolver gets logged fine though.

**Comment by kamilmysliwiec** [comment]
Context function is being executed internally within the Apollo server package before the request even hits the appropriate query/mutation handler (resolver). There's nothing we can do on our side to fix this issue
