### ISSUE TITLE
Directives to be reflected in the generated schema definition file

### ISSUE THREAD

**Issue by raulburigo** [nestjs/graphql#1997]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

As it is today, and really well documented, "Directives applied through the @Directive() decorator will not be reflected in the generated schema definition file."

I know this is at topic long discussed before, but I talked to people who faced the same issue and had to work some weird solutions or even changed to schema-first approach to avoid this. So I would like to raise it again.

https://github.com/raulburigo/subgraph

### Describe the solution you'd like

It would be really helpfull if the generated schema file reflected the directives applied through the @Directives()

### What is the motivation / use case for changing the behavior?

The main problem for us today is that we are trying to use Rover CLI to manage our federated schemas, and the missing Directives prevents us to do it. We managed to get the schema with the directives after the creation of the app (example in the repo), but I don't think this is the best solution.

**Comment by kamilmysliwiec** [comment]
We're tracking this here https://github.com/nestjs/graphql/pull/1780
