### ISSUE TITLE
[@nestjs/mercurius] Mercurius loaders

### ISSUE THREAD

**Issue by Davide-Gheri** [nestjs/graphql#2001]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Mercurius has a very nice feature called [Loaders](https://mercurius.dev/#/docs/loaders), in short, it's a solution to the n+1 query problem of GraphQL.
The current `@nestjs/mercurius` driver does not support it

### Describe the solution you'd like

Integrate Mercurius loaders in the `@nestjs/mercurius` driver. We could get inspiration from my old solution in [nestjs-mercurius](https://github.com/Davide-Gheri/nestjs-mercurius) package, especially the [GraphQLFactory](https://github.com/Davide-Gheri/nestjs-mercurius/blob/master/lib/factories/graphql.factory.ts), the [LoaderExplorerService](https://github.com/Davide-Gheri/nestjs-mercurius/blob/master/lib/services/loaders-explorer.service.ts) and the [decorator](https://github.com/Davide-Gheri/nestjs-mercurius/blob/master/lib/decorators/resolve-loader.decorator.ts)

We could define a `@ResolveLoader` inside the `@nestjs/mercurius` package and modify the `MercuriusDriver` to find (via an ExplorerService) and add them to the mercurius plugin options

### What is the motivation / use case for changing the behavior?

Support this nice feature Mercurius has

**Comment by kamilmysliwiec** [comment]
Hey Davide, long time no see!
This is actually intentional. There's no plan to bring the loaders feature to this driver as you can create loaders with the request-scoped providers, making your code platform-agnostic and not tied to any specific driver (portable between Apollo and Mercurius)
