### ISSUE TITLE
ERROR [GraphQLModule] Missing "driver" option. exits process < v10

### ISSUE THREAD

**Issue by jbool24** [nestjs/graphql#2003]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Previous issue referenced was closed but was incorrect addressed. https://github.com/nestjs/graphql/issues/2000#issue-1130154009
The issue is in fact present as early as 9.2.7. This should not throw anything more than an warning before v10.

Confirmed that the package is at exact 9.2.7
```bash
> yarn list --pattern=@nestjs/graphql                                                                                                                                                           
yarn list v1.22.17
└─ @nestjs/graphql@9.2.7
```

Nest process exits with `error 1` with the following:
```
[Nest] 28624  - 02/10/2022, 5:25:00 PM   ERROR [GraphQLModule] Missing "driver" option. In the latest version of "@nestjs/graphql" package (v10) a new required configuration property called "driver" has been introduced. Check out the official documentation for more details on how to migrate (https://docs.nestjs.com/graphql/migration-guide).
```

**Issues should not be closed before the issue author has an opportunity to acknowledge (at least 24-hrs). The previous issue was closed in under 5mins from when it was opened. This a valid bug and is not a user-land error. Thanks.**

### Minimum reproduction code

n/a

### Steps to reproduce

1. yarn add @nestjs/graphql@9.2.7
2. yarn nest start

### Expected behavior

Anything < v10 should only be a warning and not cause the process to exit.

### Package version

9.2.7

### Graphql version

`graphql`: 15.8.0
`apollo-server-express`:  3.5.0
`apollo-server-fastify`: n/a

```bash
❯ yarn list --pattern=graphql                                                                                                                                                                   
yarn list v1.22.17
├─ @apollographql/apollo-tools@0.5.2
├─ @apollographql/graphql-playground-html@1.6.29
├─ @graphql-tools/merge@8.2.1
│  └─ @graphql-tools/utils@8.5.3
├─ @graphql-tools/mock@8.4.4
│  └─ @graphql-tools/utils@8.5.3
├─ @graphql-tools/schema@8.3.1
│  └─ @graphql-tools/utils@8.5.3
├─ @graphql-tools/utils@7.10.0
├─ @nestjs/apollo@10.0.0
│  └─ @graphql-tools/utils@8.6.1
├─ @nestjs/graphql@9.2.7
│  └─ @graphql-tools/utils@8.6.1
├─ @types/graphql-upload@8.0.7
│  └─ graphql@15.8.0
├─ apollo-graphql@0.9.5
├─ apollo-server-core@3.5.0
│  └─ @graphql-tools/utils@8.5.3
├─ graphql-parse-resolve-info@4.12.0
├─ graphql-tag@2.12.6
├─ graphql-upload@12.0.0
├─ graphql-ws@5.5.5
└─ graphql@15.7.2
```

```bash
❯ yarn list --pattern=apollo                                                                                                                                                                    
yarn list v1.22.17
├─ @apollo/protobufjs@1.2.2
├─ @apollographql/apollo-tools@0.5.2
├─ @apollographql/graphql-playground-html@1.6.29
├─ @nestjs/apollo@10.0.0
├─ apollo-datasource@3.3.0
├─ apollo-graphql@0.9.5
├─ apollo-reporting-protobuf@3.2.0
├─ apollo-server-caching@3.3.0
├─ apollo-server-core@3.5.0
├─ apollo-server-env@4.2.0
├─ apollo-server-errors@3.3.0
├─ apollo-server-express@3.5.0
├─ apollo-server-plugin-base@3.4.0
├─ apollo-server-types@3.4.0
└─ apollo-server@3.5.0
```

### NestJS version

8.2.3

### Node.js version

14.17.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/graphql/issues/2000#issuecomment-1034978313

> Also, please double-check if you haven't accidentally installed the version published under the next tag. The latest working v9 version is [9.1.2](https://www.npmjs.com/package/@nestjs/graphql/v/9.1.2) (published under the latest tag)

The latest working v9 version is 9.1.2 (`latest` tag!), not 9.2.7. 9.2.7 is published under the `next` tag (which indicates it's experimental and shouldn't be used https://stackoverflow.com/a/66662006/6696689). See https://www.npmjs.com/package/@nestjs/graphql (Versions tab)
