### ISSUE TITLE
 Error  The "@nestjs/graphql" plugin is not compatible with Nest CLI. Neither "after()" nor "before()" nor "afterDeclarations()" function have been provided.

### ISSUE THREAD

**Issue by Tony133** [nestjs/graphql#2007]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I did a quick test it looks like this error: `Error The "@nestjs/graphql" plugin is not compatible with Nest CLI. Neither "after()" nor "before()" nor "afterDeclarations()"` function have been provided. Is provoked by some  plugins in `nest-cli.json` . In fact in this example: `https://github.com/nestjs/nest/tree/master/sample/23-graphql-code-first`, gives the error, removing the plugins no longer gives it.

The error was encountered only in code-first mode.

### Minimum reproduction code

https://github.com/nestjs/nest/tree/master/sample/23-graphql-code-first

### Steps to reproduce

npm install
npm run start:dev

### Expected behavior

that works when inserting plugins in the `nest-cli`, such as this:

```json
{
  "compilerOptions": {
    "plugins": [
      {
        "name": "@nestjs/graphql",
        "options": {
          "introspectComments": true
        }
      }
    ]
  }
}
```

### Package version

@nestjs/graphql: 10.0.0

### Graphql version

`graphql`: ^16.3.0
`apollo-server-express`: 3.6.2

### NestJS version

8.2.3

### Node.js version

16.13.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/graphql/issues/2005

**Comment by Tony133** [comment]
Ok, Thanks for the reply 👍
