### ISSUE TITLE
Mercurius gateway only get queries and mutations from one service

### ISSUE THREAD

**Issue by SirReiva** [nestjs/graphql#2008]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

user service definitions in playground:
![image](https://user-images.githubusercontent.com/50754871/153675352-68162adc-9590-421b-9b33-092bf3b05d98.png)
post service definitions in playground:
![image](https://user-images.githubusercontent.com/50754871/153675518-8531d3ed-7f90-47c6-ade0-e861e22d7518.png)
Gateway definitions:
![image](https://user-images.githubusercontent.com/50754871/153675619-29bc1f79-7b80-4f9c-bb3c-509469c58f71.png)
Only appear queries from one service but schema definitions are loaded
![image](https://user-images.githubusercontent.com/50754871/153676189-04b14302-e7d5-49d0-9d58-31b296099066.png)

### Minimum reproduction code

https://github.com/SirReiva/nest-mersuruis-gateway-gqlv10-issue

### Steps to reproduce

-npm i
-npm run start:user
-npm run start:post
-wait for services start...
-npm run start:gateway

### Expected behavior

Load all queries and mutations from all services

### Package version

10.0.2

### Graphql version

![image](https://user-images.githubusercontent.com/50754871/153676420-825b0bbf-1128-4811-8e72-d1d2332b6e20.png)

### NestJS version

8.2.6

### Node.js version

16.13.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by Davide-Gheri** [comment]
This is probably related to this Mercurius issue:
https://github.com/mercurius-js/mercurius/issues/273

**Comment by kamilmysliwiec** [comment]
@Davide-Gheri would you like to create a PR with the same workaround that was merged to the nestjs-mercurius package? 🤞

**Comment by Davide-Gheri** [comment]
@kamilmysliwiec yes! I'll work on it these days.

**Comment by smolinari** [comment]
@Davide-Gheri - Nice to see you here helping out. Awesome!! :)

Scott

**Comment by kamilmysliwiec** [comment]
Fixed in 10.0.4 thanks to @Davide-Gheri contribution! 🔥
