### ISSUE TITLE
ERROR `GraphQLModule.forRoot<ApolloDriverConfig>` Expected 0 type arguments, but got 1

### ISSUE THREAD

**Issue by Gasiek** [nestjs/graphql#2011]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

With the code below
```
import { ApolloDriver, ApolloDriverConfig } from '@nestjs/apollo';

GraphQLModule.forRoot<ApolloDriverConfig>({
      driver: ApolloDriver,
      autoSchemaFile: join(process.cwd(), 'src/schema.gql'),
      installSubscriptionHandlers: true
    }),
```

In local environment everything is fine, however, when run on gitlab pipeline, the following error is presented:
```
src/app/app.module.ts:28:27 - error TS[25](https://gitlab.com/a4852/backend/-/jobs/2084558381#L25)58: Expected 0 type arguments, but got 1.
[28](https://gitlab.com/a4852/backend/-/jobs/2084558381#L28)     GraphQLModule.forRoot<ApolloDriverConfig>({
                             ~~~~~~~~~~~~~~~~~~
Found 1 error(s).
Cleaning up project directory and file based variables
00:00
ERROR: Job failed: exit code 1
```

When tried without `Type` specification, the following error is shown:
```
$ npm run build
> backend@0.0.1 prebuild
> rimraf dist
> backend@0.0.1 build
> nest build
src/app/app.module.ts:29:7 - error TS[23](https://gitlab.com/a4852/backend/-/jobs/2084515625#L23)45: Argument of type '{ driver: typeof ApolloDriver; autoSchemaFile: string; installSubscriptionHandlers: true; }' is not assignable to parameter of type 'GqlModuleOptions'.
  Object literal may only specify known properties, and 'driver' does not exist in type 'GqlModuleOptions'.
[29](https://gitlab.com/a4852/backend/-/jobs/2084515625#L29)       driver: ApolloDriver,
         ~~~~~~~~~~~~~~~~~~~~
Found 1 error(s).
Cleaning up project directory and file based variables
00:01
ERROR: Job failed: exit code 1
```

### Minimum reproduction code

n/a

### Steps to reproduce

1. `npm install @nestjs/graphql@^9.1.2`
2. use forRoot to init GraphQLModule with driver setting set to ApolloDriver
3. `npm run build`

### Expected behavior

App should build correctly

### Package version

9.1.2

### Graphql version

`graphql`: 15.7.2
`apollo-server-express`: 3.6.3
`@nestjs/apollo`: 10.0.2

### NestJS version

8.0.0

### Node.js version

16.13.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
Why are you using `@nestjs/apollo` with `@nestjs/graphql@9.1.2`?

**Comment by Gasiek** [comment]
> Why are you using `@nestjs/apollo` with `@nestjs/graphql@9.1.2`?

That's what documentation says for using GraphQL with Apollo server
[https://docs.nestjs.com/graphql/quick-start](url)

![image](https://user-images.githubusercontent.com/44849134/153719959-063510aa-d528-46a1-9c7c-28929f5fee30.png)

**Comment by jmcdo29** [comment]
The current [`@nestjs/graphql`](https://www.npmjs.com/package/@nestjs/graphql) package in [10.0.2](https://github.com/nestjs/graphql/blob/master/packages/graphql/package.json#L3). I would guess a package-lock kept your install on v9 for some reason. `@nestjs/graphql` _should_ be on v10 to work with `@nestjs/apollo`

**Comment by jmcdo29** [comment]
Apollo 3 and is a graphql framework. `@nestjs/grapqhl10` was a major re-work of `@nestjs/graphql` to allow for switching out apollo for other Gql frameworks, like `mercurius`. That warning is saying that `@nestjs/graphql@>=9` **and** `@nestjs/apollo@^10` are both Apollo 3 compatible. Not that `@nestjs/graphql@9` and `@nestjs/apollo@10` work together.

Perhaps we should make that more celar

**Comment by Gasiek** [comment]
Upgrading `@nestjs/graphql` to 10.0.2 worked.

Thanks for help

**Comment by nealoke** [comment]
Wasn't clear for me either 🙈
