### ISSUE TITLE
Bug with asserting a new "driver" configuration option of GraphQLModule when using with forRootAsync

### ISSUE THREAD

**Issue by aenkas** [nestjs/graphql#2013]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When use forRootAsync options for GraphQLModule like this:
` GraphQLModule.forRootAsync({ useFactory: () => ({ driver: ApolloDriver }) })`

Applcation start crashes with error:
`ERROR [GraphQLModule] Missing "driver" option. In the latest version of "@nestjs/graphql" package (v10) a new required configuration property called "driver" has been introduced. Check out the official documentation for more details on how to migrate (https://docs.nestjs.com/graphql/migration-guide). Example:
GraphQLModule.forRoot<ApolloDriverConfig>({
  driver: ApolloDriver,
})`

I found that in new version (v10) there is new driver assertion in module forRootAsync method:
https://github.com/nestjs/graphql/blob/589a444589a5196d6afd2c80c5fe318ee408e3d2/packages/graphql/lib/graphql.module.ts#L91
And using method that  check "driver" property of input object:
https://github.com/nestjs/graphql/blob/589a444589a5196d6afd2c80c5fe318ee408e3d2/packages/graphql/lib/graphql.module.ts#L162

So, when use forRootAsync there are obviously no driver options.

I found workaround for this inserting driver option near useFactory/useClass etc. :
` GraphQLModule.forRootAsync({ driver: ApolloDriver, useFactory: () => ({ driver: ApolloDriver }) })`

With this it's OK but I suppose that should be fixed, thanks.

### Minimum reproduction code

n/a

### Steps to reproduce

1. npm install @nestjs/graphql@^10.0.2
2. use forRootAsync to init GraphQLModule with useFactory method driver setting set to ApolloDriver
3. npm run start

### Expected behavior

Driver assertion for async module options should work correct.

### Package version

10.0.2

### Graphql version

`graphql`: 16.3.0
`apollo-server-express`: 3.6.3

### NestJS version

8.2.6

### Node.js version

16.13.2

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
Based on the `GqlModuleAsyncOptions` this looks like the expected behavior

**Comment by aenkas** [comment]
Oh my bad, sorry, closing
