### ISSUE TITLE
Add Plugins to Mercurius

### ISSUE THREAD

**Issue by tugascript** [nestjs/graphql#2015]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Apart from mercurius-upload most plugins for mercurius have to be registered after mercurius is registered, therefore they should be registered in the driver.

### Describe the solution you'd like

A parameter on the MercuriusDriverConfig with an array of plugins that would be loaded with the driver.

### What is the motivation / use case for changing the behavior?

This is mostly for the users that want to use mercurius specific plugins like mercurius-cache, mercurius-auth, altair-fastify-plugin, etc.

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/graphql/pull/2016
