### ISSUE TITLE
Add support for Subscriptions with Mercurius federation driver

### ISSUE THREAD

**Issue by Davide-Gheri** [nestjs/graphql#2023]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Mercurius supports federated subscriptions, the mercurius federation driver does not.

It seems that the `buildSubgraphSchema` function (used in `GraphQLFederationFactory`) does not consider subscriptions resolvers, while `makeExecutableSchema` (used in `GraphQLFactory`) correctly adds them to the executableSchema.

### Describe the solution you'd like

I see two ways to add subscriptions support to the Mercurius federation driver:

- reimplement from scratch what `buildSubgraphSchema` does, maybe passing a `buildSchema` function as prop to the `GraphQLFederationFactory`, so each driver can implement its own solution, for example the Apollo driver could simply pass `buildSubgraphSchema` while the Mercurius driver could pass its own implementation

- add a second `transformSchema` in conjunction with the current `overrideOrExtendResolvers`, that gets subscriptions resolvers from the previously discovered resolvers and adds them to the Subscription fields:

```ts
// GraphQLFederationFactory#generateSchema
...

const resolvers = this.getResolvers(options.resolvers);

let executableSchema = buildSubgraphSchema({
  typeDefs: printSubgraphSchema(autogeneratedSchema),
  resolvers,
});

const subscriptionResolvers = resolvers.Subscription;
// if no Subscriptions are defined, this is undefined
if (subscriptionResolvers) {
  executableSchema = transformSchema(executableSchema, (type) => {
    if (isObjectType(type) && type.name === 'Subscription') {
      forEach(type.getFields(), (value, key) => {
        const resolver = subscriptionResolvers[key];
        if (resolver && !value.subscribe) {
          value.subscribe = resolver.subscribe;
        }
      })
    }
  })
}

executableSchema = this.overrideOrExtendResolvers(executableSchema, autoGeneratedSchema);

...
```
But I don't know if ApolloServer will complain about it

### What is the motivation / use case for changing the behavior?

Currently it is not possible to use Subscriptions with Mercurius, neither defining a custom Driver since the problem resides in the `@nestjs/graphql` package

**Comment by kamilmysliwiec** [comment]
Would you like to contribute to this issue @Davide-Gheri? :) 

> But I don't know if ApolloServer will complain about it

Maybe we should define a separate federation factory for Mercurius then

**Comment by Davide-Gheri** [comment]
Yes I'll onto it
