### ISSUE TITLE
Guard is not calling in queries _service and _entities (apollo federated)

### ISSUE THREAD

**Issue by endroca** [nestjs/graphql#2028]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I have an application in which I authenticate using guard to validate the user's jwt and fields middleware to verify the permission of the fields. But the `_service` and `_entities` queries do not trigger the guard

I've tried using the documentation, but I still can't solve the problem.
https://docs.nestjs.com/graphql/other-features#execute-enhancers-at-the-field-resolver-level

<img width="1680" alt="Screenshot 2022-02-18 at 18 17 21" src="https://user-images.githubusercontent.com/6523466/154762788-0af00e89-865a-4a98-8232-8ca170196ea1.png">
<img width="1680" alt="Screenshot 2022-02-18 at 18 17 42" src="https://user-images.githubusercontent.com/6523466/154762806-3eee04bf-9e82-467e-a91f-679e6b64a2e3.png">

### Minimum reproduction code

https://github.com/endroca/nestjs-repo

### Expected behavior

the guard is called using the `_service` and `_entities` queries.

### Package version

10.0.2

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by endroca** [comment]
> Please provide a [minimum reproduction repository](http://minimum-reproduction.wtf).

Ok, I updated the information

**Comment by jmcdo29** [comment]
Thanks for the reproduction. I get the feeling this is a limitation of how enhancers work in general. Without a route handler/resolver/class-method dedicated to handling the request, Nest doesn't have the appropriate metadata for binding the enhancer. The `_service` and `_entities` queries are out of the box implementations from `@apollo/federation` so I'm not sure if we'll be able to bind handlers for those or not. 

@kamilmysliwiec do you know if this is a limitation and if we should mention it in the docs?

**Comment by kamilmysliwiec** [comment]
This is the expected behavior. As @jmcdo29 mentioned above, "The _service and _entities queries are out of the box implementations from @apollo/federation", we can't bind any enhancers to their "resolvers".
