### ISSUE TITLE
Using the `key` directive automatically defines types as extensions.

### ISSUE THREAD

**Issue by Maldron** [nestjs/graphql#2029]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Adding a decorator like `@Directive('@key(fields: "id")')` to a class adds the `extend` keyword to the definition of the GraphQL type in the SDL.

As I understand it, adding the `@key` directive should [define a type as an entity](https://www.apollographql.com/docs/federation/entities/#defining-entities) in the subgraph that owns that type. Additional subgraphs that reference a type owned by another subgraph need the `extend` keyword to indicate that they're extending an entity. This bug causes every type with a key to be treated as an extension, so there's no primary entity, which breaks federation.

### Minimum reproduction code

https://github.com/Maldron/nest/tree/key_directive_automatically_makes_type_extension

### Steps to reproduce

Linked repo is a fork of the `nest` repo with `sample/23-graphql-code-first` tweaked to act as a subgraph.

1. `cd sample/23-graphql-code-first`
2. `npm install && npm run start`
3. Grab the sdl through `rover subgraph introspect http://localhost:3000/graphql` or by running the following curl
```
curl --request POST \
  --url http://localhost:3000/graphql \
  --header 'Content-Type: application/json' \
  --data '{"query":"  query {\n    _service {\n      sdl\n    }\n  }"}'
```

It'll produce the following definition for `Recipe`:
```
extend type Recipe @key(fields: "id") {
  id: ID!
  title: String!
  description: String
  creationDate: Date!
  ingredients: [String!]!
}
```

### Expected behavior

The `Recipe` type should be defined as an entity in the schema, not an extension. I.e.:
```
type Recipe @key(fields: "id") {
  id: ID!
  title: String!
  description: String
  creationDate: Date!
  ingredients: [String!]!
}
```

### Package version

10.0.2

### Graphql version

`graphql`: 16.3.0
`apollo-server-express`: 3.6.2

### NestJS version

8.2.3

### Node.js version

14.17.6

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by endroca** [comment]
Another problem is `extend type Query`. I can't extend the query

**Comment by Gamote** [comment]
Experiencing the same issue. I am happy to create a PR if some one can indicate what should be the starting point for investigating.

**Comment by Gamote** [comment]
We experience the same issue in our organization. To continue developing we're using this an ugly hack:

We created a patch that will update the `@nestjs/graphql/dist/federation/graphql-federation.factory.js:123` file from:

```
if (key === '_service') {
    value.resolve = function resolve() {
        return {
            sdl: printSchema(autoGeneratedSchema).replace('type Query {', 'type Query @extends {')
              .replace('type Mutation {', 'type Mutation @extends {')
              .replace('type Subscription {', 'type Subscription @extends {')
...
```

to

```
if (key === '_service') {
    value.resolve = function resolve() {
        return {
            sdl: printSchema(autoGeneratedSchema).replace('type Query {', 'type Query @extends {')
              .replace('type Mutation {', 'type Mutation @extends {')
              .replace('type Subscription {', 'type Subscription @extends {')
              .replace('extend type User', 'type User') // <-- manually added
              .replace('extend type Wishlist', 'type Post'), // <-- manually added
```

We of course know that this is not something that we want in production, so I will be more than happy to create a PR with the fix if anyone can point me into the right direction as I couldn't find the place where the `extend` keyword is added based on the `@key`.

**Comment by kamilmysliwiec** [comment]
I've just tested this locally with our e2e tests. After removing the `@Directive('@extends')` (but leaving `@Directive('@key...')` in place:

![image](https://user-images.githubusercontent.com/23244943/154919957-06d665b1-270c-4465-aeb4-f36413e442f6.png)

Everything seems to work as expected 

![image](https://user-images.githubusercontent.com/23244943/154920061-c6e28899-a365-4c62-b83b-02f0529fce33.png)

**Comment by kamilmysliwiec** [comment]
Thanks for looking into this @Davide-Gheri! So it seems that this issue comes from the Apollo library (`@apollo/subgraph` doesn't seem to be compatible with GraphQL v16). Is my assumption correct?

**Comment by endroca** [comment]
@kamilmysliwiec yes. 

A version ago of apollo federation was being compatible with version 15.8.0, but apparently they have already updated

https://github.com/apollographql/federation/blob/main/subgraph-js/package.json#L27

**Comment by kamilmysliwiec** [comment]
@endroca note this is the package.json content of the alpha version https://github.com/apollographql/federation/blob/main/subgraph-js/package.json#L3 that is not yet stable.

As this issue doesn't seem to be related to this package, I think we should report it in the Apollo repository instead.

**Comment by vinaybedre** [comment]
@Maldron did you solved this issue? Do you mind sharing how did you do it?

**Comment by sgadzhalov** [comment]
Not fully tested, but I managed to get it working thanks to @Davide-Gheri's comment
```
      transformAutoSchemaFile: true,
      transformSchema: (schema) => {
        Object.keys(schema?.['_typeMap']).forEach((key) => {
          const type = schema?.['_typeMap']?.[key];
          type.extensionASTNodes =
            type.extensionASTNodes && type.extensionASTNodes.length > 0
              ? type.extensionASTNodes
              : undefined;
        });
        return schema;
      }
```
