### ISSUE TITLE
ResolveField does not work in interface resolver

### ISSUE THREAD

**Issue by Karibash** [nestjs/graphql#2036]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

ResolveFields do not seem to work properly in the interface resolver.

### Minimum reproduction code

https://github.com/Karibash/nestjs-graphql-interface

### Steps to reproduce

1. `npm install`
2. `npm run start`
3. Execute the following command
```shell
curl 'http://localhost:3000/graphql' \
  -H 'content-type: application/json' \
  --data-raw '{"operationName":null,"variables":{},"query":"{\n  books {\n    id\n    title\n    titleLength\n  }\n}\n"}'
```

### Expected behavior

In order to use field resolvers with interface resolvers, you need to set the inheritResolversFromInterfaces property to true when executing the makeExecutableSchema function in the GraphQLFactory class.

See below.
https://www.graphql-tools.com/docs/generate-schema#makeexecutableschemaoptions
https://github.com/nestjs/graphql/blob/2fd5ee31aeb3a32e32647463f4623ec49e676bb6/packages/graphql/lib/graphql.factory.ts#L53-L62
https://github.com/nestjs/graphql/blob/2fd5ee31aeb3a32e32647463f4623ec49e676bb6/packages/graphql/lib/graphql.factory.ts#L95-L101

### Package version

10.0.4

### Graphql version

`graphql`: 16.3.0
`apollo-server-express`: 3.6.3

### NestJS version

8.3.1

### Node.js version

16.13.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/graphql/pull/2038

**Comment by vasily-polonsky** [comment]
Seems like it is not fixed in https://github.com/nestjs/graphql/pull/2038 . Still reproducing. You can use the same repo, and install the latest 10 version "@nestjs/graphql": "10.2.1". In my repo with latest 11 version it also doesn't work(((
