### ISSUE TITLE
Reply/Response method not found using fastify

### ISSUE THREAD

**Issue by endroca** [nestjs/graphql#2039]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

By using the interceptor to perform a header response using `express`, we were able to get the response method inside the request.

```javascript
const gql = GqlExecutionContext.create(context)
const response = gql.getContext().req.res
```

But when using `fastify` the reply method doesn't exist anywhere.

```javascript
const gql = GqlExecutionContext.create(context)
const response = gql.getContext().reply ?
```

The solution I came up with was to start the graphql module
passing:
```javascript
GraphQLModule.forRoot<ApolloFederationDriverConfig>({
   driver: ApolloFederationDriver,
   autoSchemaFile: join(process.cwd(), 'tests/src/schema.gql'),
   context: (context) => context,  // <-- add context
}),
```

Is there any other ?

### Minimum reproduction code

in description

### Expected behavior

Have a response method using fastify

### Package version

10.0.4

### Graphql version

"@nestjs/platform-fastify": "^8.3.1"

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
Please provide a [minimum reproduction repository](http://minimum-reproduction.wtf).

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
