### ISSUE TITLE
### include module not working?

### ISSUE THREAD

**Issue by madipta** [nestjs/graphql#204]
using nest sample: 12-graphql-apollo

**app.module.ts**

>     GraphQLModule.forRoot({
>       include: [CatsModule,],
>       typePaths: ['./**/*.graphql'],
>       installSubscriptionHandlers: true,
>     }),

**graphql Playground**

> {
>  cat(id:1){
>     name
>   }
> }

**result null**
> {
>   "data": {
>     "cat": null
>   }
> }

node version: 10.15.1
nest version: 6.0.5

_Originally posted by @madipta in https://github.com/nestjs/graphql/issues/118#issuecomment-480213393_

**Comment by kamilmysliwiec** [comment]
Please, use [StackOverflow](https://stackoverflow.com/questions/tagged/nestjs) for such questions.
