### ISSUE TITLE
GraphQL: Directive not registered and not working

### ISSUE THREAD

**Issue by ostempel** [nestjs/graphql#2057]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The reproduction repository is an adjusted copy of the nestjs-sample repository (https://github.com/nestjs/nest -> sample/23-graphql-code-first). This nest-project includes the "@upper" directive which is the example in the docs (https://docs.nestjs.com/graphql/directives#directives).
The directive gets registered in the GraphQLModule in the `transformSchema` option.

Adjustments:
1. added mock-data behind `recipes` query
2. added directive to `title` property of "Recipe" model

The query works fine without using the directive. But if you use the "@upper" directive on the title property, graphql will throw an error: "Unknown directive \"@upper\"."

I've already asked in the discord if something is missing. The result was, that this is a bug.

### Minimum reproduction code

https://github.com/ostempel/nestjs-graphq-directive-test

### Steps to reproduce

1. yarn install
2. nest build
3. nest start
4. Open graphql-playground (http://localhost:3000/graphql)
5. Use this query: 
```
query getRecipes {
  recipes {
    id
    title @upper
    description
    ingredients
    creationDate
  }
}
```

### Expected behavior

The directive is registered and is applicable to the "title" property. No error should be thrown when this directive is used on the property. The directive should transform the title to uppercase.

### Package version

^10.0.2

### Graphql version

    "@nestjs/apollo": "^10.0.2",
    "@nestjs/graphql": "^10.0.2",
    "apollo-server": "^3.6.2",
    "apollo-server-express": "^3.6.2"
    "graphql": "16.3.0",
    "graphql-query-complexity": "0.11.0",
    "graphql-subscriptions": "2.0.0"

### NestJS version

8.2.3

### Node.js version

v14.17.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

Adding console logs to the directive get 2 times fired on the startup.

**Comment by kamilmysliwiec** [comment]
Duplicate https://github.com/nestjs/graphql/issues/2056
