### ISSUE TITLE
resolveType factory is not compatible with Mercurius / graphql-jit

### ISSUE THREAD

**Issue by wodCZ** [nestjs/graphql#2067]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The way the [resolve-type.factory.ts is implemented](https://github.com/nestjs/graphql/blob/188b83a5fd380f07bd6b2d72b6f5f7d2bbeb8bcd/packages/graphql/lib/schema-builder/factories/resolve-type.factory.ts#L16-L24) breaks the compatibility with [Mercurius' JIT feature](https://mercurius.dev/#/docs/api/options?id=plugin-options).

The `resolveType` function is always converted to `async`, which is currently [not supported by graphql-jit](https://github.com/zalando-incubator/graphql-jit/issues/69):
https://github.com/nestjs/graphql/blob/188b83a5fd380f07bd6b2d72b6f5f7d2bbeb8bcd/packages/graphql/lib/schema-builder/factories/resolve-type.factory.ts#L16-L24

This causes requests to fail on the following:

```
"Abstract type Shape must resolve to an Object type at runtime for field Query.shape. Either the Shape type should provide a \"resolveType\" function or each possible types should provide an \"isTypeOf\" function."
```

### Minimum reproduction code

https://github.com/wodCZ/nestjs-graphql-union-reproduction

### Expected behavior

The resolveType function of createUnionType should be kept synchronous when defined as synchronous.

Monkey-patching the resolve-type.factory.js from

```js
    getResolveTypeFunction(resolveType) {
        return async (...args) => {
            var _a;
            const resolvedType = await resolveType(...args);
            if ((0, shared_utils_1.isString)(resolvedType)) {
                return resolvedType;
            }
            const typeDef = this.typeDefinitionsStorage.getObjectTypeByTarget(resolvedType);
            return (_a = typeDef === null || typeDef === void 0 ? void 0 : typeDef.type) === null || _a === void 0 ? void 0 : _a.name;
        };
    }
```

to (async/await removed)
```js
    getResolveTypeFunction(resolveType) {
        return (...args) => {
            var _a;
            const resolvedType = resolveType(...args);
            if ((0, shared_utils_1.isString)(resolvedType)) {
                return resolvedType;
            }
            const typeDef = this.typeDefinitionsStorage.getObjectTypeByTarget(resolvedType);
            return (_a = typeDef === null || typeDef === void 0 ? void 0 : typeDef.type) === null || _a === void 0 ? void 0 : _a.name;
        };
    }
```

"fixes" the issue (of course breaking real asynchronous resolveType methods.

### Package version

10.0.6

### Graphql version

`graphql`: `16.3.0`
`@nestjs/mercurius`: `10.0.6`
`mercurius`: `9.3.3`

### NestJS version

8.0.0

### Node.js version

17.6.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/graphql/pull/2069
