### ISSUE TITLE
subscriptions-transport-ws as optional peerDependency

### ISSUE THREAD

**Issue by Shinigami92** [nestjs/graphql#2073]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Everytime I install my dependencies I get following error (_red text_)/warning

<img width="1367" alt="image" src="https://user-images.githubusercontent.com/7195563/157825653-1dcdccba-c28d-4b45-a3d7-fdf4f5b6aefa.png">

>  WARN  deprecated subscriptions-transport-ws@0.11.0: The `subscriptions-transport-ws` package is no longer maintained. We recommend you use `graphql-ws` instead. For help migrating Apollo software to `graphql-ws`, see https://www.apollographql.com/docs/apollo-server/data/subscriptions/#switching-from-subscriptions-transport-ws    For general help using `graphql-ws`, see https://github.com/enisdenjo/graphql-ws/blob/master/README.md

### Describe the solution you'd like

I would like that `subscriptions-transport-ws` is moved to `peerDependencies` and marked as **optional**, so that I can decide to install it or not.
For now it may still be needed for the playground that (as far as I know) currently does not support `graphql-ws`

### What is the motivation / use case for changing the behavior?

When only `graphql-ws` is needed, we can safe a dependency 🙌

**Comment by kamilmysliwiec** [comment]
There are currently no plans to drop the `subscriptions-transport-ws` but I can guarantee that this will happen in the future, given that the package itself is no longer maintained (likely in the next major release).
