### ISSUE TITLE
Better support for schema generation during `nest build`

### ISSUE THREAD

**Issue by lightpohl** [nestjs/graphql#2084]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

> Hey! Definitely let me know if this should be opened in a different repo — it kinds touches usage in the CLI, main project, and GraphQL portions of Nest

Because the generated GraphQL schema files are not available until the app is started/initialized (using `autoSchemaFile`), it makes them a bit difficult to work with when we want to generate those schema files without starting the app.

We implemented a workaround that exits out of the `bootstrap` without starting the app and writes out to a schema file, but we'd love to get something like this behavior added into `nest build` that feels less like a workaround.

```ts
async function bootstrap() {
  if (process.env.GENERATE_GQL) {
    const app = await NestFactory.create(GraphQLSchemaBuilderModule);
    await app.init();

    const gqlSchemaFactory = app.get(GraphQLSchemaFactory);
    const schema = await gqlSchemaFactory.create(AllResolvers);

    fs.writeFileSync(
      path.join(process.cwd(), `/dist/schema.generated.gql`),
      printSchema(schema),
    );

    return;
  }

  // code to start the app regularly
}
```

This solution has two pain points:
1. `AllResolvers` needs to be an array of resolvers that you manually set in your project instead of being automatic
2. Using an environment variable feels like a "secret" API

### Describe the solution you'd like

We'd love to see the types be included in the `dist` when running `nest build` (either optionally with a flag or by default).

If that's not possible, would a flag on `nest start` be an option?

### What is the motivation / use case for changing the behavior?

There's not currently a way that I'm aware of to generate the GraphQL schema for your resolvers without starting the app. There are workarounds (like the [answers here](https://stackoverflow.com/questions/67298396/nest-js-graphql-schema-generation-during-build)), but a first-class API for it would be wonderful.

This would allow projects to more easily share their generated schema across a monorepo, or in different parts of their stack (e.g. web and mobile).

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

This has been discussed in the past and we decided to not implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
