### ISSUE TITLE
Cant generate InputType with object as field

### ISSUE THREAD

**Issue by cavator** [nestjs/graphql#2085]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

```typescript
import { Field, InputType } from '@nestjs/graphql';
import { ProductServices } from '../../product-service/entities/product-service.entity';

@InputType()
export class CreateProductInput {
  @Field(() => Number, { description: 'product name' })
  name: string;

  @Field(() => String, { description: 'Manufacturer ID' })
  manufacturerId: string;

  @Field(() => String, { description: 'Tenant ID' })
  tenantId: string;

  @Field(() => [ProductServices], { description: 'Product services' })
  productServices: ProductServices[];
}

```
the error

                throw new cannot_determine_input_type_error_1.CannotDetermineInputTypeError(hostType, typeRef);
                      ^
                Error: Cannot determine a GraphQL input type ("ProductServices") for the "productServices". Make sure your class is decorated with an appropriate decorator.

### Minimum reproduction code

https://gist.github.com/cavator

### Expected behavior

work

### Package version

99999

### Graphql version

`graphql`: 
`apollo-server-express`: 
`apollo-server-fastify`: 

### NestJS version

99999

### Node.js version

999999

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
