### ISSUE TITLE
Error details are lost when using MercuriusFederationDriver

### ISSUE THREAD

**Issue by all2pie** [nestjs/graphql#2090]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Currently this object is being returned: 

```
{
  "errors": [
    {
      "message": "Bad Request Exception",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "check"
      ]
    }
  ],
  "data": null
}
```

Also the error details are not avaliable inside the  `errorFormatter` in GraphQL module forRoot method

I am using Fastify with MercuriusFederationDriver

### Minimum reproduction code

https://github.com/all2pie/nestjs-fastify-graphql-exception-bug

### Steps to reproduce

1.  `npm i`
2. `npm start`
3. Call the `check` Query

### Expected behavior

The details of the error should be forwarded like in case of validation error. 

You can check the REST controller, the return should be something like that

### Package version

10.0.7

### Graphql version

`graphql`: ^16.3.0
`apollo-server-fastify`: ^8.4.1

### NestJS version

8.2.2

### Node.js version

16.14.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
