### ISSUE TITLE
Support Apollo Server v3 cacheControl for Code first

### ISSUE THREAD

**Issue by choco14t** [nestjs/graphql#2109]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Apollo Server v2 was sometimes automatically inserted `@cacheControl` directive and `CacheControlScope` enum. But Apollo Server v3 is never automatically inserted (refs: [migration guide](https://www.apollographql.com/docs/apollo-server/migration#cachecontrol)).

Now Nest supported custom directive, but occurred `Error: Schema must contain uniquely named types but contains multiple types` when define `@cacheControl`. Minimum reproduction code is here: https://github.com/choco14t-sandbox/nest-code-first-directive

I tried to fix the above at hand, but the cache is still not applied.
Perhaps there is a problem with the astNode when it is generating the schema.

### Describe the solution you'd like

Code first will be able to apply directive into astNode.

### What is the motivation / use case for changing the behavior?

I would like support for the features provided from Apollo.
I don't want it to become unusable due to version upgrades.

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/graphql/pull/2139

**Comment by productdevbook** [comment]
@choco14t some setting used but @Directive('@cacheControl(maxAge: 2000)') used but dont 2000, all 30 second cached. :/

Thank you pr
