### ISSUE TITLE
Appending "Extend" to entity incorrectly with graphql v16+

### ISSUE THREAD

**Issue by mpiantella** [nestjs/graphql#2112]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Seeing an error with NestJS Federation. When declaring an entity, not extending it, with the latest packages of NestJS, Apollo Federation, and graphql@^16.3.0, (as 3/28/22), the generated subgraph schema appends an "extend" keyword to the SDL incorrectly. 

List of packages:

```
"dependencies": {
    "@apollo/federation": "^0.35.4",
    "@apollo/gateway": "0.46.0",
    "@apollo/subgraph": "^0.3.3",
    "@nestjs/apollo": "^10.0.8",
    "@nestjs/common": "8.2.3",
    "@nestjs/core": "8.2.3",
    "@nestjs/graphql": "^10.0.8",
    "@nestjs/platform-express": "8.2.3",
    "apollo-server-express": "3.6.2",
    "graphql": "^16.3.0",
    "graphql-tools": "7.0.5",
    "reflect-metadata": "0.1.13",
    "rimraf": "3.0.2",
    "rxjs": "7.4.0",
    "ts-morph": "12.2.0"
  }
```
SDL generated:
```
$ rover subgraph introspect http://localhost:3001/graphql
Introspection Response: 

type Query {
  getUser(id: ID!): User!
}

# extend should not be here
extend type User @key(fields: "id") {
  id: ID!
  name: String!
}
```

### Minimum reproduction code

https://github.com/nestjs/nest/tree/master/sample/31-graphql-federation-code-first

### Steps to reproduce

I was able to replicate this with the given pkg versions (Node v14.17.5), inside the NestJS sample code 31-graphql-federation-code-first app.

### Expected behavior

This is what we should get. Note the setup for the app was not changed, only the version of the graphql npm package.

```
type User @key(fields: "id") {
  id: ID!
  name: String!
}

type Query {
  getUser(id: ID!): User!
}
```

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

graphql@16.3.0

### Packages versions

```json

```

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by joachimjusth** [comment]
We are facing the same issue with graphql 16.3
Downgrading to graphql 15.7.* solve the issue

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/graphql/issues/2157#issuecomment-1118315785
