### ISSUE TITLE
Add Support for Context sharing in GraphQL Federation

### ISSUE THREAD

**Issue by all2pie** [nestjs/graphql#2114]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Not able to share data from gateway. Headers rewrite don't take json as value and is not suitable 

### Describe the solution you'd like

The session or other data should be sharable through context

### Teachability, documentation, adoption, migration strategy

Implement this for both Apollo and Mercurius

### What is the motivation / use case for changing the behavior?

I need to pass user session from gateway to the services

**Comment by all2pie** [comment]
https://github.com/mercurius-js/mercurius/issues/762

**Comment by kamilmysliwiec** [comment]
Matteo already replied to you https://github.com/mercurius-js/mercurius/issues/762#issuecomment-1083396434.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
