### ISSUE TITLE
Trouble importing internal modules in yarn workspaces

### ISSUE THREAD

**Issue by nomadoda** [nestjs/graphql#2115]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

In a yarn workspaces context, the GraphQL module seem to have trouble importing internal modules, probably due to hoisting. When importing the GraphQL module I get this error:

```
Error: Cannot find module '@nestjs/common'
Require stack:
- /Users/Adam/Projects/nest-workspace-test/node_modules/@nestjs/apollo/dist/decorators/plugin.decorator.js
- /Users/Adam/Projects/nest-workspace-test/node_modules/@nestjs/apollo/dist/decorators/index.js
- /Users/Adam/Projects/nest-workspace-test/node_modules/@nestjs/apollo/dist/index.js
- /Users/Adam/Projects/nest-workspace-test/packages/server/dist/app.module.js
- /Users/Adam/Projects/nest-workspace-test/packages/server/dist/main.js
```

I have not encountered this issue with any other nestjs modules, so I feel like something is not working as expected here.

Please see minimum reproduction code repository for implementation details.

### Minimum reproduction code

https://github.com/nomadoda/nest-workspace-test

### Steps to reproduce

1. `yarn`
2. `yarn workspace server start:dev`

### Expected behavior

No `Error: Cannot find module '@nestjs/common'` error from `@nestjs/apollo`

### Package version

10.0.8

### Graphql version

`graphql`: 16.3.0
`apollo-server-express`: 3.6.7

### NestJS version

8.4.3

### Node.js version

16.13.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

M1

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
