### ISSUE TITLE
NestJS Federation Features Not Present in Schema

### ISSUE THREAD

**Issue by leetharris** [nestjs/graphql#2116]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When you generate a schema (either through autoSchemaFile: true OR autoSchemaFile: 'string.sql'), there are absolutely no federation features or annotations present. They are stripped entirely. 

However, they do seem to be generated upstream. You can discover this by printing the schema yourself using `printSubgraphSchema` from `@apollo/subgraph`. 

### Minimum reproduction code

https://github.com/nestjs/nest/tree/master/sample/31-graphql-federation-code-first/posts-application

### Steps to reproduce

1. Clone Nest's own example repo ([link](https://github.com/nestjs/nest/tree/master/sample/31-graphql-federation-code-first/posts-application)).
2. Run the application.
3. Inspect the schema and find that there are no federation annotations.

### Expected behavior

Our schema models should have `extend`, `@extends`, `@key`, and `@external` on them for the various federation features.

### Package version

10.0.8

### Graphql version

`graphql`: 16.3.0
`apollo-server-express`: 3.6.7
`apollo-server-fastify`: 

### NestJS version

8.0.0

### Node.js version

16.14.0

### In which operating systems have you tested?

- [X] macOS
- [X] Windows
- [ ] Linux

### Other

As noted above, you can determine that the proper Federation features and annotations are present upstream by doing the following: 

```ts
import {printSubgraphSchema} from '@apollo/subgraph';

async function generateSchema() {
  const app = await NestFactory.create(GraphQLSchemaBuilderModule);
  await app.init();

  const gqlSchemaFactory = app.get(GraphQLSchemaFactory);
  try {
    const schema = await gqlSchemaFactory.create([ProductResolver, PriceHistoryResolver], {
      skipCheck: false,
      orphanedTypes: [Product],
    });
    console.log(printSubgraphSchema(schema));
  } catch (e) {
    console.log('errors', e);
  }
}
```

This will show you the full printed out schema with all the proper information. Here is an example of the output from Nest and an output from the above function:

**Nest Output**:

```
type Product {
  id: ID!

  # The list of prices per channel per locale of the product.
  currentPrices: [PriceHistory!]!
}
```

**printSubgraphSchema Output:**

```
extend type Product @extends @key(fields: "id") {
  id: ID! @external

  """The list of prices per channel per locale of the product."""
  currentPrices: [PriceHistory!]!
}
```

**Comment by kamilmysliwiec** [comment]
Please search through some of our old issues on this (this has been discussed several times in the past).
