### ISSUE TITLE
Allow for multiple @Resolver decorators on same class

### ISSUE THREAD

**Issue by coltonehrman** [nestjs/graphql#2123]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I have found a way to do this by extending a base class, but the fact that the subclass implementations are empty is a code smell.

```typescript
class AResolver {
  @ResolveField("prop")
  async prop() {}
}

@Resolver("B")
class BResolver extends AResolver {}

@Resolver("C")
class CResolver extends AResolver {}
```

### Describe the solution you'd like

Would be a better solution to be able to decorate a single class multiple times, or be able to define a resolver for the `interface` type.

**Example 1**
Multiple decorators on single class
```typescript
@Resolver("B")
@Resolver("C")
class AResolver {
  @ResolveField("prop")
  async prop() {}
}
```

**Example 2**
Single decorator with multiple args on single class
```typescript
@Resolver("B", "C")
class AResolver {
  @ResolveField("prop")
  async prop() {}
}
```

**Example 3**
Interface type decorator that is used across all types that implement it
```typescript
@Resolver("A")
class AResolver {
  @ResolveField("prop")
  async prop() {}
}
```

### What is the motivation / use case for changing the behavior?

Use Case: I have a GQL interface that has 2 type implementations but share the same logic across the resolver for certain fields

```graphql
interface A {
  prop: String
}

type B implements A {
  prop: String
}

type C implements A {
  prop: String
}
```

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

There are no plans to implement it in the foreseeable future.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel for further questions.
