### ISSUE TITLE
GraphQLDefinitionsFactory:  error occurs as a result of required parameters being placed after optional parameters in generated type definitions file 

### ISSUE THREAD

**Issue by mesteralfreddohnani** [nestjs/graphql#2124]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

<img width="495" alt="Screenshot 2022-04-06 at 4 54 11 PM" src="https://user-images.githubusercontent.com/54582881/162027327-38a5414c-8a9c-42ba-9012-ea755d847592.png">

The `src/graphql.ts` file generated I believe by `GraphQLDefinitionsFactory ` has typescript errors because it puts required parameters after optional parameters in resolver types; which is not allowed in TypeScript as shown below:

<img width="646" alt="Screenshot 2022-04-06 at 4 57 51 PM" src="https://user-images.githubusercontent.com/54582881/162027944-595fbf1f-3306-4e79-bed3-8bbf1a9b9797.png">

Is there an option to pass to `GraphQLModule.forRoot.definitions`  or a `transformSchema` function that could correct the above-stated issue?

### Minimum reproduction code

*

### Steps to reproduce

* Below are some options passed to `GraphQLModule.forRoot:` 
* ` typePaths: ['./src/graphqlCmsSchema.graphql', './src/**/*.graphql'],
            transformSchema: schema =>
              upperDirectiveTransformer(schema, 'upper'),
            definitions: {
              path: join(process.cwd(), './src/graphqlCmsSchema.ts'),
              outputAs: 'class',
            },`

_No response_

### Expected behavior

Required arguments should come before optional arguments in resolvers of generated type definition files

### Package version

7.4.1

### Graphql version

`graphql`: 15.0.0
`apollo-server-express`: 2.14.1

### NestJS version

7.0.0

### Node.js version

v14.19.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please search through some of our old issues on this (this has been discussed several times in the past).
