### ISSUE TITLE
@ResolveReference with @Context

### ISSUE THREAD

**Issue by christopheblin** [nestjs/graphql#2127]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Create a resolveReference with `@Context`

```
  @ResolveReference()
  async resolveReference(
    reference: { __typename: string; id: string },
    @Context() ctx: ExecutionContext,
  ): Promise<void> {
    //here reference is undefined and ctx is not correct, it is in fact a GraphQLResolveInfo
    //if you remove @Context, reference is correct 
  }
```
Also use the fieldResolverEnhancers
```
GraphQLFederationModule.forRootAsync({
      inject: [ConfigService],
      imports: [ConfigModule.register(NodeEnvVar, process.env)],
      useFactory: (configService: ConfigService<NodeEnvVar>) => {
        return {
          autoSchemaFile: true,
          fieldResolverEnhancers: ['interceptors', 'guards'],
          introspection: configService.env.NODE_ENV === NodeEnv.PRODUCTION ? false : true,
          playground: true,
          buildSchemaOptions: {
            orphanedTypes: ORPHANED_TYPES,
          },
        };
      },
    })
```

### Minimum reproduction code

N/A

### Expected behavior

I expect reference to be available if I add `@Context`

I expect to use @Info instead of `@Context` if I truly want to access to GraphQLResolveInfo

### Package version

9.1.2

### Graphql version

`graphql`: 15.8.0
`apollo-server-express`: 
`apollo-server-fastify`: 3.6.1

### NestJS version

8.2.5

### Node.js version

16.11.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by choco14t** [comment]
@christopheblin 
I faced the same problem.
I don't know why can't use `@Context` in resolveReference, but you can get the context as follows.

```ts
@ResolveReference()
resolveReference(reference: { __typename: string; id: number }, context) {
  // any code...
}
```

Probably should be the same argument as `__resolveReference` in [@apollo/subgrpah](https://www.apollographql.com/docs/federation/api/apollo-subgraph#__resolvereference).

About default Apollo Server context,  refer the docs.
[API Reference: ApolloServer - Apollo GraphQL Docs](https://www.apollographql.com/docs/apollo-server/api/apollo-server/#middleware-specific-context-fields)

**Comment by christopheblin** [comment]
@choco14t thanks for your time

I discovered that nestjs/graphql is using mercurius (https://github.com/mercurius-js/mercurius with https://github.com/mercurius-js/mercurius/blob/master/docs/federation.md) so basically you can do

```
@ResolveReferrence()
async resolveReference(
    reference: { __typename: string; id: string },
    ctx: any, //the type of this object is bit strage, you have ctx.req that point to the http request
    info: GraphqlResolveInfo
  ): Promise<void> {
    //here reference is undefined and ctx is not correct, it is in fact a GraphQLResolveInfo
    //if you remove @Context, reference is correct 
  }
```

So basically, it would still seems a bug in nestjs/graphql but cou can mostly workaround with these 2 paramters

**Comment by Davide-Gheri** [comment]
Hi, you shouldn't use parameter decorators like `@Context` on non-standard resolvers (`__resolveReference` and `__resolveType`) because the underlying arguments differs from a standard one. If you need context or info you should get them as for your last comment.

Nestjs Graphql can use either Mercurius (with fastify) or Apollo (with express or fastify), but the limitations are the same.

**Comment by christopheblin** [comment]
@Davide-Gheri Thanks for clarifying

Maybe that could make its way in the docs as it is unexpected (at least for me) that the federation has a completely different support for parameter decorator (in fact, it should read "has no support for parameter decorator") 

I mean, the doc https://docs.nestjs.com/graphql/federation#code-first

> Resolver provides one additional method named resolveReference(). This method is triggered by the Apollo Gateway whenever a related resource requires a User instance. We'll see an example of this in the Posts service later. Please note that the method must be annotated with the @ResolveReference() decorator.

```
Resolver provides one additional method named resolveReference(). 
This method is trigerred by the gateway (either apollo or mercurius).
We'll see an example of this in the Posts service later. 

Please note that the method must be annotated with the @ResolveReference() decorator.
However, please also note that the method does NOT support any parameter decorator (@Context, @Info, etc...).
The only thing you have is that the resolveReference method takes 2 additional parameters

@ResolveReference()
resolveReference(
    reference: { __typename: string; id: string },
    ctx: any,
    info: GraphqlResolveInfo
  )

```

And if you know by any chance the type of ctx, do not hesitate :)

at the moment, I'm doing this for ex `ctx.req.headers.authorization`, but I dont like to rely on such fragile typing (and typing as ExecutionContext does not work, I suppose it comes from apollo/mercurius and not from nestjs ?)

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/docs.nestjs.com/issues/2285
