### ISSUE TITLE
Implementing 'Namespace-Typed' Resolvers in NestJS + GraphQL

### ISSUE THREAD

**Issue by 404Polaris** [nestjs/graphql#2135]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I want to implement  something like this,but i don't how to define the mutation.Nest's mutation seems to be in mutation by default。 

`
const express = require('express');
const { ApolloServer, gql } = require('apollo-server-express');

const typeDefs = gql`
  type Query {
    hello: String
  }

  type Mutation {
    article: ArticleMutations
  }

  type ArticleMutations {
    like(id: Int!): Boolean
    unlike: Boolean
  }
`;

const resolvers = {
    Query: {
        hello: () => 'Hello world!'
    },
    Mutation: {
        article: () => ({}), // ✨✨✨ magic! which allows to proceed call of sub-methods
    },
    ArticleMutations: {
        like: (id) => { console.log(id); return false; },
        unlike: () => { /* resolver code */ },
    },
};

const server = new ApolloServer({ typeDefs, resolvers });
server.start().then(() => {
    const app = express();
    server.applyMiddleware({ app });
    app.listen({ port: 4000 }, () =>
        console.log(`  Server ready at http://localhost:4000${server.graphqlPath}`)
    );

});`

### Describe the solution you'd like

This is defined in the resolver:

`
@Mutation(()=>GraphQLBoolean, { name: 'like', parentType: "ArticleMutations"})

    public async like(@Args('id') id: number): Promise<boolean> {
      return true
    }
`

### What is the motivation / use case for changing the behavior?

Because I want to better manage the graphql mutation API.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
