### ISSUE TITLE
How do I use an existing enum when I new a GraphQLDirective ?

### ISSUE THREAD

**Issue by Carrotzpc** [nestjs/graphql#2142]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I new a GraphQLDirective,  I can't use a exist enum and have to create a new one.

### Minimum reproduction code

N/A

### Steps to reproduce

I create a auth directive，how do I use an existing enum  'UserRole' for `requires` arg？

```ts
@Module({
  imports: [
    ServeStaticModule.forRoot({
      rootPath: join(__dirname, '..', 'public'),
      exclude: ['/graphql'],
    }),
    GraphQLModule.forRoot<ApolloDriverConfig>({
      driver: ApolloDriver,
      installSubscriptionHandlers: true,
      autoSchemaFile: join(process.cwd(), 'src/schema.gql'),
      sortSchema: true,
      transformSchema: (schema) => {
        schema = authDirectiveTransformer(schema, 'auth');
        return upperDirectiveTransformer(schema, 'upper');
      },
      buildSchemaOptions: {
        directives: [
          new GraphQLDirective({
            name: 'auth',
            locations: [
              DirectiveLocation.OBJECT,
              DirectiveLocation.FIELD_DEFINITION,
            ],
            args: {
              requires: {
                // ⚠How do I use an existing enum  'UserRole' here ?⚠
               // I have to create a new one: 'UserRole2'
                type: new GraphQLEnumType({ 
                  name: 'UserRole2',
                  values: {
                    Admin: { value: 'Admin' },
                    User: { value: 'User' },
                  },
                }),
                // type: GraphQLString,
              },
              namespace: {
                type: GraphQLBoolean,
              },
            },
          }),
          new GraphQLDirective({
            name: 'upper',
            locations: [DirectiveLocation.FIELD_DEFINITION],
          }),
        ],
      },
    }),
})
```

### Expected behavior

When I new a GraphQLDirective,  I can use a exist enum as args.

### Package version

10.0.9

### Graphql version

`graphql`:  15.8.0
`apollo-server-express`:  3.6.7

### NestJS version

8.4.4

### Node.js version

14.17.3

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

Maybe we can get `schema`, then use `schema.getType` to get exist enum.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
