### ISSUE TITLE
TypeError: Cannot define a type with relational data as a return type.

### ISSUE THREAD

**Issue by locona** [nestjs/graphql#2144]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior
[Schema First]
TypeError occurs when relational data is returned by the return type of the resolver, as shown below.

https://github.com/you-x/graphql-typscript/blob/b65568f5aec2a25799d681e51809ec91a3e2808e/src/author/author.resolver.ts

### Minimum reproduction code

https://github.com/you-x/graphql-typscript

### Steps to reproduce

1. yarn install
2. yarn dev

The result is a TypeError and ms

### Expected behavior

Allow relational data to be defined in the return type of the resolver.

https://github.com/you-x/graphql-typscript/blob/b65568f5aec2a25799d681e51809ec91a3e2808e/src/author/author.resolver.ts

### Package version

10.0.9

### Graphql version

`graphql`: 16.3.0
`apollo-server-express`: 3.6.7

### NestJS version

8.4.4

### Node.js version

14.19.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
> [Schema First]
TypeError occurs when relational data is returned by the return type of the resolver, as shown below.

What type error?

**Comment by locona** [comment]
@kamilmysliwiec 

```
 Type '{ id: number; name: string; }[]' is missing the following properties from type 'Promise<Author[]>': then, catch, finally, [Symbol.toStringTag]
```

The type is specified in the return type of the resolver, and the relational data acquisition is specified in the ResolveField.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
