### ISSUE TITLE
When a custom directive is used, the default directives are no longer available

### ISSUE THREAD

**Issue by smolinari** [nestjs/graphql#2148]
Originally reported on Discord: https://discord.com/channels/520622812742811698/601536926268260392/966560801894854726

### Is there an existing issue for this?

- [X] I have searched the existing issues

I noticed this possibly relevant issue:

https://github.com/nestjs/graphql/issues/2057

### Current behavior

If you set up the example 23, the `@skip` and `@include` directives are not available. If you comment out the custom `@upper` directive in `app.module.ts`, the default directives are available. 

### Minimum reproduction code

https://github.com/nestjs/nest/tree/master/sample/23-graphql-code-first

### Steps to reproduce

1. download the Nest repo.
2. update the example 23 dependencies
3. install deps
4. run server
5. see the `@include` and `@skip` directives are not available in graphiql/ graphql client
![image](https://user-images.githubusercontent.com/3314957/164399371-e3d89dfc-a7bf-49ae-8597-303bf444571f.png)

6. comment out the custom `@upper` directive in `app.module.ts`
![image](https://user-images.githubusercontent.com/3314957/164399718-c9fd934b-0a78-4c02-a21b-8c9802266ebc.png)
7. see the two default directives are available 
![image](https://user-images.githubusercontent.com/3314957/164398944-19c1b3ac-b8ad-4c71-87ae-5c6369c0fe16.png)

### Expected behavior

The `@include` and `@skip` directives to be available, despite a custom directive being added. 

### Package version

10.0.9

### Graphql version

`graphql`: 16.3.0
`apollo-server-express`: 3.6.7
`apollo-server-fastify`: 3.6.7

### NestJS version

8.4.4

### Node.js version

16.14.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Fixed in `@nestjs/graphql@10.0.10`

**Comment by smolinari** [comment]
@kamilmysliwiec - Thanks Kamil. Awesome. That was fast. It sure is a pleasure to work with Nest. 

Scott
