### ISSUE TITLE
Unexpected description with federated graph on the original type

### ISSUE THREAD

**Issue by d-lasagno** [nestjs/graphql#2149]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Adding a description in the options of `@ObjectType` gives the following error if also using `@Directive('@key(fields: "id")')`:
```
GraphQLError: Syntax Error: Unexpected description, descriptions are supported only on type definitions.
```
By searching on the web I found that (logically) you can't add descriptions when using @extend, but in my case I haven't used it. 

### Minimum reproduction code

https://gist.github.com/d-lasagno/9e32b9881820b08e1b020f8b84208e8f

### Expected behavior

Since this is the original type it should be able to have a description.

### Package version

10.0.8

### Graphql version

`graphql`: 16.3.0
`apollo-server-express`: 3.6.7

### NestJS version

8.4.4

### Node.js version

16.14.2

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by nmacherey** [comment]
same here !

**Comment by vinaybedre** [comment]
could be related to https://github.com/nestjs/graphql/issues/2029?

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/graphql/issues/2157#issuecomment-1118315785

**Comment by AndriiKifiak** [comment]
I have added `"@apollo/subgraph"` package and the error disappeared.
