### ISSUE TITLE
GraphQL code first apollo datasource rest injection // custom decorator

### ISSUE THREAD

**Issue by SugarDarius** [nestjs/graphql#215]
Hi ! 

I'm currently working with the GraphQL module in code first approach. 
I would like to know if you have an example to provide on how I could implement a datasource injection with or without a custom decorator into my services with apollo-datasource-rest. 

Apollo-datasource-rest has a very useful caching mechanism for preventing duplicated http responses. But the fact is ApolloServer needs to have datasources declared in is options to works well. 

My idea is to create a decorator like :
```typescript
@Injectable()
@DataSource('MYRESTDataAPI') 
// datasource initialized from the dataSources key of the GraphQLOptions
export class MyService {
    async findAll(): Promise<MyServiceData> {
        return await this.dataSource.get('/');
    }
}
```

I think if I'm not wrong the way is to create and explorer service which will find all services with @DataSource decorator and then create the property dataSource. 
But I don't really understand how to apply the explorer service and to create the property dataSource in MyService.

Can you provide an example of implementation and your thoughts on the subject ? 

Thanks a lot ! 
Aurélien

**Comment by kamilmysliwiec** [comment]
What about defining them as custom providers + using request scoped providers?

**Comment by SugarDarius** [comment]
Thanks for your answer :) 
I try it and it works. But unluckily it slows the performances. 
In fact to get better performances it's better to create a custom param decorator like : 
```TypeScript
@DataSource('myDataSourceName') 
``` 
Event if it's redundant from the point of view of the code I don't have any performance loss. 

I close the issue.
Thanks a lot for your help :)
