### ISSUE TITLE
GraphQL Federation Mercurius not working properly when using external references

### ISSUE THREAD

**Issue by all2pie** [nestjs/graphql#2157]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I have converted the [sample-31-graphql-federation-code-first](https://github.com/nestjs/nest/tree/master/sample/31-graphql-federation-code-first) to use Mercurius Federation. 

Individual services are working correctly but gateway is not able to start.

### Minimum reproduction code

https://github.com/all2pie/Nestjs-GraphQL-Federation-Mercurius

### Steps to reproduce

Check the README.md

### Expected behavior

The gateway should be able to fetch the SDLs correctly

### Package version

^10.0.10

### Graphql version

Check the related `package.json`

### NestJS version

8.2.2

### Node.js version

16.14.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Would you like to look into this one @Davide-Gheri?

**Comment by Davide-Gheri** [comment]
I suppose this issue is the same or similar to #2029 and #2112 , an incompatibility with graphql16.
This PR on the

**Comment by jfairley** [comment]
Shouldn't closing this issue wait until that PR is merged?

**Comment by all2pie** [comment]
@Davide-Gheri Just to verify my issue is related to Mercurius Federation but you mentioned the Apollo Federation is that by mistake or are they related somehow?

**Comment by kdawgwilk** [comment]
@all2pie It appears to be related to incompatibilities with graphql@16

**Comment by all2pie** [comment]
@kdawgwilk  Thanks for the clarification, should I track this [PR](https://github.com/apollographql/federation/pull/1539) for the bug resolution ?

**Comment by kdawgwilk** [comment]
@all2pie yeah I would follow that
