### ISSUE TITLE
Complexity Plugin does not Inject Dependencies

### ISSUE THREAD

**Issue by prandell** [nestjs/graphql#2170]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When trying to follow the [Nest Documentation on using the ComplexityPlugin](https://docs.nestjs.com/graphql/complexity) in GraphQL - the documentation states that the plugin can be defined anywhere and added to the `providers` array of any module.

However, when creating a separate module to the main `AppModule` and adding the `ComplexityPlugin` to the corresponding `providers` array of that module, a dependency injection failure error occurs:

```
Nest can't resolve dependencies of the ComplexityPlugin (?). Please make sure that the argument GraphQLSchemaHost at index [0] is available in the BookModule context.

Potential solutions:
- If GraphQLSchemaHost is a provider, is it part of the current BookModule?
- If GraphQLSchemaHost is exported from a separate @Module, is that module imported within BookModule?
  @Module({
    imports: [ /* the Module containing GraphQLSchemaHost */ ]
  })
  ```

This can be resolved by adding it to the `providers` array of the main `AppModule` and then exporting it from said module, but that isn't quite reflected in the documentation

### Minimum reproduction code

https://github.com/prandell/nestjs-graphql-complexity-bug

### Steps to reproduce

1. `npm i`
2. `npm run start:dev`

### Expected behavior

The `@Plugin` decorator allows the AppModule to inject the instance of `GraphQLSchemaHost` to the plugin from any external module. Alternatively, update the documentation to state that the Plugin must be defined in the `providers` array of the `AppModule` and exported to be used in other modules

### Package version

10.0.11

### Graphql version

`graphql`: 16.5.0
`apollo-server-express`: 3.7.0
`apollo-server-fastify`: N/A

### NestJS version

8.0.0 & 8.4.4

### Node.js version

16.14.2

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
