### ISSUE TITLE
Allow finding resolvers by globs for `gqlSchemaFactory`

### ISSUE THREAD

**Issue by Faithfinder** [nestjs/graphql#2172]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I would like to decouple building the schema from running the server. There's already a solution - https://docs.nestjs.com/graphql/generating-sdl, however it requires developers to register the resolvers in two places - the modules for the app, and in the schema factory for the builder. I would like to avoid that duplication

### Describe the solution you'd like

I would like the factory to accept globs, and not just resolvers

### Teachability, documentation, adoption, migration strategy

"You can also use globs in place of resolver classes":
```ts
const schema = await gqlSchemaFactory.create(
  ['src/**.resolver.ts'],
  ['src/**.scalar.ts'],
);
```

### What is the motivation / use case for changing the behavior?

-

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

This has been discussed in the past and we decided to not implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
