### ISSUE TITLE
PartialType Helper runs unnecessary recursions over fields of inherited classes multiple times and causes slower bootstrap time

### ISSUE THREAD

**Issue by rezoled** [nestjs/graphql#2187]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Using PartialType function on a GQL Schema causes slow bootstrap time.
PartialType helper is using [getFieldsAndDecoratorForType](https://github.com/nestjs/graphql/blob/aa288751e4e1fcf72083d15529888c04dcdcf84c/packages/graphql/lib/schema-builder/utils/get-fields-and-decorator.util.ts#L16) util function.
This function is supposed to retrieve a list of all the fields a schema has, but it actually returns multiple sets of all the fields.

Example: 
```
import {Field, InterfaceType, ObjectType, PartialType} from "@nestjs/graphql";

@InterfaceType({
	isAbstract: true,
})
class Base {
	@Field()
	baseField:string;
}

@InterfaceType({
	isAbstract: true,
	implements: Base,
})
class Baz extends Base {
	@Field()
	bazField:string;
}

@InterfaceType({
	isAbstract: true,
	implements: Baz,
})
class Bar extends Baz {
	@Field()
	barField:string;
}

@ObjectType({
	implements: Bar,
})
class Foo extends Bar {
	@Field()
	fooField:string;
}

PartialType(Foo);
```

The util `getFieldsAndDecoratorForType` which is called inside PartialType should return a list of 4 fields [fooField, barField, bazField, baseField].
This is what I get while debugging:
![Screen Shot 2022-05-22 at 10 42 27 AM](https://user-images.githubusercontent.com/96173928/169684479-c2e584be-7d3e-4917-a1ba-38a6fb24eba6.png)

The cause is line [88-91](https://github.com/nestjs/graphql/blob/aa288751e4e1fcf72083d15529888c04dcdcf84c/packages/graphql/lib/schema-builder/utils/get-fields-and-decorator.util.ts#L88), the function iterates over each inherited class twice. getFieldsAndDecoratorForType returns all the fields for the class and its prototype chain in #88, and in #91 inheritClassFields is collecting the same fields and merges them.

Because PartialType iterated over all the fields of the class to mark them as optional this bug becomes very expensive in some scenarios.

Having this behavior synchronised to the bootstrap of the application, while having many schemas that have many layers of inheritance, and running PartialType for each schema causes a significant slowdown of the application start up time.

### Minimum reproduction code

https://github.com/rezoled/nest-partial-type-recursive-bug

### Expected behavior

getFieldsAndDecoratorForType should return only the unique set of fields for a schema, and not multiple sets of the fields

### Package version

10.0.11

### Graphql version

`graphql`: 16.5
`apollo-server-express`: 3.7 

### NestJS version

8.4.5

### Node.js version

16.14.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by rezoled** [comment]
I'd be happy to. Where can I find the PR guidelines?

**Comment by kamilmysliwiec** [comment]
You can check out this file https://github.com/nestjs/graphql/blob/master/CONTRIBUTING.md
Setting up the local environment is as simple as running:
```
$ yarn
$ yarn build # to build all projects
```

to run tests, run:

```
$ yarn e2e
```
