### ISSUE TITLE
body.query is not parsed correctly

### ISSUE THREAD

**Issue by vyvc-comartek** [nestjs/graphql#2190]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

![image](https://user-images.githubusercontent.com/99165384/169943636-0b7d7617-34f5-42c6-b489-3c50e9f60e95.png)

### Minimum reproduction code

https://github.com/vyvc-comartek/gql-test

### Steps to reproduce

- `npm run start:debug`

- Make query1: `test(input: { str: "str" })`
--> Result: `{
  "data": {
    "test": "{\"obj\":{\"q\":\"str\"},\"str\":\"str\"}"
  }
}`

- Make query2 after query1: `test(input: {})`
--> Result: `{
  "data": {
    "test": "{\"obj\":{\"q\":\"str\"}}"
  }
}`

### Expected behavior

Make query2 with result: 
`{
  "data": {
    "test": "{\"obj\":{}}"
  }
}`

### Package version

^10.0.12

### Graphql version

`graphql`: ^16.5.0
`apollo-server-express`: ^3.7.0
`apollo-server-fastify`: 

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
