### ISSUE TITLE
Graphql-playground cannot working properly

### ISSUE THREAD

**Issue by ykxhzfj** [nestjs/graphql#2193]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

i open"localhost:3000/graphql" graphql-playground correctly. but nothing at the page. 
the browser console hint the following.
GET https://cdn.jsdelivr.net/npm/@apollographql/graphql-playground-react@1.7.42/build/static/css/index.css net::ERR_CONNECTION_TIMED_OUT
GET https://cdn.jsdelivr.net/npm/@apollographql/graphql-playground-react@1.7.42/build/static/js/middleware.js net::ERR_CONNECTION_TIMED_OUT
could not find config

### Minimum reproduction code

sorry

### Expected behavior

i hope graphql-playground can working correctly

### Package version

5.3.1

### Graphql version

`graphql`: "5.3.1",
`apollo-server-express`: "^2.4.0"
`apollo-server-fastify`: 

### NestJS version

"^5.4.0"

### Node.js version

12.18.4

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
