### ISSUE TITLE
`resolveReference` no longer called correctly in latest `@apollo/subgraph` version

### ISSUE THREAD

**Issue by trevor-scheer** [nestjs/graphql#2228]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Nest appears to depend on some non-public API within the subgraph library by calling the `resolveReference` functions directly. The location of this function was moved onto the `extensions` object in latest versions of the `@apollo/subgraph` library, so the usage needs to be updated here.

I'm not quite sure how users install dependencies and use the nest framework, so this may or may not be a breaking change for your library.

To see the change that was made: https://github.com/apollographql/federation/pull/1747

(I'm going to fill out the rest of the required template bits with nonsense, I'm not going to provide a reproduction but maybe @NeutronScott12 can)

Other useful links:
https://github.com/apollographql/federation/issues/1895
https://github.com/nestjs/graphql/blob/260ec9e7aebd79c4c63b8eab2f541d1516b41615/packages/graphql/lib/utils/transform-schema.util.ts#L31-L37
https://github.com/nestjs/graphql/blob/260ec9e7aebd79c4c63b8eab2f541d1516b41615/packages/graphql/lib/utils/transform-schema.util.ts#L85

And since I noticed it, `transformSchema` from `apollo-tooling` is no longer used (it lives in the federation repo now) so this comment should be updated:
https://github.com/nestjs/graphql/blob/260ec9e7aebd79c4c63b8eab2f541d1516b41615/packages/graphql/lib/utils/transform-schema.util.ts#L1-L3

**Comment by NeutronScott12** [comment]
Thanks for opening it here.

But it's once you install subgraph 4.2, it stops resolving across the services.

I tried with the example in samples - https://github.com/nestjs/nest/tree/master/sample/31-graphql-federation-code-first and it still didn't work.

But once I changed the version to 4.0, it worked again.

**Comment by kdawgwilk** [comment]
@NeutronScott12 Did you mean subgraph 2.0?  4.0/4.2 doesn't appear to be a valid version

**Comment by NeutronScott12** [comment]
> @NeutronScott12 Did you mean subgraph 2.0? 4.0/4.2 doesn't appear to be a valid version

0.4.2(forgot to add the 0), Nest doesn't work for version 2 of anything of Apollo yet.

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR to address this issue?

**Comment by trevor-scheer** [comment]
-> #2245

**Comment by kamilmysliwiec** [comment]
Thank you @trevor-scheer! Let's track this here https://github.com/nestjs/graphql/pull/2245
