### ISSUE TITLE
Schema first @Resolver decorator not working in some cases

### ISSUE THREAD

**Issue by kdawgwilk** [nestjs/graphql#2234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

My goal is to build a federated Supergraph but in order to avoid overhead of needing to manage many subgraphs at an early stage I am only building a single subgraph.  With this in mind I want to support migrating modules out into their own subgraphs easier.  The way of accomplishing this is to encapsulate each of the domains in each module and keep loose coupling between each of the services the `Resolver` classes depend on.  An example that show cases this and reproduces the bug is linked below but to give an overview here.

# Users Module

`users.graphql`
```graphql
type User @key(fields: "id") {
  id: ID!
  name: String!
}
extend type Post {
  user: User
}
extend type Query {
  getUser(id: ID!): User
}
```

`users.resolver.ts`
```typescript
@Injectable()
export class UsersResolver {
  constructor(private usersService: UsersService) {}

  @Query()
  getUser(@Args('id') id: number) {
    return this.usersService.findById(id);
  }

  @Resolver('Post')
  @ResolveField('user')
  user(@Parent() post: Post) {
    return this.usersService.findById(post.id);
  }

  @Resolver('User')
  @ResolveReference()
  resolveReference(reference: { __typename: string; id: number }) {
    return this.usersService.findById(reference.id);
  }
}
```

# Posts Module

`posts.graphql`
```graphql
type Post @key(fields: "id") {
  id: ID!
  title: String!
  body: String!
}
extend type User {
  posts: [Post]
}
extend type Query {
  getPosts: [Post]
}
```
`posts.resolver.ts`
```typescript
@Injectable()
export class PostsResolver {
  constructor(private readonly postsService: PostsService) {}

  @Resolver('User')
  @ResolveField('posts')
  public posts(@Parent() user: User) {
    return this.postsService.findAllByAuthorId(user.id);
  }

  @Query('getPosts')
  getPosts() {
    return this.postsService.findAll();
  }
}
```

### Minimum reproduction code

https://github.com/kdawgwilk/nest/tree/kaden/schema-gql-bug/sample/32-graphql-federation-schema-first

### Steps to reproduce

1. Start core subgraph
```sh
cd core-application && npm install && npm run start
```
2. Start gateway
```sh
cd gateway && npm install && npm run start
```
3. Open http://localhost:3002/graphql in your browser
4. Run the following query in playground
```graphql
query getUserWithPosts($userId: ID!) {
  getUser(id: $userId) {
    id
    name
    posts {
      id
      title
      user {
        id
        name
      }
    }
  }
}
```
5. See posts is null because Nest does not know how to resolve the posts field

### Expected behavior

`User.posts` is resolved normally because the `PostsResolver` annotated the posts function with 
```typescript
  @Resolver('User')
  @ResolveField('posts')
  public posts(@Parent() user: User) {
    return this.postsService.findOneByAuthorId(user.id);
  }
```

### Package version

10.0.0 or 10.0.12

### GraphQL version

`graphql`: 15.7.2 or 16.50
`apollo-server-express`: 3.6.2 or 3.6.7

### NestJS version

8.2.3 or 8.3.0

### Node.js version

16.14.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kdawgwilk** [comment]
Could I work around this issue by providing my own resolver mapping for a few of these fields and let the auto-mapping work for the rest?

**Comment by NeutronScott12** [comment]
Yeah, I separate them into their own resolvers, it seems you can not mix them easily, someone else had a similar issue.

Maybe you two can solve this issue.

https://github.com/nestjs/nest/issues/9752
