### ISSUE TITLE
Unable to set enum as a type of a union

### ISSUE THREAD

**Issue by d3v0ps** [nestjs/graphql#2265]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When setting an enum as a possible type of a union, it fails

### Minimum reproduction code

https://gist.github.com/d3v0ps/92e4e866624f5e87004ef378f5e2b471

### Steps to reproduce

1. define an enum type
2. register the enum
3. define another type
4. create a union type with the enum and the other type
5. Unable to set the enum type as a possible union type

### Expected behavior

The enum should be able to be registered as possible union type

### Package version

10.0.8

### Graphql version

`graphql`:  16.3.0
`apollo-server-express`:  3.6.7

### NestJS version

8.4.3

### Node.js version

14.16.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

Type 'readonly [typeof GenderType, typeof TextScalar]' is not assignable to type 'readonly Type<unknown>[]'.
  Type 'typeof GenderType | typeof TextScalar' is not assignable to type 'Type<unknown>'.
    Type 'typeof GenderType' is missing the following properties from type 'Type<unknown>': apply, call, bind, prototype, and 5 more.ts(2322)
create-union-type.factory.d.ts(28, 12): The expected type comes from the return type of this signature.

**Comment by kamilmysliwiec** [comment]
https://github.com/graphql/graphql-spec/issues/215
