### ISSUE TITLE
Extensions are lost from types created via PickType() when using ResolveField()

### ISSUE THREAD

**Issue by bryanmig** [nestjs/graphql#2285]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When a field is decorated with `@Extensions()` on a base type, and then is picked into a new type via PickType, AND the field is resolved via `ResolveField()`, the extensions are lost. 

### Minimum reproduction code

https://github.com/bryanmig/nest-graphql-repro-2285

### Steps to reproduce
1. Create a type `One` with fields that have extensions applied and another type `Two` that picks the fields from `One`
2. Create a resolver, `TwoResolver` that resolves queries for `Two`, and add a field resolver for one of the previously created fields

```typescript
@ObjectType()
class One {
    @Field(() => ID)
    @Extensions({
        test: true
    })
    field1: string;

    @Field(() => ID)
    @Extensions({
        test: true
    })
    field2: string;
}


@ObjectType()
export class Two extends PickType(One, ["field1", "field2"] as const) {}


@Resolver(() => Two)
export class TwoResolver {
  @Query(() => Two)
  async testQuery(
    @Args('id', { type: () => Int }) id: number,
  ): Promise<Partial<Two>> {
    return {
      field1: "working"
    };
  }

  @ResolveField(() => String)
  async field2() {
    return "not working"
  }
}
```

See repro for full reproduction including middleware that asserts the existence of the extension metadata.  To test the behavior, navigate to the Playground at http://localhost:3000/graphql and run the query:
```graphql
query Query {
  author(id: 1){
    posts{
      id
    }
  }
}
```

Note: the field resolvers do work as expected when not using `PickType`			

### Expected behavior

Extension should be maintained from source type to picked type through to field resolvers.

### Package version

10.0.18

### Graphql version

    "graphql": "^16.5.0",
    "@nestjs/apollo": "^10.0.17",
    "@nestjs/common": "^9.0.1",
    "@nestjs/core": "^9.0.1",
    "@nestjs/graphql": "^10.0.18",
    "@nestjs/platform-express": "^9.0.0",
    "apollo-server-express": "^3.9.0",

### NestJS version

9.0.1

### Node.js version

18.3

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by bryanmig** [comment]
I believe the issue originates in the `TypeMetadataStorageHost` class here: https://github.com/nestjs/graphql/blob/da8c23ac915cdfc2cebffe0cf38921301a7bb246/packages/graphql/lib/schema-builder/storages/type-metadata.storage.ts#L375-L415

In this piece of code, Nest looks up the object type class (`objectTypeRef`) and correctly finds the class that was dynamically generated by `PickType`.  Nest will then attempt to get all of the fields on this object type by basically looking at the class properties.  This works fine for normal `ObjectType()` classes but `PickType` doesn't have class properties defined for each of the fields that were picked.  As I understand it, the class only has metadata attached to describe the fields.  So because there are no fields, Nest applies the default options to this field resolver.

**Comment by Davide-Gheri** [comment]
Hey @bryanmig I tried to look into this issue and updating @nestjs/graphql to the latest version was enough to fix It. I suppose #2337 also fixed this.

Can this be closed?
