### ISSUE TITLE
Implement loadeds for Mercurius driver

### ISSUE THREAD

**Issue by akaNightmare** [nestjs/graphql#2288]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Mercurius provides the `loaders` options which allow avoiding 1:n problem, and it would be great to have this feature from the box.

### Describe the solution you'd like

A great solution exists in https://github.com/Davide-Gheri/nestjs-mercurius/ repo.

### What is the motivation / use case for changing the behavior?

No need to create own behaviour of the loaders for mercurius

**Comment by kamilmysliwiec** [comment]
Just use `dataloader` package in combination with the request-scoped providers. A built-in "loaders" feature is not needed when you use Nest.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
