### ISSUE TITLE
Make it easier to register custom directives

### ISSUE THREAD

**Issue by Karibash** [nestjs/graphql#2293]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

It would be useful to be able to register directives with the provider, like a custom scalar.
https://docs.nestjs.com/graphql/scalars#schema-first

### Describe the solution you'd like

```ts
interface CustomDirective {
  transformer: (schema: GraphQLSchema, directiveName: string) => SchemaMapper;
}
```

It would be more convenient if custom directives could be implemented by simply registering the class that implements the interface with the provider, just as custom scalars can be registered with the provider.

```ts
@Directive()
class UpperDirective implements CustomDirective {
  transformer(schema, directiveName) {
    return {
      [MapperKind.OBJECT_FIELD]: (fieldConfig) => {
        const upperDirective = getDirective(schema, fieldConfig, directiveName);

        if (upperDirective) {
          const { resolve = defaultFieldResolver } = fieldConfig;

          fieldConfig.resolve = async function (source, args, context, info) {
            const result = await resolve(source, args, context, info);
            if (typeof result === 'string') {
              return result.toUpperCase();
            }
            return result;
          };
          return fieldConfig;
        }
      },
    };
  }
}
```

```ts
@Module({
  providers: [UpperDirective],
})
export class CommonModule {}
```

### What is the motivation / use case for changing the behavior?

This makes it easier to create custom directives.

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

There are no plans to implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
