### ISSUE TITLE
Make it possible to register GraphQL transformers with the provider

### ISSUE THREAD

**Issue by Karibash** [nestjs/graphql#2296]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

This is a more abstract version of the following proposal.
https://github.com/nestjs/graphql/issues/2293

### Describe the solution you'd like

I would like to be able to register GraphQL transformers with the provider.

```ts
export interface GqlSchemaTransformer {
  transform(schema: GraphQLSchema,): GraphQLSchema | Promise<GraphQLSchema>;
}

export function Transformer(): ClassDecorator {
  ...
}

@Transformer()
class AuthDirectiveTransformer implements GqlSchemaTransformer {
  constructor(
    private readonly userRepository: UserRepository,
  ) {}

  transform(schema) {
    return mapSchema(schema, {
      [MapperKind.OBJECT_FIELD]: (fieldConfig) => {
        const authDirective = getDirective(schema, fieldConfig, 'auth');

        if (authDirective) {
          const { resolve = defaultFieldResolver } = fieldConfig;

          fieldConfig.resolve = async function (source, args, context, info) {
            const user = await this.userRepository.findByToken(context.headers.authToken);
            if (!user.hasRole(authDirective.requires)) {
              throw new Error('not authorized')
            }
            return resolve(source, args, context, info)
          };
          return fieldConfig;
        }
      },
    });
  }
}

@Module({
  providers: [AuthDirectiveTransformer],
})
export class CommonModule {}
```

### What is the motivation / use case for changing the behavior?

Currently, to convert a GraphQL schema, it must be defined as a pure function, and there is no way to access providers managed by NestJS.
However, if a GraphQL schema transformer can be registered with NestJS as a provider, it will be possible to access other providers.
This allows for greater flexibility in implementation, as the GraphQL schema transformer can manipulate repositories, etc.

**Comment by kamilmysliwiec** [comment]
As I've mentioned here https://github.com/nestjs/graphql/issues/2293#issuecomment-1181387385, there are no plans to implement this feature.

> Currently, to convert a GraphQL schema, it must be defined as a pure function, and there is no way to access providers managed by NestJS.

That's the expected behavior.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
