### ISSUE TITLE
Missing GATEWAY_BUILD_SERVICE const after upgrading to the latest @nestjs/graphql 10.0.21

### ISSUE THREAD

**Issue by RebMeir** [nestjs/graphql#2319]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Versions

9.1.2 -> 10.0.21

### Describe the regression

We used the [Sharing context](https://5f3388cfce68c70007e29eee--docs-nestjs.netlify.app/graphql/federation#sharing-context) to share the context of the requests to the subgraphs.
In the previous versions we have the `GATEWAY_BUILD_SERVICE ` const from `@nestjs/graphql` package.
But after the upgrade of the package I can't find it.

### Minimum reproduction code

```ts
import { Module } from '@nestjs/common';
import { GATEWAY_BUILD_SERVICE } from '@nestjs/graphql';
import { RemoteGraphQLDataSource } from '@apollo/gateway';

export class RemoteDataSource extends RemoteGraphQLDataSource {
    async willSendRequest({ request, context }) {
        // Get the operation name from the context
        const operationName = context.operationName;
        // Add the above operation name as http header to the request
        request.http.headers.set('operationName', operationName);
    }
}

@Module({
    providers: [
        {
            provide: RemoteDataSource,
            useValue: RemoteDataSource
        },
        {
            provide: GATEWAY_BUILD_SERVICE,
            useFactory: (RemoteDataSource) => {
                return ({ name, url }) => new RemoteDataSource({ url });
            },
            inject: [RemoteDataSource]
        }
    ],
    exports: [GATEWAY_BUILD_SERVICE]
})
export class BuildServiceModule {}

```

### Expected behavior

Module `@nestjs/graphql'` should export the `GATEWAY_BUILD_SERVICE` const.

**Comment by RebMeir** [comment]
I see it was changed here:
https://github.com/nestjs/graphql/commit/abbcac76592651931e45f87b92d75a1dc4aef39b#diff-b43154b751ddd37ea060fe44442ec78d9827bee4f2bea494c2a7e28898b9b0d5L1
what should I do?
Can you please update the documentation?

**Comment by longfeiyu127** [comment]
I find the answer here。 [apollo-gateway](https://www.apollographql.com/docs/federation/api/apollo-gateway#class-remotegraphqldatasource)

**Comment by kamilmysliwiec** [comment]
There's a `buildService` configuration property in the latest version of Apollo:

![image](https://user-images.githubusercontent.com/23244943/184137523-3f58ff36-a4d2-45d3-bf7f-dff2cbfa60ec.png)
 
 See their docs https://www.apollographql.com/docs/federation/api/apollo-gateway/#configuring-the-subgraph-fetcher
