### ISSUE TITLE
defaultValue in @Field decorator cannot be taken from enum values

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [nestjs/graphql#2321]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

 @Field(() => VerificationStatus, {
        defaultValue: VerificationStatus.none, // <--------- here compiler throws an error: Cannot read properties of undefined (reading 'none')
        nullable: true,
    })
    verificationStatus: VerificationStatus = VerificationStatus.none;

### Minimum reproduction code

-

### Expected behavior

Value can be taken from enum

### Package version

8.1.3

### Graphql version

`graphql`: 
`apollo-server-express`: 
`apollo-server-fastify`: 

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

**Comment by vytautas-pranskunas-** [comment]
@jmcdo29 if you would have started graphql project in stakcblitz this would be much easier but now i do not have time for this sry. I have just hardcoded it as string 'none'
