### ISSUE TITLE
Linting errors with Decorators and PHPSTORM  TS1241 with target es2017

### ISSUE THREAD

**Issue by Eddy84** [nestjs/graphql#2324]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Versions

9.0.0

### Describe the regression

Hello

 I am using nestjs with the default settings (target:"es2017") and get the linting error below in PHPStorm.
 When I switch to target ES5 the linting errors go away.
 
 The app works fine with target ES2017, its just about the liniting errors.

My tsconfig settings:
```
...
"emitDecoratorMetadata": true,
"experimentalDecorators": true,
"target": "es2017",
 ...
```
a

### Minimum reproduction code

```
TS1241: Unable to resolve signature of method decorator when called as an expression.
TS1270: Decorator function return type 'void | TypedPropertyDescriptor<unknown>' is not assignable to type 'void | TypedPropertyDescriptor<() => Promise<Building[]>>'.   Type 'TypedPropertyDescriptor<unknown>' is not assignable to type 'void | TypedPropertyDescriptor<() => Promise<Building[]>>'.     Type 'TypedPropertyDescriptor<unknown>' is not assignable to type 'TypedPropertyDescriptor<() => Promise<Building[]>>'.       Type 'unknown' is not assignable to type '() => Promise<Building[]>'.         Type '{}' provides no match for the signature '(): Promise<Building[]>'.
```
```
import { Query, Resolver } from '@nestjs/graphql';
import { Building } from '../models/building.model';

@Resolver(() => Building)
export class BuildingsResolver {
  @Query(() => [Building])
  async buildings(): Promise<Building[]> {
    const b = new Building();
    b.id = 1;
    b.area = 12.3;
    return [b];
  }
}

```

### Expected behavior

nestjs graphql should work without linting / type errors out of the box or atleast there should be a statement in the docs that you need to switch to ES5.

**Comment by kamilmysliwiec** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).
