### ISSUE TITLE
Field description overwritten when using model extends and ResolveField()

### ISSUE THREAD

**Issue by mattleff** [nestjs/graphql#2331]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When a field is defined in a base class that is extended by a model and that model has a resolver with a `ResolveField()` implemented for that base class field, the field `description` (and `deprecationReason`, etc.) in the base class is lost. This applies even if the `ResolveField()` in the resolver defines no options. 

### Minimum reproduction code

https://codesandbox.io/s/objective-ramanujan-53gmy7

### Steps to reproduce

1. Load CodeSandbox
2. Go to https://53gmy7.sse.codesandbox.io/graphql
3. Hover or check docs for `Cat.name`

### Expected behavior

`Cat.name` should have the description `"The name of the cat"` from `CatBase`. `Cat.isHidden` (which does not have a `ResolveField()` in the resolver) and `Cat.age` (which has a `ResolveField()` in the resolver, but the description is defined in the model instead of the base class) both correctly show their descriptions.

### Package version

10.0.21

### Graphql version

`graphql`: 16.5.0
`apollo-server-express`: 3.10.1

### NestJS version

9.0.9

### Node.js version

16.x

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [X] Linux

### Other

This is similar to #1012, #1424, and #2285. I'm happy to send a PR if you agree this is something that should be fixed.

**Comment by kamilmysliwiec** [comment]
PRs are more than welcome @mattleff! 🙌

**Comment by adalinesimonian** [comment]
This issue has not been resolved for resolvers which provide their property names via the decorator. For example:

```typescript
// The following will overwrite the base model options:
@ResolveField('fieldName', () => [Type])
async getFieldName(@Parent() parentType: ParentType) {
  // ...
}

// The following will not:
@ResolveField(() => [Type])
async fieldName(@Parent() parentType: ParentType) {
  // ...
}
```
