### ISSUE TITLE
`@InputType` field can not be deprecated

### ISSUE THREAD

**Issue by dersar00** [nestjs/graphql#2354]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Adding a `@InputType` field a `deprecationReason` option does not apply and it is missing in the generated schema.

### Minimum reproduction code

https://github.com/dersar00/nest-gql-input-type-bug

### Expected behavior

The `@InputType` field works the same as the `@ObjectType` and can be deprecated.

### Package version

10.0.16

### Graphql version

`graphql`: 15.5.1
`apollo-server-express`: 3.3.0

### NestJS version

8.2.3

### Node.js version

16.13.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
https://github.com/graphql/graphql-spec/issues/197
