### ISSUE TITLE
@nestjs/mercurius uses `lodash` without defining it as a dependency

### ISSUE THREAD

**Issue by andreialecu** [nestjs/graphql#2364]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

See: https://github.com/nestjs/graphql/blob/28d5294269be8a20f044de90e69bfc8ec43dc85c/packages/mercurius/lib/utils/build-mercurius-federated-schema.util.ts#L5

And: https://github.com/nestjs/graphql/blob/28d5294269be8a20f044de90e69bfc8ec43dc85c/packages/mercurius/package.json

This results in runtime errors when using Yarn 3 in PnP mode.

### Minimum reproduction code

...

### Expected behavior

The `forEach` call could probably be rewritten to use `Object.entries` instead

### Package version

10.0.5

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
> The forEach call could probably be rewritten to use Object.entries instead

Sounds good!

Would you like to create a PR to fix this issue?

**Comment by andreialecu** [comment]
Opened #2367

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/graphql/pull/2367
