### ISSUE TITLE
Interface fails to declare field in schema that comes from a parent interface's field resolver

### ISSUE THREAD

**Issue by CarsonF** [nestjs/graphql#2374]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Interface fails to declare field in schema that comes from a parent interface's field resolver

### Minimum reproduction code

https://github.com/CarsonF/nest-graphql-interface-resolve-from-parent-interface/commit/badd1335929a05c4e349fe7bbfcfae1a5801f676

### Expected behavior

The field resolver from the extended interface should apply to the interfaces that extend from it.

### Package version

10.0.22

### Graphql version

`graphql`: 16.6.0
`apollo-server-express`: 3.10.2

### NestJS version

9.0.0

### Node.js version

16.17.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/graphql/pull/2375
