### ISSUE TITLE
Jest tests fail when using globalSetup option

### ISSUE THREAD

**Issue by iamkhalidbashir** [nestjs/graphql#2389]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Jest e2e tests fail when using globalSetup option
I suspect the issue has something to do with circular dependency between Dto files (as shown in the attached Minimum reproduction code)

### Minimum reproduction code

https://github.com/iamkhalidbashir/nestjs-graphql-jest-error

### Steps to reproduce

# To reproduce failing tests:-
1. `npm run ci`
2. `npm run build`
3. `npm run test:e2e`

# To check why the tests fail
4. Comment [line](https://github.com/iamkhalidbashir/nestjs-graphql-jest-error/blob/79b644e11db4467e90a3bb284767990801c84559/test/globalSetup.ts#L8)
5. `npm run test:e2e` <--- The tests will pass

### Expected behavior

Should pass regardless of using globalSetup in jest options ot not

### Package version

10.1.1

### Graphql version

`graphql`: 16.6.0
`apollo-server-express`: 3.10.2
`apollo-server-fastify`: null

### NestJS version

10.1.1

### Node.js version

v14.20.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

```
> jest --config ./test/jest-e2e.json

Determining test suites to run...[class AppResolver]
 FAIL  test/app.e2e-spec.ts
  AppController (e2e)
    ✕ getMembers
    ✕ getGroups

  ● AppController (e2e) › getMembers

    Cannot determine a GraphQL output type for the "name". Make sure your class is decorated with an appropriate decorator.

      at OutputTypeFactory.create (../node_modules/@nestjs/graphql/dist/schema-builder/factories/output-type.factory.js:19:23)
          at Array.forEach (<anonymous>)

  ● AppController (e2e) › getGroups

    Cannot determine a GraphQL output type for the "name". Make sure your class is decorated with an appropriate decorator.

      at OutputTypeFactory.create (../node_modules/@nestjs/graphql/dist/schema-builder/factories/output-type.factory.js:19:23)
          at Array.forEach (<anonymous>)

Test Suites: 1 failed, 1 total
Tests:       2 failed, 2 total
Snapshots:   0 total
Time:        0.838 s, estimated 1 s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nest-typescript-starter@1.0.0 test:e2e: `jest --config ./test/jest-e2e.json`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nest-typescript-starter@1.0.0 test:e2e script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bashir/.npm/_logs/2022-09-08T14_12_22_004Z-debug.log
```

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
