### ISSUE TITLE
how to test

### ISSUE THREAD

**Issue by Jimmysh** [nestjs/graphql#24]
how to test graphql use nestjs

**Comment by kamilmysliwiec** [comment]
In the exact same way as you test native Apollo GraphQL. I'll provide more detailed example soon. Note: please, use documentation repository for such issues.

**Comment by vagostep** [comment]
Coverage not cover this line in Resolvers!

![Screenshot_1](https://user-images.githubusercontent.com/15386436/58822541-6341fd80-85fd-11e9-83ee-09fa797f6c87.png)

**Comment by chasen-bettinger** [comment]
Experiencing same experience as @vagostep .
