### ISSUE TITLE
ValidationPipe error when optional argument in resolver is null

### ISSUE THREAD

**Issue by maksimkurb** [nestjs/graphql#242]
## Current behavior
Even when optional argument in resolver is null, class is being created and checked via class-validator resulting BadRequest error

## Expected behavior
If optional argument is null, it should not be checked with class-validator

## Minimal reproduction of the problem with instructions
https://github.com/maksimkurb/graphql/tree/bug/validation-pipe
```bash
git clone https://github.com/maksimkurb/graphql bug-demo
cd bug-demo
git checkout bug/validation-pipe
yarn install
yarn build
yarn serve
```
then try to execute this request:
```graphql
# http://localhost:3000/graphql
mutation {
  addRecipeOptionalArg {
    id
  }
}
```

## What is the motivation / use case for changing the behavior?
Optional argument should be checked only if it is passed to resolver

## Environment

<pre><code>
Nest version: 6.1.1
 
For Tooling issues:
- Node version: v11.14.0
- Platform:  Windows
</code></pre>

**Comment by maksimkurb** [comment]
Update: I have found, that I can use `@UsePipes()` on resolver class. I wrote class `GraphqlValidationPipe` which is similar to `ValidationPipe`, except it has modified `toValidate` method, where it returns false, if value is null. ([example gist](https://gist.github.com/maksimkurb/8ffc13272f049b92a5d0f2708c695247))

I think [pipes documentation](https://docs.nestjs.com/pipes) (section with useGlobalPipes sample) should have a warning that `ValidationPipe` from `@nestjs/common` will not work with graphql optional types with consideration to implement custom validation pipe for graphql.

**Comment by kamilmysliwiec** [comment]
> I think pipes documentation (section with useGlobalPipes sample) should have a warning that ValidationPipe from @nestjs/common will not work with graphql optional types with consideration to implement custom validation pipe for graphql.

You could just use `@IsOptional()` decorator (`class-transformer` package). We can't use type-graphql metadata and delegate to class-transformer since we're trying to remain platform-agnostic.

**Comment by maksimkurb** [comment]
I can use `@IsOptional` only for a property, but can't use it for whole `InputType`. I have a scenario, when if argument is passed, it must contain all fields, but if it is not passed, it can be just ignored.
