### ISSUE TITLE
Schema not available in REPL

### ISSUE THREAD

**Issue by CarsonF** [nestjs/graphql#2433]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Schema is not built because an `HttpAdapterHost` / `ApplicationConfig` is not available in REPL context.
https://github.com/nestjs/graphql/blob/master/packages/graphql/lib/graphql.module.ts#L148-L151

### Minimum reproduction code

Any example should do.

### Expected behavior

Generating schema should be independent of an hosting/executing. It should be built and available even without an HTTP adapter.

### Package version

10.1.3

### Graphql version

`graphql`: 
`apollo-server-express`: 
`apollo-server-fastify`: 

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by CarsonF** [comment]
I have an authorization system, that I'd like to be informed from the GQL schema. It would use this logic on _module init_.
So it's not necessarily that I'm trying to invoke it directly from REPL, I just want REPL (and really other CLI, like nestjs-console) to still be able to boot. And I'd rather not have to add exclusions and work around making the authorization system not available in REPL/CLI.

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue? To fix this, we should likely just separate the schema creation part and move it out of the driver code (separate class? different order?)

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/graphql/pull/2435
