### ISSUE TITLE
GraphQL CLI unable to infer newly suffixed types

### ISSUE THREAD

**Issue by avedetvedea** [nestjs/graphql#2434]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I use the term `payload` like many to describe what my mutations will return. I added this suffix to the `nest-cli.json` file as described. Problem is, code-first CLI was unable to generate the corresponding `Type` in schema for this object-type. 

Because there is no "generate" command to generate the graphql schema (this was discussed in issues before; my view: a generate command is needed), I have to run `yarn start:dev` to get them generated. But then, because at first it is unable to generate them, the app throws with `Type [X] must define one or more fields.`, upon running `yarn start:dev`. 

My workaround was to put the necessary decorators and run `yarn start:dev`, and then remove them to make it infer itself onwards.

### Minimum reproduction code

https://github.com/nestjs/graphql/issues/

### Steps to reproduce

Described above

### Expected behavior

Code-first CLI to get things working when added a new suffix, at first as well.

### Package version

10.0.22

### Graphql version

graphql: 16.6.0

### NestJS version

9.0.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

I don't have time to submit a reproduction repo, feel free to delete the issue if needed.

**Comment by kamilmysliwiec** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).
