### ISSUE TITLE
Enhance documentation around nested resolvers

### ISSUE THREAD

**Issue by warent** [nestjs/graphql#2438]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Surprisingly it looks like nested resolvers aren't supported in Nest.js GraphQL apparently.

https://stackoverflow.com/questions/69741614/invoke-resolvers-of-fields-on-nested-execution-levels-in-nestjs-graphql
https://stackoverflow.com/questions/73496527/resolve-inner-or-nested-fields-in-graphql-with-nestjs
https://stackoverflow.com/questions/67419921/nested-field-resolvers-in-graphql

### Describe the solution you'd like

The ability to query on arbitrarily nested objects while reusing code defined in their respective resolvers.

### What is the motivation / use case for changing the behavior?

I don't think this is changing behavior, it's adding new behavior

**Comment by warent** [comment]
Apparently this _is_ supported. But it doesn't seem to be documented anywhere. Not that I could find at least.

Your module needs to `Provide` the nested resolver.

For example, if you have a `Library` module/resolver and a `Books` module/resolver.
You want to query like this:
```
{
  libraries {
    books {
      handle_me_in_the_books_resolver_please_not_libraries_resolver
    }
  }
}

your Library module has to `Provide` the Books resolver. So it will look something like this:
```
@Module({
  imports: [RLSModule.forFeature([Library])],
  providers: [LibrariesResolver, LibrariesService, BooksService, BooksResolver],
  exports: [LibrariesService],
})
export class LibrariesModule {}
```

I think this should be explicitly documented very clearly somewhere. It's not at all obvious.

**Comment by synerp** [comment]
How is this different than using @ResolveField?
```
  @ResolveField('books', returns => [Book])
  async getBooks(@Parent() library: Library) {
    const { id } = library;
    return this.booksService.findAll({ libraryId: id });
  }
```

**Comment by kamilmysliwiec** [comment]
> your Library module has to Provide the Books resolver. So it will look something like this:

This doesn't seem to be required. `BooksResolver` can be registered elsewhere too, it doesn't necessarily have to me listed as `LibrariesModule` provider. Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
