### ISSUE TITLE
Not able to build after @^10.1.0, when ObjectType is used like "import * as gql from '@nestjs/graphql'; @gql.ObjectType()"

### ISSUE THREAD

**Issue by tncks0121** [nestjs/graphql#2441]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

From the docs, when I want to define an ObjectType, I am expected to do it like this:

```typescript
import {ObjectType, Field} from '@nestjs/graphql';

@ObjectType()
export class HelloWorld {
  @Field(() => String)
  message: string;
}
```

But for some reason (I didn't want to import a lot), I decided to code like this:

```typescript
import * as gql from '@nestjs/graphql';

@gql.ObjectType()
export class HelloWorld {
  @gql.Field(() => String)
  message: string;
}
```

This worked until `@nestjs/graphql` v10.0.22, but when I upgrade to v10.1.0 ~ v10.1.3, I am not able to run `npm run build`.

<img width="169" alt="Screen Shot 2022-10-09 at 6 38 54 PM" src="https://user-images.githubusercontent.com/3483637/194749536-2a9a850c-1260-45c1-b6be-9b3706581215.png">

### Minimum reproduction code

https://github.com/tncks0121/nestjs-graphql-reproduction

### Steps to reproduce

Basically follow the steps as in the commits: https://github.com/tncks0121/nestjs-graphql-reproduction/commits/main

1. `nest new myapp`
2. `npm i @nestjs/graphql`
3. add @nestjs/graphql plugin into `nest-cli.json`
    ```json
    {
      "$schema": "https://json.schemastore.org/nest-cli",
      "collection": "@nestjs/schematics",
      "sourceRoot": "src",
      "compilerOptions": {
        "plugins": [
          {
            "name": "@nestjs/graphql",
            "options": {
              "typeFileNameSuffix": [".model.ts"]
            }
          }
        ]
      }
    }
    ```
5. add file `src/app.model.ts` like this. 
    ```typescript
    import * as gql from '@nestjs/graphql';

    @gql.ObjectType()
    export class HelloWorld {
        @gql.Field(() => String)
        message: string;
    }
    ```
6. Now `npm run build` shows this:
   <img width="169" alt="Screen Shot 2022-10-09 at 6 38 54 PM" src="https://user-images.githubusercontent.com/3483637/194749536-2a9a850c-1260-45c1-b6be-9b3706581215.png">

Importing GraphqlModule and creating resolvers are done in the last commit of the reproduction repository. Even without it, `npm run build` crashes.

### Expected behavior

`npm run build` should not crash.

### Package version

10.1.3

### Graphql version

`graphql`: 16.6.0
`apollo-server-express`: not used
`apollo-server-fastify`: not used

### NestJS version

9.0.0

### Node.js version

16.17.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

By inspection it seems the error occurs here (Line 168)

https://github.com/nestjs/graphql/blob/1aa7c28006c520d823c73a0eda0f61f921f33c8a/packages/graphql/lib/plugin/utils/ast-utils.ts#L165-L171

`expression.kind` is 206 (`SyntaxKind.PropertyAccessExpression`), which seems to be correct. [output.txt](https://github.com/nestjs/graphql/files/9741265/output.txt) contains the result of `console.log(expression)` and `console.log(identifier)`, to verify the claim.

I think the function `getNameFromExpression` (called in line 166) is correctly handling the case when `expression.kind === SyntaxKind.PropertyAccessExpression`

https://github.com/nestjs/graphql/blob/1aa7c28006c520d823c73a0eda0f61f921f33c8a/packages/graphql/lib/plugin/utils/ast-utils.ts#L173-L178

So maybe the error can be fixed by changing the function `getIdentifierFromName` into this:

```typescript
 function getIdentifierFromName(expression: LeftHandSideExpression) { 
   const identifier = getNameFromExpression(expression); 
   if (expression && expression.kind !== SyntaxKind.Identifier && expression.kind !== SyntaxKind.PropertyAccessExpression) { 
     throw new Error(); 
   } 
   return identifier; 
 } 
```

**Comment by kamilmysliwiec** [comment]
Fixed in 10.1.6
