### ISSUE TITLE
Incorrect behaviour on inheriting parent interface 

### ISSUE THREAD

**Issue by vip30** [nestjs/graphql#2462]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

```graphql
interface Content {
  images(skip: Int = 0, take: Int = 25, test: Int = 25): [Image]
}

type Article implements Content {
  images(skip: Int = 0, take: Int = 25, test: Int = 25): [Image]
}

type Recipe implements Content {
  images(skip: Int = 0, take: Int = 25, test: Int = 25): [Image]
}
```

### Minimum reproduction code

https://github.com/vip30/nest-graphql-reproduce

### Steps to reproduce

1. npm i
2. npm run start:dev

### Expected behavior

```graphql
interface Content {
  images: [Image]
}

type Article implements Content {
  images(skip: Int = 0, take: Int = 25, test: Int = 25): [Image]
}

type Recipe implements Content {
  images(skip: Int = 0, take: Int = 25): [Image]
}
```

### Package version

10.1.3

### Graphql version

`graphql`: 16.6.0
`apollo-server-express`: 3.10.3

### NestJS version

9.1.4

### Node.js version

16.18.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

This version ("@nestjs/graphql": "10.0.18") is working as expected

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?
