### ISSUE TITLE
Date validation is not working correctly

### ISSUE THREAD

**Issue by basiekjusz** [nestjs/graphql#2471]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Validation of date fields is not working at all. Incorrect values are transformed to `Invalid Date` or `null`.

### Minimum reproduction code

https://gist.github.com/basiekjusz/5d3a4c8e33934bddecd837071ab8ea9d

### Expected behavior

Sending query or mutation with incorrect date should result in `GRAPHQL_VALIDATION_FAILED` error.

### Package version

10.1.4

### Graphql version

`graphql`: 16.6.0
`apollo-server-express`:  3.10.3

### NestJS version

9.1.6

### Node.js version

16.5.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
