### ISSUE TITLE
GraphQL Compiler Plugin not compatible with Typescript 4.8

### ISSUE THREAD

**Issue by thekip** [nestjs/graphql#2489]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Due to changes in AST in Typescript 4.8 https://devblogs.microsoft.com/typescript/announcing-typescript-4-8/#decorators-are-placed-on-modifiers-on-typescripts-syntax-trees decorators no more accessible in the way they accessed in plugin transform. That's caused plugin to be completely non-functional. 

### Describe the solution you'd like

We need to justify plugin's transform for new typescript version while keeping backward compatibility with older typescript versions. 

### What is the motivation / use case for changing the behavior?

Want to be able to use latest typescript version

**Comment by kamilmysliwiec** [comment]
AFAIR CLI plugin was already updated to support ts 4.8 https://github.com/nestjs/graphql/commit/07aa76cc7b7e5042929a6f2a85de2f1fd310c085
