### ISSUE TITLE
Allowing multiple cors origins seems to allow all cors origins

### ISSUE THREAD

**Issue by rymanso** [nestjs/graphql#2490]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The current behaviour is that passing `origin: string` works as designed, only allowing requests from the defined origin, i.e, this works:

```
    GraphQLModule.forRoot<ApolloDriverConfig>({
      driver: ApolloDriver,
      autoSchemaFile: 'schema.gql',
      installSubscriptionHandlers: true,
      cors: { origin: 'http://localhost:3001', credentials: true },
    }),
```
request from `localhost:3001` succeeds, request from `localhost:3002` fails.

however, changing this to an array allows requests from any origin.
`cors: { origin: ['http://localhost:3001'], credentials: true }`
request from `localhost:3001` succeeds, request from `localhost:3002` succeeds.

### Minimum reproduction code

https://github.com/

### Steps to reproduce

- Alter cors config as follows `cors: { origin: [] }` - an empty array
- Run app
- curl a request to gql and find it returns a response, or open the playground.

### Expected behavior

When an array of origins are passed, any origin that is not in the array should face a cors error.
Referring to the current behaviour section:

`cors: { origin: ['http://localhost:3001'], credentials: true }`
request from `localhost:3001` succeeds, request from `localhost:3002` fails.

### Package version

10.1.3

### Graphql version

`graphql`: 16.6.0
`apollo-server-express`: 3.10.2

### NestJS version

9.0.0

### Node.js version

16.16.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
