### ISSUE TITLE
Upgrade to platform-fastify v9

### ISSUE THREAD

**Issue by sam-super** [nestjs/graphql#2502]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Because it would be nice to use a more modern versions of fastify and also to get rid of this warning:
```
(node:78725) [FST_MODULE_DEP_FASTIFY-FORMBODY] FastifyWarning.fastify-formbody: fastify-formbody has been deprecated. Use @fastify/formbody@6.0.0 instead.
```

### Describe the solution you'd like

For `@nestjs/apollo` to be made compatible with `@nestjs/platform-fastify` at `v9`.

### What is the motivation / use case for changing the behavior?

Being an outdated version of fastify (and platform-fastify) isn't great for the security and the health of the project in general (the further we get, the harder the upgrades will be).

## From what i understand:

1. https://github.com/nestjs/graphql/issues/2307#issuecomment-1190003338

> Fastify v4 cannot be used with `apollo-server-fastify` v3. If you're using Fastify + NestJS + Apollo, I'd suggest not upgrading to v9 just yet

2. `apollo-server` is relying on community modules to support fastify integration (since v4):
https://github.com/apollographql/apollo-server/releases/tag/%40apollo%2Fserver%404.0.0 (See `Removed web framework integrations`)

3. for `@nestjs/graphql` to support fastify v4 we would need to integrate with another library to support apollo-server with fastify v4.
There are some recommended libs for this:
https://www.apollographql.com/docs/apollo-server/integrations/integration-index/
https://www.npmjs.com/package/@as-integrations/fastify

(Apologies if i have misunderstood any of this, or if it is already on a roadmap, but i just wanted to check).

**Comment by kamilmysliwiec** [comment]
We're already tracking this here https://github.com/nestjs/graphql/issues/2307#issuecomment-1190003338 and here https://github.com/nestjs/graphql/issues/2445
