### ISSUE TITLE
Upgrade Apollo Server to v4

### ISSUE THREAD

**Issue by cristianTalero** [nestjs/graphql#2513]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I'm setting GraphqQL but when i install 'apollo-server-express' it says that package is deprecated and npm says same too:

The `apollo-server-express` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023). This package's functionality is now found in the `@apollo/server` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.

*From https://www.npmjs.com/package/apollo-server-express*

### I'd like to upgrade Apollo Server to v4 as I specified in the title.

Sorry for the poor issue description, I don't have much experience participating in repositories.

### What is the motivation / use case for changing the behavior?

The remaining life of apollo-server-express is specified in its npm page (As I mentioned above), and I know there is still time to migrate, but I decided to do this issue because I couldn't find another similar one (Or maybe I didn't search well, if this is the case, please cite that issue, thanks)

**Comment by tito58** [comment]
Integrar apollo server v4 a nestJs

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/graphql/issues/2445
