### ISSUE TITLE
Add resolver comment introspection to typescript plugin

### ISSUE THREAD

**Issue by Hossein-s** [nestjs/graphql#2521]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Currently typescript plugin supports introspection of comments for types. But for the operations it doesn't offer it. Would be nice to add introspection of comments from resolvers for that.

### Describe the solution you'd like

We can add support for resolver files and read comments when visiting them and add the appropriate medatada.

### What is the motivation / use case for changing the behavior?

It can make generated documentation for graphql operations more reach and we don't need to adopt another strategy for adding description of these operations in the project.

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by Hossein-s** [comment]
@kamilmysliwiec Yes I will work on it.

And I was thinking about finding also return type for it, and we can find nullable type if type is like `Promise<ReturnType | null>`.

So we can only decorate with `@Query()` and then other metadata can be extracted on compile time.

What is your opinion?
