### ISSUE TITLE
GraphQL include option not resolving resolvers.

### ISSUE THREAD

**Issue by bozvul993** [nestjs/graphql#2523]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hello, I have noticed that the include option when creating the GraphQLModule is not working:
https://docs.nestjs.com/graphql/quick-start#multiple-endpoints

I have created this repository to replicate this behaviour:
https://github.com/bozvul993/nestjs-graphql-federation/blob/main/src/graphql/app-graphql.module.ts

I am expecting in this example:  `include: [App1GraphQLModule]` for the resolvers from App1GraphQLModule to be loaded, but when trying a query in Apollo studio when running the application it is throwing an error. 
When i remove the include and provide these providers in the providers of this AppGraphQLModule resolving is working correctly.

I am aware of this open issue: https://github.com/nestjs/graphql/issues/721
But I did notice this message within the thread: 
https://github.com/nestjs/graphql/issues/721#issuecomment-632128217

so that is why i am expecting this include option to work. Otherwise the resolvers need to be shared amongst the endpoints. But this is reproducible with one endpoint as well.

### Minimum reproduction code

https://github.com/bozvul993/nestjs-graphql-federation/

### Steps to reproduce

1. `npm install`
2. `npm run start`
3. Open apollo studio on `http://localhost:3000/app1-graphql`, query `randomString` and the following error is shown:
`Cannot return null for non-nullable field Query.randomString.`

### Expected behavior

Return the string that is given in the resolver: "Welcome"

### Package version

10.1.6

### Graphql version

`graphql`: 
`apollo-server-express`: 
`apollo-server-fastify`: 

### Node.js version

18.10.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/graphql/issues/721
