### ISSUE TITLE
A way to extend schema section with @link and @composeDirective on NestJS GraphQL code first federation v2

### ISSUE THREAD

**Issue by bokjo** [nestjs/graphql#2539]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Couldn't find a way to add extra `@link` and `@composeDirective` in the `extend schema` section of the schema with the code first approach

Is there a way to easily extend the extend schema section of the schema SDL on code first approach.

On the autoSchemaFile federation v2 section of the module you can add directives to import, no way to add extra @link and @composeDirective to the same section.

Am I missing something, and is there a way to add this some other way?

Currently I'm hacking TypeDefsFederation2Decorator locally to add this stuff https://github.com/nestjs/graphql/blob/master/packages/graphql/lib/federation/type-defs-federation2.decorator.ts#L31

Not sure adding merged TypeDefs somehow can help, the formatting of the extend schema section seems important

current  outcome 

```ts
extend schema
  @link(url: "https://specs.apollo.dev/federation/v2.1", import: ["@key", "@shareable", "@external", "@override", "@requires", "@composeDirective"])
```

### Describe the solution you'd like

Should be able to add extra @link and @composeDirective to the `autoSchemaFile` federation v2 field of the GraphQL module.

 desired outcome

```ts
extend schema
  @link(url: "https://specs.apollo.dev/federation/v2.1", import: ["@key", "@shareable", "@external", "@override", "@requires", "@composeDirective"])
  @link(url: "https://myspecs.dev/complexity/v1.0", import: ["@complexity"])
  @composeDirective(name: "@complexity")
```

### Teachability, documentation, adoption, migration strategy

https://www.apollographql.com/docs/federation/federated-types/federated-directives/#composedirective

According to the apollo federation docs and compatibility matrix adding @link to the schema should be already supported in Nest

Currently using:
`@nestjs/graphql:`v10.1.5
`graphql:`v16.6.0
`apollo-server-express:`v3.11.1
`@nestjs/core:`v9.2.0
`nodejs:`v18.11.0

### What is the motivation / use case for changing the behavior?

To be able to use custom federation directives from subgraphs and preserve/propagate it to the federated supergraph.

**Comment by dariuszkuc** [comment]
Hello 👋 
This was closed but I don't see any API changes to allow easily specifying the `@composeDirective` -> I guess this is doable through `schema/transformSchema` options on `GqlModuleOptions` but it is somewhat PITA to use (as you manually need to apply the necessary transforms). Is there a better way to do it?
