### ISSUE TITLE
Use an external class as as abstract object type

### ISSUE THREAD

**Issue by coler-j** [nestjs/graphql#2548]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

We have a published open api client library that exposes some models that I would like to extend and re-use as abstract base classes for `ObjectTypes`, but I run into the `<type> doesn't have fields` error.

```
// in external dependency
export class SomeClass {
    prop1: string
    prop2: boolean
}
```

```
// in my NestJS project
import { SomeClass } from 'external-package

@ObjectType()
class MyObject extends SomeClass {}
```

### Describe the solution you'd like

```
// in my NestJS project
import { SomeClass } from 'external-package

@ObjectType()
class MyObject extends AsType(SomeClass, ObjectType) {}
```

Would be nice to have a type helper like `AsType`

### What is the motivation / use case for changing the behavior?

Might be specific to my current usecase where we are using NestJS GQL as a subgraph in front of a REST service communicating by openapi generated client.

**Comment by kamilmysliwiec** [comment]
This doesn't seem to be feasible, unfortunately.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
