### ISSUE TITLE
Add @apollo/server this apollo-server-* are deprected

### ISSUE THREAD

**Issue by luas10c** [nestjs/graphql#2556]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

It is urgently necessary to update apollo-server to @apollo/server because the previous package is deprecated

### Describe the solution you'd like

I believe that an urgent update would solve the problems

### What is the motivation / use case for changing the behavior?

Fixed issues, added new apollo studio playground

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/graphql/issues/2445
