### ISSUE TITLE
How to get the internal value of enum instead of key?

### ISSUE THREAD

**Issue by Adherentman** [nestjs/graphql#2558]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

```Typescript
export enum StatusCode {
  SUCCESS = 200,
  UnauthorizedError = 401,
  ForbiddenError = 403,
}

registerEnumType(StatusCode, {
  name: 'StatusCode',
  description: 'statusCode',
  valuesMap: {
    SUCCESS: {
      description: 'ok',
    },
    UnauthorizedError: {
      description: 'not login',
    },
    ForbiddenError: {
      description: 'no permission',
    },
  },
});

@ObjectType({ description: 'error' })
export class TTError {
  @Field(() => StatusCode, { description: 'ok' })
  statusCode: StatusCode;

  @Field({ description: 'desc' })
  message: string;
}

@ObjectType({ description: 'return' })
export class TTSuccess {
  @Field(() => StatusCode, { description: 'code' })
  statusCode: StatusCode;

  @Field({ description: 'desc' })
  message: string;
}


export const ResultSendSMS = createUnionType({
  name: 'ResultSendSMS',
  types: () => [TTSuccess, TTError] as const,
  description: 'sendSms',
  resolveType: (v: TTSuccess | TTError) => {
    if (v.statusCode == StatusCode.SUCCESS) return TTSuccess;
    return TTError;
  },
});

@Mutation(() => ResultSendSMS, { description: 'sendSms' })
async sendSMS(): Promise<TTSuccess | TTError> {
  return {
    statusCode: StatusCode.SUCCESS,
    message: 'ok',
  } 
}
```

<img width="495" alt="image" src="https://user-images.githubusercontent.com/26477346/208018952-bbaad92c-e9c3-4baf-8a86-d8281a81136f.png">

### Minimum reproduction code

https://github.com/Adherentman/graphql-enum-bug

### Expected behavior

```
{
  "data": {
    "sendSMS": {
      "statusCode": 200,
      "message": "sendOk"
    }
  }
}
```

### Package version

10.1.5

### Graphql version

"@nestjs/graphql": "^10.1.5",
"@nestjs/apollo": "^10.1.4",
"apollo-server-core": "^3.11.1",
"apollo-server-express": "^3.11.1",
"graphql": "^16.6.0",

### NestJS version

9.0.0

### Node.js version

18.12.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
