### ISSUE TITLE
Apollo fastify server workaround

### ISSUE THREAD

**Issue by tkow** [nestjs/graphql#2582]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I recently have  @nestjs/graphql configuration  worked with fastify v4. If someone reach https://github.com/nestjs/graphql/issues/2307, this [link](https://github.com/apollographql/apollo-server/pull/6798 ) is helpful. 

Currently, my dependencies are

```
"@nestjs/apollo": "^10.1.6",
"@nestjs/cli": "^9.1.5",
"@nestjs/common": "^9.2.0",
"@nestjs/core": "^9.2.0",
"@nestjs/graphql": "^10.1.6",
"@nestjs/platform-fastify": "^9.2.0",
"@fastify/static": "^6.5.0",
"@fastify/swagger": "^8.1.0",
"fastify": "^4.9.2"
"apollo-server-fastify": "^3.11.1",
```

 and you need including

```
"resolutions": {
    "apollo-server-fastify/@fastify/accepts": "^4.0.0",
    "apollo-server-fastify/@fastify/cors": "^8.0.0"
}
```

in you package.json if you use yarn (or override for npm users may work) and do cofigurations as official docs say..

Currently, no doc explains what versions are correctly worked, so I want to write the configs to docs.

### Describe the solution you'd like

Mention the configurations in the official doc.

### What is the motivation / use case for changing the behavior?

For someone want to use fastify-apollo-server v3 with nestjs.

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/graphql/pull/2636#issuecomment-1429493262
