### ISSUE TITLE
@nestjs/mercurius support for v11 / security fix

### ISSUE THREAD

**Issue by synerp** [nestjs/graphql#2598]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hi there, I am getting the following warning:
@nestjs/mercurius@10.1.7" has incorrect peer dependency "mercurius@^8.12.0 || ^9.0.0 || ^10.0.0".
https://github.com/mercurius-js/mercurius current version is 11.5.0
Latest mercurius update is a security fix.
Thanks

### Minimum reproduction code

https://github.com/nestjs/nest/tree/master/sample/33-graphql-mercurius

### Steps to reproduce

 npm i @nestjs/graphql @nestjs/mercurius graphql mercurius fastify

### Expected behavior

@nestjs/mercurius to work against latest version of mercurius 

### Package version

10.1.7

### Graphql version

mercurius v11.5.0

### NestJS version

9.0.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/graphql/pull/2619
