### ISSUE TITLE
@Body

### ISSUE THREAD

**Issue by gavinwilliams** [nestjs/graphql#26]
Is there any way to add @Body to this library for the args param. Finding it frustrating having to convert POJO's from inputs to TypeScript classes.

**Comment by cschroeter** [comment]
Have a look at [class-transformer-validaotr](https://www.npmjs.com/package/class-transformer-validator)

So you can do something like
```typescript
  @Mutation('createUser')
  async createUser(obj, args, context): Promise<User> {
    try {
        const user: User = await transformAndValidate(User, args.input);
        // ... persists user and return
    } catch (error) {
       throw new BadRequestException()
    }
  }
```

**Comment by gavinwilliams** [comment]
👌just what I was looking for!
