### ISSUE TITLE
Access to resolver from field middleware

### ISSUE THREAD

**Issue by jessemyers** [nestjs/graphql#2603]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I am trying to write role-based access control (RBAC) using field middleware. My goal is to define a set of roles granted to an authenticated user (e.g. via JWT claims) and a set of allowed roles attached to each resolver (e.g. via `reflect-metadata`) and then have a field middleware perform the (simple) check whether any of former exists in the latter.

I am aware of the example that demonstrates using field middleware for role-based authorization, however I'd prefer to map the authorization logic to the mechanism by which a field is queried/mutated (e.g. the resolver) rather than the field definition itself because the same entity (and the same fields) can be mapped in different ways and its the business logic that I want to authorize, not just the data.

I am able to access the authenticated user; the provided context gives me access to the request and `passport` saves the user there.

I am not able to get access to the resolver from the provided `context` (please tell me if I've missed it somehow) and the `next` function is neither a reference to the resolver nor guaranteed to *be* the resolver (because middleware can be chained).

### Describe the solution you'd like

Pass the instance of the resolver that will (eventually) be used to resolve the field as an argument to the middleware.

Option 1: extend the context

```ts
export const myMiddleware: FieldMiddleware = async (
    // resolver is now available in the middleware context
    { resolver }: MiddlewareContext,
    next: NextFn,
) => {
   ...
}
```

Option 2: extend the arguments

```ts
export const myMiddleware: FieldMiddleware = async (
    context: MiddlewareContext,
    next: NextFn,
    // resolver is now available in the middleware context
    resolver: Type,
) => {
   ...
}
```

### Teachability, documentation, adoption, migration strategy

Users will be able to use `Reflector` (or similar) to access metadata attached to the resolver.

### What is the motivation / use case for changing the behavior?

I want to be able to inspect (e.g. via `Reflector`) the resolver for metadata and use it to support role-based access control in a field middleware. I especially want to be able to tie authorization to the code path that is used to resolve data, not just the data itself.

**Comment by jessemyers** [comment]
I've dug a bit more and it appears that the `@Extensions` decorator is, at least, legal to apply to queries and mutations; if this worked, it would solve my problem perfectly and would probably be more in the style of existing GraphQL code.

That said, it's not clear where to look for values created by applying the decorator this way.
 
 - I don't see anything like an `extensions` attribute on `context.info.operation` and the query/mutation doesn't appear in the `context.info` anywhere else (as far as I can tell)
 - I tried using `context.schema.getQueryType()` and context.schema.getMutationType()` to get an object type for the operation; these types do have an `extensions` attribute, but not one that gets populated with the values from the decorator.

**Comment by jessemyers** [comment]
It is possible to find the query or mutation type and its extensions in the `info.schema` using logic like:

```ts
const mutationType = info.schema.getMutationType();
const { extensions } = mutationType.getFields()[nameOfMutation];
```

And it is possible to find the `nameOfMutation` using something like:

```ts
import { responsePathAsArray } from 'graphql';

const nameOfMutation = responsePathAsArray(info.path)[0];
```

So I think I have a workable solution that at least lets me validate RBAC against the top-level GraphQL operation. It's not quite as nice as having resolver-level roles, but we can make it work.

I'll leave it up to the maintainers whether to close this issue as WONTFIX or take on improving the field middleware RBAC documentation to include operation-based access control.

**Comment by choco14t** [comment]
If you want to implement RBAC for Resolver, I think you can do it with guard and a custom decorator, but is it impossible?

**Comment by jessemyers** [comment]
@choco14t We considered using a guard, but there are two challenges:

 - We have other guards in place and the controls for enabling guards against resolvers are not granular enough to enabling only a _specific_ guard. We didn't want to have make code changes in our existing guards to avoid having them operate against resolvers.
 - We really like the basic approach for RBAC that is documented by this project; if we used a guard, we wouldn't get access to the GraphQL `info` data and wouldn't be able to leverage field/object/query/mutation level metadata.

**Comment by kamilmysliwiec** [comment]
Field middleware functions were designed to be independent of the ioc container - you can't reference the resolver instance nor inject other dependencies and that's by design.

Thanks for your suggestion anyway!

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
