### ISSUE TITLE
Inefficient Regular Expression Complexity in glob-parent      

### ISSUE THREAD

**Issue by adirbenyossef** [nestjs/graphql#2626]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The glob-parent package before 6.0.1 for Node.js allows ReDoS (regular expression denial of service) attacks against the enclosure regular expression.

├─┬ @nestjs/graphql@10.1.7
│ ├─┬ chokidar@3.5.3
│ │ └── glob-parent@5.1.2
│ └─┬ fast-glob@3.2.12
│   └── glob-parent@5.1.2

### Minimum reproduction code

.

### Steps to reproduce

npm ls glob-parent

### Expected behavior

Upgrade to version 6.0.1 or above.

### Package version

10.1.7

### Graphql version

`graphql`: 
`apollo-server-express`: 
`apollo-server-fastify`: 

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Given how we use this library in this package, it shouldn't really bother us.
