### ISSUE TITLE
Federated schema doesn't work

### ISSUE THREAD

**Issue by Brilhante29** [nestjs/graphql#2627]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

super(
    ^
GraphQLError: The schema is not a valid GraphQL schema.. Caused by:
Invalid definition for directive "@tag": "@tag" should have locations FIELD_DEFINITION, OBJECT, INTERFACE, UNION, ARGUMENT_DEFINITION, SCALAR, ENUM, ENUM_VALUE, INPUT_OBJECT, INPUT_FIELD_DEFINITION, but found (non-subset) FIELD_DEFINITION, OBJECT, INTERFACE, UNION, ARGUMENT_DEFINITION, SCALAR, ENUM, ENUM_VALUE, INPUT_OBJECT, INPUT_FIELD_DEFINITION, SCHEMA

### Minimum reproduction code

https://github.com/Brilhante29/fix-nestjs

### Steps to reproduce

1. create new nestjs project -> nest new project

2. install graphql libraries -> yarn add @nestjs/graphql @nestjs/apollo graphql graphql-tools apollo-server-express @apollo/subgraph 

3. run project -> yarn start

### Expected behavior

super(
    ^
GraphQLError: The schema is not a valid GraphQL schema.. Caused by:
Invalid definition for directive "@tag": "@tag" should have locations FIELD_DEFINITION, OBJECT, INTERFACE, UNION, ARGUMENT_DEFINITION, SCALAR, ENUM, ENUM_VALUE, INPUT_OBJECT, INPUT_FIELD_DEFINITION, but found (non-subset) FIELD_DEFINITION, OBJECT, INTERFACE, UNION, ARGUMENT_DEFINITION, SCALAR, ENUM, ENUM_VALUE, INPUT_OBJECT, INPUT_FIELD_DEFINITION, SCHEMA

### Package version

10.1.7

### Graphql version

`graphql`: 
`apollo-server-express`: 

### NestJS version

9.2.0

### Node.js version

18.14.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
