### ISSUE TITLE
Missing peer dependency?

### ISSUE THREAD

**Issue by coler-j** [nestjs/graphql#2641]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

With yarn pnp we are getting:

`Error: @nestjs/apollo tried to access apollo-server-core (a peer dependency) but it isn't provided by your application; this makes the require call ambiguous and unsound.` 

Using:
- `@apollo/server": "4.3.3"`
- `@nestjs/apollo": "10.2.0"`
- `"graphql": "16.6.0"`

It seems like `apollo-server-core` should no longer be a dependency of `10.2.0`.

### Minimum reproduction code

https://github.com/coler-j/minimal-apollo-error

### Steps to reproduce

1. This project uses yarn 2 with []Zero Installs](https://yarnpkg.com/features/zero-installs)
2. You should be able to download the repo and run yarn start:dev
3. you will then encounter the following error:
Error: @nestjs/apollo tried to access apollo-server-core (a peer dependency) but it isn't provided by your application; this makes the require call ambiguous and unsound.

### Expected behavior

No error is raised on we can use `@apollo/server": "4.3.3"`

### Package version

10.2.0

### Graphql version

`graphql`:  16.6.0
`apollo-server-express`:  <- Should not be used
`@apollo/server"`: 4.3.3
`@nestjs/apollo"`: 10.2.0

### NestJS version

9.2.1

### Node.js version

18.13.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by coler-j** [comment]
Do we need to do something like https://stackoverflow.com/a/64242991/1689262 where that dependency is still imported into this lib?

**Comment by kamilmysliwiec** [comment]
`apollo-server-core` is already flagged as a peer dependency of `@nestjs/apollo` https://github.com/nestjs/graphql/blob/master/packages/apollo/package.json#L54. Perhaps you just need to update to the latest version
