### ISSUE TITLE
Installation failure with "npm install @nestjs/apollo@next"

### ISSUE THREAD

**Issue by juergenzimmermann** [nestjs/graphql#2655]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

`npm install @nestjs/graphql@next` works fine. However, `npm install @nestjs/apollo@next` yields the error below. I guess there is an issue with `peerDependencies` in `package.json`.

```
> npm install @nestjs/apollo@next
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: buch@2023.1.0
npm ERR! Found: @nestjs/graphql@11.0.0-next.1
npm ERR! node_modules/@nestjs/graphql
npm ERR!   @nestjs/graphql@"11.0.0-next.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @nestjs/graphql@"^10.1.7" from @nestjs/apollo@11.0.0-next.1
npm ERR! node_modules/@nestjs/apollo
npm ERR!   @nestjs/apollo@"11.0.0-next.1" from the root project
```

### Minimum reproduction code

obsolet

### Steps to reproduce

1. npm install @nestjs/graphql@next
2. npm install @nestjs/apollo@next

### Expected behavior

`npm install @nestjs/apollo@next` should work without using the option `--force`.

### Package version

11.0.0-next.1

### Graphql version

`graphql`: 16.6.0
`@apollo/server`: 4.3.2
`apollo-server-express`: 3.11.1
`apollo-server-fastify`:  --

### NestJS version

9.3.9

### Node.js version

v19.6.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/graphql/pull/2636

**Comment by luas10c** [comment]
that "serverWillStart" plugin being set by default is preventing apollo from using the new playground.

![Screenshot from 2023-02-15 08-23-34](https://user-images.githubusercontent.com/66514698/219014377-7b43e7e7-5219-49cb-8573-5161170845e1.png)

**Comment by luas10c** [comment]
from what I understand it is a hook that runs every time the application starts where you can customize the playground with your face. but that should be optional

What do you think about removing the plugin by default and leaving the customization up to the user?

**Comment by luas10c** [comment]
Apollo's default playground has much more functionality, which is very interesting for debugging queries, mutations and subscriptions
