### ISSUE TITLE
[federation] support new `@interfaceObject` directive in code first solution

### ISSUE THREAD

**Issue by dariuszkuc** [nestjs/graphql#2659]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

New Federation features (`@interfaceDirective` and `@composeDirective` https://github.com/nestjs/graphql/issues/2539)) are not supported "out-of-the-box" in the code first solution (they work fine in schema first approach).

### Describe the solution you'd like

[type-defs-federation2.decorator.ts](https://github.com/nestjs/graphql/blob/master/packages/graphql/lib/federation/type-defs-federation2.decorator.ts) should be updated to automatically import new directives and default to Federation version `2.3`, i.e. `@link` directive applied on schema object should default to

```
@link(
  url: "https://specs.apollo.dev/federation/v2.3",
  import: ["@composeDirective", "@extends", "@external", "@key", "@inaccessible", "@interfaceObject", "@override", "@provides", "@requires", "@shareable", "@tag"]
)
```

### Teachability, documentation, adoption, migration strategy

* [`@interfaceObject` directive definition](https://www.apollographql.com/docs/federation/federated-types/federated-directives#interfaceobject)
* [Entity Interface documentation](https://www.apollographql.com/docs/federation/federated-types/interfaces)
* [Announcement blog post](https://www.apollographql.com/blog/announcement/platform/apollo-federation-and-graphos-add-support-for-entity-interfaces-to-streamline-collaboration/)

Apollo Federation v2.3 introduced new `@interfaceObject` directive that allows users to extend entity functionality through inheritance., i.e. given subgraph A

```graphql
interface Product {
 id: ID!
 title: String
}

# Book entity with key
type Book implements Product @key(fields: "id") {
 id: ID!
 title: String
 pages: Int
}

# Movie entity with key
type Movie implements Product @key(fields: "id") {
 id: ID!
 title: String
 duration: Int
}
```

We can generically extend the `Product` interface in other subgraphs by treating it as local object type with `@interfaceObject` that will inform composition logic that it is actually an entity interface.  This allows us to add new functionality in subgraph B without knowing any implementation details (i.e. without knowing anything about `Book` and `Movie` types).

```graphql
type Product @key(fields: "id") @interfaceObject {
 id: ID!
 reviews: [Review!]!
}

type Review {
 author: String
 text: String
 rating: Int
}
```

---
New directive functionality can be tested using [Apollo Federation Subgraph Compatibility](https://www.npmjs.com/package/@apollo/federation-subgraph-compatibility) NPX script (and [Github Action](https://github.com/marketplace/actions/apollo-federation-subgraph-compatibility)). Example integration project is already provided in the [subgraph compatibility testing repository](https://github.com/apollographql/apollo-federation-subgraph-compatibility/tree/main/implementations/nestjs-code-first).

### What is the motivation / use case for changing the behavior?

Ability to extend entity functionality through inheritance and functionality parity with schema first solution.

**Comment by dariuszkuc** [comment]
For convenience -> [link to the Federation v2.3 subgraph spec definitions](https://specs.apollo.dev/federation/v2.3/federation-v2.3.graphql)

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by dariuszkuc** [comment]
@kamilmysliwiec I opened up https://github.com/nestjs/graphql/pull/2677

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/graphql/pull/2677
