### ISSUE TITLE
[v11.0.0-next.2] Integration with class-validator doesn't work

### ISSUE THREAD

**Issue by juergenzimmermann** [nestjs/graphql#2676]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Versions

v11.0.0-next.2

### Describe the regression

I have a class with a property like this one:
```typescript
@IsInt()
@Min(0)
@Max(9)
readonly rating: number;
```
When I submit a mutation request with `rating` and value `999` then I get this response body:
```json
{
  "errors": [
    {
      "message": "Unprocessable Entity Exception",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "create"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "stacktrace": [
          "UnprocessableEntityException: Unprocessable Entity Exception",
          "    at ValidationPipe.exceptionFactory (C:\\workspace\\software-engineering\\buch\\node_modules\\@nestjs\\common\\pipes\\validation.pipe.js:99:20)",
          "    at ValidationPipe.transform (C:\\workspace\\software-engineering\\buch\\node_modules\\@nestjs\\common\\pipes\\validation.pipe.js:72:30)",
          "    at processTicksAndRejections (node:internal/process/task_queues:95:5)",
          "    at resolveParamValue (C:\\workspace\\software-engineering\\buch\\node_modules\\@nestjs\\core\\helpers\\external-context-creator.js:136:31)",
          "    at async Promise.all (index 0)",
          "    at pipesFn (C:\\workspace\\software-engineering\\buch\\node_modules\\@nestjs\\core\\helpers\\external-context-creator.js:138:13)",
          "    at C:\\workspace\\software-engineering\\buch\\node_modules\\@nestjs\\core\\helpers\\external-context-creator.js:66:17"
        ]
      }
    }
  ],
  "data": {
    "create": null
  }
}
```

### Minimum reproduction code

See above

### Expected behavior

Should work as in @nestjs/graphql@10.x

**Comment by Tony133** [comment]
Hi @juergenzimmermann, when you find some time can you create a minimal reproduction in a repository git clonabile?

**Comment by kamilmysliwiec** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).
