### ISSUE TITLE
Apollo 4 with fastify server

### ISSUE THREAD

**Issue by wladimirguerra** [nestjs/graphql#2682]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

See Issue https://github.com/nestjs/graphql/issues/2582#issue-1524189194

### Describe the solution you'd like

To follow the @glasser suggestion at https://github.com/apollographql/apollo-server/issues/6576#issuecomment-1448593055 to use the https://www.npmjs.com/package/@as-integrations/fastify package to integrate apollo 4 with fastify server.

### What is the motivation / use case for changing the behavior?

To use Apollo 4 and the libraries that depend on it with Nest.JS using the fastify server.

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/graphql/pull/2636#issuecomment-1429493262
