### ISSUE TITLE
Switch to `@apollo/server` package

### ISSUE THREAD

**Issue by all2pie** [nestjs/graphql#2697]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Both packages suggested by the [documentation](https://docs.nestjs.com/graphql/quick-start#installation) are now deprecated

[apollo-server-express](https://www.npmjs.com/package/apollo-server-express)
[apollo-server-fastify](https://www.npmjs.com/package/apollo-server-fastify)

### Describe the solution you'd like

Switch to `@apollo/server` package 

https://www.apollographql.com/docs/apollo-server/getting-started#step-2-install-dependencies
https://www.apollographql.com/docs/apollo-server/integrations/integration-index

### What is the motivation / use case for changing the behavior?

To have proper support for GraphQL latest features & a well maintained library

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/graphql/pull/2636
