### ISSUE TITLE
Apollo sandbox not working

### ISSUE THREAD

**Issue by gabriiels** [nestjs/graphql#2708]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current behavior

```

src/app.module.ts:60:17 - error TS2322: Type 'ApolloServerPlugin<BaseContext>' is not assignable to type 'ApolloServerPlugin<any>'.
  Types of property 'serverWillStart' are incompatible.
    Type '(service: GraphQLServiceContext) => Promise<void | GraphQLServerListener>' is not assignable to type '(service: GraphQLServerContext) => Promise<void | GraphQLServerListener>'.
      Types of parameters 'service' and 'service' are incompatible.
        Type 'GraphQLServerContext' is missing the following properties from type 'GraphQLServiceContext': schemaHash, serverlessFramework

60       plugins: [ApolloServerPluginLandingPageLocalDefault()],
```

### Minimum reproduction code

https://github.com/gabriiels/bug-apollo-server-plugin-landing-page-local-default

### Steps to reproduce

1. pnpm i
2. pnpm run start:dev
3. See error in the console

### Expected behavior

Correct operation of Apollo sandbox.

### Package version

"^11.0.0"

### Graphql version

 "graphql": "^16.6.0",
 "apollo-server-core": "^3.12.0",

### NestJS version

^9.0.0

### Node.js version

v18.12.1

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by faustinozanetto** [comment]
Have you tried using the new import that is mentioned in the Apollo V4 migration guide? The new import is:

`import { ApolloServerPluginLandingPageLocalDefault } from '@apollo/server/plugin/landingPage/default';`

**Comment by Tony133** [comment]
I did this PR:https://github.com/nestjs/docs.nestjs.com/pull/2651 which updates small parts of the documentation including the part sandbox for graphql.

hope it can help

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/graphql/issues/2708#issuecomment-1464993474
