### ISSUE TITLE
Add new line at the end of schema file for code first approach

### ISSUE THREAD

**Issue by Kolobamanacas** [nestjs/graphql#2732]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Many code styling guidelines suggest to put empty line at the end of every text file and many teams set up their pipelines to check for this line existence. When dealing with auto-generated code though, it becomes a tiresome task to manually add new line every time, for example, the schema is generated.

### Describe the solution you'd like

It would be nice to have an option, to tell schema generator to add a new at the en of every generated file.

### What is the motivation / use case for changing the behavior?

Currently I manually add new line to schema file a couple of times per week. I'm looking for some way to automate this.

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this?

**Comment by Kolobamanacas** [comment]
Well, with some assistance I think I could. I'm not familiar with the code base, so if someone points me towards the file/module responsible for schema generation, generation options and any helpful docs, I would be really grateful.

**Comment by jan-hecker** [comment]
> Well, with some assistance I think I could. I'm not familiar with the code base, so if someone points me towards the file/module responsible for schema generation, generation options and any helpful docs, I would be really grateful.

I think it is this [line](https://github.com/nestjs/graphql/blob/master/packages/graphql/lib/graphql-schema.builder.ts#L69) where it could be added
