### ISSUE TITLE
Path resolution issue in Windows after upgrading package

### ISSUE THREAD

**Issue by all2pie** [nestjs/graphql#2734]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Versions

10.0.10 -> 11.0.0

### Describe the regression

Please run the code to check the error

Getting error when using the class as a return type in query
Typescript import is working properly
App works correctly if I remove the export with ConfigOptions class

Here is the discord support thread: https://discord.com/channels/520622812742811698/1086233002310377473
Here is the previous reported issue: #2719 

### Minimum reproduction code

https://github.com/all2pie/nestjs-graphql-path-issue

### Expected behavior

App should work properly

Check the `cat.resolver.ts` comments for the fix
Also try to remove the export with ConfigOptions class

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/graphql/pull/2788
