### ISSUE TITLE
Middleware for GraphQL fields is ignored

### ISSUE THREAD

**Issue by kaihaase** [nestjs/graphql#2751]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I integrate a middleware into a GraphQL Field from an InputType, it is ignored:

Middleware `to-lower-case.middleware.ts`:
```typescript
import { FieldMiddleware, MiddlewareContext, NextFn } from '@nestjs/graphql';

/**
 * Field middleware to convert string to lowercase letters
 */
export const toLowerCase: FieldMiddleware = async (
  ctx: MiddlewareContext,
  next: NextFn,
) => {
  console.log('FieldMiddleware toLowerCase');
  const value = await next();
  console.log('value:', value);
  return value?.toLowerCase();
};
```

InputType `app.input.ts`:
```typescript
import { Field, InputType } from '@nestjs/graphql';
import { toLowerCase } from './to-lower-case.middleware';

@InputType({
  description:
    'Simple input with string property converted to lowercase letters',
})
export class Input {
  @Field({
    description: 'Any string with upper and lower case letters',
    nullable: false,
    middleware: [toLowerCase],
  })
  str?: string = undefined;
}
```

Resolver `app.resolver.ts`:
```typescript
import { Args, Query, Resolver } from '@nestjs/graphql';
import { Input } from './app.input';

@Resolver()
export class AppResolver {
  @Query(() => String, { description: 'String to lower case' })
  async getLowerCase(@Args('input') input: Input) {
    return input.str;
  }
}
```
Neither the string manipulation is performed nor the console logs show up.

Expected behavior:
- String is handled with toLowerCase
- Console logs are output

### Minimum reproduction code

https://github.com/lenneTech/graphql-field-middleware

### Steps to reproduce

1. install packages: `npm install`
2. start (in watch mode): `npm run start:dev`
3. open playground: `open https://localhost:3000/graphql`
4. send query:
```
query {
  getLowerCase(input: {str: "Test"})
}
```

### Expected behavior

```json
{
  "data": {
    "getLowerCase": "test"
  }
}
```

### Package version

11.0.4

### Graphql version

"@apollo/server": "4.5.0",
"@nestjs/apollo": "11.0.4",
"@nestjs/common": "9.3.12",
"@nestjs/core": "9.3.12",
"@nestjs/graphql": "11.0.4",
"@nestjs/platform-express": "9.3.12",
"graphql": "16.6.0",
"reflect-metadata": "0.1.13",
"rxjs": "7.8.0"

### NestJS version

9.3.12

### Node.js version

16.17.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/graphql/issues/2446#issuecomment-1290386387
