### ISSUE TITLE
Configuring CORS

### ISSUE THREAD

**Issue by rhutchison** [nestjs/graphql#2752]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Potential Commit/PR that introduced the regression

PR #2636

### Versions

10.2.0 -> 11.0.4

### Describe the regression

Support for configuring CORs was removed.

It looks like the changes to support new apollo server was done as suggested in the [guide](https://www.apollographql.com/docs/apollo-server/security/cors/#configuring-cors-options-for-apollo-server):

https://github.com/nestjs/graphql/commit/951f9070d878d93932564e7887f49ae0b3dc9ce4#diff-c3a3b52cf11536118537eaffe950a721dd8246bde13d7681c96678d85bec445fR159

then later removed:

https://github.com/nestjs/graphql/commit/1e099fa326715afd9b03ebd3a26d4ccb45cdd908#diff-c3a3b52cf11536118537eaffe950a721dd8246bde13d7681c96678d85bec445fL144

### Minimum reproduction code

```ts

GraphQLModule.forRoot<ApolloDriverConfig>({
  driver: ApolloDriver,
  autoSchemaFile: true,
  sortSchema: true,
  cors: {
    credentials: true,
    origin: ['https://www.your-app.example'],
  },
})

```

### Expected behavior

From the documentation:

The [startStandaloneServer](https://www.apollographql.com/docs/apollo-server/api/standalone) function's CORS configuration is unalterable and enables any website on the internet to tell a user's browser to connect to your server. [Depending on your use case,](https://www.apollographql.com/docs/apollo-server/security/cors/#choosing-cors-options-for-your-project) you might need to further [customize your CORS behavior](https://www.apollographql.com/docs/apollo-server/security/cors/#passing-credentials-with-cors) to ensure your server's security.

**Comment by magrinj** [comment]
@kamilmysliwiec Actually the guide you just linked show a `cors` option in the `GraphQLModule` but this one is not available anymore. I guess it's what @rhutchison is referencing.

**Comment by kamilmysliwiec** [comment]
Great catch @magrinj! I just removed the entire GraphQL-related section - `cors` option has been removed in Apollo v4 (which is great since we didn't need that either way) and everyone should now be able to just use the `enableCors()` method - regardless of whether they build a GQL or REST API

**Comment by rhutchison** [comment]
> Great catch @magrinj! I just removed the entire GraphQL-related section - `cors` option has been removed in Apollo v4 (which is great since we didn't need that either way) and everyone should now be able to just use the `enableCors()` method - regardless of whether they build a GQL or REST API

Thanks - this simplifies things.

Ref: https://github.com/nestjs/docs.nestjs.com/commit/474491c9cab4ec145c8e20cd96078838ad7ce4a4
