### ISSUE TITLE
Fastify `reply` (aka `res`) not being passed to `context` function in gql module options

### ISSUE THREAD

**Issue by sadams** [nestjs/graphql#2759]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Illustrated here: https://github.com/sadams/nest/pull/3

The issue is that the fastify reply is not being propagated to the context function option:
```    
GraphQLModule.forRoot<ApolloDriverConfig>({
      driver: ApolloDriver,
      context: ({res, req, reply}) => {
        console.log({typeofReply: typeof reply, typeofRes: typeof res})
        return {res, req};
      },
})
```
In older versions of nest/gql `reply` was present, as illustrated here: https://github.com/sadams/nest/pull/2

### Minimum reproduction code

https://github.com/sadams/nest/pull/3

### Steps to reproduce

to reproduce:
1. `cd sample/23-graphql-code-first` 
1. `npm install`
1. `npm run start:dev`
1. visit http://localhost:3000/graphql
1. execute query `{recipes{title}}`
1. see output in terminal:
```
{ typeofReply: 'undefined', typeofRes: 'undefined' }
```

### Expected behavior

The `reply` prop should be passed to the context function correct, as per this example from legacy versions:
https://github.com/sadams/nest/pull/2

### Package version

11.0.0

### Graphql version

    "@apollo/server": "4.5.0",
    "@as-integrations/fastify": "1.3.2",
    "@nestjs/apollo": "11.0.4",
    "@nestjs/graphql": "11.0.4",
    "@nestjs/platform-fastify": "9.3.12",
    "graphql": "16.6.0",

### NestJS version

9.3.12

### Node.js version

16.15.1

### In which operating systems have you tested?

- [X] macOS

**Comment by sadams** [comment]
This looked related: https://github.com/nestjs/graphql/commit/2f6b55da1d9b31daa0f62e8d87e106856fe72b67
but i bumped the version in the example (https://github.com/sadams/nest/pull/3) to nestjs/graphql version to 11.0.4 but still no joy.

**Comment by kamilmysliwiec** [comment]
@Davide-Gheri would you like to take a look into this issue? I don't think this is related to your PR specifically though

**Comment by sadams** [comment]
I had a dig into https://github.com/apollo-server-integrations/apollo-server-integration-fastify and i think i understand now: reply is the second argument passed to the context:
https://github.com/apollo-server-integrations/apollo-server-integration-fastify/issues/97#issuecomment-1365862279
Probably just needs a documentation update.

**Comment by Davide-Gheri** [comment]
Yes as [this comment](https://github.com/apollo-server-integrations/apollo-server-integration-fastify/issues/97#issuecomment-1365862279) states the new fastify integration has changed the way it passes Request and Reply to the context factory fn.

Maybe we could see if it is possible to "normalize" how req and res (for ApolloDriver, MercuriusDriver and custom drivers?) are passed to the context factory

**Comment by kamilmysliwiec** [comment]
> Probably just needs a documentation update.

@sadams Would you like to create a PR for this?

> Maybe we could see if it is possible to "normalize" how req and res (for ApolloDriver, MercuriusDriver and custom drivers?) are passed to the context factory

Let's think about this in the future!
