### ISSUE TITLE
Pass data in Mutation Args 

### ISSUE THREAD

**Issue by evengyl** [nestjs/graphql#2763]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

"dependencies": {
    "@apollo/server": "^4.6.0",
    "@nestjs/apollo": "^11.0.4",
    "@nestjs/common": "^9.0.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/graphql": "^11.0.4",
    "@nestjs/jwt": "^10.0.3",
    "@nestjs/mapped-types": "^1.2.2",
    "@nestjs/platform-express": "^9.0.0",
    "@nestjs/swagger": "^6.3.0",
    "@nestjs/typeorm": "^9.0.1",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.14.0",
    "express-formidable": "^1.2.0",
    "express-session": "^1.17.3",
    "graphql": "^16.6.0",
    "mssql": "^7.3.5",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.2.0",
    "typeorm": "^0.3.12"
  },
  "devDependencies": {
    "@nestjs/cli": "^9.0.0",
    "@nestjs/schematics": "^9.0.0",
    "@nestjs/testing": "^9.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "29.2.4",
    "@types/node": "18.11.18",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "29.3.1",
    "prettier": "^2.3.2",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "29.0.3",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "4.1.1",
    "typescript": "^4.7.4"
  },

- [x] #BUG not resolve
- [ ] #Reproduction https://github.com/evengyl/demo_nest_graphQL_await_for_issue

----- ERROR -----
error : 
"errors": [
    {
      "message": "Cannot return null for non-nullable field Mutation.createUser."
}]

----- ERROR -----

- [x] #BUG resolve with tricks

in InputType object graphQL

------ BEFORE ------ 
@InputType()
export class CreateUser{

    @Field(type => String)
    name : string

    @Field(type => String)
    pseudo : string

    @Field(type => String)
    password: string
}

------ AFTER ------ 
import { IsNotEmpty } from "class-validator";

@InputType()
export class CreateUser{

    @Field(type => String)
    @IsNotEmpty()
    name : string

    @Field(type => String)
    @IsNotEmpty()
    pseudo : string

    @Field(type => String)
    @IsNotEmpty()
    password: string
}

### Minimum reproduction code

https://github.com/evengyl/demo_nest_graphQL_await_for_issue

### Steps to reproduce

npm install
npm run strat:dev

go to localhost:5000/graphql
in playground -> create mutation : 

mutation {
  createUser(   args: { name: "test", pseudo: "test", password: "test1234_" }  ) {
    id
  }
}

### Expected behavior

when passing complex objects as mutation arguments "@Args("args") createUser : CreateUser", the retrieved object remains empty, a trick must be used in the shifting of the mutation scheme, with @IsNotEmpty() coming from class-validator.

### Package version

^11.0.4

### Graphql version

"@apollo/server": "^4.6.0",
"@nestjs/apollo": "^11.0.4",
"@nestjs/graphql": "^11.0.4",
"graphql": "^16.6.0",

### NestJS version

^9.0.0

### Node.js version

v16.16.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Other

On vs Code Ide
windows 10
with npm
debug on firefox & firefox private navigation

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
