### ISSUE TITLE
Enum key value mapping.

### ISSUE THREAD

**Issue by latuconsinafr** [nestjs/graphql#2774]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The query result returns the key enum as a value rather than the enum value itself.

For example:

**Query**
```
query Query($userId: String!) {
  user(id: $userId) {
    roles
  }
}
```

**Variables**
```
{
  "userId": "b1bc1795-59a3-45f3-8eaf-b74960ad0f9d"
}
```

**Response**
```json
{
  "data": {
    "user": {
      "roles": [
        "SuperAdmin"
      ]
    }
  }
}
```

### Minimum reproduction code

https://github.com/latuconsinafr/nestjs-graphql-enum-issues

### Steps to reproduce

1. `npm i`
2. Create a postgresql database named `nestjs-graphql-enum-issues-db` or change the variables inside TypeOrmModule.forRoot configuration to suit the environment.
3. `npm run start:dev`

### Expected behavior

The query result returns the enum value instead of the key.

For example:

**Query**
```
query Query($userId: String!) {
  user(id: $userId) {
    roles
  }
}
```

**Variables**
```
{
  "userId": "b1bc1795-59a3-45f3-8eaf-b74960ad0f9d"
}
```

**Response**
```json
{
  "data": {
    "user": {
      "roles": [
        "super-admin" // * should return the enum value, not the key
      ]
    }
  }
}
```

### Package version

^11.0.5

### Graphql version

`graphql`: ^16.6.0
`@apollo/server`: ^4.6.0
`@nestjs/apollo`: ^11.0.5
`@nestjs/graphql`: ^11.0.5

### NestJS version

^9.0.0

### Node.js version

16.18.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please search through some of our old issues on this (this has been discussed several times in the past).
