### ISSUE TITLE
SWC Compatibility

### ISSUE THREAD

**Issue by brotsky** [nestjs/graphql#2806]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

[SWC](https://swc.rs/) works for NestJS but not NestJS/GraphQL. 

It gives errors because SWC doesn't handle decorators such as @InputObject() and @TypeObject().

Errors look like this:

```
 GraphQLError: Input Object type ExampleInput must define one or more fields.
        at SchemaValidationContext.reportError (/my/path/api/node_modules/graphql/type/validate.js:73:7)
```

The problem is that _GRAPHQL_METADATA_FACTORY() is not in the compiled JS.

You could reproduce this by running the standard `next build` script that uses `tsc` and looking at an input type that uses @InputObject(). Then running the swc build script (something like: `npx swc src -d dist/src`) and comparing the results. You will notice the `_GRAPHQL_METADATA_FACTORY()` is missing since it is created with the decorator. 

### Describe the solution you'd like

Ultimately, I just want it to work even if its a work around. 

### What is the motivation / use case for changing the behavior?

SWC is WAY faster than TSC, like 20x faster.

**Comment by srmagura** [comment]
Can you post your `.swcrc`?

Are decorators enabled in the `jsc.parser` options? https://swc.rs/docs/configuration/compilation#typescript

**Comment by srmagura** [comment]
Here's the swc config from the vite-plugin-node library, which works for me:

```
module: {
      type: 'es6',
    },
    jsc: {
      target: 'es2019',
      parser: {
        syntax: 'typescript',
        decorators: true,
      },
      transform: {
        legacyDecorator: true,
        decoratorMetadata: true,
      },
    },
```

**Comment by brotsky** [comment]
> Can you post your `.swcrc`?
> 
> 
> 
> Are decorators enabled in the `jsc.parser` options? https://swc.rs/docs/configuration/compilation#typescript

```
{
  "$schema": "https://json.schemastore.org/swcrc",
  "sourceMaps": "inline",
  "module": {
    "type": "commonjs",
    "strict": true
  },
  "exclude": [".*\\.js$", ".*\\.map$"],
  "jsc": {
    "target": "es2017",
    "parser": {
      "syntax": "typescript",
      "tsx": false,
      "decorators": true,
      "dynamicImport": false
    },
    "transform": {
      "legacyDecorator": true,
      "decoratorMetadata": true
    },
    "keepClassNames": true,
    "baseUrl": "./",
    "externalHelpers": true,
    "loose": false
  },
  "minify": false
}

```

**Comment by brotsky** [comment]
> Here's the swc config from the vite-plugin-node library, which works for me:
> 
> 
> 
> ```
> 
> module: {
> 
>       type: 'es6',
> 
>     },
> 
>     jsc: {
> 
>       target: 'es2019',
> 
>       parser: {
> 
>         syntax: 'typescript',
> 
>         decorators: true,
> 
>       },
> 
>       transform: {
> 
>         legacyDecorator: true,
> 
>         decoratorMetadata: true,
> 
>       },
> 
>     },
> 
> ```

Are you using Vite with NestJS? If so, is it a lot better? Do you think it will help make SWC work?

**Comment by srmagura** [comment]
I am using Vite with NestJS, through vite-plugin-node. There are a number of issues (mainly, no support for WebSockets), but it does work...

**Comment by brotsky** [comment]
> I am using Vite with NestJS, through vite-plugin-node. There are a number of issues (mainly, no support for WebSockets), but it does work...

Ah, that might be a dealbreaker. We are using GraphQL Subscriptions.

**Comment by srmagura** [comment]
See [this comment](https://github.com/axe-me/vite-plugin-node/issues/87) for the solution I am currently using. It is working well.

**Comment by kamilmysliwiec** [comment]
CLI plugins don't work with SWC, as stated in the docs.
