### ISSUE TITLE
Documentation: Prisma and NestJS

### ISSUE THREAD

**Issue by cschroeter** [nestjs/graphql#29]
I've started working on an example project to integrate [Prisma](https://www.prisma.io/) in NestJS.
If requested I can write a more detailed explanation and add them to the official docs. Here is the project https://github.com/cschroeter/nestjs-prisma

- [x] Project setup
- [x] Queries
- [x] Mutations
- [x] Subscriptions
- [x] Intellisense support

**Comment by kamilmysliwiec** [comment]
Hi @cschroeter,
Looks very promising! Feel free to create a PR, if you have some spare time. I'd love to review it :)

**Comment by kamilmysliwiec** [comment]
I suppose that Recipes might be a better place here

**Comment by kamilmysliwiec** [comment]
Example is done, docs PR is in progress. Great job @cschroeter!
