### ISSUE TITLE
GraphQL Mapped Types not working with SWC

### ISSUE THREAD

**Issue by masurceac** [nestjs/graphql#2908]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I have the following setup: Monorepo, SWC and NestJS GraphQL CLI Plugin.
Everything works fine until I start using [Mapped Types](https://docs.nestjs.com/graphql/mapped-types). After adding a class using Mapped Types I get following error: `GraphQLError: Type CatEntity must define one or more fields.` (see repo attached).

### Minimum reproduction code

https://github.com/masurceac/nest-monorepo-swc

### Steps to reproduce

`npm run start:dev`

### Expected behavior

`ReadonlyVisitor` should properly generate metadata when using Mapped types.

### Package version

12.0.7

### Graphql version

    "graphql": "^16.7.1",
    "@apollo/server": "^4.7.5",
    "@nestjs/apollo": "^12.0.7",

### NestJS version

10.0.5

### Node.js version

18.13.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Could you test with `npm i @nestjs/graphql@12.0.8-next.1`?

**Comment by kamilmysliwiec** [comment]
@masurceac why `ValidationPipe` is applied after `listen()`?

![image](https://github.com/nestjs/graphql/assets/23244943/5cb81658-20f1-415e-8f05-54d5bb43b047)

**Comment by masurceac** [comment]
@kamilmysliwiec right, I moved up the validation pipe and now it works. Thanks for pointing this out!

Also the bug seems to be fixed. Thank you. 👍
