### ISSUE TITLE
Incompatible Dependencies on install

### ISSUE THREAD

**Issue by erikwrede** [nestjs/graphql#2911]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When cloning the current master HEAD, the npm i fails on a clean repo without package lock or node modules. There is a version conflict with the GraphQL dependencies. `npm i --legacy-peer-deps` fixes the problem. 

See for past occurence of this issue. https://github.com/nestjs/graphql/issues/1408

The fix here is to upgrade the dependencies

### Minimum reproduction code

see below.

### Steps to reproduce

```bash
 ~/dev/oss/graphql/nestjs-graphql   master  npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: @nestjs/apollo@12.0.7
npm ERR! Found: graphql@16.7.1
npm ERR! node_modules/graphql
npm ERR!   peer graphql@"^16.6.0" from @nestjs/apollo@12.0.7
npm ERR!   packages/apollo
npm ERR!     @nestjs/apollo@12.0.7
npm ERR!     node_modules/@nestjs/apollo
npm ERR!       workspace packages/apollo from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer graphql@"^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0" from apollo-cache-inmemory@1.6.6
npm ERR! node_modules/apollo-cache-inmemory
npm ERR!   dev apollo-cache-inmemory@"1.6.6" from @nestjs/apollo@12.0.7
npm ERR!   packages/apollo
npm ERR!     @nestjs/apollo@12.0.7
npm ERR!     node_modules/@nestjs/apollo
npm ERR!       workspace packages/apollo from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

```

### Expected behavior

it works.

### Package version

HEAD

### Graphql version

master

### In which operating systems have you tested?

- [X] macOS
- [X] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Please, report this issue in the apollo repository https://github.com/apollographql/apollo-server
