### ISSUE TITLE
`ObjectType` class not registered in the generated schema when the class is not included in a query/mutation

### ISSUE THREAD

**Issue by NilsMoller** [nestjs/graphql#2935]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When decorating a class as `ObjectType`, it should become available as a type in the schema. When the class is not used in a query or mutation, the class is not added to the schema.

### Minimum reproduction code

https://github.com/NilsMoller/object-type-not-registered-with-empty-resolver

### Steps to reproduce

1. Globally install the Nest CLI
2. Create a new Nest project: `nest new`
3. Add the GraphQL packages: `npm i @nestjs/graphql @nestjs/apollo @apollo/server graphql`
4. Import the `GraphQLModule` in the `AppModule`
5. Create a healthcheck resolver (there must be at least one query)
6. Create the `Foo` ObjectType and a `FooResolver` resolver
7. Run the app to generate the schema
8. Observe that the schema does not include the `Foo` type

### Expected behavior

The generated schema includes the class decorated with `ObjectType`.

### Package version

v12.0.8

### Graphql version

`@apollo/server`: `^4.8.1`
`@nestjs/apollo`: `^12.0.7`
`@nestjs/common`: `^10.0.0`
`@nestjs/core`: `^10.0.0`
`@nestjs/graphql`: `^12.0.8`
`@nestjs/platform-express`: `^10.0.0`
`graphql`: `^16.7.1`

### NestJS version

10.1.10

### Node.js version

20.2.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Other

I originally asked this as a question on Discord, and papooch replied with him experiencing the same behavior in the minimum reproduction repository and suggested create an issue here. He was not sure whether this was a bug or a feature request, and whether this happens in "raw" Apollo as well.

**Comment by kamilmysliwiec** [comment]
This is the expected behavior. If your object type is not referenced in any query/mutation, you should register it as an "orphaned type":

```ts
GraphQLModule.forRoot<...>({
  // ...
  buildSchemaOptions: {
    orphanedTypes: [Foo],
  },
})
```
