### ISSUE TITLE
ESM compatibility with plugin code gen

### ISSUE THREAD

**Issue by CarsonF** [nestjs/graphql#2945]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Currently the plugin emits:
```ts
static _GRAPHQL_METADATA_FACTORY() {
  return {
    id: { type: () => String },
    status: { type: () => require("./status").Status },
    items: { type: () => [require("./item").Item] },
  };
}
```

### Describe the solution you'd like

I'd like to change it to this:
```ts
static async _GRAPHQL_METADATA_FACTORY() {
  const { Status } = await import("./status");
  const { Item } = await import("./item");
  return {
    id: { type: () => String },
    status: { type: () => Status },
    items: { type: () => [Item] },
  };
}
```
Maybe not the exact syntax, since I know that matters here with AST work, but that's the idea.
The import/require could be conditional with a new config option. And maybe determined automatically?

### Teachability, documentation, adoption, migration strategy

User change is none, other than a config option.

### What is the motivation / use case for changing the behavior?

ESM Support

**Comment by kamilmysliwiec** [comment]
We already use the `await import` syntax for metadata files generated for projects that use SWC builder so the migration should be rather seamless.

Anyways, it may take some time before we fully migrate to ESM so let's track this in one place https://github.com/nestjs/graphql/issues/2568#issuecomment-1655658256
