### ISSUE TITLE
ObjectType implementing multiple levels of InterfaceType do not get generated in schema

### ISSUE THREAD

**Issue by Pikachews** [nestjs/graphql#2953]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When there are multiple levels of interfaces (e.g. `InterfaceType (Base) -> InterfaceType (Child) -> ObjectType (Concrete)`) and only the grandparent (`Base`) type is referenced, then the neither the parent nor child types are present in the resulting schema.

With the following:
```ts
@InterfaceType()
export abstract class Base {
  @Field()
  type: string;
}

@InterfaceType()
export abstract class Child extends Base {
  @Field()
  child: string;
}

@ObjectType({ implements: [Child] })
export class Concrete extends Child {
  @Field()
  field: string;
}

@ObjectType()
export class TestClass {
  @Field()
  concrete: Base;
}
```

the resulting schema is:
```graphql
interface Base {
  type: String!
}

type Query {
  test: String!
}
```
which doesn't include the `Concrete` type, making it not possible to use.

If I change `concrete: Base;` to `concrete: Child;`, then `Concrete` shows up in the schema, although `Base` no longer does:

```graphql
interface Child {
  type: String!
  child: String!
}

type Concrete implements Child {
  type: String!
  child: String!
  field: String!
}

type Query {
  test: String!
}
```

If `@ObjectType({ implements: [Child] })` is changed to `@ObjectType({ implements: [Base, Child] })` then both the `Base` and `Concrete` are present in the schema, but that seems a bit redundant and could be done without? Is it required to be specified as such?

### Minimum reproduction code

https://github.com/Pikachews/interface-types-test

### Steps to reproduce

1. `pnpm install`
2. `pnpm start:dev`
3. View `schema.graphql`

### Expected behavior

I would expect `Concrete` to show up in the generated `schema.graphql`, despite it only being referenced by indirectly.

### Package version

12.0.8

### Graphql version

`graphql`: 16.7.1

### NestJS version

10.1.3

### Node.js version

18.16.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
If your types are not referenced in resolvers, then you need to register them as `orphanedTypes` https://github.com/nestjs/graphql/issues/2935#issuecomment-1649244712
