### ISSUE TITLE
Allow guards and/or exception filters to return `null`

### ISSUE THREAD

**Issue by mstykow** [nestjs/graphql#2970]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

In @nestjs/graphql, I would like to short-circuit the resolver logic with a guard or at least an exception filter that catches the exception raised by the guard in order to return `null`.

I found this issue which is similar but was closed without resolution a while ago: https://github.com/nestjs/graphql/issues/200

### Describe the solution you'd like

I would either like to be able to return `null` directly inside the guard (instead of true/false which either forwards the request or raises an exception), or, I would like to be able to catch the exception raised by the guard with an exception filter and then use the exception filter to return null. As described in the closed issue above, the problem is that returning `null` from an exception filter gets ignored by NestJS.

### What is the motivation / use case for changing the behavior?

My motivation is similar to the closed issue from before: in certain scenarios I want to convert a raised exception to a null response instead, making the GraphQL type nullable. This is useful, for example in queries such as `getTodo(id: String!): Todo` where I don't want to raise an exception just because the "todo" does not exist, but still need to perform authentication logic (via a guard) in case it does.

An even simpler example: create a global exception filter that converts all NOT_FOUND exceptions in the application to nullable types.

**Comment by kamilmysliwiec** [comment]
AFAIR you can return null from exception filters

**Comment by mstykow** [comment]
> AFAIR you can return null from exception filters

Yes, you can return `null` but it will tell NestJS _to do nothing_, i.e., it will not be the actual return value of request.

**Comment by kamilmysliwiec** [comment]
Could you create a minimum reproduction repository?
