### ISSUE TITLE
remove deprecated dep `@apollo/server-plugin-landing-page-graphql-playground`

### ISSUE THREAD

**Issue by elijaholmos** [nestjs/graphql#2972]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The Apollo package depends on `@apollo/server-plugin-landing-page-graphql-playground`, which has been deprecated since Dec 31, 2022. Even though I no longer use that dependency in my repository, this package still references it, yielding an annoying deprecation error in my console:

![image](https://github.com/nestjs/graphql/assets/35435704/815060c1-fc71-4a2a-801b-85cecfea2a86)

### Minimum reproduction code

https://www.npmjs.com/package/@apollo/server-plugin-landing-page-graphql-playground

### Steps to reproduce

1. `npm install @nestjs/apollo`
2. Observe deprecation error

### Expected behavior

I expect this popular package to avoid deprecated dependencies as often as practical. 

### Package version

12.0.8

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Let's track this conversation here https://github.com/nestjs/graphql/pull/2973

**Comment by elijaholmos** [comment]
> Let's track this conversation here #2973

Doesn't engage for two years, then proceeds to close and lock PR conversation after issuing an ultimatum 😆
