### ISSUE TITLE
While doing mutation without any bearer token i was expecting unauthorize exception but got  bad user input exception

### ISSUE THREAD

**Issue by sandeshtamanq** [nestjs/graphql#2984]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

This is my resolver
` @UseGuards(JwtAuthGuard)
  @Mutation(() => ChatBotType)
  createChatBot(
    @CurrentUser() user: UserType,
    @Args('createChatBotInput') createChatBotInput: CreateChatBotInput,
  ) {
    console.log(user);
    return this.chatBotService.create(user, createChatBotInput);
  }`

This is the input type
`
@InputType()
export class CreateChatBotInput {
  @Field()
  type: string;

  @Field(() => Int, { nullable: true })
  num_of_characters: number;

  @Field(() => OptionInput, { nullable: true })
  options?: OptionInput;
}
`

While make a request in createChatBot mutation without any token i got 
"message": "Variable \"$createChatBotInput\" got invalid value {}; Field \"type\" of required type \"String!\" was not provided."
this error

### Minimum reproduction code

a

### Expected behavior

I was expecting an unauthorize response as it works when i try to query an endpoint

### Package version

9.1.1

### Graphql version

`graphql`: 15.7.2
`apollo-server-express`: 3.4.0
`apollo-server-fastify`: 

### NestJS version

8.0.0

### Node.js version

18.14.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
