### ISSUE TITLE
Cannot find module 'graphql-upload-ts' or its corresponding type declarations.

### ISSUE THREAD

**Issue by binoiii** [nestjs/graphql#2989]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Cannot find module 'graphql-upload-ts' or its corresponding type declarations.

### Minimum reproduction code

n.a

### Steps to reproduce

    "@apollo/server": "4.9.0",
    "@as-integrations/fastify": "2.1.0",
    "@nestjs/apollo": "12.0.7",
    "@nestjs/common": "10.1.3",
    "@nestjs/config": "3.0.0",
    "@nestjs/core": "10.1.3",
    "@nestjs/graphql": "12.0.8",
    "@nestjs/mongoose": "10.0.1",
    "@nestjs/platform-fastify": "10.1.3",
    "graphql-upload-ts": "^2.1.0",

### Expected behavior

No error should occur

### Package version

12.0.8

### Graphql version

graphql: 16.6.0
apollo-server-fastify: 3.6.4

### NestJS version

10.1.3

### Node.js version

14.17.6

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
