### ISSUE TITLE
Nested array of child inputs missing values w/ JSON.stringify

### ISSUE THREAD

**Issue by ALPHAvibe** [nestjs/graphql#2992]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When we JSON.stringify an InputType object from our gql request, if that object has nested array of inputs, we are not able to serialize values from inputs in the array.

```typescript
@InputType()
export class ChildInput {
  @Field(() => [String])
  @IsNotEmpty()
  name: string[]
}

@InputType()
export class ParentInput {
  @Field(() => [ChildInput])
  @IsNotEmpty()
  children: ChildInput[]
}
```

```typescript
@Resolver(() => Relationship)
export class RelationshipResolver {
  @Mutation(() => Boolean, { name: 'set' })
  set(@Args('input') input: ParentInput): boolean {
    console.log('input.children', input.children)
    console.log('input.children', JSON.stringify(input.children))
    return true
  }
}
```

console output
```console
> input.children [ [ name: [ 'ricky' ] ], [ name: [ 'bobby' ] ] ]
> input.children [[],[]]
```

Based on the console output, it looks like input.children might be an array of arrays with key values. Where the the underlying object should be an array of ChildInputs. We think this incorrect map is causing the objects to be ignored  when using JSON.stringify.

We did not get the same behavior with nested ObjectTypes.

We have a workaround for now by transferring our child input values into a new ChildInput.

### Minimum reproduction code

https://github.com/makepumpkinpie/nest-js-inputtype-bug

### Expected behavior

Expected behavior should serialize the nested array of inputs
```console
> input.children [{ "name": "ricky"}, { "name": "bobby"}]
```

### Package version

12.0.8

### Graphql version

"@apollo/server": "^4.5.0",
"@nestjs/apollo": "^12.0.7",
"@nestjs/common": "^10.1.3",
"@nestjs/config": "^3.0.0",
"@nestjs/core": "^10.1.3",
"@nestjs/platform-express": "^10.1.3",

### NestJS version

10.1.3

### Node.js version

19.7

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
