### ISSUE TITLE
Code first multiple paths

### ISSUE THREAD

**Issue by garysb** [nestjs/graphql#2993]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I would like to be able to provide a different set of Queries/Subscriptions/Mutations depending on the path used to access the system when using a code first approach.

### Describe the solution you'd like

Allow for me to create two instances of GraphQLModule each with a different list of modules each with their own resolvers.

### What is the motivation / use case for changing the behavior?

An example of a use case would be to have publicly facing queries/mutations and have a different set for private queries/mutations for administration, dashboards.

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/graphql/issues/721
