### ISSUE TITLE
`@Field` cannot set null value for   `defaultValue` with `{nullable: true}`

### ISSUE THREAD

**Issue by linus-sh** [nestjs/graphql#2995]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Potential Commit/PR that introduced the regression

https://github.com/nestjs/graphql/pull/2330

### Versions

10.2.1 > 11.0.6

### Describe the regression

I tried updatting `@nestjs/apollo` and `@nestjs/graphql`, but after installing Typescript alert `Type 'null' is not assignable to type 'Boolean | undefined'.` for `  @Field(() => String, { nullable: true, defaultValue: null })`.

I assume this is because `nullable: true` in `@Field' is not reflected in the defaultValue type annotation.

https://github.com/nestjs/graphql/blob/master/packages/graphql/lib/interfaces/base-type-options.interface.ts

### Minimum reproduction code

```ts
class User {
  @Field(() => String, { nullable: true, defaultValue: null }) # Type 'null' is not assignable to type 'String | undefined'.ts(2322)
  name!: string | null;
}
```

### Expected behavior

`@Field` can set null value as defaultValut with `{nullable: true}`

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by linus-sh** [comment]
I tried.

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/graphql/pull/3002
