### ISSUE TITLE
Schema validation

### ISSUE THREAD

**Issue by partyka95** [nestjs/graphql#3]
Hello,

Is there any good way to validate data in mutations like string length etc?

``typescript
mutation {
  createSth(name:"something", website:"http://test.com/") {
    id
    name
    website
  }
}
``

How can i validate name or website data? 

PS: Kamil, great job with nestjs!

Regards

**Comment by iamclaytonray** [comment]
You'd just want to write some helper functions and then implement them in your resolver file

**Comment by kamilmysliwiec** [comment]
That would be a good use-case for pipes integration.

**Comment by partyka95** [comment]
@kamilmysliwiec To use the pipes, we need a decorators like @Body(new ValidatorPipe()) in controllers, right? Do you have plans to create a decorator for resolvers like @Args()?

**Comment by kamilmysliwiec** [comment]
@partyka95 we don't need that, see microservices & websockets. you can use pipes with them already

**Comment by partyka95** [comment]
Could anyone give an example?

**Comment by kamilmysliwiec** [comment]
`ExternalContextCreator` has to be agnostic, meaning, we cannot adjust it to the GraphQL purposes. As a result, pipes won't be integrated with `@nestjs/graphql` package. Instead, you can keep validation responsibilities in the business logic.

**Comment by Zeldaze** [comment]
Any clearer examples on how to best implement validation for mutation inputs? Things like min/max lengths, advanced type fields etc. that we are used to from packages like class-validator?

**Comment by biels** [comment]
I'm interested in this as well. Maybe with anotations on the fields in the
schema?
