### ISSUE TITLE
GraphQLDefinitionsFactory should additionally generate wrapped input types

### ISSUE THREAD

**Issue by kal4l** [nestjs/graphql#3006]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Given a schema that uses input objects for queries/mutations:
```graphql
input SampleEntityInput {
  entityId: String!
}

type Query {
  sampleEntity(input: SampleEntityInput!): SampleEntityResponse!
}
```

The following types are generated:
```ts
export interface SampleEntityInput {
    entityId: string;
}

export interface IQuery {
    sampleEntity(input: SampleEntityInput): SampleEntityResponse | Promise<SampleEntityResponse>;
}
```

But the actual input that comes in through the resolver is wrapped in `input`, e.g.
```
{"input":{"entityId":"fe3ccdf4-6d48-43a6-915a-78843fd64674"}}
```

Which forces you to define the actual input type yourself in the resolver:
```ts
  @Query()
  async sampleEntity(@Args() { input }: { input: SampleEntityInput }) {
    ...
  }
```

### Describe the solution you'd like

Similar to `graphql-codegen`, additional types should be generated that are wrapped in the input name so they can be used in the resolvers.

e.g. 
```ts
export interface QuerySampleEntityInput {
    input: SampleEntityInput;
}
```

And used in the resolver:
```ts
  @Query()
  async sampleEntity(@Args() { input }: QuerySampleEntityInput) {
    ...
  }
```

### What is the motivation / use case for changing the behavior?

* Improves the usability of generated types when using objects for query and mutation input.

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this?

**Comment by jan-hecker** [comment]
@kal4l you can also pass the name argument to the @ Args() decorator. 
```TS
  @Query()
  async sampleEntity(@Args('input') input: QuerySampleEntityInput) {
    ...
  }
```
This then the input object is not wrapped in a object.
