### ISSUE TITLE
Generating an SDL File for Scheme First Approch?

### ISSUE THREAD

**Issue by farawaysouthwest** [nestjs/graphql#3014]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

We need a feature for generating a SDL with the schema first approch that is the equivalent of the method laid out here: https://docs.nestjs.com/graphql/generating-sdl

I attempted to use `autoSchemaFile`, but it throws an error when using schema first resolvers.

As a workaround, I have a file writer patched into the `transformSchema` prop of the module, but this only works on server startup and is a little hacky.
```
GraphQLModule.forRoot<ApolloFederationDriverConfig>({
      driver: ApolloFederationDriver,
      typePaths: ['./**/*.graphql'],
      inheritResolversFromInterfaces: true,
      transformSchema: (schema) => {
        writeFileSync(
          join(process.cwd(), `/schema.generated.gql`),
          printSchema(schema),
        );
        return schema;
      },
    }),
```

### Describe the solution you'd like

Something similar to the existing `GraphQLSchemaFactory` compatible with schema first would be ideal.

Code first example from the docs:
```
const gqlSchemaFactory = app.get(GraphQLSchemaFactory);
  const schema = await gqlSchemaFactory.create([RecipesResolver]);
  console.log(printSchema(schema));
```

### What is the motivation / use case for changing the behavior?

We need a feature for schema first that is the equivalent of the method laid out here: https://docs.nestjs.com/graphql/generating-sdl

As a workaround, I have a file writer patched into the `transformSchema` prop of the module, but this only works on server startup.

I attempted to use `autoSchemaFile`, but it throws an error when using schema first resolvers.

```
GraphQLModule.forRoot<ApolloFederationDriverConfig>({
      driver: ApolloFederationDriver,
      typePaths: ['./**/*.graphql'],
      inheritResolversFromInterfaces: true,
      transformSchema: (schema) => {
        writeFileSync(
          join(process.cwd(), `/schema.generated.gql`),
          printSchema(schema),
        );
        return schema;
      },
    }),
```

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
