### ISSUE TITLE
Mercurius error message very vague

### ISSUE THREAD

**Issue by axyom-dev** [nestjs/graphql#3021]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When a request is rejected by the `ValidationPipe`, the error message does not adequately explain the nature of the issue and simply returns 'Bad Request Exception' as the message.

### Minimum reproduction code

https://github.com/nestjs/nest/tree/master/sample/33-graphql-mercurius

### Steps to reproduce

Run a dev server server and try to send a request who will be rejected by the `validationPipe` like this:

```
mutation {
    addNewRecipe(newRecipeData: { title: "Lorem", description: "Ipsum", ingredients: ["Lorem", "Ipsum"] }) {
       id
    }
}
```

### Expected behavior

You should receive a vague error message:

```
{
  "data": null,
  "errors": [
    {
      "message": "Bad Request Exception",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "register"
      ]
    }
  ]
}
```

### Package version

12.0.9

### Graphql version

`graphql`: 
`apollo-server-express`: 
`apollo-server-fastify`: 

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please search through some of our old issues on this (this has been discussed several times in the past).
