### ISSUE TITLE
Provide way to delegate nested type resolution to resolver for that type

### ISSUE THREAD

**Issue by shohoney** [nestjs/graphql#3023]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues _I found some related issues, but none of them were fully addressed.  I feel like my example is more concise on what the goals are, so I created it_

### Is your feature request related to a problem? Please describe it

When designing a graph that has deeply nested entities, there isn't a way to delegate resolution of those entities to their corresponding resolvers in a declarative way. Ideally, resolvers and resolver chains would be constructed in a way that delegates any entity resolution down to the resolver for the type, rather than needing to import a provider for the type to the parent.  This is particularly evident in federated graphs where our types are orphaned.  In this example, our graph doesn't actually define any root queries.  Our types are simply extensions of existing types.

Let's take the following example:
```typescript
@ObjectType()
export class Viewer { // This is a root type that's fetched via request context
  @Field()
  isAdmin: boolean;

  @Field()
  fullName: string;

  @Field(type => Company)
  company: Company;
  // ... many other fields.
}

@ObjectType()
export class Company {
  @Field()
  id: string;

  @Field()
  name: string;

  @Field(type => Configuration)
  someProductConfiguration: Configuration
}

@ObjectType()
export class Configuration {
  @Field(type => ID)
  id: string;

  @Field()
  name: string;

  // ... other fields
}

@Resolver(of => Viewer)
export class ViewerResolver {
  constructor(
    private readonly viewerLoader: Dataloader,
    private readonly companyLoader: Dataloader, // for the example below.  I ideally do not want to do this.
    private readonly productConfigurationLoader: Dataloader, // more dependency sprawl
  ) {}

  /**
   * there are a few field resolver examples here to show what's possible today.
   */
  @ResolveField(type => Company, { name: 'company' })
  async resolveCompanyBySpreadingParent(@Parent() viewer) {
    /**
     * This will execute the resolver of the corresponding type, but this entity cannot be nullable, otherwise we'll
     * get an error when trying to resolve fields on on that type which will naturally come back null since an entity
     * doesn't exist.  We get "cannot return null for non-null field..."
     */
    return { ...viewer }
  }

  @ResolveField(type => Company, { name: 'company' })
  async resolveCompanyWithProvider(@Parent() viewer) {
    /**
     * Great, we loaded a company.  However, there's a problem.  How do we resolve the `someProductConfiguration` field?
     * Once again, we have an entity that might look like
     * {
     *   id: string
     *   name: string
     *   productNames: Array<string>;
     * }
     * So now we'd need a field resolver to get that field.  We need an additional provider imported to the resolver now.
     */
    return this.companyLoader.byId.load(viewer.companyId)
  }

  @ResolveField(type => Company, { name: 'company' })
  async resolveCompleteCompanyWithProvider(@Parent() viewer) {
    /**
     * Okay, now we have a full company.  But now, the viewer resolver is basically responsible for everything. Worse,
     * we still need to define all the resolvers for these other types because they're independently resolvable.  We need
     * a way to delegate resolution to the resolvers of the corresponding field's type.
     */
    const [
      company,
      someProductConfiguration
    ] = await Promise.all([
      this.companyLoader.byId.load(viewer.companyId),
      this.productConfigurationLoader.byName.load(viewer.company.products.find(p => p.name === 'someProduct'))
    ])
    return {
      ...company,
      someProductConfiguration,
    }
  }
  
  @ResolveReference()
  resolveReference(ref: { __typename: string, id: string}) {
    /**
     * The backing datatype for this might be something like:
     * {
     *   isAdmin: boolean;
     *   fullName: string;
     *   companyId: string;
     * }
     * so, we need a field resolver to resolve the company
     */
    return this.viewerLoader.byId.load(ref.id);
  }
}
```

As is evident, as this graph grows, this `ViewerResolver` is going to get out of control.  Arguably, it already is.

### Describe the solution you'd like

Rather than what we have above, I'd like to see if we can introduce one (or both) of two things.  
### The `@ResolveEntityField` decorator, or possible an `@Entity` field decorator for `ObjectType`
This would indicate that the field that's getting resolved should get delegated to a different resolver.  I'm not sure of the mechanics, but the usage would look like:
```typescript
// On an object type
@ObjectType()
export class Viewer { // This is a root type that's fetched via request context but it's reall
  @Field()
  isAdmin: boolean;

  @Field()
  fullName: string;

  @Entity(type => Company)
  company: Company;
}
```
or
```typescript
@Resolver(of => Viewer)
export class ViewerResolver {
  constructor(
    private readonly viewerLoader: Dataloader,
  ) {}

  @ResolveEntityField(type => Company)
  company: Company;

  @ResolveReference()
  resolveReference(ref: { __typename: string, id: string}) {
    /**
     * The backing datatype for this might be something like:
     * {
     *   isAdmin: boolean;
     *   fullName: string;
     *   companyId: string;
     * }
     * so, we need a field resolver to resolve the company
     */
    return this.viewerLoader.byId.load(ref.id);
  }
}
```
By doing this, we can delegate all of the example problem code to a `CompanyResolver` and subsequently a `ProductConfigurationResolver`.  This helps keep concerns isolated to their respective modules, rather than spreading our dependencies across many modules.

### The `@ResolveType` decorator.

This is inspired by how `@ResolveReference` works.  Since resolveReference is required to return a whole representation of the local entity, we can leverage the ability to spread the parent into the result of a field resolver to resolve the child type. Nullability still needs to get addressed, but it could look something like this

```typescript
@Resolver(of => Viewer)
export class ViewerResolver {
  constructor(
    private readonly viewerLoader: Dataloader,
  ) {}

  @ResolveField()
  company(@Parent() parent) {
    return { ...parent };
  }

  @ResolveReference()
  resolveReference(ref: { __typename: string, id: string}) {
    /**
     * The backing datatype for this might be something like:
     * {
     *   isAdmin: boolean;
     *   fullName: string;
     *   companyId: string;
     * }
     * so, we need a field resolver to resolve the company
     */
    return this.viewerLoader.byId.load(ref.id);
  }
}
```
and the corresponding `CompanyResolver`
```typescript
@Resolver(of => Company)
export class CompanyResolver {
  constructor(private readonly companyLoader: Dataloader) {}
  
  @ResolveField()
  someProductConfiguration(@Parent() p: Company) {
    /**
     * this woudl delegate to the `ProductConfigurationResolver` which would also have a `@ResolveType` resolver method
     * which can handle a product name, and maybe also a product id, etc.
     */
    return {
      ...p,
      productName: 'someProduct',
    }
  }
  
  @ResolveType()
  resolveType(@Parent() p) {
    const { companyId } = p;
    return this.companyLoader.loadById(companyId);
  }
}
```
Again, this addresses the concern of having resolvers that end up being god classes of loaders and resolvers.  In a deeply nested graph, you could end up in a scenario where each root type you have ends up loading all nested entities.  

### What is the motivation / use case for changing the behavior?

Ultimately the goal is to have a declarative way to indicate to nest and graphql that for a particular field, I want the result of that field's type's resolver.  I've had mixed luck with different attempts at this, and each of them are somewhat incomplete or cause a different class of issues.  I've not found any clear documentation on how to do this within the framework, so I'm assuming it's either not documented or not possible yet.  This will help people develop highly decoupled graphs and types and will ultimately lead to more maintainable code-bases for those of us who want to really lean into using NestJS for our GraphQL servers.

**Comment by shohoney** [comment]
I've been playing with this locally, and I did the following to get it to "work".  I'm sure there are tons of holes here, however:
in `packages/graphql/lib/schema-builder/storages/type-metadata.storage.ts`
update `addResolverMetadata`
```typescript
  addResolverMetadata(metadata: ResolverClassMetadata) {
    this.metadataByTargetCollection.get(metadata.target).resolver = metadata;
    this.metadataByTargetCollection.get(metadata.typeFn()).resolver = metadata;
  }
```
in the same file, add a new method: 
```typescript
  getResolverMetadataFor(metadata: PropertyMetadata): ResolverClassMetadata {
    // there is a tsc error here, so I just tossed an any on it for now
    return this.metadataByTargetCollection.get(metadata.typeFn() as any).resolver;
  }
```
in `packages/graphql/lib/schema-builder/factories/object-type-definition.factory.ts` update `createFieldResolver` to look for a resolver of a type.
```typescript

  private createFieldResolver<
    TSource extends object = any,
    TContext = {},
    TArgs = { [argName: string]: any },
    TOutput = any,
  >(field: PropertyMetadata, options: BuildSchemaOptions) {
    // get the the resolver for this field's type
    const typeResolver = TypeMetadataStorage.getResolverMetadataFor(field);

    const rootFieldResolver = (root: object) => {
      const value = root[field.name];
      // if typeResolver exists
      if(typeResolver) {
       /**
        * get the instance but I don't think this would be correctly scoped. I also assume
        * using moduleRef in each field resolver might be expensive.  Given these concerns, this is just to prove it 
        * some amount of possibility exists here.
        */
        const instance = this.moduleRef.get(typeResolver.target, { strict: false, });
        if(instance) {
          /**
           * make an assumption that some "common" method exists (see `resolveType` proposal from above)
           * otherwise fallback do existing possible values.
           */
          return instance['resolve']?.(root) ?? value ?? field.options.defaultValue;
        }
      }

      
      return typeof value === 'undefined' ? field.options.defaultValue : value;
    };
    const middlewareFunctions = (options.fieldMiddleware || []).concat(
      field.middleware || [],
    );
    if (middlewareFunctions?.length === 0) {
      return rootFieldResolver;
    }
    const rootResolveFnFactory = (root: TSource) => () =>
      rootFieldResolver(root);

    return decorateFieldResolverWithMiddleware<
      TSource,
      TContext,
      TArgs,
      TOutput
    >(rootResolveFnFactory, middlewareFunctions);
  }
}
```

**Comment by shohoney** [comment]
What I've essentially come to a "what needs to happen" conclusion is that we need a way to replace the "default" resolvers that are assigned during the schema building step with a method that ultimately wraps the child objectType's resolver.  

When we look at the `schema` that's generated in `graphql-federation.factory.ts` with a debugger, we can peek at the `_typeMap` which defines every type. Each type there has a `_fields` object which defines all of your fields and their resolvers.  Anywhere we have a `field` with a type of `GraphQLObjectType`, we need to be able to replace/delegate it's `resolve` function with a method that leverages the resolver for that type. In cases where we defined a field resolver, with @ResolveField, we have a function named "resolverCallback" otherwise we have a resolver called `rootFieldResolver`. Where either of those is defined, we need a way to get at scoped resolvers for the corresponding type and replace the resolver with the annotated `@Resolver` for that type.

**Comment by shohoney** [comment]
I put up a relatively incomplete draft PR as far as the community standards go, but I hope it helps with some inspiration/guidance for myself https://github.com/nestjs/graphql/pull/3026/files

**Comment by smolinari** [comment]
@shohoney - I'm not at all experienced with federation. But, I've done some research in the past. 

Is this the kind of problem you are wanting to solve and does Nest not offer it? 

https://medium.com/volvo-car-mobility-tech/working-with-entities-in-graphql-federation-a88e9f9865b2#:~:text=Querying%20an%20Entity%20in%20a%20subgraph&text=Normally%2C%20a%20query%20in%20GraphQL,order%20to%20fetch%20any%20entity.&text=Thus%2C%20every%20federated%20subgraph%20has%20to%20be%20able%20to%20resolve%20Query.

Scott

**Comment by shohoney** [comment]
While a federated grap surfaced the issue for us, this isn't actually a federation problem.  This is ultimately a separation of concerns issue.  I create resolvers for every type of my graph.  I want those resolvers to handle the resolution of their respective types.  Not for some parent resolver to suddenly usurp the responsibility because the framework simply doesn't delegate resolution down to the relevant resolver. I'm here with the aim of correcting that.  From what I can tell, NestJS does not do this, at least not by default or by understood convention. There are some simple hacks above that accomplish this, as I mentioned above, but all are incomplete. My rough PR shows a different way of accomplishing this, but is also incomplete.  That said, I feel that my solution is closer to the spirit of resolver chains than how nest handles it today.

**Comment by smolinari** [comment]
> I feel that my solution is closer to the spirit of resolver chains

Where did you get your current understanding of the "spirit of resolver chains"? GraphQL (with Nest or without) has been like this for many years with nobody complaining. Could it possibly be your understanding on this is a bit "off"? 

Above and beyond that, if you need that very niche structure of grabbing deeper and deeper non-hierarchical data to make it hierarchical, couldn't you:

1. Inject the service that offers the data (since it's not a federation issue???) into the resolver?

2.  you have your service return (merge) the data as needed? 

3. if it is a federation issue, check to see if Nest does offer what I pointed out in the article? I bet it does, because it comes from Apollo Federation and Nest rarely, if at all, mutes features of the packages it wraps.  

4. have your UI component query for the data it needs, outside of the business graph (like getting a config from a company???)? I.e. You don't have to pump all data for a page through one query and make it all "fit". In fact, that would be pretty silly. You can have multiple queries to get a single page loaded. In most cases, you will.  

And above and beyond that all, can you show any other GraphQL implementations (in other languages) that do what you are requesting? It might help your argument for the change. 

Scott

**Comment by jmcdo29** [comment]
Something I want to point out, that may not be completely clear in the docs, is that these "god class" resolvers that you have, the Viewer settings the resolve for both the configuration and the company, is not actually necessary. As `Viewer` has the child of `Company` it _should_ set up a resolve for the company. However, as `Company` has the child of `Configuration` _its_ resolver should set up the resolve field for the `Configuration` object. 

[I've made a very simplistic example](https://github.com/jmcdo29/nestjs-grpahql-child-field-resolve) that shows how Foo, which has a child of Bar, which has a child of Baz, which has a child of Quu, can each set up their child's direct resolver while letting the children each handle their child resolvers, so that `Foo` doesn't need to be aware of anything deeper than the first level.

---

With the above in mind, it might still be interesting to see a different approach to how it _might_ be possible to set up resolve field references on the object itself for when it is a child of a query. I'll try to take some time to read through and comprehend the approach that you've already got theorized here and provide what feedback I can

**Comment by shohoney** [comment]
@jmcdo29 , thanks for the example.  We've definitely done some of this, and it's where we start seeing providers getting a little unwieldy, IMO.  Especially where you have a large root type that resolves several types from a bunch of unrelated modules/providers.  I've opened 2 PRs on my playground repository which I hope shed light on what the ultimate goal is here.

Please note, the first PR has some unrelated stuff from a previous thing I was tinkering on.  you'll primarily want to focus on the `foo` `bar` and `baz` folders.  however, I also have `viewer` `company` and `configuration` available for querying:
```graphql
{
	foo {
    foo
    bar {
      bar
      baz {
        id
        baz
      }
    }
  }
}
```
and for teh viewer root
```graphql
{
  viewer {
    fullName
    company {
      name
      someProductConfig{ 
        name
      }
    }
  }
}
```

Without my proposal: https://github.com/shohoney/playground/pull/1
with the proposal from #3026 : https://github.com/shohoney/playground/pull/2

If you want to pull it down, I think you should be able to just clone on each branch and do a `yarn install`.  If you have issues for some reason, let me know I'm happy to help.

**Comment by jmcdo29** [comment]
Okay, looking at the playground PRs, I get the idea of what you're wanting to achieve. _M personal opinion_ is that the current implementation is correct, in how it __explicitly__ requires you to say how the current resolver handles its child resolutions. It moves the requirement from the child saying how to resolve itself to the parent saying how to get its child. And this, I think, makes sense, especially in cases where you need to pass information about the `@Parent()` to the resolver. Now, if you can do this in the proposed API as well, that's great.

I want to ask: with the proposed API, how do you handle when you want slightly different behavior between the way two parents resolve the same child type? Say that you have `Foo` and `Bar` both wanting to be able to resolve `Baz`, but you want the resulting baz to either be `foobaz` or `barbaz` depending on its parent. So a query like
```graph
query {
  foo {
    foo
    bar {
      bar
      baz {
        baz
      }
    }
    baz {
      baz
    }
  }
}
```

Might come out to something like

```json
{
  "foo": {
    "foo": "this is the normal foo",
    "bar": {
      "bar": "this is the normal bar",
      "baz": {
        "baz": "barbaz"
      }
    },
    "baz": {
      "baz": "foobaz"
    }
  }
}
```

If this `@ResolveObjectType()` is used, can it handle different resolutions between parent types, or is that something that has to be implemented within the context of that specific method? I feel like that would get messy rather quickly. And if looking back at a REST context, injecting the child resolver into the parent would be the "correct" approach, if you don't plan on using a join to manage that

**Comment by shohoney** [comment]
I think maybe one of the questions you're getting at that I didn't address in regards to the second question is more around how a type may resolve differently relative to the parent args that exists. This is a valid issue.  When I was thinking about it, I was largely thinking of this as a similar idea to the `referenceResolver` that's used with federated graphs.  That referenceResolver gets information about the inbound type so it knows how to resolve itself based on that. In the context of this, it's a bit more complicated.  I'll think about it some and see if I can reason around a sensible solution for that.

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

There are no plans to implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
