### ISSUE TITLE
A little necessary to bring the type of prism

### ISSUE THREAD

**Issue by msf-caesar** [nestjs/graphql#3029]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

![carbon](https://github.com/nestjs/graphql/assets/113716133/0f8dd71e-64c1-45bc-aaba-b524ccb8d70b)

### Describe the solution you'd like

empty

### Teachability, documentation, adoption, migration strategy

empty

### What is the motivation / use case for changing the behavior?

empty

**Comment by jmcdo29** [comment]
So...what's the point of this?
