### ISSUE TITLE
Field defined in resolvers, but not in schema when using class as return value

### ISSUE THREAD

**Issue by zuffik** [nestjs/graphql#3031]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Given this code and assuming everything else is set up correctly (I can provide Graphql module config if necessary)

```typescript
import {
  Field,
  Int,
  ObjectType,
  Query,
  ResolveField,
  Resolver,
} from '@nestjs/graphql';

const getDto = () => {
  @ObjectType({ isAbstract: true })
  abstract class Dto {
    @Field(() => Int)
    id: number = 1;
  }
  return Dto;
};

@ObjectType()
export class Child extends getDto() {}

const getDynamicResolver = () => {
  @Resolver(getDto(), { isAbstract: true })
  abstract class DynamicResolver {
    @Query(() => Child)
    dto() {
      return new Child();
    }
    @Query(() => Child)
    setDto() {
      return new Child();
    }

    //@ResolveField(() => String)
    //helloWorld() {
    //  return 'foo';
    // }
  }

  return DynamicResolver;
};

@Resolver(Child)
export class DynamicResolver extends getDynamicResolver() {}

```

I get this error: `Error: Child.helloWorld defined in resolvers, but not in schema`. Everything else works fine (queries and mutations are executed as expected) and everything is present in schema. 

### Workaround

One of the options is to set `@Field` to entity that is defined in `@Resolver` argument but in this way I'm not able to use `@Args`.

### Minimum reproduction code

https://github.com/zuffik/nestjs-schema-problem-repo/tree/main/src

### Steps to reproduce

1. install dependencies (`yarn`)
2. start project (`yarn start:dev`)

### Expected behavior

I expect the application is able to recognize fields in any context.

### Package version

12.0.9

### Graphql version

`graphql`: 16.8.1
`@nestjs/apollo`: 12.0.9

### NestJS version

10.2.7

### Node.js version

20.8.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
