### ISSUE TITLE
12.0.9 breaking schema generation of DateTime DateTimeISO

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [nestjs/graphql#3032]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When trying to start a graphql server with nest I know get the following error

```
Error: Schema must contain uniquely named types but contains multiple types named "DateTimeISO".
at new GraphQLSchema (<ProjectRoot>\node_modules\graphql\type\schema.js:219:15)
at mapSchema (<ProjectRoot>\node_modules\@nestjs\graphql\node_modules\@graphql-tools\utils\cjs\mapSchema.js:14:12)
at createNewSchemaWithResolvers (<ProjectRoot>\node_modules\@nestjs\graphql\node_modules\@graphql-tools\schema\cjs\addResolversToSchema.js:191:36)
```

### Minimum reproduction code

null

### Steps to reproduce

1. add graphql scalars datetime: datetimeisoresolver
2. try to start nest app

### Expected behavior

Startup and Schema works as before

### Package version

12.0.9

### Graphql version

`graphql`: 
`apollo-server-express`: 
`apollo-server-fastify`: 

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).
