### ISSUE TITLE
Field arguments cannot be deprecated (incorrect docs and missing behavior in `@Args`)

### ISSUE THREAD

**Issue by victorandree** [nestjs/graphql#3033]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The `@Args` decorator does not support `deprecationReason` as an option, but the documentation for this decorator says that it should: https://docs.nestjs.com/graphql/resolvers#args-decorator-options.

- The type of `ArgsOptions` does not include `deprecationReason`.
- Casting args as `any` and passing `deprecationReason` does not result in the field being marked as deprecated.

### Minimum reproduction code

https://github.com/bodil-dev/nest-graphql-args-deprecated

### Steps to reproduce

1. Create a project that uses the `@Args` decorator
2. Try to pass `deprecationReason` as an option, as documented on https://docs.nestjs.com/graphql/resolvers#args-decorator-options.
3. Get a type error seen below.
4. Cast the options object to `any`, and the generated schema will not include the deprecation reason.

TypeScript gives me the following error:

```
No overload matches this call.
  The last overload gave the following error.
    Argument of type '{ nullable: true; deprecationReason: string; }' is not assignable to parameter of type 'ArgsOptions'.
      Object literal may only specify known properties, and 'deprecationReason' does not exist in type 'ArgsOptions'.
```

### Expected behavior

It should be possible to deprecate arguments, per the GraphQL specification and NestJS documentation for the `@Args` decorator.

### Package version

12.0.9

### Graphql version

`graphql`: 16.8.1
`@apollo/server`: 4.9.4

### NestJS version

10.2.7

### Node.js version

20.5.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by rvitaliy** [comment]
i have a similar issue but in my case i use class with `@ArgsType & @Field` to define arguments.

minimal code to reproduce the problem:

```
import {
  Args,
  ArgsType,
  Field,
  Mutation,
  Resolver,
  ReturnTypeFuncValue,
} from '@nestjs/graphql';

@ArgsType()
class EditServiceArgs {
  @Field({
    deprecationReason: 'This field is deprecated!',
  })
  readonly id: string;

  constructor(id: string) {
    this.id = id;
  }
}

@Resolver()
export class UpdateServiceResolver {
  @Mutation((): ReturnTypeFuncValue => Boolean)
  async updateService(
    @Args() editServiceArgs: EditServiceArgs,
  ): Promise<boolean> {
    // eslint-disable-next-line no-console
    console.log(editServiceArgs);
    // ...do magic with editServiceArgs...

    return true;
  }
}
```

current generated schema:
```
updateService(id: String!): Boolean!
```

expected generated schema:
```
updateService(id: String!): Boolean! @deprecated(reason: "This field is deprecated!")
```

**Comment by kamilmysliwiec** [comment]
This should be partially fixed in this PR https://github.com/nestjs/graphql/pull/2969

**Comment by j3bb9z** [comment]
@kamilmysliwiec I tried doing it just as @rvitaliy, but for me it still doesn't work.

Did anyone here got it working?
