### ISSUE TITLE
Enabling ts-morph v20.x

### ISSUE THREAD

**Issue by BCsabaEngine** [nestjs/graphql#3034]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

https://github.com/nestjs/graphql/blob/master/packages/graphql/package.json#L53C1-L53C1 does not allow ts-morph v20.x

### Minimum reproduction code

Private, sorry

### Expected behavior

Should enabling ts-morph v20

### Package version

12.0.9

### Graphql version

`graphql`: 
`apollo-server-express`: 
`apollo-server-fastify`: 

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/graphql/pull/3020
