### ISSUE TITLE
MappedType PartialType throws error when using option decorator factory input

### ISSUE THREAD

**Issue by Maetes** [nestjs/graphql#3050]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

After upgrading to upgrading to version >12.

When starting the dev server the error:

```
GraphQLError: Input Object type UpdateUser must define one or more fields.
```
pops up.

### Minimum reproduction code

i think this is not nescessary

### Steps to reproduce

run dev server npm run start:dev

this is the relavant extract from my model file:

```
import {
  Field,
  InputType,
  ObjectType,
  OmitType,
  PartialType,
  registerEnumType,
} from '@nestjs/graphql';
import { Role } from '@prisma/client';
import {
  IsDefined,
  IsEmail,
  IsNotEmpty,
  MinLength,
  Validate,
} from 'class-validator';
import { IsUserAlreadyExist } from '../validators/is-user-already-exist.validator';

@ObjectType()
export class User {
  @Field(() => Number, { nullable: false })
  id: number;

  @Field(() => String, { nullable: false })
  email: string;

  @Field(() => String, { nullable: false })
  password: string;

  @Field(() => String, { nullable: true })
  refresh_token?: string;

  @Field(() => String, { nullable: true })
  forgotKey?: string;

  @Field(() => String, { nullable: true })
  confirmKey?: string;

  @Field(() => Boolean, { nullable: false, defaultValue: false })
  confirmed: boolean;

  @Field(() => Role, { nullable: false, defaultValue: Role.USER })
  role: Role;
}

@InputType()
export class UpdateUser extends PartialType<User>(User, InputType) {}

```

When I add any field to the "UpdateUser" class it works...

### Expected behavior

start smoothly

### Package version

12.0.10

### Graphql version

`graphql`: 16.8.1
`apollo-server-express`: 3.12.1
`apollo-server-fastify`:  n/a

### NestJS version

10.2.8

### Node.js version

20.9.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

**Comment by cskiwi** [comment]
Got the same issue, had to downgrade from `12.0.10` to `12.0.9`. I can test if any beta versions become available

**Comment by jkossis** [comment]
After poking around, it looks like [this recent change](https://github.com/nestjs/graphql/pull/2988) broke the validation. The following will help, utilizing the new `PartialTypeOptions` interface, but I need to dive into this more to understand why that change caused the previously working validation to fail.

Before:
```
@InputType()
export class UpdateDeviceSettingsInput extends PartialType(DeviceSettings, InputType) {}
```

After:
```
@InputType()
export class UpdateDeviceSettingsInput extends PartialType(DeviceSettings, { decorator: InputType, omitDefaultValues: true }) {}
```

**Comment by jkossis** [comment]
@kamilmysliwiec @cskiwi tagging you all just for reference.

**Comment by kamilmysliwiec** [comment]
@jkossis would you like to create a PR to fix this issue? My hunch is that the current behavior of `isPartialTypeOptions` might be broken but I'd have to double-check to confirm

**Comment by Maetes** [comment]
Thank you @jkossis. Was traveling abroad. Sorry for the late response. So a minimum reporduction is not necessary anymore?

**Comment by cskiwi** [comment]
Version 12.0.11 resolves this issue for me. thanks for the fix!

**Comment by jkossis** [comment]
Still seeing this issue, even with 12.0.11, using the example provided above.
