### ISSUE TITLE
CLI doesn't register object union with null

### ISSUE THREAD

**Issue by adamghowiba** [nestjs/graphql#3128]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Using a union type with null. IE string | null

### Minimum reproduction code

NA

### Expected behavior

Using the GraphQL CLI, set an object property to a union containing null

```ts
import { User} from '@prisma/client';


@ObjectType()
export class UserEntity implements User {
  @Field(() => ID)
  id!: number;

  first_name!: string;

  middle_name!: string | null; // <-- Will not set the output object to be nullable. 
  
  // Setting middle_name to undefined will throw a type error
  // because prisma will always return null for undefined fields
}
```

### Package version

12.0.11

### Graphql version

`graphql`:  16.8.1

### NestJS version

12.0.11

### In which operating systems have you tested?

- [x] macOS
- [ ] Windows
- [ ] Linux

**Comment by adamghowiba** [comment]
If all else fails, is there any easy way to fork the NestJS GraphQL CLI to accommodate null unions?

**Comment by kamilmysliwiec** [comment]
This should be working as expected now https://github.com/nestjs/graphql/blob/2429c07c44c45b5a41321fab51615f97d4ac8171/packages/graphql/tests/plugin/fixtures/nullable.dto.ts
