### ISSUE TITLE
Add jsdoc for `debug` and `introspection` in `GraphQLModule`

### ISSUE THREAD

**Issue by aarontravass** [nestjs/graphql#3142]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

No

### Describe the solution you'd like

Add jsdoc for the keys `debug` and `introspection`

### Teachability, documentation, adoption, migration strategy

Auto-completion along with jsDocs can help users understand the use case of each.

### What is the motivation / use case for changing the behavior?

Currently, the keys seem to not exist in the interface and hence, autocomplete does not work.

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by aarontravass** [comment]
@kamilmysliwiec I'm getting npm errors

```log
C:\Users\aaron\Documents\projects\nestjs-graphql>npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: @nestjs/graphql-workspace@0.0.0
npm ERR! Found: prettier@2.8.8
npm ERR! node_modules/prettier
npm ERR!   dev prettier@"2.8.8" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer prettier@">=3.0.0" from eslint-plugin-prettier@5.1.3
npm ERR! node_modules/eslint-plugin-prettier
npm ERR!   dev eslint-plugin-prettier@"5.1.3" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! C:\Users\aaron\AppData\Local\npm-cache\_logs\2024-02-12T18_51_19_689Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: C:\Users\aaron\AppData\Local\npm-cache\_logs\2024-02-12T18_51_19_689Z-debug-0.log

```

Node version: 18.19.0
npm version: 10.2.3

**Comment by aarontravass** [comment]
Never mind, looks like I was supposed to use `yarn` instead of `npm`

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/graphql/pull/3150
