### ISSUE TITLE
TypeScript definitions generated with wrong case

### ISSUE THREAD

**Issue by domusofsail** [nestjs/graphql#3147]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

In a schema-first approach, given a GraphQL schema having a lowercase type, the Typescript definitions generated have inconsistent case between class definition and method return types.

Given the following schema:
```gql
type person {
  name: String
  surname: String
}

type Query {
  persons(search: String!): [person!]!
}
```

the following Typescript gets generated:
```typescript
export class Person {
    name?: Nullable<string>;
    surname?: Nullable<string>;
}

export abstract class IQuery {
    abstract persons(search: string): person[] | Promise<person[]>;
}
```

resulting in a Typescript error TS2552: Cannot find name 'person'. Did you mean 'Person'?

![image](https://github.com/nestjs/graphql/assets/10399737/019e851e-a662-4582-961f-25dac6c3e601)

### Minimum reproduction code

https://github.com/domusofsail/nestjs-graphql-example

### Steps to reproduce

`pnpm start:dev`

### Expected behavior

Either class generated lowercase, or return type generated uppercase.

### Package version

12.1.1

### Graphql version

`graphql`: 16.8.1
`apollo-server-express`: N/A
`apollo-server-fastify`: N/A

### NestJS version

10.0.0

### Node.js version

20.11.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by domusofsail** [comment]
Ok, I'll try to do my best.

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/graphql/pull/3154
