### ISSUE TITLE
`GraphQLModule` should throw an error if schema files are not found

### ISSUE THREAD

**Issue by aarontravass** [nestjs/graphql#3148]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

The other day when I was setting up Graphql, I accidentally set `typeDefs` instead of `typePaths` and Nest refused to start. I couldn't understand the issue at first and hence, I set `autoSchemaFile` which ended up resolving the issue but I still wasn't able to manually define schema files. Once I researched the docs, I realized I was supposed to set `typePaths` if I was using the schema first approach

### Describe the solution you'd like

Throw an error with a message saying schema files were not found

### What is the motivation / use case for changing the behavior?

Nest provides no useful way of notifying me if there is a schema file issue.

**Comment by kamilmysliwiec** [comment]
> Nest provides no useful way of notifying me if there is a schema file issue.

Not sure if I'm following. Could you provide us with an example project to demonstrate this issue?

**Comment by aarontravass** [comment]
Looks like it is not an issue because rather application errors are not logged but instead, sent to sentry
```ts
await app.listen(process.env.PORT || 3000).catch((error) => {
    Sentry.captureException(error)
  })
```
