### ISSUE TITLE
@nestjs/graphql compatibility with ts-morph 22.0.0

### ISSUE THREAD

**Issue by AsetaShadrach** [nestjs/graphql#3208]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Getting the following error on running npm install with 
```
...
"@nestjs/graphql": "^12.1.1",
"ts-morph": "^22.0.0",
...
```

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @nestjs/graphql@12.1.1
npm ERR! Found: ts-morph@22.0.0
npm ERR! node_modules/ts-morph
npm ERR!   ts-morph@"^22.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peerOptional ts-morph@"^16.0.0 || ^17.0.0 || ^18.0.0 || ^19.0.0 || ^20.0.0 || ^21.0.0" from @nestjs/graphql@12.1.1
npm ERR! node_modules/@nestjs/graphql
npm ERR!   @nestjs/graphql@"^12.1.1" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: ts-morph@21.0.1
npm ERR! node_modules/ts-morph
npm ERR!   peerOptional ts-morph@"^16.0.0 || ^17.0.0 || ^18.0.0 || ^19.0.0 || ^20.0.0 || ^21.0.0" from @nestjs/graphql@12.1.1
npm ERR!   node_modules/@nestjs/graphql
npm ERR!     @nestjs/graphql@"^12.1.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

### Minimum reproduction code

https://gist.github.com/AsetaShadrach/f60839e43fa130dc46d976441154cb39

### Steps to reproduce

In the packge.json i have ;
```
...
"@nestjs/graphql": "^12.1.1",
"ts-morph": "^22.0.0",
...
```
On running npm install i get the error 

### Expected behavior

Expected the installation/build to go through successfully after updating to ts-morph 22.0.0

And downgrading ts-morph results in an error that was rasied in [this ts-morph issue](https://github.com/dsherret/ts-morph/issues/1513)

### Package version

12.1.1

### Graphql version

"@nestjs/graphql": "^12.1.1",
"graphql": "^16.8.1",
"graphql-type-json": "^0.3.2",
"graphql-ws": "^5.16.0",

### NestJS version

10.3.2

### Node.js version

20.12.2

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

OS: Linux Ubuntu 22
IDE: VS code
Package manger : npm

**Comment by kamilmysliwiec** [comment]
Use `npm i --legacy-peer-deps` for now.

Let's track this here https://github.com/nestjs/graphql/pull/3181
