### ISSUE TITLE
Regular Expression Denial of Service (ReDoS) vulnerability

### ISSUE THREAD

**Issue by andreeatirgovatu** [nestjs/graphql#3209]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

yes, we need an upgrade for chokidar package to fix Regular Expression Denial of Service (ReDoS) vulnerability
[link](https://security.snyk.io/vuln/SNYK-JS-SEMVER-3247795?_gl=1%2a15dnl3o%2a_ga%2aMTQyNzU1Njk3MS4xNjk4MDcxNTQw%2a_ga_X9SH3KP7B4%2aMTcxNTY4MDMyNC41Ny4xLjE3MTU2ODI1MzkuMC4wLjA.)

### Describe the solution you'd like

upgrade chokidar package to fix Regular Expression Denial of Service (ReDoS) 
[link](https://security.snyk.io/vuln/SNYK-JS-SEMVER-3247795?_gl=1%2a15dnl3o%2a_ga%2aMTQyNzU1Njk3MS4xNjk4MDcxNTQw%2a_ga_X9SH3KP7B4%2aMTcxNTY4MDMyNC41Ny4xLjE3MTU2ODI1MzkuMC4wLjA.)

### What is the motivation / use case for changing the behavior?

fix Regular Expression Denial of Service (ReDoS) vulnerability

**Comment by DanielSoCra** [comment]
Any updates here?

**Comment by kamilmysliwiec** [comment]
Chokidar is used exclusively to watch graphql files in order to generate corresponding TS definitions. Its API is not exposed - meaning, you can safely ignore this vulnerability in your project
