### ISSUE TITLE
Feat | clarifying `DefinitionsGeneratorOptions#defaultTypeMapping` supported types

### ISSUE THREAD

**Issue by Neosoulink** [nestjs/graphql#3210]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Using the **schema first approach**, I was caught on a small issue related to `DefinitionsGeneratorOptions#defaultTypeMapping`.
Yes, I passed the wrong type `nomber` instead of `number` to one of my scalar fields.

But I wonder if it will be better to just have clear type definitions for those scalar fields...

### Describe the solution you'd like

inside the `DefinitionsGeneratorOptions` type, [graphql-ast.explorer.ts#L66-L72](https://github.com/nestjs/graphql/blob/master/packages/graphql/lib/graphql-ast.explorer.ts#L66-L72) instead of defining the `defaultTypeMapping` property as follows:
```ts
Partial<
    Record<'ID' | 'Boolean' | 'Float' | 'String' | 'Int', string>
  >;
```

We can define a better definition like:
```ts
Partial<
    Record<'ID' | 'Float' | 'String' | 'Int', 'string' | 'number'> & Record<'Boolean', 'boolean' | 'number'>
 >;
```
> Or use a concrete object type (something like `{ ID: 'number' | 'string' }`).

>💡 Of course, we can go much further by checking the passed type if it's not a supported `typescript` type...

### What is the motivation / use case for changing the behavior?

As I mentioned in the above section, I made a mistake when I was defining the `defaultTypeMapping`.

I noticed the error very quickly and took me half of a second to solve it. However, I could have avoided it just with my `typescript` highlighter or with an error message.

This is just a very small improvement and maybe there's a reason behind this *definition type choice*, but I'll be grateful to receive your thoughts about this one.

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this?

**Comment by Neosoulink** [comment]
> Would you like to create a PR for this?

Yes, sure

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/graphql/pull/3346
