### ISSUE TITLE
@nestjs/graphql depends on vulnerable version of ws

### ISSUE THREAD

**Issue by sam-artuso** [nestjs/graphql#3214]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

@nestjs/graphql depends on `ws@8.16.0`, which is vulnerable to DoS attack.

This was fixed in `ws@8.17.1`.

Please update this dependency.

### Minimum reproduction code

https://github.com/nestjs/graphql

### Steps to reproduce

1. `npm install`
2. `npm audit --audit-level=high --prod`

### Expected behavior

@nestjs/graphql dependes on `ws@8.17.1`.

### Package version

12.1.1

### Graphql version

n/a

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/graphql/pull/3213
