### ISSUE TITLE
npm warn deprecated @apollo/server-plugin-landing-page-graphql-playground@4.0.0

### ISSUE THREAD

**Issue by ChronoBoot** [nestjs/graphql#3255]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When installing @nestjs/apollo

`npm warn deprecated @apollo/server-plugin-landing-page-graphql-playground@4.0.0: The use of GraphQL Playground in Apollo Server was supported in previous versions, but this is no longer the case as of December 31, 2022. This package exists for v4 migration purposes only. We do not intend to resolve security issues or other bugs with this package if they arise, so please migrate away from this to [Apollo Server's default Explorer](https://www.apollographql.com/docs/apollo-server/api/plugin/landing-pages) as soon as possible.`

### Minimum reproduction code

https://github.com/nestjs/graphql/blob/master/packages/apollo/package.json

### Steps to reproduce

npm i @nestjs/apollo --save

### Expected behavior

There shouldn't be a warning for a deprecated archive dated from 31 December 2022.
I know this is reported in the dependency dashboard (https://github.com/nestjs/graphql/issues/1725) but shouldn't there be an alternative by now ?

### Package version

12.2.0

### Graphql version

`graphql`: 
`apollo-server-express`: 
`apollo-server-fastify`: 

### NestJS version

10.3.10

### Node.js version

22.3.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
You can safely use this package in your project
