### ISSUE TITLE
Allow sortSchema via GraphQLDefinitionsFactory

### ISSUE THREAD

**Issue by olivierlacan** [nestjs/graphql#3256]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Currently the only way to enable `sortSchema: true` is via the [GraphQLModule's GqlModuleOption](https://github.com/nestjs/graphql/blob/7a5b7343ae9d4a20ae9993f46b3790bb29c54164/packages/graphql/lib/interfaces/gql-module-options.interface.ts#L72) but the `sortSchema` option isn't available in [its GenerateOptions type](https://github.com/nestjs/graphql/blob/7a5b7343ae9d4a20ae9993f46b3790bb29c54164/packages/graphql/lib/graphql-definitions.factory.ts#L13-L20).

When using a schema first approach, this means the only way to generate a sorted schema is to run the NestJS app that instantiates the GraphQLModule. This is a bummer because the example script shown in the [schema first](https://docs.nestjs.com/graphql/quick-start#schema-first) documentation only uses the GraphQLDefinitionsFactory. 

### Describe the solution you'd like

`GraphQLDefinitionsFactory` should allow the same `sortSchema` option in its `GenerateOptions`. 

### What is the motivation / use case for changing the behavior?

It should be possible to generate the same GraphQL schema via GraphQLModule and GraphQLDefinitionsFactory.

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this?
