### ISSUE TITLE
NestJS GraphQL subscriptions not working with graphql-ws

### ISSUE THREAD

**Issue by bhavyshekhaliya** [nestjs/graphql#3272]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Utilizing the `graphql-ws ` instead of subscriptions-transport-ws breaks the whole subscription.
I'm trying to upgrade our NestJS GraphQL subscriptions server to utilize` graphql-ws` rather than the current `subscriptions-transport-ws `(as suggested by the NestJS documentation). 

when i use only `subscriptions-transport-ws: true` it works but not work in `graphql-ws: true` and got below error 

```
{
  "error": "Could not connect to websocket endpoint ws://localhost:2233/graphql. Please check if the endpoint url is correct."
}
```

my GraphqlModule code is below 

```
GraphQLModule.forRootAsync<ApolloDriverConfig>({
      driver: ApolloDriver,
      useFactory: (configService: ConfigService, authService: AuthService) => ({
        autoSchemaFile: join(process.cwd(), 'src/schema.gql'),
        playground: configService.getOrThrow<boolean>('GRAPHQL_PLAYGROUND'),
        introspection: configService.getOrThrow<string>('NODE_ENV') !== 'production',
        context: ({ req, resp }) => ({ req, resp }),
        csrfPrevention: true,
        subscriptions: {
          'graphql-ws': true
        }
      }),
      imports: [AuthModule],
      inject: [ConfigService, AuthService],
    }),
```

### Minimum reproduction code

https://github.com/bhavyshekhaliya/NestJs-GraphQL-chat-app

### Expected behavior

when i user `graphql-ws : true` i got the error but when i use `subscriptions-transport-ws: true` i can not got the below error 

```
{
  "error": "Could not connect to websocket endpoint ws://localhost:2233/graphql. Please check if the endpoint url is correct."
}
```

### Package version

12.2.0

### Graphql version

```
 "@apollo/server": "^4.10.5",
 "@nestjs/apollo": "^12.2.0",
 "@nestjs/common": "^10.0.0",
 "@nestjs/config": "^3.2.3",
 "@nestjs/core": "^10.0.0",
 "@nestjs/graphql": "^12.2.0",
 "graphql": "^16.9.0",
 "graphql-subscriptions": "^2.0.0",
 "graphql-ws": "^5.16.0",
```

### NestJS version

10.4.2

### Node.js version

22.3.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Thank you for taking the time to submit your report! From the looks of it, this could be better discussed on our Discord. If you haven't already, please join [here](https://discord.gg/nestjs) and send a new post in the #⁠ 🐈 nestjs-help forum. Make sure to include a link to this issue, so you don't need to write it all again. We have a large community of helpful members, who will assist you in getting this to work.
