### ISSUE TITLE
Improve deprecation Reason to ArgsOptions

### ISSUE THREAD

**Issue by L-Luciano** [nestjs/graphql#3287]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

When I deprecate an input field. I see it on schema but it's not included in mutation.

### Describe the solution you'd like

Hello,

When I read this spec https://github.com/graphql/graphql-spec/pull/525/files. I think we can choose if we include the field or not. 

Is-it possible to add this feature ? 

Regards,
Laurent

### What is the motivation / use case for changing the behavior?

The motivation is "deprecate input field without break the front application"

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by L-Luciano** [comment]
Sorry, I just saw the problem is in apollo playground. 
It doesn't display the deprecated field whereas apollo explorer does.
I need to update my @graphql-codegen package too. 
I close the issue.
Sorry
