### ISSUE TITLE
@ResolveField identified as defined in resolver but not in schema

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [nestjs/graphql#3294]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

with the latest version serving a graphql server might lead to an error showing up like
```
Error: Entity.someField defined in resolvers, but not in schema
```
so in 12.2.0 you get the error
in 12.0.2 it is all good and also correct since most of the time it is a field in that entity type.

Maybe it is introduced by some dependency upgrade or maybe straight from nestjs/graphql

### Minimum reproduction code

null

### Steps to reproduce

1. add a field to a type in graphql schema first
2. add a @ResolveField for that field in the resolver
3. try to serve the server
4. getting error that the field is defined in resolver but not in schema

### Expected behavior

fields should be correctly regognized as defined in resolver and schema

### Package version

12.2.0

### Graphql version

`graphql`: 16.8.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).
