### ISSUE TITLE
Allow ts-morph ^22.0.0

### ISSUE THREAD

**Issue by Yogu** [nestjs/graphql#3302]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

nestjs/graphql currently allows ts-morph up to 21.0.0 in the peerDependencies. If you want to use typescript 5.4 or 5.5 in your app, you need ts-morph because of this bugfix: https://github.com/dsherret/ts-morph/pull/1515

### Describe the solution you'd like

Extend the version range of ts-morph to include 22.0.0

### What is the motivation / use case for changing the behavior?

Using TypeScript 5.4 or 5.5 in an app

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/graphql/pull/3241
