### ISSUE TITLE
Replace `fast-glob` with `fdir` or `tinyglobby`

### ISSUE THREAD

**Issue by benmccann** [nestjs/graphql#3307]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

`fast-glob` has 17 dependencies and really isn't needed where it's used
https://npmgraph.js.org/?q=fast-glob

### Describe the solution you'd like

Ideally replace with `fdir` since globbing isn't actually needed in this case
Alternatively, replace with `tinyglobby`, which has a more 1:1 API and would be a slightly faster migration

### What is the motivation / use case for changing the behavior?

Reduce the number of unnecessary dependencies

**Comment by kamilmysliwiec** [comment]
We plan to move to the built-in glob (sooner or later) https://github.com/nodejs/node/pull/51912
