### ISSUE TITLE
Class Transformer not working with ArgsType fields

### ISSUE THREAD

**Issue by kpervin** [nestjs/graphql#3311]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

If I define an ArgsType:

```ts
@ArgsType()
class ExampleArgs {
  @Field(() => String)
  @Transform(({ value }) => Number(value))
  number: number;
}
```
and use it in a resolver: 

```ts
@Resolver()
export class ExampleResolver {
  @Query(() => Boolean)
  exampleQuery(
    @Args() args: ExampleArgs
  ): boolean {
    console.log(args);
    return true;
  }
}
```

and then attempt the query with params `{ number: "1" }`, the transform function runs but does not actually serialize. Instead, we simply get the sent input.

### Minimum reproduction code

https://stackblitz.com/edit/request-context-nestjs-issue?file=src%2Fapp.module.ts

### Steps to reproduce

1. Open Stackblitz link and wait for project launch.
2. Navigate to the GQL playground
3. Enter the following query:
```graphql
query ExampleQuery($number: String!, $trueNumber: Float!) {
  exampleQuery(number: $number, trueNumber: $trueNumber) {
    number
    trueNumber
  }
}

{
  "number": "1",
  "trueNumber": 1
}
```
4. View the console logs on the server showing the discrepancy:
![image](https://github.com/user-attachments/assets/d4eda61e-01d9-43f7-b49a-bd252225c063)

### Expected behavior

The args should be serialized, such that given the above example:

Input: `{ number: "1" }`
Output: `{ number: 1 }`

This is expected due to [this response in another issue.](https://github.com/nestjs/graphql/issues/1145#issuecomment-724628669)

### Package version

`@nestjs/apollo`: ^12.2.0

### Graphql version

`graphql`: ^16.9.0
`@apollo/server`: ^4.11.0
`class-transformer`: ^0.5.1

### NestJS version

^10.4.1

### Node.js version

20.9.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [X] Linux

**Comment by kpervin** [comment]
The main reason for attempting to use `@Transform` here is because of not being able to use Field-level Pipes if I want to create an ArgsType class.

**Comment by kamilmysliwiec** [comment]
```ts
{
  provide: APP_PIPE,
  useValue: new ValidationPipe({ transform: true }),
},
```
