### ISSUE TITLE
ResolveField for a abstract dto

### ISSUE THREAD

**Issue by Diluka** [nestjs/graphql#3329]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I have a abstract dto, and I want to add a resolve field to it.

### Describe the solution you'd like

I want to something like this to work. https://codesandbox.io/p/devbox/graphql-resolve-field-for-abstract-dto-rhd7hc

### What is the motivation / use case for changing the behavior?

If I can add a resolve field to base one, then I don't add to each child.

**Comment by kamilmysliwiec** [comment]
I'd recommend using mixin classes in this case. Since abstract classes are designed not to be reflected in the schema, registering resolvers for them won't have any effect (and that's the expected behavior)
