### ISSUE TITLE
GraphQL Nested types + JEST bug

### ISSUE THREAD

**Issue by G0maa** [nestjs/graphql#3356]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Application works in development environment without problems, yet in `e2e` tests particularly on the second `app.init()` i.e. after `globalSetup` runs it throws
`Cannot determine a GraphQL output type for the "text". Make sure your class is decorated with an appropriate decorator.`.

This happens only when I have a nested model like [this](https://github.com/G0maa/i18n-graphql/blob/main/src/dto/responses.dto.ts) one.

### Minimum reproduction code

https://github.com/G0maa/i18n-graphql

### Steps to reproduce

1. `npm install`
2. Verify that development works `npm run start:dev`
3. `npm run test:e2e`
- or just visit [this](https://gitpod.io/?autostart=true#https://github.com/G0maa/i18n-graphql) GitPod link and it will do everything for you :smile: 

### Expected behavior

Tests should work without throwing the error specified above.

### Package version

12.2.1

### Graphql version

    "@apollo/server": "^4.11.0",
    "@nestjs/apollo": "^12.2.1",
    "graphql": "^16.9.0",

### NestJS version

10.4.6

### Node.js version

v20.17.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

I've spent many ~~hours~~ days searching for a solution, I've also asked on [Discord](https://discord.com/channels/520622812742811698/1296441519221506111/1296441519221506111), I am yet to find a solution to this bug. There's a similar [issue](https://github.com/nestjs/graphql/issues/2393), which its owner also posted on Discord and as it appears he didn't find a solution either.

**Comment by G0maa** [comment]
Somehow, in the main project I'm working on, when I removed the use of `globalSetup` and `globalTeardown` and instead used the same scripts but called them manually i.e. something like `npx ts-node `./test/setup.ts` (and changed the to functions ofc). It worked (((For now))).

**Comment by kamilmysliwiec** [comment]
Thank you for taking the time to submit your report! From the looks of it, this could be better discussed on our Discord. If you haven't already, please join [here](https://discord.gg/nestjs) and send a new post in the #⁠ 🐈 nestjs-help forum. Make sure to include a link to this issue, so you don't need to write it all again. We have a large community of helpful members, who will assist you in getting this to work.
