### ISSUE TITLE
Why all methods in class with @Resolver are resolvers

### ISSUE THREAD

**Issue by aerodestino** [nestjs/graphql#36]
Example: 
`import { Query, Resolver } from '@nestjs/graphql';

@Resolver('Example')
export class ExampleResolvers {
  constructor() {
  }
  @Query('example')
  async example(obj, args, context, info) {
    return {name: 'alik'};
  }
  async otherMethod() {
    return 'hello word';
  }
}
`

y have this error **(node:8600) UnhandledPromiseRejectionWarning: Error: Example.otherMethod defined in resolvers, but not in schema**

**Comment by kamilmysliwiec** [comment]
Fixed in 5.1.0

**Comment by Crewnie** [comment]
I have exactly the same problem but only when I take the application off the server.
While I'm developing it locally, everything works fine:
`npm run start: dev`
works well
`npm run build`
compile well

but when I deploy the application on the server I get the same error that you describe.

How can I debug what I am doing wrong?
