### ISSUE TITLE
AppModule with graphql and @Response decorator dont work in a Controller

### ISSUE THREAD

**Issue by alikdelrisco92** [nestjs/graphql#37]
My AppModule have this configuration [https://docs.nestjs.com/graphql/quick-start](url), but a need to upload a file with multipart/form-data, i added a new Module with a Controller with this method:
` @Post('upload')
  @UseInterceptors(FileInterceptor('file', { storage }))
  async uploadFile(@UploadedFile() file, @Response() res) {
     return {};
  }`
this method never respond to a client

**Comment by kamilmysliwiec** [comment]
`FileInterceptor` is not supposed to work with the `GraphQL` module
