### ISSUE TITLE
Graphql Context, Info, Parent is missing from generated typescript definition

### ISSUE THREAD

**Issue by himkwtn** [nestjs/graphql#377]
## Bug Report

Graphql Context, Info, Parent is missing from generated typescript definition

## Current behavior

Only args argument are generated

## Input Code

Generated file:
```ts
export interface IMutation {
    login(email: string, password: string): AuthPayload | Promise<AuthPayload>;
    // ...more
}
```
```ts
@Resolver('User')
export class UserResolver implements Partial<IMutation> {
  constructor(private readonly userService: UserService) {}

  @Mutation()
  login(
    @Args('email') email: string,
    @Args('password') password: string,
    @Context() ctx: Ctx,
    @Info() info: GraphQLResolveInfo,
  ) {
    return this.userService.login(email, password);
  }
}
```

## Expected behavior
ctx and info should be defined in the interface

## Possible Solution
```ts
export interface IMutation {
    login(email: string, password: string, ...extraStuff?: any[]): AuthPayload | Promise<AuthPayload>;
}
```

**Comment by kamilmysliwiec** [comment]
They are not supposed to be generated. All TypeScript definitions are produced based on the GraphQL SDL files. This:

```
implements Partial<IMutation>
```
won't make sense in most cases (e.g. what if you have a custom decorator https://docs.nestjs.com/custom-decorators)

**Comment by himkwtn** [comment]
Can you explain the use case of the generated schema if I can not use it like this?
