### ISSUE TITLE
Impossible to fetch the context from the graphQLOptions in the resolver

### ISSUE THREAD

**Issue by hloos** [nestjs/graphql#38]
Playing with the [graphql sample](https://github.com/nestjs/nest/tree/master/sample/12-graphql-apollo) provided in the samples of nestjs, I was looking for a way to fetch the context in the resolver in order to extract user token in the header of the request to forward it to other backend services.
Unfortunately, it does not seem to be given as parameter despite its presence in the [method signature](https://github.com/nestjs/nest/blob/master/sample/12-graphql-apollo/src/cats/cats.resolvers.ts) -> findByOneId.

Here follows the context added to each request and expected in the resolver method call (object ->req.headers)...

```typescript
  configure(consumer: MiddlewareConsumer) {
    const schema = this.createSchema();
    this.subscriptionsService.createSubscriptionServer(schema);

    consumer
      .apply(
        graphiqlExpress({
          endpointURL: '/graphql',
          subscriptionsEndpoint: `ws://localhost:3001/subscriptions`,
        }),
      )
      .forRoutes('/graphiql')
      .apply(graphqlExpress(req => ({ schema, rootValue: req, context: req.headers })))
      .forRoutes('/graphql');
  }
```

```typescript
  @Query('cat')
  async findOneById(obj, args, context, info): Promise<Cat> {
    const { id } = args;
    return await this.catsService.findOneById(+id);
  }
```
All parameters are undefined except the args one which contains the id.

**Moreover, I figured out other unexpected behaviors when adding decorators to the method:** 

```typescript
  @Query('cat')
  async findOneById(@Req() req, obj, args, context, info): Promise<Cat> {
    const { id } = args;
    return await this.catsService.findOneById(+id);
  }
```
Here all arguments are undefined except the args one which contains... the context !! (same issue when replacing the `@Req()` with `@Body()`)

```typescript
  @Query('cat')
  async findOneById(@Body() body, @Req() req, obj, args, context, info): Promise<Cat> {
    const { id } = args;
    return await this.catsService.findOneById(+id);
  }
```
2 decorators allows here to fetch the whole `GraphQLOptions` in the args parameter (other param still undefined). Same behavior for the signature `async findOneById(args): Promise<Cat>`.

**Comment by hloos** [comment]
So after multiple attempts in debug mode, etc... the this weird parameter values are due to the use of the **async** keyword (tested in v5.1.0/v5.0.0/v4.61). Without it, it works as expected.

This needs a fix :)

**Comment by YemSalat** [comment]
Any update on this by any chance?
This makes using decorators for graphql routes pretty much impossible unfortunately

**Comment by cschroeter** [comment]
@hloos I don't get your issue. If you like to add something to the context you simply can add information like so

```typescript
        graphqlExpress(async req => ({
          schema,
          rootValue: req,
          context: { foo: 'bar' },
        }))
```

If you following the documentation related to `nestjs/passport` and your GraphQL configuration looks like 

```typescript
       graphqlExpress(async req => ({
          schema,
          rootValue: req,
          context: req,
        }))
```

You will find yourself an user object in your resolvers.
```typescript
  @Query('currentUser')
  async currentUser(obj, args, context: Context): Promise<User> {
    const currentUser = context.user;
    return await this.userService.findById(currentUser.id);
  }
```

**Comment by hugoloos** [comment]
@YemSalat the workaround I am using consists in removing the async keyword from the main method (the one annotated with @Query) and using another class method (with async keyword) to do the await I need.

@cschroeter your example is quite similar to mine (only the signature method seems different). I am not sure how it can work...

**Comment by kamilmysliwiec** [comment]
It should be easy to achieve in the latest module release (which support Apollo v2)
