### ISSUE TITLE
How to generate document for graphql api ?

### ISSUE THREAD

**Issue by twilroad** [nestjs/graphql#4]
With @nestjs/graphql, how to generate document for graphql api ?
![image](https://user-images.githubusercontent.com/5193767/34657812-033f6010-f465-11e7-8a33-909e1041bc2a.png)
There is No Description.

**Comment by iamclaytonray** [comment]
Try adding a comment above the type or field you'd like to have a description for. Comments are:

```graphql
# This is a Post
type Post {
  # A unique identifier
  id: ID!
}
```

**Comment by rgolea** [comment]
@kamilmysliwiec, @iamclaytonray For me it's not working either. And yes, I do have the description set. Just for some reason it gets discarded. Any idea? I believe it comes from the `merge-graphql-schemas` module. Nest (`nestjs/graphql`) uses `^1.3.0` and the module is on it's `1.4.0` version. Not really sure if it affects. Can anyone help?
![screen shot 2018-02-23 at 14 21 36](https://user-images.githubusercontent.com/8843202/36596109-f469152c-18a4-11e8-88cf-1792d1f8f44f.png)

**Comment by iamclaytonray** [comment]
@rgolea - Can you shoot over a small repro. I'll test it out locally and get back with you

**Comment by rgolea** [comment]
@iamclaytonray not sure how. As far as I can gather, the typedefs come from the documents without the comments. Does it work for you? This is my `package.json`:
```
"dependencies": {
    "@nestjs/common": "^4.6.4",
    "@nestjs/core": "^4.6.4",
    "@nestjs/graphql": "^2.0.0",
    "@nestjs/testing": "^4.6.1",
    "apollo-server-express": "^1.3.2",
    "graphql": "^0.13.1",
    "graphql-tools": "^2.21.0",
    "reflect-metadata": "^0.1.12",
    "rxjs": "^5.5.6",
     ...
  }
```

**Comment by iamclaytonray** [comment]
Yep, works for me

**Comment by rgolea** [comment]
@iamclaytonray is there any way we can talk in private? Gitter?

**Comment by iamclaytonray** [comment]
Yeah, let me make an account real quick

**Comment by VChabrette** [comment]
Hi everyone !
I was wondering if any of you came to a solution, because my documentation isn't showing either and it's bugging me :confused:

**Comment by rgolea** [comment]
This was happening because of the version of graphql. Use 0.11.7.

**Comment by danil-z** [comment]
I have a same issue

my package json:

```
$ grep -i graphql package.json
    "@nestjs/graphql": "^5.5.1",
    "@types/graphql": "^14.0.5",
    "graphql": "^14.1.0",
    "graphql-iso-date": "^3.6.1",
    "graphql-tools": "^4.0.3",
    "graphql-type-json": "^0.2.1",
```
