### ISSUE TITLE
forRootAsync doesn't use default path when useGlobalPrefix true and no path set

### ISSUE THREAD

**Issue by spencersteers** [nestjs/graphql#418]
## I'm submitting a...
<pre><code>
[ ] Regression
[x ] Bug report
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

`GraphQLModule.forRootAsync(...)` and config like:
```ts
createGqlOptions(): GqlModuleOptions {
  return {
    useGlobalPrefix: true,     
  };
}
```

configures apollo to use the path `/${globalPrefix}undefined`.

## Expected behavior

`GraphQLModule.forRootAsync(...)` with `useGlobalPrefix: true` configures apollo with the default path `/${globalPrefix/graphql`

## Minimal reproduction of the problem with instructions

```ts
// main.ts
const app = await NestFactory.create(AppModule);
app.setGlobalPrefix('app-global-prefix');

// app.module.ts
GraphQLModule.forRootAsync({
  imports: [ConfigModule],
  useExisting: ConfigService,
}),

// config-service.ts
createGqlOptions(): GqlModuleOptions {
  return {
    useGlobalPrefix: true,
  };
}
```

The final path will be `/app-global-prefixundefined`.

## What is the motivation / use case for changing the behavior?

I would expect the defaults from [merge-defauts.util.ts](https://github.com/nestjs/graphql/blob/0479bf73b0bcf869a18c417111b85f1016db12c0/lib/utils/merge-defaults.util.ts) to be used when using `GraphQLModule.forRootAsync`.

## Environment

```
Nest version: 6.6.7
Nest graphql version: 6.5.1
```

The fix should be simple enough - ensuring [merge-defauts.util.ts](https://github.com/nestjs/graphql/blob/0479bf73b0bcf869a18c417111b85f1016db12c0/lib/utils/merge-defaults.util.ts) is used when creating the module with `GraphQLModule.forRootAsync()`. Will submit a PR that fixes this.

**Comment by kamilmysliwiec** [comment]
Published 6.5.2 :)
