### ISSUE TITLE
Support for property resolvers for interface types

### ISSUE THREAD

**Issue by justinmchase** [nestjs/graphql#429]
## I'm submitting a...
[x] Feature request

## Current behavior
I would like to create a resolver for an interface type which has a property resolver

## Expected behavior
I should be able to define a resolver for an interface type and add property resolvers for virtual fields on that resolver. It should have access to services via constructor injection, etc.

## Minimal reproduction of the problem with instructions
```ts
@InterfaceType()
export class IExample {
}

@Resolver(of => IExample)
export class ExampleResolver {
  constructor(
    private readonly example: ExampleService
  ) { }

  @ResolveProperty(type => Boolean)
  public async foo(@Root() item: IExample) {
    // this.example is available for this function
    return false
  }
}
```

## What is the motivation / use case for changing the behavior?
If you have an interface type with multiple concrete types you want to be able to access it in gql like:
```gql
examples {
  foo
}
```
Not
```gql
examples {
  ... on ConcreteType {
    foo
  }
}
```

Which it seems like right now the only way to do it is to promote the field to resolvers for each concrete type.

## Environment
Nest version: `^6.7.2`
For Tooling issues:
- Node version: `v12.8.0`
- Platform:  `linux`

**Comment by justinmchase** [comment]
By the way the error I get when I try to do this is:
```js
{
  "code": "GRAPHQL_VALIDATION_FAILED",
  "exception": {
    "stacktrace": [
      "GraphQLError: Cannot query field \"foo\" on type \"IExample\". Did you mean to use an inline fragment on \"ConcreteType\"?",
      "..."
    ]
  }
}
```

**Comment by marcus-sa** [comment]
You can't query interfaces, you can only implement them and use them in fragments.

**Comment by kamilmysliwiec** [comment]
It's not related to NestJS, but rather the GraphQL itself

**Comment by justinmchase** [comment]
I think you can, it clearly works for fields right on the object. I think that my problem may simply be that I didn't put the field on the interface though! I'll double check and follow up here.

Thanks.

**Comment by marcus-sa** [comment]
@justinmchase nope you can't.
An interface in GraphQL is just like an interface in TS.

**Comment by justinmchase** [comment]
Well they're doing it even in that example you linked...

The character interface has a `name` field which you can then query without the concrete type. Of course the object you're returning has to match a concrete type in the union but you should be able to query fields on the interface type without having to use a concrete fragment.

```gql
interface Character {
  id: ID!
  name: String!
  friends: [Character]
  appearsIn: [Episode]!
}
```

```gql
query HeroForEpisode($ep: Episode!) {
  hero(episode: $ep) {
    name # <-- this is a field on the interface
    ... on Droid {
      primaryFunction
    }
  }
}
```

Imagine you want the `name` field to be a resolver which is the same for all implementers of `Character`. I'll play with it a little later, I think I forgot to put the field on my interface and that's whats really blocking me.

**Comment by justinmchase** [comment]
Looking at this more, adding the field to the interface doesn't help. I am getting a crash in `type-graphql` which I'm filing a bug over there for but I do think that this is a legitimate issue in this library and think this ticket should be re-opened.

I think its legitimate because I am able to do this with graphql without using this library and it is documented in their documentation and it is a limitation of this library that this isn't supported.

I think the example from the gql documentation for characters that @marcus-sa  linked to is a good one, so this feature request / bug becomes how can I implement `Character.name` as a property resolver?

```ts
@InterfaceType()
export class Character {
  @Field()
   public name: string
}

@Resolver(of => Character ) // <-- this crashes my app
export class CharacterResolver {
  constructor(
    private readonly characters: CharacterService
  ) { }

  @ResolveProperty(type => String)
  public async name(@Root() character: Character) {
    return this.charcaters.resolveName(character)
  }
}
```
