### ISSUE TITLE
Global cache not supported in GraphQL

### ISSUE THREAD

**Issue by eduarevalo** [nestjs/graphql#443]
## Current behavior
Graphql does not work if is set up along with Global Cache manager
Here is an example of ApplicationModule to reproduce the bug.
You can paste this little snippet into the 12-graphql-apollo sample project

## Input Code

```ts
@Module({
  imports: [
    CatsModule,
    CacheModule.register({ ttl: 5 }),
    GraphQLModule.forRoot({
      typePaths: ['./**/*.graphql'],
      installSubscriptionHandlers: true,
    }),
  ],
  providers: [
    {
      provide: APP_INTERCEPTOR,
      useClass: CacheInterceptor,
    }
  ],
})
export class ApplicationModule {}
```

## Expected behavior
Two possible expected solutions:
1. Be able to exclude some modules to be intercepted by the caching manager, when installed as global
2. Support caching for Graphql

**Comment by eduarevalo** [comment]
I have the same issue. Any news?

**Comment by kamilmysliwiec** [comment]
We've added a note in the documentation (**Caching** chapter)

![image](https://user-images.githubusercontent.com/23244943/76744362-66653f00-6774-11ea-861f-940456d7bfe7.png)

To enable caching in your GraphQL application, follow this documentation:
https://www.apollographql.com/docs/apollo-server/performance/caching/

#### Setting a default `maxAge`

```typescript
GraphQLModule.forRoot({
  cacheControl: {
     defaultMaxAge: 5,
  },
}),
```

#### Saving full responses to a cache 

```typescript
GraphQLModule.forRoot({
  plugins: [responseCachePlugin()],
}),
```

and:

```typescript
import responseCachePlugin from 'apollo-server-plugin-response-cache';
```

To read more about plugins, visit this website https://docs.nestjs.com/graphql/plugins#using-external-plugins
