### ISSUE TITLE
problem with deploying to zeit now

### ISSUE THREAD

**Issue by cheel1337** [nestjs/graphql#454]
## I'm submitting a...
<pre><code>
[ ] Regression
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
Using @now/node builder
Build works fine. On runtime logs i get this:
```
Cannot find module '@nodelib/fs.stat'
Did you forget to add it to "dependencies" in `package.json`?
```

## Minimal reproduction of the problem with instructions
Just deploy nest application with netjs/graphql module to zeit now

## What is the motivation / use case for changing the behavior?
Few days ago i oppened issue [here](https://github.com/zeit/now/issues/3115)
And styfle tolds me:
```
The @nodelib/fs.stat error is likely from fast-glob and globby tracked here (https://github.com/zeit/node-file-trace/issues/55)

If you can replace that dependency with a different glob implementation, it should work.
```
That is all we have

## Environment
<pre><code>
Nest version: 6.8.2
nest/graphql version: 6.5.3
Platform:  Zeit Now
</code></pre>

**Comment by kamilmysliwiec** [comment]
Can you please provide a minimal repository which reproduces your issue?

**Comment by cheel1337** [comment]
@kamilmysliwiec https://github.com/cheel1337/nestjs-problem
run:
```bash
yarn
yarn deploy
```

go to zeit now and check the runtime logs, you will get this:
```
Cannot find module '@nodelib/fs.stat'
Did you forget to add it to "dependencies" in `package.json`?
Process exited before completing request
```

**Comment by kamilmysliwiec** [comment]
This issue doesn't seem to be related to NestJS. Let's track this here https://github.com/zeit/now/issues/3115
