### ISSUE TITLE
ResolveProperty - TypeError: Cannot read property 'fields' of undefined

### ISSUE THREAD

**Issue by PiotrSokolinski** [nestjs/graphql#482]
Hi, I am building a simple server in nestjs using Graphql architecture. Unfortunately, I came across an error which I can not overcome. It occurs when I want to user @ResolveProperty decorator to create a Graphql tree. The error is the following: 
<img width="1100" alt="Screenshot 2019-11-19 at 10 14 06" src="https://user-images.githubusercontent.com/37448494/69133540-5c794b00-0ab6-11ea-8678-8f67d0c35318.png">

I spent a few days on research but I could not find the solution. It is probably something wrong with my code but I can not figure out what. Maybe I do not understand something correctly.
I am providing a minimal repository, which reproduces the error. 
https://github.com/PiotrSokolinski/test-project

I am connecting to the local Postgres database. There is a Group entity, which should have members and using Query for a group I want to obtain also the members using @ResolveProperty.

GroupDto:
```
import { Field, ObjectType, ID, Int } from 'type-graphql';
import { UserEntity } from '../user/user.entity';
import { UserDto } from '../user/user.dto';

@ObjectType()
export class GroupDto {
  @Field(type => ID) readonly id?: number;
  @Field() readonly name: string;
  @Field({ nullable: true }) readonly avatarUrl?: string;
  @Field({ nullable: true }) readonly address?: string;
  @Field(type => Int, { nullable: true }) readonly number?: number;
  @Field({ nullable: true }) readonly zipCode?: string;
  @Field({ nullable: true }) readonly city?: string;
  @Field({ nullable: true }) readonly country?: string;
  // ??????
  @Field(type => [UserDto]) readonly members: UserDto[];
}
```

GroupResolver:
```import {
  Resolver,
  Query,
  Mutation,
  Args,
  ResolveProperty,
  Parent,
} from '@nestjs/graphql';
import { Inject, forwardRef, UseGuards } from '@nestjs/common';
import { ID } from 'type-graphql';
import { GroupEntity } from './group.entity';
import { GroupDto } from './group.dto';
import { GroupService } from './group.service';
import { UserService } from '../user/user.service';
import { UserDto } from '../user/user.dto';

@Resolver(of => GroupEntity)
export class GroupResolver {
  constructor(
    private readonly groupService: GroupService,
    @Inject(forwardRef(() => UserService))
    private readonly userService: UserService,
  ) {}

  @Query(returns => GroupDto, { name: 'group' })
  async getGroup(@Args({ name: 'id', type: () => ID }) id: number) {
    return await this.groupService.findOneById(id);
  }

  @ResolveProperty(returns => [UserDto], { name: 'members' })
  async getUsers(@Parent() group) {
    const { id } = group;
    return await this.userService.findGroupUsers(id);
  }
}
```
GroupService:
```import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { GroupEntity } from './group.entity';
import { Repository } from 'typeorm';
import { GroupDto } from './group.dto';
import { UserEntity } from '../user/user.entity';

@Injectable()
export class GroupService {
  constructor(
    @InjectRepository(GroupEntity)
    private readonly GroupRepository: Repository<GroupEntity>,
  ) {}

  async findOneById(passedId: number): Promise<GroupEntity> {
    return this.GroupRepository.findOne({ where: { id: passedId } });
  }
}
```

UserDto:
```import { Field, ObjectType, ID } from 'type-graphql';

@ObjectType()
export class UserDto {
  @Field(type => ID) readonly id?: number;
  @Field() readonly email: string;
  @Field() readonly firstName: string;
  @Field() readonly lastName: string;
  @Field() readonly nick: string;
  @Field() readonly role: string;
  @Field() readonly color: string;
  @Field({ nullable: true }) readonly avatarUrl?: string;
  @Field() readonly owner: boolean;
  @Field({ nullable: true }) readonly token?: string;
}
```

UserService:
```import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { UserEntity } from './user.entity';
import { Repository, In } from 'typeorm';

@Injectable()
export class UserService {
  constructor(
    @InjectRepository(UserEntity)
    private readonly UserRepository: Repository<UserEntity>,
  ) {}

  async getUsers(): Promise<UserEntity[]> {
    return await this.UserRepository.find();
  }

  async findGroupUsers(passedId: number) {
    return await this.UserRepository.find({
      where: { group: { id: passedId } },
    });
  }
}
```

Thank you in advance!

**Comment by kamilmysliwiec** [comment]
Please, provide a minimal repository which reproduces your issue.

**Comment by PiotrSokolinski** [comment]
As I said, here is the minimal repository which cases the issue: https://github.com/PiotrSokolinski/test-project. The code which is on the master branch connects to my local DB. On the other hand, I created the branch master-mock-data where I got rid of DB and tried to reproduce the error using mock data. I had very similar issues with the mock data.

**Comment by kamilmysliwiec** [comment]
So I've cloned your repo locally and I don't really understand what you're trying to accomplish. You have resolvers of `GroupEntity` and `UserEntity` but these aren't even using `type-graphql` decorators, hence, neither one contains a single field. You can find a similar example here https://github.com/MichalLytek/type-graphql/tree/master/examples/typeorm-basic-usage

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) next time for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by bennett-jacob** [comment]
I'm not a fan of the Discord server. Searching on Discord, while possible, is not easy nor indexed for searching in the way we can on the web. Additionally, solutions for issues posted on Discord aren't indexed on search engines, so we can't find them when searching Google.
