### ISSUE TITLE
Bug: iterall not in package.json

### ISSUE THREAD

**Issue by andreialecu** [nestjs/graphql#537]
https://github.com/nestjs/graphql/blob/487379b8c0524fe3cdbeb085038d804ba6fff0fd/lib/utils/async-iterator.util.ts#L1

This library imports `iterall` but it is not defined in package.json.

This is a problem with yarn v2, the upcoming version of yarn, resulting in errors such as:

```
Cannot find module 'iterall' from 'async-iterator.util.js'

      at Resolver.resolveModule (../.yarn/cache/jest-resolve-npm-24.9.0-56dbaf2e7d-1.zip/node_modules/jest-resolve/build/index.js:259:17)
      at Object.<anonymous> (../.yarn/virtual/@nestjs-graphql-virtual-9a8fdb1b99/0/cache/@nestjs-graphql-npm-6.5.3-98b2ad3bf3-1.zip/node_modules/@nestjs/graph
ql/dist/utils/async-iterator.util.js:12:19)
```

The library should be added to dependencies.

**Comment by andreialecu** [comment]
This probably worked before because of the behavior described in this comment:

https://github.com/yarnpkg/berry/issues/271#issuecomment-507432524

**Comment by kamilmysliwiec** [comment]
This issue is not related to NestJS

**Comment by andreialecu** [comment]
???

This package is using a library not defined in its package.json. How is this not related?
