### ISSUE TITLE
Use pre-defined schema?

### ISSUE THREAD

**Issue by blissi** [nestjs/graphql#54]
Hallo,

in a previous release there has been the GraphQLFactory provider with the createSchema()-function. This has been removed and it seems there is no way to pass merged GraphQL types to GraphQLModule.forRoot(). Am I right or did I overlook something?

What is the reason to remove support for predefined types?

My use case is this: I have a multi-repo project and one of them returns the merged types. Until now I have simply passed them to createSchema(), but now I have to update to the latest nestjs/graphql version (I need the Root()-decorator).

Thanks,
Steven

**Comment by kamilmysliwiec** [comment]
Nothing has changed. You can pass all these options to either `forRoot()` or `forRootAsync()` method
