### ISSUE TITLE
Update needed for  NPM Module

### ISSUE THREAD

**Issue by sanzhardanybayev** [nestjs/graphql#577]
Please, update your NPM Module

**Comment by sanzhardanybayev** [comment]
In the current version I cannot get **reply** object in Apollo Context when using Fastify

**Comment by kamilmysliwiec** [comment]
We'll publish a new release as soon as possible.

**Comment by sanzhardanybayev** [comment]
@kamilmysliwiec Thank you! Much appreciated!
