### ISSUE TITLE
support Grpc 

### ISSUE THREAD

**Issue by zuohuadong** [nestjs/graphql#59]
like this: https://github.com/google/rejoiner

Creates a uniform GraphQL schema from microservices
Allows the GraphQL schema to be flexibly defined and composed as shared components
Generates GraphQL types from Proto definitions
Populates request Proto based on GraphQL query parameters
Supplies a DSL to modify the generated schema
Joins data sources by annotating methods that fetch data
Creates Proto FieldMasks based on GraphQL selectors

**Comment by kamilmysliwiec** [comment]
We don't plan to support this feature (no bandwidth)
