### ISSUE TITLE
Subscriptions client examples?

### ISSUE THREAD

**Issue by joefru** [nestjs/graphql#6]
**Very** excited about NestJS. Thinking of becoming a sponsor if it proves out for my new project.

I need to get GraphQL subscriptions working. For starters, I've implemented the example from docs, and now I'm trying to connect Graph**i**QL with something like this:

```
  consumer
    .apply(graphiqlExpress({
      endpointURL: "/graphql", 
      subscriptionsEndpoint: `ws://localhost:${process.env.PORT || 3000}/subscriptions`
    }))
    .forRoutes({path: "/graphiql", method: RequestMethod.GET})
    .apply(graphqlExpress(req => ({schema, rootValue: req})))
    .forRoutes({path: "/graphql", method: RequestMethod.ALL});
```

I'm getting `ERR_CONNECTION_REFUSED` in browser console. I feel like I'm missing the connection between GraphQL Subscriptions and WebSockets, but I can't seem to piece it together from the docs.

Are there any working e2e examples out there?

**Comment by kamilmysliwiec** [comment]
Hi @joefru,
I'm glad that you enjoy the project & and happy about the sponsor idea 🙂 
Have you created the subscriptions endpoint in the same way as explained here? https://dev-blog.apollodata.com/tutorial-graphql-subscriptions-server-side-e51c32dc2951 (**WebSocket Transport for Subscriptions**)

**Comment by joefru** [comment]
I did happen to read that article. I'm wondering how to include the following code in 'the nest way'...

```
// Wrap the Express server
const ws = createServer(server);
ws.listen(PORT, () => {
  console.log(`GraphQL Server is now running on http://localhost:${PORT}`);
  // Set up the WebSocket for handling GraphQL subscriptions
  new SubscriptionServer({
    execute,
    subscribe,
    schema
  }, {
    server: ws,
    path: '/subscriptions',
  });
});
```

I tried something like this:

```
@WebSocketGateway({ port: process.env.PORT || 3000, namespace: "subscriptions" })
export class SubscriptionGateway implements OnGatewayInit {

	constructor(private graphQLFactory: GraphQLFactory) {}
	
	afterInit(server: any) {
		const schema = this.createSchema();

		new SubscriptionServer({
			execute,
			subscribe,
			schema
		}, {
			server: server,
			path: "/subscriptions",
		});
	}

	createSchema() {
		const typeDefs = this.graphQLFactory.mergeTypesByPaths("./**/*.graphql");

		return this.graphQLFactory.createSchema({ typeDefs });
	}
}
```

But that yields the following build-time error: `Error: listen EADDRINUSE :::3000`.  When I switch to port 3001, it compiles but then I get the following error in browser console:

'WebSocket connection to 'ws://localhost:3001/subscriptions' failed: Connection closed before receiving a handshake response'

**Comment by kamilmysliwiec** [comment]
Hi @joefru,
I think you should avoid using `@Gateway()` here, let's make use of an **async component** instead. Register a `SUBSCRIPTION_SERVER` somewhere, for example inside the `AppModule`:

```typescript
components: [
    {
      provide: SUBSCRIPTION_SERVER,
      useFactory: async () => {
        const server = createServer();
        return await new Promise((resolve) => server.listen(PORT, resolve));
      },
    }
  ]
```
Then inject this component into module class:

```typescript
export class ApplicationModule implements NestModule {
  constructor(
    private readonly graphQLFactory: GraphQLFactory,
    @Inject(SUBSCRIPTION_SERVER) private readonly ws,
  ) {}

  /// rest of code
}
```
Afterwards, create instance of `SubscriptionServer`:

```typescript
  configure(consumer: MiddlewaresConsumer) {
    const schema = this.createSchema();
    this.initSubscriptionServer(schema);

    consumer
      .apply(graphiqlExpress({
        endpointURL: "/graphql", 
        subscriptionsEndpoint: `ws://localhost:${process.env.PORT || 3000}/subscriptions`
      }))
      .forRoutes({path: "/graphiql", method: RequestMethod.GET})
      .apply(graphqlExpress(req => ({schema, rootValue: req})))
      .forRoutes({path: "/graphql", method: RequestMethod.ALL});
  }

  initSubscriptionServer(schema) {
    new SubscriptionServer({ execute, subscribe, schema}, {
	server: this.ws,
	path: "/subscriptions",
    });
  }
```
That's all. Remember to kill server (`ws` instance) using `OnModuleDestroy` hook.

**Comment by joefru** [comment]
First of all, thanks for the help and quick responses. Unfortunately, I still think something is missing. I followed your directions using the nest [graphql-apollo example](https://github.com/nestjs/nest/tree/master/examples/12-graphql-apollo) for simplicity's sake, and I get these warnings:

```
(node:71978) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): TypeError: Cannot convert undefined or null to object
(node:71978) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

When trying to access GraphiQL on localhost, the browser churns for several minutes, and eventually I get `ERR_CONNECTION_REFUSED`. Any thoughts?

**Comment by kamilmysliwiec** [comment]
Will try to reproduce this locally

**Comment by kamilmysliwiec** [comment]
Could you provide a little bit more code? What actually have you changed? Did you add a snippet that I shared with your or sth more?

**Comment by joefru** [comment]
I cloned the [graphql-apollo](https://github.com/nestjs/nest/tree/master/examples/12-graphql-apollo) example and contained all changes within [app.module.ts](https://github.com/nestjs/nest/blob/master/examples/12-graphql-apollo/src/app.module.ts):

```typescript
import {
  Inject,
  Module,
  MiddlewaresConsumer,
  NestModule,
  RequestMethod,
} from '@nestjs/common';
import { createServer } from 'http';
import { graphqlExpress, graphiqlExpress } from 'apollo-server-express';
import { GraphQLModule, GraphQLFactory } from '@nestjs/graphql';
import { SubscriptionServer } from 'subscriptions-transport-ws';
import { execute, subscribe } from 'graphql';
import { CatsModule } from './cats/cats.module';

@Module({
  components: [
    {
      provide: "SUBSCRIPTION_SERVER",
      useFactory: async () => {
        const server = createServer();

        return new Promise((resolve, reject) => {
          server.on("error", reject);
          server.listen(process.env.PORT || 3000, resolve);
        });
      },
    }
  ],
  imports: [CatsModule, GraphQLModule],
})
export class ApplicationModule implements NestModule {
  constructor(private readonly graphQLFactory: GraphQLFactory, @Inject("SUBSCRIPTION_SERVER") private readonly ws) {}

  configure(consumer: MiddlewaresConsumer) {
    const schema = this.createSchema();

    console.log(this.ws);
    this.initSubscriptionServer(schema);

    consumer
      .apply(graphiqlExpress({
        endpointURL: '/graphql', 
        subscriptionsEndpoint: `ws://localhost:${process.env.PORT || 3000}/subs`
      }))
      .forRoutes({ path: '/graphiql', method: RequestMethod.GET })
      .apply(graphqlExpress(req => ({ schema, rootValue: req })))
      .forRoutes({ path: '/graphql', method: RequestMethod.ALL });
  }

  createSchema() {
    const typeDefs = this.graphQLFactory.mergeTypesByPaths('./**/*.graphql');
    const schema = this.graphQLFactory.createSchema({ typeDefs });
    return this.graphQLFactory.createSchema({ typeDefs });
  }

  initSubscriptionServer(schema) {
    const ss = new SubscriptionServer({execute, subscribe, schema}, {
      server: this.ws,
      path: "/subs",
    });
    console.log(ss);
  }

  onModuleDestroy() {
    this.ws.close();
  }
}
```

**Comment by kamilmysliwiec** [comment]
@joefru I'm sorry.. It was my mistake 🙁  Let's use code below instead:
```
{
      provide: 'SUBSCRIPTION_SERVER',
      useFactory: () => {
        const server = createServer();
        return new Promise(resolve => server.listen(process.env.PORT || 3000, () => resolve(server)));
      },
},
```

**Comment by kamilmysliwiec** [comment]
I updated example with the subscription server:
https://github.com/nestjs/nest/tree/master/examples/12-graphql-apollo

Subscribe in one window:
```
subscription {
  catCreated {
  	name
  }
}
```

Mutate in the different one:
```
mutation {
  createCat(name: "Nest") {
    name
  }
}
```
Everythin works fine 🙂

**Comment by joefru** [comment]
Downloaded the latest example but I still get `[object Object]` in the results window when I run the subscription query.

Also, what I'd really like to achieve is to have the subscription server listen on the same port as the express http server. That way, I can deploy a single application to Heroku, which only allows a single port per deployment.

**Comment by kamilmysliwiec** [comment]
I have tested this example and it works fine for me, there's no `[object Object]`, that's weird. What kind of mutation are you executing from the graphiql? It has nothing to do with `@nestjs/graphql` module, but rather with this issue that you mentioned about earlier (https://github.com/apollographql/subscriptions-transport-ws/issues/236#issuecomment-326869192)

**Comment by andrew-hamilton-dev** [comment]
I was having the same issue with [Object Object] as @joefru but I was able to resolve it by playing around with the package versions in the dependency versions.  Below are the versions i ended up with to have it working.    Might help you out @joefru.
`"dependencies": {
    "@nestjs/common": "^4.5.9",
    "@nestjs/core": "^4.5.10",
    "@nestjs/graphql": "^2.0.0",
    "apollo-server-express": "^1.3.2",
    "graphql": "0.11.7",
    "graphql-subscriptions": "^0.5.6",
    "graphql-tools": "^2.19.0",
    "reflect-metadata": "^0.1.12",
    "rxjs": "^5.5.6",
    "subscriptions-transport-ws": "^0.9.5",
    "typescript": "^2.6.2",
    "ws": "^4.0.0"
  },
  "devDependencies": {
    "@types/node": "^9.4.0",
    "ts-node": "^4.1.0"
  }`

**Comment by andrew-hamilton-dev** [comment]
I was having the same issue with [Object Object] as @joefru but I was able to resolve it by playing around with the package versions in the dependency versions.  Below are the versions i ended up with to have it working.    Might help you out @joefru.

`"dependencies": {
    "@nestjs/common": "^4.5.9",
    "@nestjs/core": "^4.5.10",
    "@nestjs/graphql": "^2.0.0",
    "apollo-server-express": "^1.3.2",
    "graphql": "0.11.7",
    "graphql-subscriptions": "^0.5.6",
    "graphql-tools": "^2.19.0",
    "reflect-metadata": "^0.1.12",
    "rxjs": "^5.5.6",
    "subscriptions-transport-ws": "^0.9.5",
    "typescript": "^2.6.2",
    "ws": "^4.0.0"
  },
  "devDependencies": {
    "@types/node": "^9.4.0",
    "ts-node": "^4.1.0"
  }`

**Comment by Stradivario** [comment]
Hello Guys i have created GAPI project for easy start and deploy your application it is inspired by Angular IOC dependency injection and it is really easy to start.

The most easy way to start is explained here:
https://stradivario.github.io/gapi-cli/

Check this out [Gapi](https://github.com/Stradivario/gapi)

It has testing utility with Jest
It is based on Apollo, Graphql
It has [Sequelize Typescript](https://github.com/Stradivario/gapi-sequelize) Module integrated inside [ gapi-starter-advanced ](https://github.com/Stradivario/gapi-starter-postgres-sequelize-rabbitmq) example.

It has Docker integration with pre-configurated nginx Proxy docker container which handles API Workers and subscription and Autobalance all API to be served as a single endpoint https://localhost:80/graphiql and wss://localhost:80/subscriptions you can add your custom certificates inside nginx directory (generated from https://www.sslforfree.com/)

You can create separate thread for Testing like in this example here:

```yml
  testing:
    stop:
      - docker rm -f gapi-api-prod-worker-tests-executor
      - docker rm -f gapi-api-prod-worker-tests-provider
    start:
      - gapi testing start-provider
      - sleep 10
      - gapi testing start-executor
      - echo Cleaning...
      - gapi testing stop
    start-provider: docker run -d --network=gapiapiprod_gapi --ip=182.10.0.101 --name gapi-api-prod-worker-tests-provider gapi/api/prod
    start-executor:
      - docker run -d --network=gapiapiprod_gapi --ip=182.10.0.100 --name gapi-api-prod-worker-tests-executor gapi/api/prod
      - docker exec gapi-api-prod-worker-tests-provider npm -v
      - gapi test --worker --before

```
Check [this](https://github.com/Stradivario/gapi-starter-postgres-sequelize-rabbitmq/blob/master/gapi-cli.conf.yml#L51) link for reference 

In this environment all you need to do to create new Query Subscription or Mutation is this:

Create Controller:

```typescript
import { Query, GraphQLNonNull, Scope, Type, GraphQLObjectType, Mutation, GapiController, Service, GraphQLInt, Injector } from "gapi";
import { UserService } from './services/user.service';
import { UserObjectType } from './services/type/user.type';
import { UserMessageType } from './user.subscription.controller';

@GapiController()
export class UserQueriesController {

    @Injector(UserService) userService: UserService;

    @Scope('ADMIN')
    @Type(UserObjectType)
    @Query({
        id: {
            type: new GraphQLNonNull(GraphQLInt)
        }
    })
    findUser(root, { id }, context) {
        return this.userService.findUser(id);
    }

}

```

Import this controller to nearest Module for example `users.module`

```typescript

import { GapiModule } from 'gapi';
import { UserQueriesController } from './user-queries.controller';
import { UserService } from './services/user.service';
import { AnotherService } from './services/another.service';


@GapiModule({
    controllers: [
        UserQueriesController
    ],
    services: [
        UserService,
        AnotherService
    ]
})
export class UserModule {}
```

Import Usersmodule inside AppModule

```typescript

import { GapiModule } from 'gapi';
import { UserModule } from './user/user.module';
import { CoreModule } from './core/core.module';

@GapiModule({
    imports: [
        UserModule,
        CoreModule
    ]
})
export class AppModule { }
```
Bootstrap Appmodule  via Gapi Bootstrap method

```typescript
import { AppModule } from './app/app.module';
import { Bootstrap } from 'gapi';

Bootstrap(AppModule);
```

Execute

```bash
gapi start
```

Single test iteration
```bash
gapi test 
```

Watch mode

```bash
gapi test --watch
```


You can configurate your methods via gapi-cli for example you want to create custom method:
```bash
gapi your-cli my-command
```
All you need to do is to create `gapi-cli.conf.yml` file inside your project with following content

```yml
commands:
   your-cli:
      my-command: npm -v

```
Then you can execute this like:

```bash
gapi your-cli my-command
```

Read more inside [Wiki](https://github.com/Stradivario/gapi-cli/wiki) for details
Working example you can find [here](https://github.com/Stradivario/gapi-starter-postgres-sequelize-rabbitmq/blob/master/gapi-cli.conf.yml)

Njoy!
Hope you like it! :))

**Comment by Stradivario** [comment]
@kamilmysliwiec  i really don't understand why you delete the comment...

**Comment by Stradivario** [comment]
Its a Community right ? and you can share your Subscription Methods to Others ? What is your point ? and problem ?

**Comment by Stradivario** [comment]
I am out will ban nest community for sure
