### ISSUE TITLE
404 for playground and introspection

### ISSUE THREAD

**Issue by blissi** [nestjs/graphql#62]
Hallo,

I discovered the following bug, using nestjs/graphql@5.1.2 and apollo-server-express@2.0.6:
whenever I try to access the playground or introspect my GraphQL schema, the server responds with 404. NODE_ENV is set to debug.

The following is happening:
```
	const app = await NestFactory.create(AppModule);
	await app.listen(config.httpPort);
```
app.listen() triggers NestApplication.init() which looks like this:
```
async init() {
        ....
        await this.registerModules();
        await this.registerRouter();
        await this.callInitHook();
        ...
    }
```
registerRouter() calls RoutesResolver.registerNotFoundHandler(), which installs the 404 handler in the express router.
After that, callInitHook() will trigger the onModuleInit()-function of the GraphQLModule which installs the /graphql-route.

-> in short: the 404 route is installed *before* the /graphql-route.
Whenever I now try to access localhost:3000/graphql, the 404 handler responds to this request and the graphql-handler isn't called.

To verify my assumption, I commented out the code of registerNotFoundHandler() and tried again -> now it worked.

**Comment by kamilmysliwiec** [comment]
This issue has been fixed a while ago. Ensure to update all nest packages (graphql, common, core)

**Comment by blissi** [comment]
Thanks, you're right!
