### ISSUE TITLE
GraphQLGatewayModule interceptor not working

### ISSUE THREAD

**Issue by volbrene** [nestjs/graphql#651]
## Current behavior
I would like to use a global interceptor before graphql gateway send the request to federation services. This isn´t working. Is that correct?

## Reproduce
Repository to reproduce this issue: https://github.com/volbrene/nestjs-graphql-gateway-interceptor-bug-report

## Environment
@nestjs/core@6.11.11
@nestjs/graphql@6.6.2

**Comment by volbrene** [comment]
@kamilmysliwiec I have add a repo to reproduces my issue in the issue description. Hope it helps.

**Comment by kamilmysliwiec** [comment]
This is not how it is supposed to work. Enhancers (like interceptors) can be applied to handlers defined **within the application**. External services don't have any handlers. If you pass a list of services (in a gateway definition), Nest will simply use Apollo Gateway to connect to them (and nothing else).
