### ISSUE TITLE
Add debug mode for schema generation errors

### ISSUE THREAD

**Issue by gempain** [nestjs/graphql#699]
Could be related to #115 in a bigger picture.

## I'm submitting a...

```
[x] Feature request
```

## Current behavior

When you forget to annotate an object with `@ObjectType()` or `@InputTyoe()` or have forgotten to register a custom scalar for a type, you get this error:
```
Error: Cannot determine GraphQL output type for config

    at OutputTypeFactory.create (.../node_modules/@nestjs/graphql/dist/schema-builder/factories/output-type.factory.js:17:23)
    at .../node_modules/@nestjs/graphql/dist/schema-builder/factories/object-type-definition.factory.js:63:53
```

It's difficult to locate exactly what causes the error, because we only have the property name.

Current workaround, add the following at line 62 in `node_modules/@nestjs/graphql/dist/schema-builder/factories/object-type-definition.factory.js` to get a nice log stack that helps locate the property causing the error:

```
`console.log(field.name, field.typeFn(), options, field.options);`
```

## Expected behavior

It would be nice to have a way of enabling some logs for debugging these kind of errors.

## What is the motivation / use case for changing the behavior?

Trying to locate the property causing the error mentioned above.

## Environment
```
"@nestjs/graphql": "^7.0.10"
```

## Places to debug

I'll list here the places where debug tracing logs would be useful when I encounter one that I need. This is a reference for a future PR.

- `node_modules/@nestjs/graphql/dist/schema-builder/factories/args.factory.js:16`

**Comment by kamilmysliwiec** [comment]
@gempain would you like to create a PR for this issue? :)

**Comment by gempain** [comment]
@kamilmysliwiec sure ! I'll give it a shot when I get some free time - shouldn't be too hard to implement. I don't promise anything shortly, but leave this open so I can come back to it then :)

**Comment by kamilmysliwiec** [comment]
We've updated it to `Cannot determine a GraphQL output type for the "${hostType}". Make sure your class is decorated with an appropriate decorator.` to give a bit more information on what's needed to fix this issue.

**Comment by gempain** [comment]
@kamilmysliwiec shame on me I never got the time to do a PR :( sorry !
