### ISSUE TITLE
Batching and Caching Documentation

### ISSUE THREAD

**Issue by Jonatthu** [nestjs/graphql#7]
## I'm submitting a...
<pre><code>
[ x] Documentation issue or request
</code></pre>

On the documentation of Graphql there is nothing talking about Batching or Caching
https://www.npmjs.com/package/dataloader
Is there any example integrating this or get a same behavior with nestjs?

**Comment by obedm503** [comment]
duplicate of #2

**Comment by kamilmysliwiec** [comment]
I'll publish a small chapter in the docs about integration with DataLoader soon 🤞 Stay tuned!

**Comment by zuohuadong** [comment]
@kamilmysliwiec   we need it  too.

**Comment by zerox12311** [comment]
We need it too~~~ @kamilmysliwiec 
Any news??

**Comment by JeetChaudhari** [comment]
@kamilmysliwiec Is docs added for using Dataloader with this module? I still can not find it in docs.

**Comment by esistgut** [comment]
Leaving a comment for people who end on this issue looking for documentation: there are a couple of implementations in these other issues:
https://github.com/nestjs/graphql/issues/20#issuecomment-500427559 and https://github.com/nestjs/graphql/issues/2#issuecomment-498968008

**Comment by yassern** [comment]
it is cool see those examples but i think this issue should be reopen
