### ISSUE TITLE
@FIeld() on @ObjectType() methods.

### ISSUE THREAD

**Issue by j** [nestjs/graphql#702]
I'm migrating from `type-graphql` and have a lot of class methods that are assigned to a field.

```typescript
@ObjectType()
class Cart {
  // ...

  @GraphQL.Field(() => [Adjustment], { name: 'adjustments' })
  getAdjustments(
    @GraphQL.Args({ name: 'type', type: () => AdjustmentType, nullable: true })
    type?: AdjustmentType
  ): Adjustment[] {
    return !type
      ? this.adjustments
      : this.adjustments.filter(a => a.type === type);
  }
}
```

This doesn't work anymore.  Is class method -> field mapping supported anymore?

**Comment by GrayStrider** [comment]
Is `@ResolveField()` decorator what you're looking for, by any chance?
https://docs.nestjs.com/graphql/resolvers

**Comment by kamilmysliwiec** [comment]
@j see this discussion for more details: https://github.com/nestjs/graphql/issues/659
my answer: https://github.com/nestjs/graphql/issues/659#issuecomment-600602551

**Comment by j** [comment]
@kamilmysliwiec looked through that discussion.  I left a comment and don't agree with putting simple getters onto resolvers.  Anyone who ends up doing this will just create a resolver that calls the root's method defeating the purpose of it.  I use field resolvers on a resolver level for things like relations or when I need to use a service.  In cases where I'm doing simple filtering of backend stuff, boolean checks based off criteria (`hasRole(role: UserRole)`), I want them to be in the model.

**Comment by kamilmysliwiec** [comment]
Replied again here https://github.com/nestjs/graphql/issues/659#issuecomment-604527681
