### ISSUE TITLE
@nestjs/graphql v7 does not work when used  prisma2

### ISSUE THREAD

**Issue by sessionboy** [nestjs/graphql#711]
I tried to combine [prisma2](https://github.com/prisma/prisma2) with `nestjs/graphql`, but I got an error when I upgraded to `@nestjs/graphql v7`. 
The schema generated by `@nestjs/graphql v7` is not compatible with the schema generated by `prisma2`.
I used this example: [nestjs-prisma-starter](https://github.com/fivethree-team/nestjs-prisma-starter).
It is still v6, you need to upgrade it to v7.

**Comment by kamilmysliwiec** [comment]
`nestjs-prisma-starter` is not an official NestJS repository, but rather the community example. Please, report an issue there instead
