### ISSUE TITLE
There are not enough document to show how to upload using graphql.

### ISSUE THREAD

**Issue by imhazige** [nestjs/graphql#722]
I have spend much time on it, but there are no answer related to nestjs + graphql + upload.

need a workable github example to show how to make it work.

I have try this https://github.com/jaydenseric/apollo-upload-examples. but it is not using nestjs. did not work in my code.

**Comment by robertwestbury** [comment]
https://stackoverflow.com/questions/56097187/nestjs-apollo-graphql-upload-scalar I've used this in the past.

**Comment by imhazige** [comment]
OMG, the issue is related [here](https://github.com/jaydenseric/apollo-upload-client/issues/108#issuecomment-410570336) and [here](https://github.com/apollographql/apollo-client/issues/3161). that's not a issue for nestjs, but should blame the apollo document.
---
so to sum, apollo-boost did not support upload setup.
and graphql upload is not good for upload large file as there are no progress to show.
use rest api to upload is better.
