### ISSUE TITLE
nullable is not work with ObjectType

### ISSUE THREAD

**Issue by sessionboy** [nestjs/graphql#731]
My model
```js
import { Field, Int, ObjectType } from '@nestjs/graphql';

@ObjectType()
export class Verified {
  @Field()
  name: string;

  @Field()
  description: string;
}

@ObjectType()
export class User {
  @Field()
  id: string;
  // ....

  @Field({ nullable: true })
  verified?: Verified;

}
```
In the `User` class, when `verified` does not exist, the value of the `verified` field should be null, but this does not work.

```js
{
  "errors": [
    {
      "message": "Cannot return null for non-nullable field Verified.name.",
      "locations": [
        {
          "line": 8,
          "column": 6
        }
      ],
      ...
```
I have to set all the fields in the `Verified` class to `nullable:true` to run, but this is not what I want.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
