### ISSUE TITLE
GraphQLDefinitionsFactory generation with resolver arguments

### ISSUE THREAD

**Issue by tomasAlabes** [nestjs/graphql#744]
## Is your feature request related to a problem? Please describe.
If you generate the typescript interfaces/classes from a SDL, the resolvers functions don't have the optional args, root, info, context parameters.

## Describe the solution you'd like
For them to be generated. Other libraries do it, for example [graphql-code-generator](https://github.com/dotansimha/graphql-code-generator).

## Teachability, Documentation, Adoption, Migration Strategy
Adding it as an option in `GraphQLDefinitionsFactory`

## What is the motivation / use case for changing the behavior?
If the resolvers use `@Arg`, `@Context`, etc, then the generated types are useless.

**Comment by kamilmysliwiec** [comment]
Can you show us a current vs expected definitions?

**Comment by tomasAlabes** [comment]
Yes, the best and more complete way to see it is using [graphql-code-generator live generator](https://graphql-code-generator.com/#live-demo), adding `- typescript-resolvers` to the config (they have more options in the doc). 

Using [Nest's cat sample](https://github.com/nestjs/nest/blob/master/sample/12-graphql-schema-first/src/cats/cats.graphql), this [is the current output](https://github.com/nestjs/nest/blob/master/sample/12-graphql-schema-first/src/graphql.schema.ts) and graphql-code-generator's output is: https://gist.github.com/tomasAlabes/3cb1aa705486e578f0a4a33d14670e78.
I didn't copy it here because it's quite big.

**Comment by kamilmysliwiec** [comment]
It should be fairly easy to implement. Would you like to create a PR for this issue?

**Comment by tomasAlabes** [comment]
I'm already working extra time migrating my services to nest, idk if I'll have the brain power.
Could you provide some pointers / explanation here in case I (or anyone else) wants to give it a go?
Thanks

**Comment by kamilmysliwiec** [comment]
I will take this one then, no worries! Any ideas on what name for this option property would be the most appropriate for that?

**Comment by tomasAlabes** [comment]
Wow cool! Thanks!
The library has plenty of [plugins](https://graphql-code-generator.com/docs/plugins/), if we want to provide its full power then maybe I'd add an option inside `definitions`, called something like `plugins` and let the user pick (installing the corresponding plugin).

If not, some simple option like `type` where it can be `basic` or `full`, where `basic` it's the current behavior and `full` includes resolvers.

Hope the ideas help :) 
Thanks again!

**Comment by kamilmysliwiec** [comment]
It will be added as a part of this PR #785:
```typescript
const definitionsFactory = new GraphQLDefinitionsFactory();
definitionsFactory.generate({
  // ...
  skipResolverArgs: true,
});
```

**Comment by tomasAlabes** [comment]
@kamilmysliwiec thank you! That was quick! But... 😕  
I pulled the latest (7.3.1) and I still see the same output types (without resolvers params). I also tried with the cats sample. Am I missing something?
