### ISSUE TITLE
The resolveType option passed to createUnionType is removed when using GraphQLFederationModule (code-first)

### ISSUE THREAD

**Issue by parkerself22** [nestjs/graphql#886]
**I realize I'm jumping the gun a little here on using the code-first approach with federation, but figured this would be helpful to submit.**

## I'm submitting a...

<pre><code>[x] Bug report</code></pre>

## Current behavior

When using the `GraphQLFederationModule`, `resolveType` is removed from union types created via `createUnionType`, causing the following error in queries that contain that union type:

```
GraphQLError: Abstract type "CartItem" must resolve to an Object type at runtime for field "scan_export.cart_items" with value {...}, received "undefined". 
Either the "CartItem" type should provide a "resolveType" function or each possible type should provide an "isTypeOf" function.
at ensureValidRuntimeType (node_modules/graphql/execution/execute.js:687:11)
at completeAbstractValue (node_modules/graphql/execution/execute.js:680:42)
at completeValue (node_modules/graphql/execution/execute.js:604:12)
at completeValue (node_modules/graphql/execution/execute.js:576:21)
at completeValueCatchingError (node_modules/graphql/execution/execute.js:514:19)
at node_modules/graphql/execution/execute.js:636:25
at from (<anonymous>)
...
```

I dug into `graphql-federation.factory` and it looks like resolveType functions for all UnionTypes are being removed in the `generateSchema` method (comments added by me):

```ts
// Union types in autoGeneratedSchema still have resolveType defined
const autoGeneratedSchema: GraphQLSchema = await this.gqlSchemaBuilder.buildFederatedSchema(
  options.autoSchemaFile,
  options,
  this.resolversExplorerService.getAllCtors()
);
// Union types in executableSchema are all missing resolveType
const executableSchema = buildFederatedSchema({
  typeDefs: gql(printSchema(autoGeneratedSchema)),
  resolvers: this.getResolvers(options.resolvers)
});
```

I'm assuming this is due to the fact that `printSchema` is being used to get the `typeDefs` for `buildFederatedSchema`, but haven't had time to get into potential fixes (though my guess is to do another transform on `executableSchema` where we swap in the Union types from `autoGeneratedSchema`.)

## Expected behavior

The `resolveType` function I provide to `createUnionType` should still be there in the generated schema. I was able to fix this by passing resolvers in the module options, but that shouldn't be required when using `createUnionType`:

```ts
           resolvers: {
                CartItem: {
                    __resolveType(value: CartItemSingle | CartItemGroup) {
                        if (value.type === CartItemTypeEnum.group) {
                            return 'CartItemGroup';
                        }
                        return 'CartItemSingle';
                    }
                }
            }
```

## Minimal reproduction of the problem with instructions

Try to use the `GraphQLFederationModule` with a code-first approach and a union type. All `resolveType` methods on the union types will be missing in the output schema.

## Environment

<pre><code>
"@nestjs/common": "7.0.13",
"@nestjs/core": "7.0.13",
"@nestjs/graphql": "7.3.9",

</code></pre>

**Comment by kamilmysliwiec** [comment]
Could you please provide a minimum reproduction repository? This would help us a lot

**Comment by kamilmysliwiec** [comment]
BTW Can you test with the 7.3.11 release?

**Comment by parkerself22** [comment]
@kamilmysliwiec See my PR, there's something weird going on with`@apollo/federation` where your changes in 7.3.11 still don't fix the problem. My version works but I can't totally explain what is going on behind the scenes in apollo to make that the case.

**Comment by joemckie** [comment]
I just came across this issue after fixing a very similar bug where `resolveType` wasn't being respected. @kamilmysliwiec I noticed the OP here is returning a string from `resolveType`, however in the docs it shows a class being returned. Which is correct?

**Comment by parkerself22** [comment]
@joemckie I'm not actually returning a string in the `resolveType` prop passed to `createUnionType`, there I followed the docs exactly. I'm returning a string in the \_\_resolveType property on the union's resolver manually passed to `GraphQLFederationModule`.

Maybe this will make it clearer:

```ts
export const CartItemUnion = createUnionType({
  // this is never actually being called due to the bug but here I am returning the class type
  resolveType: (value: any) => {
    if (value.type === CartItemTypeEnum.group) {
      return CartItemGroup;
    }
    return CartItemSingle;
  },
  name: "CartItem",
  types: () => [CartItemGroup, CartItemSingle]
});

@Module({
  imports: [
    GraphQLFederationModule.forRoot({
      // this is necessary or else the union type for CartItem wont work
     // I tried returning the class-type here first originally, but that doesn't work because
     // this resolver is not transformed by nestjs, its called directly by apollo / js-graphql
      resolvers: {
        CartItem: {
          __resolveType(value: CartItemSingle | CartItemGroup) {
            return value.type === CartItemTypeEnum.group
              ? "CartItemGroup"
              : "CartItemSingle";
          }
        }
      }
    })
  ]
})
export class GraphqlModule {}
```

**Comment by joemckie** [comment]
@parkerself22 see I have the opposite happening to me -- `resolveType` (in union type) is being called, but `__resolveType` isn't being called!

Also the union returns `null` (but no errors) if a string isn't returned from `resolveType`.

I'm honestly not sure what's going on or why it works 😅

**Comment by parkerself22** [comment]
@joemckie are you running `7.3.11`? My approach was a hack that worked with `v7.3.9`, the changes in `7.3.11` fixed the issue with `resolveType` not being called but not the fact that returning the full class type causes the union to alway be `null` in the query result. Having worked with the changes made for `7.3.11` it makes sense to me that `__resolveType` no longer works.

> I'm honestly not sure what's going on or why it works 😅

Yeah, same. It's pretty frustrating. I spent a couple hours debugging this for my PR, was literally stepping line-by-line through the `graphql` and `@apollo/federation` code that was attempting to resolve the union's type, and couldn't come up with an explanation. My best guess is something funky in apollo. Probably should open a ticket over there too, just haven't had time to investigate fully enough to give it a good write up. 

Federation has been both a godsend and a pain in the butt for us, but I guess that's what you sign up for when you live on the bleeding edge.

**Comment by parkerself22** [comment]
@joemckie I owe you a thank you, in explaining it I actually just now figured out the core issue. If you're interested in an overly detailed explanation you can check out #898, otherwise for now just make sure the string you return in `resolveType` exactly matches the name of the object type in your schema (vs the class name or whatever), and you'll be fine.

**Comment by joemckie** [comment]
> I guess that's what you sign up for when you live on the bleeding edge.

Ha, too right 😄 glad you got it working! And yep, I figured it would need to match the type name exactly. I just return `.name` from the expected class. Thanks for clearing it up!
