### ISSUE TITLE
Input type's with nested validation should hydrate without `@Type` annotation

### ISSUE THREAD

**Issue by j** [nestjs/graphql#889]
If you use @InputType and validation, first thing, you have to use nested validation to validate nested properties.  But you still have to annotate that property with `@Type`.  It'd be nice if this was inferred within the @Field()'s type?

Edit:

I'm not sure if this is a validation thing, or just a hydration thing.  Without `@Type`, the nested object doesn't hydrate into the correct class when it should.

**Comment by kamilmysliwiec** [comment]
This is related to the `class-transformer` and `class-validator` packages (nested properties must be decorator with `@Type())` :(
