### ISSUE TITLE
Can't start since apollo-server-core 2.13.1

### ISSUE THREAD

**Issue by bfo2ses** [nestjs/graphql#892]
Hello guys !

Thanks for the amazing work but since the new release I can't start my projects...

So the culprit is the upgrade of apollo-server-core 2.13.1 dependency of apollo-server-express which introduce Websocket and typescript doesn't compile anymore...

Module '"...@types/ws/index"' can only be default-imported using the 'esModuleInterop' flag
import WebSocket from 'ws';

I tried many things during the day but I can't find a workaround...
And it works fine without nestjs....

If you need more details, please feel free to ask :)

Thanks again !

**Comment by kamilmysliwiec** [comment]
Hi @bfo2ses! Please, check out this issue for more information https://github.com/nestjs/graphql/issues/854 Here's a solution for your problem https://github.com/nestjs/graphql/issues/854#issuecomment-627794472

**Comment by bfo2ses** [comment]
Sorry, I forgot to check the closed issues....
Thanks a lot !
