### ISSUE TITLE
Possibility: Autorziation to a Schema

### ISSUE THREAD

**Issue by MasterofDesaster3** [nestjs/graphql#909]
Hello my Graphql/nestjs friends,

We all know that Authorization in Graphql is possible and the access to data for unauthorized person can be denied.

But now i want that the "unauthorized" person is even denied to see the Possibilties in the schema (for example in Graphql playground) or on the Gateway. 

My dream would be, that at first the user only sees login and register in the schema than according to that information new Querys and Mutation will be visible in the Schema. 

So is it possible to set options of types or whole querys/mutations to invisible according to authorization?

Or has somebody an idea?

Thanks a lot for every help.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
