### ISSUE TITLE
Deprecate Prisma 1 in favor of Prisma 2

### ISSUE THREAD

**Issue by un33k** [nestjs/graphql#964]
Prima 1 is deprecated and Prisma 2 is a total new package.

## I'm submitting a...
<pre><code>
[ ] Regression 
[ ] Bug report
[ ] Feature request
[ x ] Documentation issue or request
</code></pre>

## Current behavior
Current Prisma documentation and example
https://github.com/nestjs/nest/tree/master/sample/22-graphql-prisma

## Expected behavior
Be nice to update the example page to something like
https://github.com/MichalLytek/type-graphql/tree/prisma/examples/3-nest-js

## What is the motivation / use case for changing the behavior?
Be nice to update your docs to keep up with the latest compatible packages.

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/docs.nestjs.com/pull/1277

**Comment by un33k** [comment]
Great! - Thx
