### ISSUE TITLE
 UnhandledPromiseRejectionWarning: GraphQLError: Syntax Error: Unexpected <EOF>

### ISSUE THREAD

**Issue by legraxieux53** [nestjs/graphql#987]
## UnhandledPromiseRejectionWarning: GraphQLError: Syntax Error: Unexpected <EOF>

<pre>
(node:12096) UnhandledPromiseRejectionWarning: GraphQLError: Syntax Error: Unexpected <<code>EOF</code>>.
    at syntaxError (E:\Projets clients\gestion pressing\client-workspace\node_modules\graphql\error\syntaxError.js:15:10)
    at Parser.unexpected (E:\Projets clients\gestion pressing\client-workspace\node_modules\graphql\language\parser.js:1482:41)
    at Parser.parseDefinition (E:\Projets clients\gestion pressing\client-workspace\node_modules\graphql\language\parser.js:155:16)
    at Parser.many (E:\Projets clients\gestion pressing\client-workspace\node_modules\graphql\language\parser.js:1537:26)
    at Parser.parseDocument (E:\Projets clients\gestion pressing\client-workspace\node_modules\graphql\language\parser.js:109:25)
    at parse (E:\Projets clients\gestion pressing\client-workspace\node_modules\graphql\language\parser.js:36:17)
    at parseDocument (E:\Projets clients\gestion pressing\client-workspace\node_modules\graphql-tag\lib\graphql-tag.umd.js:135:16)
    at Object.gql (E:\Projets clients\gestion pressing\client-workspace\node_modules\graphql-tag\lib\graphql-tag.umd.js:176:10)
    at GraphQLFactory.<anonymous> (E:\Projets clients\gestion pressing\client-workspace\node_modules\@nestjs\graphql\dist\graphql.factory.js:65:56)
    at Generator.next (<anonymous>)
(node:12096) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:12096) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
<code>

[ ] Regression 
[*] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior

Please, I encounter this error after having built my nestJS project that I want to deploy it with the command node main.

## Expected behavior

It seems that there is a rejection of promise not taken into account. I want to be able to execute the project built on the node server.

## Minimal reproduction of the problem with instructions

(My NestJs code)

```
// app.module.ts 
import { SetResolver } from './set.resolver';
import { Module } from '@nestjs/common';
import {GraphQLModule} from '@nestjs/graphql';

import { AppController } from './app.controller';
import { AppService } from './app.service';

@Module({
  imports: [
    GraphQLModule.forRoot({
      typePaths: ['./**/*.graphql'],
    })
  ],
  controllers: [AppController],
  providers: [
    AppService,
    SetResolver
  ],
})
export class AppModule {}

```

```
//schema.graphql
type Set {
    id: Int!
    name: String
    year: Int
    numParts: Int
}

type Query {
    allSets: [Set]
}

type Mutation {
    addSet(name: String, year: String, numParts: Int): Set
}

```

```
//set.resolver.ts
import { Args, Mutation, Query, Resolver } from '@nestjs/graphql';

export interface SetEntity {
  id: number;
  name: string;
  numParts: number;
  year: string;
}

@Resolver('Set')
export class SetResolver {
  private sets: SetEntity[] = [
    {
      id: 1,
      name: 'Voltron',
      numParts: 2300,
      year: '2019'
    },
    {
      id: 2,
      name: 'Ship in a Bottle',
      numParts: 900,
      year: '2019'
    },
    {
        id: 3,
        name: 'Ship in a wistle',
        numParts: 1200,
        year: '2020'
      }
  ];

  @Query('allSets')
  getAllSets(): SetEntity[] {
    return this.sets;
  }

  @Mutation()
  addSet(
    @Args('name') name: string,
    @Args('year') year: string,
    @Args('numParts') numParts: number
  ) {
    const newSet = {
      id: this.sets.length + 1,
      name,
      year,
      numParts: +numParts
    };

    this.sets.push(newSet);

    return newSet;
  }
}
```

after I built with the command `nx run my-project: build`
And finally I launched the command `node main.js`

## What is the motivation / use case for changing the behavior?

I have to create an intranet. So I need to deploy my project locally. Please help me. It's urgent.

## Environment

<pre><code>
Nest version: ^6.8.3

 
For Tooling issues:
- Node version: XX  v12.14.0
- Platform:  Windows 

Others:
"@nestjs/graphql": "^7.4.1",
"@nestjs/platform-express": "^6.8.3",
"apollo-server-express": "^2.15.0",
"graphql": "^15.1.0",
"graphql-tools": "^6.0.10",

</code></pre>

**Comment by kamilmysliwiec** [comment]
Please see this issue https://github.com/nestjs/graphql/issues/972. I've added a more descriptive error message in this commit https://github.com/nestjs/graphql/commit/f5dd30270bea3fb9a976bcb4506c764e4e548aa1. It will be available in the next patch release shortly

**Comment by legraxieux53** [comment]
Thank you so much. When building, webpack did not directly add the `* .graphql ` files. As a result, my built code could not find any of these files.
